### ISSUE TITLE
test_leader_demoted_when_hibernated failed

### ISSUE THREAD

**Issue by gengliqi** [tikv/tikv#10309]
### What version of TiKV are you using?
master

### What operating system and CPU are you using?
doesn't master

### Steps to reproduce
run test_leader_demoted_when_hibernated

### What did you expect?
test succeed

### What did happened?
This test fails frequently.
> thread 'raftstore::test_hibernate::test_leader_demoted_when_hibernated' panicked at 'peer 4 is still not leader after 5 seconds.', tests/integrations/raftstore/test_hibernate.rs:462:13
stack backtrace:
   0: std::panicking::begin_panic
             at /Users/gengliqi/.rustup/toolchains/nightly-2021-04-15-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:519:12
   1: integrations::raftstore::test_hibernate::test_leader_demoted_when_hibernated
             at ./integrations/raftstore/test_hibernate.rs:462:13
   2: integrations::raftstore::test_hibernate::test_leader_demoted_when_hibernated::{{closure}}
             at ./integrations/raftstore/test_hibernate.rs:406:1
   3: core::ops::function::FnOnce::call_once
             at /Users/gengliqi/.rustup/toolchains/nightly-2021-04-15-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
   4: test_util::runner::run_test_with_hook::{{closure}}::{{closure}}
             at /Users/gengliqi/myrepo/tikv/components/test_util/src/runner.rs:64:21
   5: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /Users/gengliqi/.rustup/toolchains/nightly-2021-04-15-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
   6: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/alloc/src/boxed.rs:1546:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test raftstore::test_hibernate::test_leader_demoted_when_hibernated ... FAILED

**Comment by BusyJay** [comment]
Should be fixed by #10403.
