### ISSUE TITLE
test case is not stable

### ISSUE THREAD

**Issue by hicqu** [tikv/tikv#10380]
Here is a stack trace for a failure:
```
[2021-06-17T08:16:25.075Z] test raftstore::test_stats::test_query_stats ... thread 'main' panicked at 'assertion failed: check_query_num_write(&cluster, store_id, QueryKind::Put, 1)', tests/integrations/raftstore/test_stats.rs:339:9
[2021-06-17T08:16:25.075Z] stack backtrace:
[2021-06-17T08:16:25.333Z]    0: rust_begin_unwind
[2021-06-17T08:16:25.333Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/panicking.rs:493:5
[2021-06-17T08:16:25.333Z]    1: core::panicking::panic_fmt
[2021-06-17T08:16:25.333Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/panicking.rs:92:14
[2021-06-17T08:16:25.333Z]    2: core::panicking::panic
[2021-06-17T08:16:25.333Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/panicking.rs:50:5
[2021-06-17T08:16:25.333Z]    3: integrations::raftstore::test_stats::test_query_num::{{closure}}
[2021-06-17T08:16:25.333Z]              at /home/jenkins/tikv-src/tests/integrations/raftstore/test_stats.rs:339:9
[2021-06-17T08:16:25.333Z]    4: integrations::raftstore::test_stats::test_query_num
[2021-06-17T08:16:25.333Z]              at /home/jenkins/tikv-src/tests/integrations/raftstore/test_stats.rs:380:5
[2021-06-17T08:16:25.333Z]    5: integrations::raftstore::test_stats::test_query_stats
[2021-06-17T08:16:25.333Z]              at /home/jenkins/tikv-src/tests/integrations/raftstore/test_stats.rs:268:5
[2021-06-17T08:16:25.333Z]    6: integrations::raftstore::test_stats::test_query_stats::{{closure}}
[2021-06-17T08:16:25.333Z]              at /home/jenkins/tikv-src/tests/integrations/raftstore/test_stats.rs:135:1
[2021-06-17T08:16:25.333Z]    7: core::ops::function::FnOnce::call_once
[2021-06-17T08:16:25.333Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/ops/function.rs:227:5
[2021-06-17T08:16:25.333Z]    8: test_util::runner::run_test_with_hook::{{closure}}::{{closure}}
[2021-06-17T08:16:25.333Z]              at /home/jenkins/tikv-src/components/test_util/src/runner.rs:64:21
[2021-06-17T08:16:25.333Z]    9: core::ops::function::FnOnce::call_once{{vtable.shim}}
[2021-06-17T08:16:25.333Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/ops/function.rs:227:5
[2021-06-17T08:16:25.333Z]   10: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
[2021-06-17T08:16:25.333Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/alloc/src/boxed.rs:1546:9
[2021-06-17T08:16:25.333Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2021-06-17T08:16:25.333Z] FAILED
```

**Comment by hicqu** [comment]
I have no idea why it fails. Could you take look or re-dispatch it @lhy1024 ?
