### ISSUE TITLE
Unstable test `test_stale_read::test_read_index_when_transfer_leader_2`

### ISSUE THREAD

**Issue by zhouqiang-cl** [tikv/tikv#10513]
## Bug Report
```

[2021-07-02T13:49:47.767Z] test cases::test_stale_read::test_read_index_when_transfer_leader_2 ... thread 'main' panicked at 'can't get value Some("v0") for key 6B30', components/test_raftstore/src/util.rs:76:5
[2021-07-02T13:49:47.767Z] stack backtrace:
[2021-07-02T13:49:47.767Z]    0: rust_begin_unwind
[2021-07-02T13:49:47.767Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/panicking.rs:493:5
[2021-07-02T13:49:47.767Z]    1: std::panicking::begin_panic_fmt
[2021-07-02T13:49:47.767Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/panicking.rs:435:5
[2021-07-02T13:49:48.026Z]    2: test_raftstore::util::must_get
[2021-07-02T13:49:48.026Z]              at /home/jenkins/tikv-src/components/test_raftstore/src/util.rs:76:5
[2021-07-02T13:49:48.026Z]    3: test_raftstore::util::must_get_equal
[2021-07-02T13:49:48.026Z]              at /home/jenkins/tikv-src/components/test_raftstore/src/util.rs:84:5
[2021-07-02T13:49:48.026Z]    4: failpoints::cases::test_stale_read::test_read_index_when_transfer_leader_2
[2021-07-02T13:49:48.026Z]              at /home/jenkins/tikv-src/tests/failpoints/cases/test_stale_read.rs:340:5
[2021-07-02T13:49:48.026Z]    5: failpoints::cases::test_stale_read::test_read_index_when_transfer_leader_2::{{closure}}
[2021-07-02T13:49:48.026Z]              at /home/jenkins/tikv-src/tests/failpoints/cases/test_stale_read.rs:323:1
[2021-07-02T13:49:48.026Z]    6: core::ops::function::FnOnce::call_once
[2021-07-02T13:49:48.027Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/ops/function.rs:227:5
[2021-07-02T13:49:48.027Z]    7: test_util::runner::run_test_with_hook::{{closure}}::{{closure}}
[2021-07-02T13:49:48.027Z]              at /home/jenkins/tikv-src/components/test_util/src/runner.rs:64:21
[2021-07-02T13:49:48.027Z]    8: core::ops::function::FnOnce::call_once{{vtable.shim}}
[2021-07-02T13:49:48.027Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/ops/function.rs:227:5
[2021-07-02T13:49:48.027Z]    9: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
[2021-07-02T13:49:48.027Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/alloc/src/boxed.rs:1546:9
[2021-07-02T13:49:48.027Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2021-07-02T13:49:49.405Z] FAILED
```

### Steps to reproduce

in ci https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/3521/pipeline

**Comment by gengliqi** [comment]
It's caused by a slow disk.
```
[2021-07-02T13:50:10.531Z] 21:49:46.849 snap.rs:806: [INFO] scan snapshot, takes: 5.420526425s, size: 1051, key_count: 1, snapshot: /tmp/test_clusterahmjrJ/gen_1_6_9_(default|lock|write).sst, region_id: 1
```
The time of generating snapshot is too long. I think maybe we can ignore this failure if the frequency is very low.

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further feedback regarding this issue has been reported, it can be safely closed.
