### ISSUE TITLE
Unstable test ``test_split_region::test_node_auto_split_region`

### ISSUE THREAD

**Issue by zhouqiang-cl** [tikv/tikv#10514]
## Bug Report
in ci https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/3515/pipeline

**Comment by zhouqiang-cl** [comment]
```
[2021-07-02T11:21:00.837Z] test raftstore::test_split_region::test_node_auto_split_region ... thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Other("[components/test_raftstore/src/pd.rs:1304]: no region contains key ")', tests/integrations/raftstore/test_split_region.rs:181:42
[2021-07-02T11:21:00.837Z] stack backtrace:
[2021-07-02T11:21:00.837Z]    0: rust_begin_unwind
[2021-07-02T11:21:00.837Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/panicking.rs:493:5
[2021-07-02T11:21:00.837Z]    1: core::panicking::panic_fmt
[2021-07-02T11:21:00.837Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/panicking.rs:92:14
[2021-07-02T11:21:00.837Z]    2: core::result::unwrap_failed
[2021-07-02T11:21:00.837Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/result.rs:1355:5
[2021-07-02T11:21:00.837Z]    3: core::result::Result<T,E>::unwrap
[2021-07-02T11:21:00.837Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/result.rs:1037:23
[2021-07-02T11:21:00.837Z]    4: integrations::raftstore::test_split_region::test_auto_split_region
[2021-07-02T11:21:00.837Z]              at /home/jenkins/tikv-src/tests/integrations/raftstore/test_split_region.rs:181:16
[2021-07-02T11:21:00.837Z]    5: integrations::raftstore::test_split_region::test_node_auto_split_region
[2021-07-02T11:21:00.837Z]              at /home/jenkins/tikv-src/tests/integrations/raftstore/test_split_region.rs:227:5
[2021-07-02T11:21:00.837Z]    6: integrations::raftstore::test_split_region::test_node_auto_split_region::{{closure}}
[2021-07-02T11:21:00.837Z]              at /home/jenkins/tikv-src/tests/integrations/raftstore/test_split_region.rs:224:1
[2021-07-02T11:21:00.837Z]    7: core::ops::function::FnOnce::call_once
[2021-07-02T11:21:00.837Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/ops/function.rs:227:5
[2021-07-02T11:21:00.837Z]    8: test_util::runner::run_test_with_hook::{{closure}}::{{closure}}
[2021-07-02T11:21:00.837Z]              at /home/jenkins/tikv-src/components/test_util/src/runner.rs:64:21
[2021-07-02T11:21:00.837Z]    9: core::ops::function::FnOnce::call_once{{vtable.shim}}
[2021-07-02T11:21:00.837Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/ops/function.rs:227:5
[2021-07-02T11:21:00.837Z]   10: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
[2021-07-02T11:21:00.837Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/alloc/src/boxed.rs:1546:9
[2021-07-02T11:21:00.837Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2021-07-02T11:21:00.837Z] FAILED
```
