### ISSUE TITLE
TiKV support Bulk Load

### ISSUE THREAD

**Issue by marsishandsome** [tikv/tikv#10563]

**Comment by tisonkun** [comment]
With an offline discussion it seems this work requires a dedicated repository to maintain the bulkload code.

@marsishandsome would you mind to translate the proposal to English and create a PR on [tikv/rfcs](https://github.com/tikv/rfcs)?

@BusyJay please check this background and the design to see whether or not we would create a dedicate repository for it.

**Comment by tisonkun** [comment]
@marsishandsome BTW you can tracking issues instead of PRs, like https://github.com/pingcap/tidb/issues/26022 or https://github.com/tikv/tikv/issues/10537 . See also the [rationale](https://tisonkun.github.io/ziggurat/f379bf788b20/#Issus-or-Pull-Request).

**Comment by marsishandsome** [comment]
> With an offline discussion it seems this work requires a dedicated repository to maintain the bulkload code.
> 
> @marsishandsome would you mind to translate the proposal to English and create a PR on [tikv/rfcs](https://github.com/tikv/rfcs)?
> 
here https://github.com/tikv/rfcs/pull/72

**Comment by marsishandsome** [comment]
> @marsishandsome BTW you can tracking issues instead of PRs, like [pingcap/tidb#26022](https://github.com/pingcap/tidb/issues/26022) or #10537 . See also the [rationale](https://tisonkun.github.io/ziggurat/f379bf788b20/#Issus-or-Pull-Request).

done

**Comment by tutububug** [comment]
@marsishandsome The bulkload feature when to plan to release? 
And would you explain the reason why generate SST files in tikv-server?

**Comment by chrislusf** [comment]
We are having trouble following https://github.com/tikv/migration/tree/main/online-bulk-load , and getting `EpochNotMatch` error.

We are using all default configuration on TiKV 6.1.0 branch in a quiet cluster.

The command we use:

```:~/tikv-migration$ ~/app/spark/bin/spark-submit --jars ../tikv-client-java/target/tikv-client-java-3.3.0-SNAPSHOT.jar --class org.tikv.bulkload.example.BulkLoadExample online-bulk-load/target/online-bulk-load-0.0.1-SNAPSHOT.jar 10.224.18.147:2379,10.224.37.20:2379,10.224.30.133:2379 example 10000000 10 true true
22/09/30 20:23:27 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
22/09/30 20:23:27 INFO BulkLoadExample$:
*****************
pdaddr=10.224.18.147:2379,10.224.37.20:2379,10.224.30.133:2379
prefix=example
size=10000000
partition=10
exit=true
exact=true
*****************

22/09/30 20:23:27 INFO SparkContext: Running Spark version 3.3.0
22/09/30 20:23:27 INFO ResourceUtils: ==============================================================
22/09/30 20:23:27 INFO ResourceUtils: No custom resources configured for spark.driver.
22/09/30 20:23:27 INFO ResourceUtils: ==============================================================
22/09/30 20:23:27 INFO SparkContext: Submitted application: org.tikv.bulkload.example.BulkLoadExample
22/09/30 20:23:28 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
22/09/30 20:23:28 INFO ResourceProfile: Limiting resource is cpu
22/09/30 20:23:28 INFO ResourceProfileManager: Added ResourceProfile id: 0
22/09/30 20:23:28 INFO SecurityManager: Changing view acls to: ben
22/09/30 20:23:28 INFO SecurityManager: Changing modify acls to: ben
22/09/30 20:23:28 INFO SecurityManager: Changing view acls groups to:
22/09/30 20:23:28 INFO SecurityManager: Changing modify acls groups to:
22/09/30 20:23:28 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(ben); groups with view permissions: Set(); users  with modify permissions: Set(ben); groups with modify permissions: Set()
22/09/30 20:23:28 INFO Utils: Successfully started service 'sparkDriver' on port 32502.
22/09/30 20:23:28 INFO SparkEnv: Registering MapOutputTracker
22/09/30 20:23:28 INFO SparkEnv: Registering BlockManagerMaster
22/09/30 20:23:28 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
22/09/30 20:23:28 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
22/09/30 20:23:28 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
22/09/30 20:23:28 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-a6a86381-4b0f-4883-951a-380628bbbab4
22/09/30 20:23:28 INFO MemoryStore: MemoryStore started with capacity 13.2 GiB
22/09/30 20:23:28 INFO SparkEnv: Registering OutputCommitCoordinator
22/09/30 20:23:28 INFO Utils: Successfully started service 'SparkUI' on port 4040.
22/09/30 20:23:28 INFO SparkContext: Added JAR file:///home/ben/tikv-client-java/target/tikv-client-java-3.3.0-SNAPSHOT.jar at spark://10.224.30.68:32502/jars/tikv-client-java-3.3.0-SNAPSHOT.jar with timestamp 1664587407971
22/09/30 20:23:28 INFO SparkContext: Added JAR file:/home/ben/tikv-migration/online-bulk-load/target/online-bulk-load-0.0.1-SNAPSHOT.jar at spark://10.224.30.68:32502/jars/online-bulk-load-0.0.1-SNAPSHOT.jar with timestamp 1664587407971
22/09/30 20:23:28 INFO Executor: Starting executor ID driver on host 10.224.30.68
22/09/30 20:23:28 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
22/09/30 20:23:28 INFO Executor: Fetching spark://10.224.30.68:32502/jars/online-bulk-load-0.0.1-SNAPSHOT.jar with timestamp 1664587407971
...```

all seems fine, but at the end of the run:

```22/09/30 20:23:44 INFO TaskSetManager: Finished task 14.0 in stage 8.0 (TID 64) in 2889 ms on 10.224.30.68 (executor driver) (1/34)
22/09/30 20:23:44 INFO TaskSetManager: Finished task 26.0 in stage 8.0 (TID 76) in 2889 ms on 10.224.30.68 (executor driver) (2/34)
22/09/30 20:23:44 INFO TaskSetManager: Finished task 5.0 in stage 8.0 (TID 55) in 2892 ms on 10.224.30.68 (executor driver) (3/34)
22/09/30 20:23:44 INFO TaskSetManager: Finished task 16.0 in stage 8.0 (TID 66) in 2890 ms on 10.224.30.68 (executor driver) (4/34)
22/09/30 20:23:44 INFO TaskSetManager: Finished task 8.0 in stage 8.0 (TID 58) in 2891 ms on 10.224.30.68 (executor driver) (5/34)
22/09/30 20:23:44 INFO TaskSetManager: Finished task 28.0 in stage 8.0 (TID 78) in 2889 ms on 10.224.30.68 (executor driver) (6/34)
22/09/30 20:23:44 INFO TaskSetManager: Finished task 20.0 in stage 8.0 (TID 70) in 2891 ms on 10.224.30.68 (executor driver) (7/34)
22/09/30 20:23:44 INFO TaskSetManager: Finished task 32.0 in stage 8.0 (TID 82) in 2888 ms on 10.224.30.68 (executor driver) (8/34)
22/09/30 20:23:44 INFO TaskSetManager: Finished task 22.0 in stage 8.0 (TID 72) in 2890 ms on 10.224.30.68 (executor driver) (9/34)
22/09/30 20:23:44 INFO TaskSetManager: Finished task 1.0 in stage 8.0 (TID 51) in 2895 ms on 10.224.30.68 (executor driver) (10/34)
22/09/30 20:23:44 INFO TaskSetManager: Finished task 23.0 in stage 8.0 (TID 73) in 2891 ms on 10.224.30.68 (executor driver) (11/34)
22/09/30 20:23:44 INFO TaskSetManager: Finished task 7.0 in stage 8.0 (TID 57) in 2894 ms on 10.224.30.68 (executor driver) (12/34)
22/09/30 20:23:44 INFO TaskSetManager: Finished task 19.0 in stage 8.0 (TID 69) in 2892 ms on 10.224.30.68 (executor driver) (13/34)
22/09/30 20:23:44 INFO TaskSetManager: Finished task 31.0 in stage 8.0 (TID 81) in 2890 ms on 10.224.30.68 (executor driver) (14/34)
22/09/30 20:23:44 INFO TaskSetManager: Finished task 4.0 in stage 8.0 (TID 54) in 2895 ms on 10.224.30.68 (executor driver) (15/34)
22/09/30 20:23:44 INFO TaskSetManager: Finished task 2.0 in stage 8.0 (TID 52) in 2896 ms on 10.224.30.68 (executor driver) (16/34)
22/09/30 20:23:45 INFO Executor: Finished task 17.0 in stage 8.0 (TID 67). 1189 bytes result sent to driver
22/09/30 20:23:45 INFO TaskSetManager: Finished task 17.0 in stage 8.0 (TID 67) in 3885 ms on 10.224.30.68 (executor driver) (17/34)
22/09/30 20:23:45 INFO Executor: Finished task 29.0 in stage 8.0 (TID 79). 1189 bytes result sent to driver
22/09/30 20:23:45 INFO TaskSetManager: Finished task 29.0 in stage 8.0 (TID 79) in 3886 ms on 10.224.30.68 (executor driver) (18/34)
22/09/30 20:23:45 INFO Executor: Finished task 11.0 in stage 8.0 (TID 61). 1189 bytes result sent to driver
22/09/30 20:23:45 INFO TaskSetManager: Finished task 11.0 in stage 8.0 (TID 61) in 3890 ms on 10.224.30.68 (executor driver) (19/34)
22/09/30 20:23:45 INFO Executor: Finished task 25.0 in stage 8.0 (TID 75). 1189 bytes result sent to driver
22/09/30 20:23:45 INFO TaskSetManager: Finished task 25.0 in stage 8.0 (TID 75) in 3889 ms on 10.224.30.68 (executor driver) (20/34)
22/09/30 20:23:45 INFO Executor: Finished task 13.0 in stage 8.0 (TID 63). 1189 bytes result sent to driver
22/09/30 20:23:45 INFO Executor: Finished task 10.0 in stage 8.0 (TID 60). 1189 bytes result sent to driver
22/09/30 20:23:45 INFO TaskSetManager: Finished task 13.0 in stage 8.0 (TID 63) in 3903 ms on 10.224.30.68 (executor driver) (21/34)
22/09/30 20:23:45 INFO TaskSetManager: Finished task 10.0 in stage 8.0 (TID 60) in 3904 ms on 10.224.30.68 (executor driver) (22/34)
22/09/30 20:23:45 INFO Executor: Finished task 12.0 in stage 8.0 (TID 62). 1189 bytes result sent to driver
22/09/30 20:23:45 INFO TaskSetManager: Finished task 12.0 in stage 8.0 (TID 62) in 4229 ms on 10.224.30.68 (executor driver) (23/34)
22/09/30 20:23:45 INFO Executor: Finished task 9.0 in stage 8.0 (TID 59). 1189 bytes result sent to driver
22/09/30 20:23:45 INFO TaskSetManager: Finished task 9.0 in stage 8.0 (TID 59) in 4411 ms on 10.224.30.68 (executor driver) (24/34)
22/09/30 20:23:45 INFO Executor: Finished task 27.0 in stage 8.0 (TID 77). 1189 bytes result sent to driver
22/09/30 20:23:45 INFO Executor: Finished task 3.0 in stage 8.0 (TID 53). 1189 bytes result sent to driver
22/09/30 20:23:45 INFO TaskSetManager: Finished task 27.0 in stage 8.0 (TID 77) in 4459 ms on 10.224.30.68 (executor driver) (25/34)
22/09/30 20:23:45 INFO TaskSetManager: Finished task 3.0 in stage 8.0 (TID 53) in 4463 ms on 10.224.30.68 (executor driver) (26/34)
22/09/30 20:23:46 INFO Executor: Finished task 24.0 in stage 8.0 (TID 74). 1189 bytes result sent to driver
22/09/30 20:23:46 INFO TaskSetManager: Finished task 24.0 in stage 8.0 (TID 74) in 4478 ms on 10.224.30.68 (executor driver) (27/34)
22/09/30 20:23:46 WARN ImporterClient: ingest failed.
org.tikv.common.exception.RegionException: Region Exception occurred EpochNotMatch conf_ver: 341 version: 16 != conf_ver: 347 version: 16
	at org.tikv.common.importer.ImporterStoreClient.multiIngest(ImporterStoreClient.java:158)
	at org.tikv.common.importer.ImporterClient.ingestWithRetry(ImporterClient.java:266)
	at org.tikv.common.importer.ImporterClient.ingest(ImporterClient.java:261)
	at org.tikv.common.importer.ImporterClient.write(ImporterClient.java:136)
	at org.tikv.bulkload.RawKVBulkLoader.ingestWithRetry(RawKVBulkLoader.scala:237)
	at org.tikv.bulkload.RawKVBulkLoader.writeAndIngest(RawKVBulkLoader.scala:201)
	at org.tikv.bulkload.RawKVBulkLoader.$anonfun$bulkLoad$1(RawKVBulkLoader.scala:118)
	at org.tikv.bulkload.RawKVBulkLoader.$anonfun$bulkLoad$1$adapted(RawKVBulkLoader.scala:117)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1011)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1011)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2268)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
22/09/30 20:23:46 INFO Executor: Finished task 18.0 in stage 8.0 (TID 68). 1189 bytes result sent to driver
22/09/30 20:23:46 INFO TaskSetManager: Finished task 18.0 in stage 8.0 (TID 68) in 4497 ms on 10.224.30.68 (executor driver) (28/34)
22/09/30 20:23:46 INFO Executor: Finished task 21.0 in stage 8.0 (TID 71). 1189 bytes result sent to driver
22/09/30 20:23:46 INFO TaskSetManager: Finished task 21.0 in stage 8.0 (TID 71) in 4513 ms on 10.224.30.68 (executor driver) (29/34)
22/09/30 20:23:46 INFO Executor: Finished task 0.0 in stage 8.0 (TID 50). 1189 bytes result sent to driver
22/09/30 20:23:46 INFO TaskSetManager: Finished task 0.0 in stage 8.0 (TID 50) in 4531 ms on 10.224.30.68 (executor driver) (30/34)
22/09/30 20:23:46 INFO Executor: Finished task 15.0 in stage 8.0 (TID 65). 1189 bytes result sent to driver
22/09/30 20:23:46 INFO TaskSetManager: Finished task 15.0 in stage 8.0 (TID 65) in 4532 ms on 10.224.30.68 (executor driver) (31/34)
22/09/30 20:23:46 INFO Executor: Finished task 6.0 in stage 8.0 (TID 56). 1189 bytes result sent to driver
22/09/30 20:23:46 INFO TaskSetManager: Finished task 6.0 in stage 8.0 (TID 56) in 4590 ms on 10.224.30.68 (executor driver) (32/34)
22/09/30 20:23:46 INFO Executor: Finished task 30.0 in stage 8.0 (TID 80). 1189 bytes result sent to driver
22/09/30 20:23:46 INFO TaskSetManager: Finished task 30.0 in stage 8.0 (TID 80) in 4604 ms on 10.224.30.68 (executor driver) (33/34)
22/09/30 20:23:48 WARN ImporterClient: ingest failed.
org.tikv.common.exception.RegionException: Region Exception occurred EpochNotMatch conf_ver: 348 version: 16 != conf_ver: 353 version: 16
	at org.tikv.common.importer.ImporterStoreClient.multiIngest(ImporterStoreClient.java:158)
	at org.tikv.common.importer.ImporterClient.ingestWithRetry(ImporterClient.java:266)
	at org.tikv.common.importer.ImporterClient.ingest(ImporterClient.java:261)
	at org.tikv.common.importer.ImporterClient.write(ImporterClient.java:136)
	at org.tikv.bulkload.RawKVBulkLoader.ingestWithRetry(RawKVBulkLoader.scala:237)
	at org.tikv.bulkload.RawKVBulkLoader.$anonfun$ingestWithRetry$1(RawKVBulkLoader.scala:273)
	at org.tikv.bulkload.RawKVBulkLoader.$anonfun$ingestWithRetry$1$adapted(RawKVBulkLoader.scala:251)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at org.tikv.bulkload.RawKVBulkLoader.ingestWithRetry(RawKVBulkLoader.scala:251)
	at org.tikv.bulkload.RawKVBulkLoader.writeAndIngest(RawKVBulkLoader.scala:201)
	at org.tikv.bulkload.RawKVBulkLoader.$anonfun$bulkLoad$1(RawKVBulkLoader.scala:118)
	at org.tikv.bulkload.RawKVBulkLoader.$anonfun$bulkLoad$1$adapted(RawKVBulkLoader.scala:117)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1011)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1011)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2268)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
22/09/30 20:23:52 INFO Executor: Finished task 33.0 in stage 8.0 (TID 83). 1189 bytes result sent to driver
22/09/30 20:23:52 INFO TaskSetManager: Finished task 33.0 in stage 8.0 (TID 83) in 11327 ms on 10.224.30.68 (executor driver) (34/34)
22/09/30 20:23:52 INFO TaskSchedulerImpl: Removed TaskSet 8.0, whose tasks have all completed, from pool
22/09/30 20:23:52 INFO DAGScheduler: ResultStage 8 (foreachPartition at RawKVBulkLoader.scala:117) finished in 11.339 s
22/09/30 20:23:52 INFO DAGScheduler: Job 3 is finished. Cancelling potential speculative or zombie tasks for this job
22/09/30 20:23:52 INFO TaskSchedulerImpl: Killing all running tasks in stage 8: Stage finished
22/09/30 20:23:52 INFO DAGScheduler: Job 3 finished: foreachPartition at RawKVBulkLoader.scala:117, took 13.142837 s
22/09/30 20:23:52 INFO PDClient: checker merge resumed
22/09/30 20:23:53 INFO RawKVBulkLoader: finish to load data.
22/09/30 20:23:53 INFO BulkLoadExample$: total time: 25s```

**Comment by andylokandy** [comment]
cc @haojinming

**Comment by haojinming** [comment]
@chrislusf could you help paste the configuration of `tikv-server` ?

**Comment by haojinming** [comment]
`EpochNotMatch` is an expected error and should retry [here](  https://github.com/tikv/migration/blob/b559233b0f166429b904b8a4390db310a966dacb/online-bulk-load/src/main/scala/org/tikv/bulkload/RawKVBulkLoader.scala#L240-L272). And timeout is set [60s](https://github.com/tikv/migration/blob/b559233b0f166429b904b8a4390db310a966dacb/online-bulk-load/src/main/scala/org/tikv/bulkload/RawKVBulkLoader.scala#L200). The log shows that just takes 25s totally. Not sure why the exception is thrown. @chrislusf do you see any retry info in log file?

**Comment by chrislusf** [comment]
We tested with an empty tikv cluster with 100 tikv servers and 3 pd servers. Nothing else special.
We ran the spark bulk loading example job in local mode with 10 million records and 10 partitions.

**Comment by haojinming** [comment]
I check the log again and found that bulk load actualy succeed and the result log `RawKVBulkLoader: finish to load data` has been print. The error message in the log is just the warning when ingest failed in the inner process, `bulk load` will do retry and it finally succeed.  @chrislusf

**Comment by chrislusf** [comment]
how to manually trigger the pd to balance the data better?

**Comment by haojinming** [comment]
> how to manually trigger the pd to balance the data better? Noticed some servers much more .sst files than other servers.

May refer here https://docs.pingcap.com/zh/tidb/dev/pd-control#scheduler-describe-balance-region-scheduler, or launch new discussion in [pd repo](https://github.com/tikv/pd).
