### ISSUE TITLE
Unstable test `cases::test_replica_stale_read::test_stale_read_on_learner`

### ISSUE THREAD

**Issue by purelind** [tikv/tikv#10607]
## Bug Report

unstable tests
```shell
[2021-07-19T08:05:48.916Z] failures:

[2021-07-19T08:05:48.916Z] 

[2021-07-19T08:05:48.916Z] failures:

[2021-07-19T08:05:48.916Z]     cases::test_replica_stale_read::test_stale_read_on_learner

[2021-07-19T08:05:48.916Z]     cases::test_replica_stale_read::test_stale_read_while_region_merge

[2021-07-19T08:05:48.916Z]     cases::test_snap::test_cancel_snapshot_generating

[2021-07-19T08:05:48.916Z] 

[2021-07-19T08:05:48.916Z] test result: FAILED. 138 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out; finished in 195.57s

[2021-07-19T08:05:48.916Z] 

[2021-07-19T08:05:49.479Z] error: test failed, to rerun pass '-p tests --test failpoints'
```

stack backtrace
```shell
[2021-07-19T08:04:26.146Z] thread 'cases::test_replica_stale_read::test_stale_read_on_learner' panicked at 'message: "peer 4 is not ready, safe_ts 138, region 1" data_is_not_ready { region_id: 1 peer_id: 4 safe_ts: 138 }', components/test_raftstore/src/util.rs:865:5

[2021-07-19T08:04:26.146Z] stack backtrace:

[2021-07-19T08:04:26.146Z]    0: rust_begin_unwind

[2021-07-19T08:04:26.146Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/panicking.rs:493:5

[2021-07-19T08:04:26.146Z]    1: std::panicking::begin_panic_fmt

[2021-07-19T08:04:26.146Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/panicking.rs:435:5

[2021-07-19T08:04:26.404Z]    2: test_raftstore::util::must_kv_read_equal

[2021-07-19T08:04:26.404Z]              at /home/jenkins/agent/workspace/tikv_nightly_test_arm64_master/go/src/github.com/pingcap/tikv/components/test_raftstore/src/util.rs:865:5

[2021-07-19T08:04:26.404Z]    3: failpoints::cases::test_replica_stale_read::PeerClient::must_kv_read_equal

[2021-07-19T08:04:26.404Z]              at ./failpoints/cases/test_replica_stale_read.rs:44:9

[2021-07-19T08:04:26.404Z]    4: failpoints::cases::test_replica_stale_read::test_stale_read_on_learner

[2021-07-19T08:04:26.404Z]              at ./failpoints/cases/test_replica_stale_read.rs:660:5

[2021-07-19T08:04:26.404Z]    5: failpoints::cases::test_replica_stale_read::test_stale_read_on_learner::{{closure}}

[2021-07-19T08:04:26.404Z]              at ./failpoints/cases/test_replica_stale_read.rs:643:1

[2021-07-19T08:04:26.404Z]    6: core::ops::function::FnOnce::call_once

[2021-07-19T08:04:26.404Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/ops/function.rs:227:5

[2021-07-19T08:04:26.404Z]    7: test_util::runner::run_test_with_hook::{{closure}}::{{closure}}

[2021-07-19T08:04:26.404Z]              at /home/jenkins/agent/workspace/tikv_nightly_test_arm64_master/go/src/github.com/pingcap/tikv/components/test_util/src/runner.rs:64:21

[2021-07-19T08:04:26.404Z]    8: core::ops::function::FnOnce::call_once{{vtable.shim}}

[2021-07-19T08:04:26.404Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/ops/function.rs:227:5

[2021-07-19T08:04:26.404Z]    9: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once

[2021-07-19T08:04:26.404Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/alloc/src/boxed.rs:1546:9

[2021-07-19T08:04:26.404Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

[2021-07-19T08:04:26.664Z] test cases::test_replica_stale_read::test_stale_read_on_learner ... FAILED

[2021-07-19T08:04:27.604Z] test cases::test_replica_stale_read::test_stale_read_while_applying_snapshot ... ok

[2021-07-19T08:04:34.181Z] thread 'cases::test_replica_stale_read::test_stale_read_while_region_merge' panicked at 'message: "peer 2 is not ready, safe_ts 136, region 1" data_is_not_ready { region_id: 1 peer_id: 2 safe_ts: 136 }', components/test_raftstore/src/util.rs:865:5

[2021-07-19T08:04:34.181Z] stack backtrace:

[2021-07-19T08:04:34.181Z]    0: rust_begin_unwind

[2021-07-19T08:04:34.181Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/panicking.rs:493:5

[2021-07-19T08:04:34.181Z]    1: std::panicking::begin_panic_fmt

[2021-07-19T08:04:34.181Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/panicking.rs:435:5

[2021-07-19T08:04:34.181Z]    2: test_raftstore::util::must_kv_read_equal

[2021-07-19T08:04:34.181Z]              at /home/jenkins/agent/workspace/tikv_nightly_test_arm64_master/go/src/github.com/pingcap/tikv/components/test_raftstore/src/util.rs:865:5

[2021-07-19T08:04:34.181Z]    3: failpoints::cases::test_replica_stale_read::PeerClient::must_kv_read_equal

[2021-07-19T08:04:34.181Z]              at ./failpoints/cases/test_replica_stale_read.rs:44:9

[2021-07-19T08:04:34.181Z]    4: failpoints::cases::test_replica_stale_read::test_stale_read_while_region_merge

[2021-07-19T08:04:34.181Z]              at ./failpoints/cases/test_replica_stale_read.rs:481:5

[2021-07-19T08:04:34.181Z]    5: failpoints::cases::test_replica_stale_read::test_stale_read_while_region_merge::{{closure}}

[2021-07-19T08:04:34.181Z]              at ./failpoints/cases/test_replica_stale_read.rs:437:1

[2021-07-19T08:04:34.181Z]    6: core::ops::function::FnOnce::call_once

[2021-07-19T08:04:34.181Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/ops/function.rs:227:5

[2021-07-19T08:04:34.181Z]    7: test_util::runner::run_test_with_hook::{{closure}}::{{closure}}

[2021-07-19T08:04:34.181Z]              at /home/jenkins/agent/workspace/tikv_nightly_test_arm64_master/go/src/github.com/pingcap/tikv/components/test_util/src/runner.rs:64:21

[2021-07-19T08:04:34.181Z]    8: core::ops::function::FnOnce::call_once{{vtable.shim}}

[2021-07-19T08:04:34.181Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/ops/function.rs:227:5

[2021-07-19T08:04:34.181Z]    9: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once

[2021-07-19T08:04:34.181Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/alloc/src/boxed.rs:1546:9

[2021-07-19T08:04:34.181Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

[2021-07-19T08:04:34.181Z] test cases::test_replica_stale_read::test_stale_read_while_region_merge ... FAILED

[2021-07-19T08:04:35.127Z] test cases::test_replica_stale_read::test_update_apply_index_before_sync_read_state ... ok

[2021-07-19T08:04:36.067Z] test cases::test_replica_stale_read::test_update_resoved_ts_before_apply_index ... ok

[2021-07-19T08:04:38.601Z] test cases::test_server::test_mismatch_store_node ... ok

[2021-07-19T08:04:45.170Z] thread 'cases::test_snap::test_cancel_snapshot_generating' panicked at '[region 1] log is still not truncated to 29: index: 23 term: 6 on store 1', /home/jenkins/agent/workspace/tikv_nightly_test_arm64_master/go/src/github.com/pingcap/tikv/components/test_raftstore/src/cluster.rs:1066:17

[2021-07-19T08:04:45.170Z] stack backtrace:

[2021-07-19T08:04:45.170Z]    0: rust_begin_unwind

[2021-07-19T08:04:45.170Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/panicking.rs:493:5

[2021-07-19T08:04:45.170Z]    1: std::panicking::begin_panic_fmt

[2021-07-19T08:04:45.170Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/panicking.rs:435:5

[2021-07-19T08:04:45.170Z]    2: test_raftstore::cluster::Cluster<T>::wait_log_truncated

[2021-07-19T08:04:45.170Z]              at /home/jenkins/agent/workspace/tikv_nightly_test_arm64_master/go/src/github.com/pingcap/tikv/components/test_raftstore/src/cluster.rs:1066:17

[2021-07-19T08:04:45.170Z]    3: failpoints::cases::test_snap::test_cancel_snapshot_generating

[2021-07-19T08:04:45.170Z]              at ./failpoints/cases/test_snap.rs:451:5

[2021-07-19T08:04:45.170Z]    4: failpoints::cases::test_snap::test_cancel_snapshot_generating::{{closure}}

[2021-07-19T08:04:45.170Z]              at ./failpoints/cases/test_snap.rs:419:1

[2021-07-19T08:04:45.170Z]    5: core::ops::function::FnOnce::call_once

[2021-07-19T08:04:45.170Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/ops/function.rs:227:5

[2021-07-19T08:04:45.170Z]    6: test_util::runner::run_test_with_hook::{{closure}}::{{closure}}

[2021-07-19T08:04:45.171Z]              at /home/jenkins/agent/workspace/tikv_nightly_test_arm64_master/go/src/github.com/pingcap/tikv/components/test_util/src/runner.rs:64:21

[2021-07-19T08:04:45.171Z]    7: core::ops::function::FnOnce::call_once{{vtable.shim}}

[2021-07-19T08:04:45.171Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/ops/function.rs:227:5

[2021-07-19T08:04:45.171Z]    8: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once

[2021-07-19T08:04:45.171Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/alloc/src/boxed.rs:1546:9

[2021-07-19T08:04:45.171Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### What version of TiKV are you using?
branch master

### Steps to reproduce

`make dev`
### What did happened?
in ci https://ci.pingcap.net/blue/organizations/jenkins/tikv_nightly_test_arm64/detail/master/25/pipeline

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further feedback regarding this issue has been reported, it can be safely closed.
