### ISSUE TITLE
Unstable test `server::raft_client::test_tombstone_block_list`

### ISSUE THREAD

**Issue by zhouqiang-cl** [tikv/tikv#10639]
## Bug Report

```
[2021-07-27T13:50:19.344Z] test server::raft_client::test_tombstone_block_list ... thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Disconnected', tests/integrations/server/raft_client.rs:312:39

[2021-07-27T13:50:19.344Z] stack backtrace:

[2021-07-27T13:50:19.603Z]    0: rust_begin_unwind

[2021-07-27T13:50:19.603Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/panicking.rs:493:5

[2021-07-27T13:50:19.603Z]    1: core::panicking::panic_fmt

[2021-07-27T13:50:19.603Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/panicking.rs:92:14

[2021-07-27T13:50:19.603Z]    2: core::result::unwrap_failed

[2021-07-27T13:50:19.603Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/result.rs:1355:5

[2021-07-27T13:50:19.603Z]    3: core::result::Result<T,E>::unwrap

[2021-07-27T13:50:19.603Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/result.rs:1037:23

[2021-07-27T13:50:19.603Z]    4: integrations::server::raft_client::test_tombstone_block_list

[2021-07-27T13:50:19.604Z]              at /home/jenkins/tikv-src/tests/integrations/server/raft_client.rs:312:5

[2021-07-27T13:50:19.604Z]    5: integrations::server::raft_client::test_tombstone_block_list::{{closure}}

[2021-07-27T13:50:19.604Z]              at /home/jenkins/tikv-src/tests/integrations/server/raft_client.rs:266:1

[2021-07-27T13:50:19.604Z]    6: core::ops::function::FnOnce::call_once

[2021-07-27T13:50:19.604Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/ops/function.rs:227:5

[2021-07-27T13:50:19.604Z]    7: test_util::runner::run_test_with_hook::{{closure}}::{{closure}}

[2021-07-27T13:50:19.604Z]              at /home/jenkins/tikv-src/components/test_util/src/runner.rs:64:21

[2021-07-27T13:50:19.604Z]    8: core::ops::function::FnOnce::call_once{{vtable.shim}}

[2021-07-27T13:50:19.604Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/ops/function.rs:227:5

[2021-07-27T13:50:19.604Z]    9: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once

[2021-07-27T13:50:19.604Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/alloc/src/boxed.rs:1546:9

[2021-07-27T13:50:19.604Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

[2021-07-27T13:50:19.604Z] FAILED
```
### Steps to reproduce

in ci https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/4938/pipeline

**Comment by hicqu** [comment]
@BusyJay would you mind to take a look?

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further feedback regarding this issue has been reported, it can be safely closed.
