### ISSUE TITLE
Test storage::txn::flow_controller::tests::test_flow_controller_l0 fails

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#11088]
## Bug Report

https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/9106/pipeline#step-322-log-216

```
[2021-10-18T09:25:07.577Z] test storage::txn::flow_controller::tests::test_flow_controller_l0 ... thread 'main' panicked at 'assertion failed: `(left == right)`

[2021-10-18T09:25:07.577Z]   left: `true`,

[2021-10-18T09:25:07.577Z]  right: `false`', src/storage/txn/flow_controller.rs:1060:9

[2021-10-18T09:25:07.577Z] stack backtrace:

[2021-10-18T09:25:08.143Z]    0: rust_begin_unwind

[2021-10-18T09:25:08.143Z]              at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/panicking.rs:515:5

[2021-10-18T09:25:08.143Z]    1: core::panicking::panic_fmt

[2021-10-18T09:25:08.143Z]              at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/panicking.rs:92:14

[2021-10-18T09:25:08.143Z]    2: core::panicking::assert_failed_inner

[2021-10-18T09:25:08.143Z]    3: core::panicking::assert_failed

[2021-10-18T09:25:08.143Z]              at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/panicking.rs:117:5

[2021-10-18T09:25:08.402Z]    4: tikv::storage::txn::flow_controller::tests::test_flow_controller_l0

[2021-10-18T09:25:08.402Z]              at /home/jenkins/tikv-src/src/storage/txn/flow_controller.rs:1060:9

[2021-10-18T09:25:08.402Z]    5: tikv::storage::txn::flow_controller::tests::test_flow_controller_l0::{{closure}}

[2021-10-18T09:25:08.402Z]              at /home/jenkins/tikv-src/src/storage/txn/flow_controller.rs:1033:5

[2021-10-18T09:25:08.402Z]    6: core::ops::function::FnOnce::call_once

[2021-10-18T09:25:08.402Z]              at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/ops/function.rs:227:5

[2021-10-18T09:25:08.402Z]    7: core::ops::function::FnOnce::call_once

[2021-10-18T09:25:08.402Z]              at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/ops/function.rs:227:5

[2021-10-18T09:25:08.402Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

[2021-10-18T09:25:08.661Z] FAILED

```

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further feedback regarding this issue has been reported, it can be safely closed.
