### ISSUE TITLE
Unstable test `server_encryption::test_node_snapshot_encryption`

### ISSUE THREAD

**Issue by zhouqiang-cl** [tikv/tikv#11184]
## Bug Report

```
[2021-10-28T16:50:05.486Z] test server_encryption::test_node_snapshot_encryption ... thread 'main' panicked at 'request timeout', /home/jenkins/tikv-src/components/test_raftstore/src/cluster.rs:830:9
[2021-10-28T16:50:05.486Z] stack backtrace:
[2021-10-28T16:50:05.486Z]    0: std::panicking::begin_panic
[2021-10-28T16:50:05.486Z]              at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/panicking.rs:541:12
[2021-10-28T16:50:05.486Z]    1: test_raftstore::cluster::Cluster<T>::request
[2021-10-28T16:50:05.486Z]              at /home/jenkins/tikv-src/components/test_raftstore/src/cluster.rs:830:9
[2021-10-28T16:50:05.486Z]    2: test_raftstore::cluster::Cluster<T>::batch_put
[2021-10-28T16:50:05.486Z]              at /home/jenkins/tikv-src/components/test_raftstore/src/cluster.rs:992:20
[2021-10-28T16:50:05.486Z]    3: test_raftstore::cluster::Cluster<T>::must_put_cf
[2021-10-28T16:50:05.486Z]              at /home/jenkins/tikv-src/components/test_raftstore/src/cluster.rs:971:15
[2021-10-28T16:50:05.486Z]    4: test_raftstore::cluster::Cluster<T>::must_put
[2021-10-28T16:50:05.486Z]              at /home/jenkins/tikv-src/components/test_raftstore/src/cluster.rs:967:9
[2021-10-28T16:50:05.486Z]    5: integrations::server_encryption::test_snapshot_encryption
[2021-10-28T16:50:05.486Z]              at /home/jenkins/tikv-src/tests/integrations/server_encryption.rs:10:9
[2021-10-28T16:50:05.486Z]    6: integrations::server_encryption::test_node_snapshot_encryption
[2021-10-28T16:50:05.486Z]              at /home/jenkins/tikv-src/tests/integrations/server_encryption.rs:27:5
[2021-10-28T16:50:05.486Z]    7: integrations::server_encryption::test_node_snapshot_encryption::{{closure}}
[2021-10-28T16:50:05.486Z]              at /home/jenkins/tikv-src/tests/integrations/server_encryption.rs:25:1
[2021-10-28T16:50:05.486Z]    8: core::ops::function::FnOnce::call_once
[2021-10-28T16:50:05.486Z]              at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/ops/function.rs:227:5
[2021-10-28T16:50:05.486Z]    9: test_util::runner::run_test_with_hook::{{closure}}::{{closure}}
[2021-10-28T16:50:05.486Z]              at /home/jenkins/tikv-src/components/test_util/src/runner.rs:64:21
[2021-10-28T16:50:05.486Z]   10: core::ops::function::FnOnce::call_once{{vtable.shim}}
[2021-10-28T16:50:05.486Z]              at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/ops/function.rs:227:5
[2021-10-28T16:50:05.486Z]   11: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
[2021-10-28T16:50:05.486Z]              at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/alloc/src/boxed.rs:1572:9
[2021-10-28T16:50:05.486Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2021-10-28T16:50:08.023Z] FAILED
[2021-10-28T16:50:09.402Z] test server_encryption::test_server_snapshot_encryption ... thread 'enc:key' panicked at 'EncryptedFile::write /tmp/test_clustervNvkfL/key.7739186824189709623.tmp', components/encryption/src/encrypted_file/mod.rs:73:33
[2021-10-28T16:50:09.402Z] stack backtrace:
[2021-10-28T16:50:09.403Z] thread 'enc:key' panicked at 'EncryptedFile::write /tmp/test_cluster6asDcH/key.256383481611978415.tmp', components/encryption/src/encrypted_file/mod.rs:73:33
[2021-10-28T16:50:09.403Z]    0: rust_begin_unwind
[2021-10-28T16:50:09.403Z]              at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/panicking.rs:515:5
[2021-10-28T16:50:09.403Z]    1: std::panicking::begin_panic_fmt
[2021-10-28T16:50:09.403Z]              at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/panicking.rs:457:5
[2021-10-28T16:50:09.403Z]    2: encryption::encrypted_file::EncryptedFile::write::{{closure}}
[2021-10-28T16:50:09.403Z]              at /home/jenkins/tikv-src/components/encryption/src/encrypted_file/mod.rs:73:33
[2021-10-28T16:50:09.403Z]    3: core::result::Result<T,E>::unwrap_or_else
[2021-10-28T16:50:09.403Z]              at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/result.rs:1065:23
[2021-10-28T16:50:09.403Z]    4: encryption::encrypted_file::EncryptedFile::write
[2021-10-28T16:50:09.403Z]              at /home/jenkins/tikv-src/components/encryption/src/encrypted_file/mod.rs:69:28
[2021-10-28T16:50:09.403Z]    5: encryption::manager::Dicts::save_key_dict
[2021-10-28T16:50:09.403Z]              at /home/jenkins/tikv-src/components/encryption/src/manager/mod.rs:154:9
[2021-10-28T16:50:09.403Z]    6: encryption::manager::Dicts::rotate_key
[2021-10-28T16:50:09.403Z]              at /home/jenkins/tikv-src/components/encryption/src/manager/mod.rs:287:9
[2021-10-28T16:50:09.403Z]    7: encryption::manager::Dicts::maybe_rotate_data_key
[2021-10-28T16:50:09.403Z]              at /home/jenkins/tikv-src/components/encryption/src/manager/mod.rs:336:9
[2021-10-28T16:50:09.403Z]    8: encryption::manager::run_background_rotate_work
[2021-10-28T16:50:09.403Z]              at /home/jenkins/tikv-src/components/encryption/src/manager/mod.rs:377:17
[2021-10-28T16:50:09.403Z]    9: encryption::manager::DataKeyManager::from_dicts::{{closure}}
[2021-10-28T16:50:09.403Z]              at /home/jenkins/tikv-src/components/encryption/src/manager/mod.rs:555:17
[2021-10-28T16:50:09.403Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2021-10-28T16:50:09.403Z] stack backtrace:
[2021-10-28T16:50:09.403Z]    0: rust_begin_unwind
[2021-10-28T16:50:09.403Z]              at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/panicking.rs:515:5
[2021-10-28T16:50:09.403Z]    1: std::panicking::begin_panic_fmt
[2021-10-28T16:50:09.403Z]              at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/panicking.rs:457:5
[2021-10-28T16:50:09.403Z]    2: encryption::encrypted_file::EncryptedFile::write::{{closure}}
[2021-10-28T16:50:09.403Z]              at /home/jenkins/tikv-src/components/encryption/src/encrypted_file/mod.rs:73:33
[2021-10-28T16:50:09.403Z]    3: core::result::Result<T,E>::unwrap_or_else
[2021-10-28T16:50:09.403Z]              at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/result.rs:1065:23
[2021-10-28T16:50:09.403Z]    4: encryption::encrypted_file::EncryptedFile::write
[2021-10-28T16:50:09.403Z]              at /home/jenkins/tikv-src/components/encryption/src/encrypted_file/mod.rs:69:28
[2021-10-28T16:50:09.403Z]    5: encryption::manager::Dicts::save_key_dict
[2021-10-28T16:50:09.403Z]              at /home/jenkins/tikv-src/components/encryption/src/manager/mod.rs:154:9
[2021-10-28T16:50:09.403Z]    6: encryption::manager::Dicts::rotate_key
[2021-10-28T16:50:09.403Z]              at /home/jenkins/tikv-src/components/encryption/src/manager/mod.rs:287:9
[2021-10-28T16:50:09.403Z]    7: encryption::manager::Dicts::maybe_rotate_data_key
[2021-10-28T16:50:09.403Z]              at /home/jenkins/tikv-src/components/encryption/src/manager/mod.rs:336:9
[2021-10-28T16:50:09.403Z]    8: encryption::manager::run_background_rotate_work
[2021-10-28T16:50:09.403Z]              at /home/jenkins/tikv-src/components/encryption/src/manager/mod.rs:377:17
[2021-10-28T16:50:09.403Z]    9: encryption::manager::DataKeyManager::from_dicts::{{closure}}
[2021-10-28T16:50:09.403Z]              at /home/jenkins/tikv-src/components/encryption/src/manager/mod.rs:555:17
```
### Steps to reproduce

in ci https://ci.pingcap.net/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/9785/nodes/105/steps/261/log/?start=0

**Comment by BusyJay** [comment]
This is probably a bug.
