### ISSUE TITLE
test_resolve::test_joint_confchange failed

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#11325]
### What version of TiKV are you using?
Nightly

### What operating system and CPU are you using?
Linux

### Steps to reproduce
Make dev

### What did you expect?
Tests pass.

### What did happened?
It failed occasionally.

```
test test_resolve::test_joint_confchange ... thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', components/cdc/tests/failpoints/../mod.rs:69:87
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/result.rs:1599:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/result.rs:1281:23
   4: failpoints::testsuite::new_event_feed::{{closure}}
             at /home/jenkins/tikv-src/components/cdc/tests/failpoints/../mod.rs:69:34
   5: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/alloc/src/boxed.rs:1586:9
   6: failpoints::test_resolve::test_joint_confchange::{{closure}}
             at /home/jenkins/tikv-src/components/cdc/tests/failpoints/test_resolve.rs:191:25
   7: failpoints::test_resolve::test_joint_confchange
             at /home/jenkins/tikv-src/components/cdc/tests/failpoints/test_resolve.rs:235:5
   8: failpoints::test_resolve::test_joint_confchange::{{closure}}
             at /home/jenkins/tikv-src/components/cdc/tests/failpoints/test_resolve.rs:181:1
   9: core::ops::function::FnOnce::call_once
             at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/ops/function.rs:227:5
  10: test_util::runner::run_test_with_hook::{{closure}}::{{closure}}
             at /home/jenkins/tikv-src/components/test_util/src/runner.rs:64:21
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/ops/function.rs:227:5
  12: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/alloc/src/boxed.rs:1572:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
FAILED
```

Logs can be found at https://ci.pingcap.net/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/10866/nodes/104/steps/191/log/?start=0.

**Comment by BusyJay** [comment]
Another case: https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/11117/pipeline/

**Comment by BusyJay** [comment]
Any updates? /cc @overvenus 

If no one is going to fix the issue, I will disable the case in this week.

**Comment by BusyJay** [comment]
Latest logs about the failing case can be found at https://ci.pingcap.net/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/14378/nodes/101/steps/164/log/?start=0.

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further feedback regarding this issue has been reported, it can be safely closed.
