### ISSUE TITLE
tikv panicked in parse_proc_cgroup_v2

### ISSUE THREAD

**Issue by duament** [tikv/tikv#11609]
### What version of TiKV are you using?
 5.3.0

### What operating system and CPU are you using?

Ubuntu 20.04 in systemd-nspawn container (host kernel 5.15.2)
x86_64

### Steps to reproduce

`tiup cluster deploy tidb-test v5.3.0 ./topology.yaml --user root -i .ssh/id_ed25519`
(using config-templates/simple-mini.yaml)

### What did you expect?
Deploy successfully

### What did happened?
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `1`', components/tikv_util/src/sys/cgroup.rs:167:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

tiup log:
```
{"task": "UserSSH: user=tidb, host=192.168.180.86\nMkdir: host=192.168.180.86, directories='/tidb-deploy/tikv-20160','/tidb-deploy/tikv-20160/log','/tidb-deploy/tikv-20160/bin','/tidb-deploy/tikv-20160/conf','/tidb-deploy/tikv-20160/scripts'\nMkdir: host=192.168.180.86, directories='/tidb-data/tikv-20160'\nCopyComponent: component=tikv, version=v5.3.0, remote=192.168.180.86:/tidb-deploy/tikv-20160 os=linux, arch=amd64\nInitConfig: cluster=tidb-test, user=tidb, host=192.168.180.86, path=/root/.tiup/storage/cluster/clusters/tidb-test/config-cache/tikv-20160.service, deploy_dir=/tidb-deploy/tikv-20160, data_dir=[/tidb-data/tikv-20160], log_dir=/tidb-deploy/tikv-20160/log, cache_dir=/root/.tiup/storage/cluster/clusters/tidb-test/config-cache", "error": "init config failed: 192.168.180.86:20160: executor.ssh.execute_failed: Failed to execute command over SSH for 'tidb@192.168.180.86:22' {ssh_stderr: thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `2`,\n right: `1`', components/tikv_util/src/sys/cgroup.rs:167:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n, ssh_stdout: , ssh_command: export LANG=C; PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin /tidb-deploy/tikv-20160/bin/tikv-server --config-check --config=/tidb-deploy/tikv-20160/conf/tikv.toml --pd \"\" --data-dir \"/tidb-data/tikv-20160\"}, cause: Process exited with status 101: check config failed", "errorVerbose": "check config failed\nexecutor.ssh.execute_failed: Failed to execute command over SSH for 'tidb@192.168.180.86:22' {ssh_stderr: thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `2`,\n right: `1`', components/tikv_util/src/sys/cgroup.rs:167:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n, ssh_stdout: , ssh_command: export LANG=C; PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin /tidb-deploy/tikv-20160/bin/tikv-server --config-check --config=/tidb-deploy/tikv-20160/conf/tikv.toml --pd \"\" --data-dir \"/tidb-data/tikv-20160\"}, cause: Process exited with status 101\ngithub.com/pingcap/tiup/pkg/cluster/spec.checkConfig\n\tgithub.com/pingcap/tiup/pkg/cluster/spec/server_config.go:308\ngithub.com/pingcap/tiup/pkg/cluster/spec.(*TiKVInstance).InitConfig\n\tgithub.com/pingcap/tiup/pkg/cluster/spec/tikv.go:284\ngithub.com/pingcap/tiup/pkg/cluster/task.(*InitConfig).Execute\n\tgithub.com/pingcap/tiup/pkg/cluster/task/init_config.go:51\ngithub.com/pingcap/tiup/pkg/cluster/task.(*Serial).Execute\n\tgithub.com/pingcap/tiup/pkg/cluster/task/task.go:85\ngithub.com/pingcap/tiup/pkg/cluster/task.(*StepDisplay).Execute\n\tgithub.com/pingcap/tiup/pkg/cluster/task/step.go:111\ngithub.com/pingcap/tiup/pkg/cluster/task.(*Parallel).Execute.func1\n\tgithub.com/pingcap/tiup/pkg/cluster/task/task.go:142\nruntime.goexit\n\truntime/asm_amd64.s:1581\ninit config failed: 192.168.180.86:20160"}
```

I noticed my `/proc/self/cgroup` has 2 lines:
```
root@focal:~# cat /proc/self/cgroup 
1:name=systemd:/
0::/user.slice/user-0.slice/session-13.scope
```

*Edit*: It seems the strange 2-line `/proc/self/cgroup` is a result of running centos 7 in nspawn container (Image from https://hub.nspawn.org/images/). It restored 1-line after a reboot.

**Comment by sticnarf** [comment]
From the [cgroup v2 doc](https://www.kernel.org/doc/Documentation/cgroup-v2.txt):

> "/proc/$PID/cgroup" lists a process's cgroup membership.  If legacy cgroup is in use in the system, this file may contain multiple lines, one for each hierarchy.  The entry for cgroup v2 is always in the format "0::$PATH"::

This two-line cgroup file is definitely not conformant with the spec.

I'm guessing some systemd bug in the centos 7 (which contains a rather old systemd) breaks the unified hierachy of the cgroup v2...

**Comment by sticnarf** [comment]
I think this should only happen with operating system bugs. Lower severity to minor.
