### ISSUE TITLE
Unstable test: resource_metering::test_read_keys::test_read_keys_coprocessor

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#11765]
## Bug Report

See https://ci.pingcap.net/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/14507/nodes/113/steps/272/log/?start=0 for details.

```
[2021-12-31T06:23:53.148Z] test resource_metering::test_read_keys::test_read_keys_coprocessor ... thread 'main' panicked at 'assertion failed: `(left == right)`
[2021-12-31T06:23:53.148Z]   left: `8`,
[2021-12-31T06:23:53.148Z]  right: `4`', tests/integrations/resource_metering/test_read_keys.rs:218:5
[2021-12-31T06:23:53.148Z] stack backtrace:
[2021-12-31T06:23:53.148Z]    0: rust_begin_unwind
[2021-12-31T06:23:53.148Z]              at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/panicking.rs:515:5
[2021-12-31T06:23:53.148Z]    1: core::panicking::panic_fmt
[2021-12-31T06:23:53.148Z]              at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/panicking.rs:92:14
[2021-12-31T06:23:53.148Z]    2: core::panicking::assert_failed_inner
[2021-12-31T06:23:53.406Z]    3: core::panicking::assert_failed
[2021-12-31T06:23:53.406Z]              at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/panicking.rs:117:5
[2021-12-31T06:23:53.406Z]    4: integrations::resource_metering::test_read_keys::test_read_keys_coprocessor
[2021-12-31T06:23:53.406Z]              at /home/jenkins/tikv-src/tests/integrations/resource_metering/test_read_keys.rs:218:5
[2021-12-31T06:23:53.406Z]    5: integrations::resource_metering::test_read_keys::test_read_keys_coprocessor::{{closure}}
[2021-12-31T06:23:53.406Z]              at /home/jenkins/tikv-src/tests/integrations/resource_metering/test_read_keys.rs:177:1
[2021-12-31T06:23:53.406Z]    6: core::ops::function::FnOnce::call_once
[2021-12-31T06:23:53.406Z]              at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/ops/function.rs:227:5
[2021-12-31T06:23:53.406Z]    7: test_util::runner::run_test_with_hook::{{closure}}::{{closure}}
[2021-12-31T06:23:53.406Z]              at /home/jenkins/tikv-src/components/test_util/src/runner.rs:64:21
[2021-12-31T06:23:53.406Z]    8: core::ops::function::FnOnce::call_once{{vtable.shim}}
[2021-12-31T06:23:53.406Z]              at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/ops/function.rs:227:5
[2021-12-31T06:23:53.406Z]    9: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
[2021-12-31T06:23:53.406Z]              at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/alloc/src/boxed.rs:1572:9
[2021-12-31T06:23:53.406Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by breeswish** [comment]
@mornyx PTAL~
