### ISSUE TITLE
 The two testcase test_rate_limited_light_flow,test_rate_limited_hybrid_flow failed by running `make test`

### ISSUE THREAD

**Issue by cosven** [tikv/tikv#12024]
### What version of TiKV are you using?
c92681f45bf0d1d8a395c7cbd569346e5d4f8f49

### What operating system and CPU are you using?

KVM(vcpu count 12)
```
processor       : 0                                                                                                                                                                                     
vendor_id       : GenuineIntel                                                                                                                                                                          
cpu family      : 6                                                                                                                                                                                     
model           : 61                                                                                                                                                                                    
model name      : Intel Core Processor (Broadwell, IBRS)                                                                                                                                                
stepping        : 2                                                                                                                                                                                     
microcode       : 0x1                                                                                                                                                                                   
cpu MHz         : 2199.996                                                                                                                                                                              
cache size      : 4096 KB                                                                                                                                                                               
physical id     : 0                                                                                                                                                                                     
siblings        : 1                                                                                                                                                                                     
core id         : 0                                                                                                                                                                                     
cpu cores       : 1                                                                                                                                                                                     
apicid          : 0                                                                                                                                                                                     
initial apicid  : 0                                                                                                                                                                                     
fpu             : yes                                                                                                                                                                                   
fpu_exception   : yes                                                                                                                                                                                   
cpuid level     : 13                                                                                                                                                                                    
wp              : yes                                                                                                                                                                                   
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good nopl cpuid tsc_known_freq pni pclmulqdq ssse3
 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm 3dnowprefetch invpcid_single pti ibrs ibpb fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed
 adx smap xsaveopt                                                                                                                                                                                      
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit srbds                                                                                          
bogomips        : 4399.99                                                                                                                                                                               
clflush size    : 64                                                                                                                                                                                    
cache_alignment : 64                                                                                                                                                                                    
address sizes   : 46 bits physical, 48 bits virtual                                                                                                                                                     
power management:         

...
...
...                                                                                                                                                                              
```

### Steps to reproduce
Just run make test.

### What did you expect?
`make test` pass

### What did happened?

```
...
...
running 19 tests                                                                                                                                                                                        
test file::tests::test_unix_file_allocate_failure ... ok                                                                                                                                                
test tests::test_delete_file_if_exist ... ok                                                                                                                                                            
test tests::test_create_delete_dir ... ok                                                                                                                                                               
test tests::test_file_exists ... ok                                                                                                                                                                     
test rate_limiter::tests::bench_critical_section ... ok                                                                                                                                                 
test tests::test_get_file_size ... ok                                                                                                                                                                   
test tests::test_sync_dir ... ok                                                                                                                                                                        
test tests::test_reserve_space_for_recover ... ok                                                                                                                                                       
test thread_io::tests::bench_fetch_thread_io_bytes ... ok                                                                                                                                               
test thread_io::tests::test_read_bytes ... ok                                                                                                                                                           
test thread_io::tests::test_write_bytes ... ok                                                                                                                                                          
thread 'rate_limiter::tests::test_rate_limited_light_flow' panicked at 'assertion failed: (stats.fetch(IOType::Compaction, IOOp::Write) as f64) >=\n    (actual_kbytes_per_sec as f64 * duration.as_secs
_f64() * 1000.0) * 0.85', components/file_system/src/rate_limiter.rs:757:9                                                                                                                              
stack backtrace:                                                                                                                                                                                        
thread 'rate_limiter::tests::test_rate_limited_hybrid_flow' panicked at 'assertion failed: (write_bytes as f64) >=\n    ((write_work * bytes_per_sec / 100) as f64 * duration.as_secs_f64()) *\n        
0.85', components/file_system/src/rate_limiter.rs:812:9                                                                                                                                                 
test file::tests::test_instrumented_file ... ok                                                                                                                                                         
test tests::test_calc_crc32 ... ok
   0:     0x55a780c0e08c - std::backtrace_rs::backtrace::libunwind::trace::h38d656af46687c91                                                                                                            
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5                                                       
   1:     0x55a780c0e08c - std::backtrace_rs::backtrace::trace_unsynchronized::h6463e81b43d545da                                                                                                        
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5                                                             
   2:     0x55a780c0e08c - std::sys_common::backtrace::_print_fmt::h7d0aeff1635ad318                                                                                                                    
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:66:5                                                                          
   3:     0x55a780c0e08c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he9ed9f7bc97615c6                                                                         
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:45:22                                                                         
   4:     0x55a780c3553c - core::fmt::write::h26fb070fd492e04f                                                                                                                                          
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/fmt/mod.rs:1190:17                                                                                   
   5:     0x55a780c095f8 - std::io::Write::write_fmt::ha7a1cfea3d855428                                                                                                                                 
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/io/mod.rs:1657:15                                                                                     
   6:     0x55a780c101b7 - std::sys_common::backtrace::_print::h6a43ee74b02286e0                                                                                                                        
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:48:5                                                                          
   7:     0x55a780c101b7 - std::sys_common::backtrace::print::hfe9d3eef26a9b46f                                                                                                                         
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:35:9                                                                          
   8:     0x55a780c101b7 - std::panicking::default_hook::{{closure}}::he3bbb991ed25ca71                                                                                                                 
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:295:22                                                                                   
   9:     0x55a780c0fe7f - std::panicking::default_hook::h4e425f0c50c308bd                                                                                                                              
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:314:9
  10:     0x55a780c1091a - std::panicking::rust_panic_with_hook::h22c18dec3fc9e708
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:698:17
  11:     0x55a780c105c9 - std::panicking::begin_panic_handler::{{closure}}::hd86c4a70dd9a9d4a
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:586:13
  12:     0x55a780c0e534 - std::sys_common::backtrace::__rust_end_short_backtrace::ha98c5d7cc0ee2da0
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55a780c10309 - rust_begin_unwind
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:584:5
  14:     0x55a780325503 - core::panicking::panic_fmt::h53f61fbdec3080b3
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panicking.rs:143:14
  15:     0x55a7803253cd - core::panicking::panic::h950eea06a1dc9ad4
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panicking.rs:48:5
  16:     0x55a78032ebe7 - file_system::rate_limiter::tests::test_rate_limited_light_flow::h933cddd5c791294b
                               at /home/cosven/pingcap/tikv/components/file_system/src/rate_limiter.rs:757:9
  17:     0x55a78033b19a - file_system::rate_limiter::tests::test_rate_limited_light_flow::{{closure}}::ha2e01ec65707cb87
                               at /home/cosven/pingcap/tikv/components/file_system/src/rate_limiter.rs:736:5
  18:     0x55a78033e88e - core::ops::function::FnOnce::call_once::h62f400ec4ded3162
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/ops/function.rs:227:5
  19:     0x55a780be2493 - core::ops::function::FnOnce::call_once::hc8bba15014c4beea
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/ops/function.rs:227:5
  20:     0x55a780be2493 - test::__rust_begin_short_backtrace::hd460fd9f75eeba5f
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/test/src/lib.rs:575:5
  21:     0x55a780be115d - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4ee9be99affacb0f
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/alloc/src/boxed.rs:1854:9
  22:     0x55a780be115d - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h28201f0d6ec2068a
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panic/unwind_safe.rs:271:9
  23:     0x55a780be115d - std::panicking::try::do_call::hc6185aa5fff2063e
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:492:40
  24:     0x55a780be115d - std::panicking::try::hb602029255393744
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:456:19
  25:     0x55a780be115d - std::panic::catch_unwind::heeeeea0671593c22
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panic.rs:137:14
  26:     0x55a780be115d - test::run_test_in_process::h3ce9cfc9fdbcee7a
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/test/src/lib.rs:598:18
  27:     0x55a780be115d - test::run_test::run_test_inner::{{closure}}::hdff2b3e1656f98cd
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/test/src/lib.rs:492:39
  28:     0x55a780beaa21 - test::run_test::run_test_inner::{{closure}}::h9f1d586a6ef9df4b
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/test/src/lib.rs:519:37
  29:     0x55a780beaa21 - std::sys_common::backtrace::__rust_begin_short_backtrace::h00494840398bee50
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:122:18
  30:     0x55a780bb6a7f - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h67c40c52080f039b
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/thread/mod.rs:498:17
  31:     0x55a780bb6a7f - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h0170d0df3f1089c7
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panic/unwind_safe.rs:271:9
  32:     0x55a780bb6a7f - std::panicking::try::do_call::h58c11b7f9ff3e26a
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:492:40
  33:     0x55a780bb6a7f - std::panicking::try::h34ff80b8b781efbd
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:456:19
  34:     0x55a780bb6a7f - std::panic::catch_unwind::h342638075d359033
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panic.rs:137:14
  35:     0x55a780bb6a7f - std::thread::Builder::spawn_unchecked_::{{closure}}::h50918b4d51ab8a21
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/thread/mod.rs:497:30
  36:     0x55a780bb6a7f - core::ops::function::FnOnce::call_once{{vtable.shim}}::hda7049ec592f5801
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/ops/function.rs:227:5
  37:     0x55a780c17323 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h353fa42c42b20ec5
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/alloc/src/boxed.rs:1854:9
  38:     0x55a780c17323 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h0930c1c2fa5dac80
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/alloc/src/boxed.rs:1854:9
  39:     0x55a780c17323 - std::sys::unix::thread::Thread::new::thread_start::hb3ede8336acd4f71
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys/unix/thread.rs:108:17
  40:     0x7f7d1843c6db - start_thread
                               at /build/glibc-2ORdQG/glibc-2.27/nptl/pthread_create.c:463
  41:     0x7f7d177a3a3f - clone
                               at /build/glibc-2ORdQG/glibc-2.27/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  42:                0x0 - <unknown>
stack backtrace:                                                                                                                                                                                        
   0:     0x55a780c0e08c - std::backtrace_rs::backtrace::libunwind::trace::h38d656af46687c91                                                                                                            
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55a780c0e08c - std::backtrace_rs::backtrace::trace_unsynchronized::h6463e81b43d545da
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55a780c0e08c - std::sys_common::backtrace::_print_fmt::h7d0aeff1635ad318
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55a780c0e08c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he9ed9f7bc97615c6
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55a780c3553c - core::fmt::write::h26fb070fd492e04f
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/fmt/mod.rs:1190:17
   5:     0x55a780c095f8 - std::io::Write::write_fmt::ha7a1cfea3d855428
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/io/mod.rs:1657:15
   6:     0x55a780c101b7 - std::sys_common::backtrace::_print::h6a43ee74b02286e0
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55a780c101b7 - std::sys_common::backtrace::print::hfe9d3eef26a9b46f
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55a780c101b7 - std::panicking::default_hook::{{closure}}::he3bbb991ed25ca71
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:295:22
   9:    test rate_limiter::tests::test_rate_limited_light_flow ...  FAILED0x
55a780c0fe7f - std::panicking::default_hook::h4e425f0c50c308bd
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:314:9
  10:     0x55a780c1091a - std::panicking::rust_panic_with_hook::h22c18dec3fc9e708
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:698:17
  11:     0x55a780c105c9 - std::panicking::begin_panic_handler::{{closure}}::hd86c4a70dd9a9d4a
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:586:13
  12:     0x55a780c0e534 - std::sys_common::backtrace::__rust_end_short_backtrace::ha98c5d7cc0ee2da0
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55a780c10309 - rust_begin_unwind
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:584:5
  14:     0x55a780325503 - core::panicking::panic_fmt::h53f61fbdec3080b3
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panicking.rs:143:14
  15:     0x55a7803253cd - core::panicking::panic::h950eea06a1dc9ad4
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panicking.rs:48:5
  16:     0x55a78032f4d1 - file_system::rate_limiter::tests::test_rate_limited_hybrid_flow::h65c9529b1ba6391b
                               at /home/cosven/pingcap/tikv/components/file_system/src/rate_limiter.rs:812:9
  17:     0x55a78033b1ba - file_system::rate_limiter::tests::test_rate_limited_hybrid_flow::{{closure}}::hd03f1f208b21336c
                               at /home/cosven/pingcap/tikv/components/file_system/src/rate_limiter.rs:764:5
  18:     0x55a78033ee2e - core::ops::function::FnOnce::call_once::he79cace1d0d0f441
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/ops/function.rs:227:5
  19:     0x55a780be2493 - core::ops::function::FnOnce::call_once::hc8bba15014c4beea
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/ops/function.rs:227:5
  20:     0x55a780be2493 - test::__rust_begin_short_backtrace::hd460fd9f75eeba5f
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/test/src/lib.rs:575:5
  21:     0x55a780be115d - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4ee9be99affacb0f
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/alloc/src/boxed.rs:1854:9
  22:     0x55a780be115d - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h28201f0d6ec2068a
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panic/unwind_safe.rs:271:9
  23:     0x55a780be115d - std::panicking::try::do_call::hc6185aa5fff2063e
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:492:40
  24:     0x55a780be115d - std::panicking::try::hb602029255393744
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:456:19
  25:     0x55a780be115d - std::panic::catch_unwind::heeeeea0671593c22
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panic.rs:137:14
  26:     0x55a780be115d - test::run_test_in_process::h3ce9cfc9fdbcee7a
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/test/src/lib.rs:598:18
  27:     0x55a780be115d - test::run_test::run_test_inner::{{closure}}::hdff2b3e1656f98cd
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/test/src/lib.rs:492:39
  28:     0x55a780beaa21 - test::run_test::run_test_inner::{{closure}}::h9f1d586a6ef9df4b
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/test/src/lib.rs:519:37
  29:     0x55a780beaa21 - std::sys_common::backtrace::__rust_begin_short_backtrace::h00494840398bee50
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:122:18
  30:     0x55a780bb6a7f - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h67c40c52080f039b
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/thread/mod.rs:498:17
  31:     0x55a780bb6a7f - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h0170d0df3f1089c7
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panic/unwind_safe.rs:271:9
  32:     0x55a780bb6a7f - std::panicking::try::do_call::h58c11b7f9ff3e26a
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:492:40
  33:     0x55a780bb6a7f - std::panicking::try::h34ff80b8b781efbd
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:456:19
  34:     0x55a780bb6a7f - std::panic::catch_unwind::h342638075d359033
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panic.rs:137:14
  35:     0x55a780bb6a7f - std::thread::Builder::spawn_unchecked_::{{closure}}::h50918b4d51ab8a21
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/thread/mod.rs:497:30
  36:     0x55a780bb6a7f - core::ops::function::FnOnce::call_once{{vtable.shim}}::hda7049ec592f5801
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/ops/function.rs:227:5
  37:     0x55a780c17323 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h353fa42c42b20ec5
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/alloc/src/boxed.rs:1854:9
  38:     0x55a780c17323 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h0930c1c2fa5dac80
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/alloc/src/boxed.rs:1854:9
  39:     0x55a780c17323 - std::sys::unix::thread::Thread::new::thread_start::hb3ede8336acd4f71
                               at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys/unix/thread.rs:108:17
  40:     0x7f7d1843c6db - start_thread
                               at /build/glibc-2ORdQG/glibc-2.27/nptl/pthread_create.c:463
  41:     0x7f7d177a3a3f - clone
                               at /build/glibc-2ORdQG/glibc-2.27/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  42:                0x0 - <unknown>
test rate_limiter::tests::test_rate_limited_hybrid_flow ... FAILED
test tests::test_sha256 ... ok
test rate_limiter::tests::test_rate_limit_toggle ... ok
test rate_limiter::tests::test_rate_limit_dynamic_priority ... ok
test rate_limiter::tests::test_rate_limited_heavy_flow ... ok

failures:

failures:
    rate_limiter::tests::test_rate_limited_hybrid_flow
    rate_limiter::tests::test_rate_limited_light_flow

test result: FAILED. 17 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 6.09s

error: test failed, to rerun pass '-p file_system --lib'
Makefile:252: recipe for target 'run' failed
make[1]: *** [run] Error 101
make[1]: Leaving directory '/home/cosven/pingcap/tikv'
Makefile:260: recipe for target 'test' failed
make: *** [test] Error 2
```

**Comment by cosven** [comment]
I found https://github.com/tikv/tikv/pull/10304 tried to fix this issue once, however, the two testcases may still fail.
