### ISSUE TITLE
test `delete_range_when_worker_is_full` failed

### ISSUE THREAD

**Issue by hunterlxt** [tikv/tikv#12191]
## Bug Report

commit master [ea61ca2](https://github.com/tikv/tikv/commit/ea61ca2c1bdd71133a62babc7087597e82a2493f)

```
[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-80)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-81)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-82)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-83)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-84)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-85)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-86)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-87)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-88)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-89)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-90)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-91)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-92)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-93)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-94)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-95)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-96)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-97)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-98)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-99)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-100)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-101)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-102)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-103)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-104)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-105)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-106)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-107)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-108)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-109)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-110)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-111)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-112)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-113)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-114)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-115)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-116)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-117)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-118)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-119)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-120)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-121)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-122)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-123)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-124)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-125)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-126)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-127)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-128)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-129)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-130)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-131)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-132)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-133)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-134)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-135)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-136)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-137)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-138)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-139)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-140)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-141)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-142)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-143)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-144)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-145)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-146)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-147)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-148)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-149)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-150)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-151)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-152)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-153)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-154)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-155)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-156)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-157)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-158)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-159)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-160)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-161)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-162)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-163)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-164)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-165)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-166)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-167)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-168)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-169)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-170)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-171)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-172)[](https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17912/pipeline/99#step-300-log-173)[2022-03-17T05:45:51.559Z] running 104 tests

[2022-03-17T05:45:51.559Z] test server::gc_worker::applied_lock_collector::tests::test_start_stop ... ok

[2022-03-17T05:45:51.834Z] test server::gc_worker::compaction_filter::tests::test_compaction_filter_basic ... ok

[2022-03-17T05:45:54.451Z] test server::gc_worker::compaction_filter::tests::test_compaction_filter_handle_deleting ... ok

[2022-03-17T05:45:54.451Z] test server::gc_worker::compaction_filter::tests::test_is_compaction_filter_allowed ... ok

[2022-03-17T05:45:54.451Z] test server::gc_worker::compaction_filter::tests::test_mvcc_properties ... ok

[2022-03-17T05:45:54.739Z] test server::gc_worker::compaction_filter::tests::test_remove_and_skip_until ... ok

[2022-03-17T05:45:54.739Z] test server::gc_worker::gc_manager::tests::test_auto_gc_a_round_without_rewind ... ok

[2022-03-17T05:45:54.739Z] test server::gc_worker::gc_manager::tests::test_auto_gc_rewinding ... ok

[2022-03-17T05:45:54.739Z] test server::gc_worker::gc_manager::tests::test_gc_manager_initialize ... ok

[2022-03-17T05:45:55.036Z] test server::gc_worker::gc_manager::tests::test_update_safe_point ... ok

[2022-03-17T05:46:05.211Z] test server::gc_worker::gc_worker::tests::delete_range_when_worker_is_full ... thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Timeout', src/server/gc_worker/gc_worker.rs:1766:58

[2022-03-17T05:46:05.212Z] stack backtrace:

[2022-03-17T05:46:05.784Z]    0: rust_begin_unwind

[2022-03-17T05:46:05.784Z]              at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:584:5

[2022-03-17T05:46:05.784Z]    1: core::panicking::panic_fmt

[2022-03-17T05:46:05.784Z]              at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panicking.rs:143:14

[2022-03-17T05:46:05.784Z]    2: core::result::unwrap_failed

[2022-03-17T05:46:05.784Z]              at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/result.rs:1749:5

[2022-03-17T05:46:05.784Z]    3: core::result::Result<T,E>::unwrap

[2022-03-17T05:46:05.784Z]              at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/result.rs:1065:23

[2022-03-17T05:46:06.046Z]    4: tikv::server::gc_worker::gc_worker::tests::delete_range_when_worker_is_full

[2022-03-17T05:46:06.046Z]              at /home/jenkins/tikv-src/src/server/gc_worker/gc_worker.rs:1766:17

[2022-03-17T05:46:06.046Z]    5: tikv::server::gc_worker::gc_worker::tests::delete_range_when_worker_is_full::{{closure}}

[2022-03-17T05:46:06.046Z]              at /home/jenkins/tikv-src/src/server/gc_worker/gc_worker.rs:1697:5

[2022-03-17T05:46:06.046Z]    6: core::ops::function::FnOnce::call_once

[2022-03-17T05:46:06.046Z]              at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/ops/function.rs:227:5

[2022-03-17T05:46:06.046Z]    7: core::ops::function::FnOnce::call_once

[2022-03-17T05:46:06.046Z]              at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/ops/function.rs:227:5

[2022-03-17T05:46:06.046Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

[2022-03-17T05:46:09.358Z] thread 'gc-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', src/server/gc_worker/gc_worker.rs:1756:38

[2022-03-17T05:46:09.358Z] stack backtrace:

[2022-03-17T05:46:09.358Z]    0: rust_begin_unwind

[2022-03-17T05:46:09.358Z]              at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:584:5

[2022-03-17T05:46:09.358Z]    1: core::panicking::panic_fmt

[2022-03-17T05:46:09.358Z]              at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panicking.rs:143:14

[2022-03-17T05:46:09.358Z]    2: core::result::unwrap_failed

[2022-03-17T05:46:09.358Z]              at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/result.rs:1749:5

[2022-03-17T05:46:09.358Z]    3: core::result::Result<T,E>::unwrap

[2022-03-17T05:46:09.358Z]              at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/result.rs:1065:23

[2022-03-17T05:46:09.358Z]    4: tikv::server::gc_worker::gc_worker::tests::delete_range_when_worker_is_full::{{closure}}

[2022-03-17T05:46:09.358Z]              at /home/jenkins/tikv-src/src/server/gc_worker/gc_worker.rs:1756:25

[2022-03-17T05:46:09.358Z]    5: core::ops::function::FnOnce::call_once{{vtable.shim}}

[2022-03-17T05:46:09.358Z]              at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/ops/function.rs:227:5

[2022-03-17T05:46:09.358Z]    6: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once

[2022-03-17T05:46:09.358Z]              at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/alloc/src/boxed.rs:1854:9

[2022-03-17T05:46:09.358Z]    7: <tikv::server::gc_worker::gc_worker::GcRunner<E,RR> as tikv_util::worker::pool::Runnable>::run

[2022-03-17T05:46:09.358Z]              at /home/jenkins/tikv-src/src/server/gc_worker/gc_worker.rs:646:17

[2022-03-17T05:46:09.358Z]    8: tikv_util::worker::pool::Worker::start_impl::{{closure}}

[2022-03-17T05:46:09.358Z]              at /home/jenkins/tikv-src/components/tikv_util/src/worker/pool.rs:433:25

[2022-03-17T05:46:09.358Z]    9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

[2022-03-17T05:46:09.358Z]              at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/future/mod.rs:84:19

[2022-03-17T05:46:09.358Z]   10: yatp::task::future::RawTask<F>::poll

[2022-03-17T05:46:09.358Z]              at /rust/git/checkouts/yatp-e704b73c3ee279b6/5f3d580/src/task/future.rs:59:9

[2022-03-17T05:46:09.358Z]   11: yatp::task::future::TaskCell::poll

[2022-03-17T05:46:09.358Z]              at /rust/git/checkouts/yatp-e704b73c3ee279b6/5f3d580/src/task/future.rs:103:9

[2022-03-17T05:46:09.358Z]   12: <yatp::task::future::Runner as yatp::pool::runner::Runner>::handle

[2022-03-17T05:46:09.359Z]              at /rust/git/checkouts/yatp-e704b73c3ee279b6/5f3d580/src/task/future.rs:387:20

[2022-03-17T05:46:09.359Z]   13: <tikv_util::yatp_pool::YatpPoolRunner<T> as yatp::pool::runner::Runner>::handle

[2022-03-17T05:46:09.359Z]              at /home/jenkins/tikv-src/components/tikv_util/src/yatp_pool/mod.rs:104:24

[2022-03-17T05:46:09.359Z]   14: yatp::pool::worker::WorkerThread<T,R>::run

[2022-03-17T05:46:09.359Z]              at /rust/git/checkouts/yatp-e704b73c3ee279b6/5f3d580/src/pool/worker.rs:48:13

[2022-03-17T05:46:09.359Z]   15: yatp::pool::builder::LazyBuilder<T>::build::{{closure}}

[2022-03-17T05:46:09.359Z]              at /rust/git/checkouts/yatp-e704b73c3ee279b6/5f3d580/src/pool/builder.rs:114:25

[2022-03-17T05:46:09.359Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

[2022-03-17T05:46:09.359Z] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', /rust/git/checkouts/yatp-e704b73c3ee279b6/5f3d580/src/pool.rs:66:26

[2022-03-17T05:46:09.359Z] stack backtrace:

[2022-03-17T05:46:09.359Z]    0:     0x55d9c4d9b42c - std::backtrace_rs::backtrace::libunwind::trace::h38d656af46687c91

[2022-03-17T05:46:09.359Z]                                at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5

[2022-03-17T05:46:09.359Z]    1:     0x55d9c4d9b42c - std::backtrace_rs::backtrace::trace_unsynchronized::h6463e81b43d545da

[2022-03-17T05:46:09.359Z]                                at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5

[2022-03-17T05:46:09.359Z]    2:     0x55d9c4d9b42c - std::sys_common::backtrace::_print_fmt::h7d0aeff1635ad318

[2022-03-17T05:46:09.359Z]                                at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:66:5

[2022-03-17T05:46:09.359Z]    3:     0x55d9c4d9b42c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he9ed9f7bc97615c6

[2022-03-17T05:46:09.359Z]                                at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:45:22

[2022-03-17T05:46:09.359Z]    4:     0x55d9c4dc757c - core::fmt::write::h26fb070fd492e04f

[2022-03-17T05:46:09.359Z]                                at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/fmt/mod.rs:1190:17

[2022-03-17T05:46:09.359Z]    5:     0x55d9c4d92c98 - std::io::Write::write_fmt::ha7a1cfea3d855428

[2022-03-17T05:46:09.359Z]                                at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/io/mod.rs:1657:15

[2022-03-17T05:46:09.359Z]    6:     0x55d9c4d9dba7 - std::sys_common::backtrace::_print::h6a43ee74b02286e0

[2022-03-17T05:46:09.359Z]                                at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:48:5

[2022-03-17T05:46:09.359Z]    7:     0x55d9c4d9dba7 - std::sys_common::backtrace::print::hfe9d3eef26a9b46f

[2022-03-17T05:46:09.359Z]                                at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:35:9

[2022-03-17T05:46:09.359Z]    8:     0x55d9c4d9dba7 - std::panicking::default_hook::{{closure}}::he3bbb991ed25ca71

[2022-03-17T05:46:09.359Z]                                at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:295:22

[2022-03-17T05:46:09.359Z]    9:     0x55d9c4d9d86f - std::panicking::default_hook::h4e425f0c50c308bd

[2022-03-17T05:46:09.359Z]                                at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:314:9

[2022-03-17T05:46:09.359Z]   10:     0x55d9c4d9e30a - std::panicking::rust_panic_with_hook::h22c18dec3fc9e708

[2022-03-17T05:46:09.359Z]                                at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:698:17

[2022-03-17T05:46:09.359Z]   11:     0x55d9c4d9dff7 - std::panicking::begin_panic_handler::{{closure}}::hd86c4a70dd9a9d4a

[2022-03-17T05:46:09.359Z]                                at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:588:13

[2022-03-17T05:46:09.359Z]   12:     0x55d9c4d9b8d4 - std::sys_common::backtrace::__rust_end_short_backtrace::ha98c5d7cc0ee2da0

[2022-03-17T05:46:09.359Z]                                at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:138:18

[2022-03-17T05:46:09.359Z]   13:     0x55d9c4d9dcf9 - rust_begin_unwind

[2022-03-17T05:46:09.359Z]                                at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:584:5
```

**Comment by LykxSassinator** [comment]
Not a flaky case now in nightly version ([aa5fb36](https://github.com/tikv/tikv/commit/aa5fb36af8e942bb136fc285a5498adf80be9c8c))
