### ISSUE TITLE
case test_report_min_resolved_ts_disable is unstable

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#12337]
## Bug Report

```
thread 'test_report_min_resolved_ts_disable' panicked at 'assertion failed: ts3 == ts1', components/resolved_ts/tests/failpoints/mod.rs:114:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panicking.rs:143:14
   2: core::panicking::panic
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panicking.rs:48:5
   3: failpoints::test_report_min_resolved_ts_disable
             at ./components/resolved_ts/tests/failpoints/mod.rs:114:5
   4: failpoints::test_report_min_resolved_ts_disable::{{closure}}
             at ./components/resolved_ts/tests/failpoints/mod.rs:90:1
   5: core::ops::function::FnOnce::call_once
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/ops/function.rs:227:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

More trace can be found at https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/18729/pipeline/82

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further feedback regarding this issue has been reported, it can be safely closed.
