### ISSUE TITLE
Container fails to start when running the simple TiKV getting started guide

### ISSUE THREAD

**Issue by tobiemh** [tikv/tikv#13049]
### What version of TiKV are you using?
6.1

### What operating system and CPU are you using?
Apple M1 with macOS 12.4

### Steps to reproduce
Followed the example here: https://tikv.org/docs/3.0/tasks/try/docker-stack/

<details>
  <summary>The error is also visible when starting TiKV with the following Docker commands...</summary>

```
docker run --rm -d \
	--name pd \
	-p 2379:2379 \
	-p 2380:2380 \
	-v ~/cluster:/data \
	-v /etc/localtime:/etc/localtime:ro \
	pingcap/pd:latest \
	--name="pd" \
	--data-dir="/data/pd" \
	--peer-urls="http://0.0.0.0:2380" \
	--client-urls="http://0.0.0.0:2379" \
	--advertise-peer-urls="http://127.0.0.1:2380" \
	--advertise-client-urls="http://127.0.0.1:2379" \
	--initial-cluster="pd=http://127.0.0.1:2380"

docker run --rm \
	--name tikv \
	-p 20160:20160 \
	-v ~/cluster:/data \
	-v /etc/localtime:/etc/localtime:ro \
	pingcap/tikv:latest \
	--data-dir="/data/kv" \
	--addr="0.0.0.0:20160" \
	--pd="127.0.0.1:2379" \
	--advertise-addr="127.0.0.1:20160"
```

</details>

### What did you expect?
Expected the container to start and a single-instance TiKV setup to be available.

### What happened?

The PD docker container starts fine. However, received the following error in the `pingcap/tikv` docker container:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InternalError(bug at /rust/registry/src/github.com-1ecc6299db9ec823/procfs-0.12.0/src/process/stat.rs:310 (please report this procfs bug)
Internal Unwrap Error: Internal error: bug at /rust/registry/src/github.com-1ecc6299db9ec823/procfs-0.12.0/src/lib.rs:259 (please report this procfs bug)
Internal Unwrap Error: NoneError)', components/tikv_util/src/sys/cgroup.rs:203:63
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by tobiemh** [comment]
Ah actually - if I specify the full version of the docker image (`pingcap/pd:v6.1.0`) and (`pingcap/tikv:v6.1.0`) then the error does not occur.

I presume therefore this error is because the `pingcap/tikv:latest` does not have a `linux/arm64` platform build for Apple Silicon CPUs.
