### ISSUE TITLE
`test-all` script exited with 0 when some tests failed

### ISSUE THREAD

**Issue by wuhuizuo** [tikv/tikv#14594]
### What version of TiKV are you using?

- branch: `release-6.5`
- commit sha: `a29f525cec48a801e9d8b1748356a88385bcfd33`

### What operating system and CPU are you using?

```log
root@bd6dcf1953ec:/data/tikv# cat /proc/cpuinfo | head -50
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
stepping        : 1
microcode       : 0xb00002a
cpu MHz         : 1251.196
cache size      : 25600 KB
physical id     : 0
siblings        : 20
core id         : 0
cpu cores       : 10
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 20
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 invpcid_single rsb_ctxsw ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts spec_ctrl intel_stibp
bogomips        : 4400.16
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

```

### Steps to reproduce

1. start docker container and install tools, ref:
```Dockerfile
FROM rust:1.68

# install build essential
RUN apt-get update && \
    apt-get install -y build-essential cmake llvm protobuf-compiler python3 && \
    apt-get clean
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1

# install nextest tool.
RUN cargo install cargo-nextest --locked

######### run test for TiKV ########

# git clone https://github.com/tikv/tikv.git --branch release-6.5 
```
2. git clone tikv/tikv in the container, and checkout to `release-6.5` branch.
3. run `./scripts/test-all`.

### What did you expect?

None tests failed and exit with `0`.

### What did happened?

Some tests failed but exited with 0:

```log
test write_batch::write_batch_write_twice_2 ... ok
test write_batch::write_batch_write_twice_3 ... ok

failures:

---- ctor::new_engine_opt_readonly_dir stdout ----
thread 'ctor::new_engine_opt_readonly_dir' panicked at 'called `Result::unwrap_err()` on an `Ok` value: RocksEngine { db: Db [path=/tmp/tikv-engine-traits-testsqqz4V8/readonly], shared_block_cache: false, support_multi_batch_write: false }', components/engine_traits_tests/src/ctor.rs:91:9
stack backtrace:
   0:     0x557fb93bef90 - std::backtrace_rs::backtrace::libunwind::trace::he534b130db6360ed
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x557fb93bef90 - std::backtrace_rs::backtrace::trace_unsynchronized::hc3486e10c7777b38
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x557fb93bef90 - std::sys_common::backtrace::_print_fmt::ha24198a22cf70db0
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x557fb93bef90 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he928616f28db1c44
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x557fb93e3cee - core::fmt::write::hfc4e1f18015528cf
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/fmt/mod.rs:1209:17
   5:     0x557fb93bbaa5 - std::io::Write::write_fmt::h20ebfd4da7aadc9c
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/io/mod.rs:1682:15
   6:     0x557fb93bed55 - std::sys_common::backtrace::_print::hc5210df762c2ee4d
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x557fb93bed55 - std::sys_common::backtrace::print::h01d5ef97fb586ab1
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x557fb93c0a4f - std::panicking::default_hook::{{closure}}::hfaf4dc37dc2875b0
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:267:22
   9:     0x557fb93c070e - std::panicking::default_hook::h22df008dfc46e0e0
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:283:9
  10:     0x557fb916bb07 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h978ad2ab11c40243
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/alloc/src/boxed.rs:2032:9
  11:     0x557fb916bb07 - test::test_main::{{closure}}::hd44c68f6cb8f1f35
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/test/src/lib.rs:135:21
  12:     0x557fb86a64e8 - panic_hook::track_hook::{{closure}}::h178f4b8d48740c3d
  13:     0x557fb86a5094 - std::thread::local::LocalKey<T>::try_with::hdeae8d52e24755b0
  14:     0x557fb86a4d8e - std::thread::local::LocalKey<T>::with::h8d57134e1faeaac1
  15:     0x557fb86a47f5 - panic_hook::track_hook::h4ed5fab76be316d9
  16:     0x557fb86a4b35 - core::ops::function::Fn::call::h71982d9fa0be2d6e
  17:     0x557fb93c116d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::ha8979dc0d5fa3133
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/alloc/src/boxed.rs:2032:9
  18:     0x557fb93c116d - std::panicking::rust_panic_with_hook::h8bb52976cbf68a37
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:692:13
  19:     0x557fb93c0ee7 - std::panicking::begin_panic_handler::{{closure}}::hb6582e9b11a93445
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:579:13
  20:     0x557fb93bf43c - std::sys_common::backtrace::__rust_end_short_backtrace::hd69a588bdd28408e
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys_common/backtrace.rs:137:18
  21:     0x557fb93c0c02 - rust_begin_unwind
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:575:5
  22:     0x557fb860e683 - core::panicking::panic_fmt::hb1806527c2beebe3
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panicking.rs:65:14
  23:     0x557fb860e943 - core::result::unwrap_failed::he2b30c6b959db85a
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/result.rs:1791:5
  24:     0x557fb865ce6d - core::result::Result<T,E>::unwrap_err::h5f1578c1bb039878
  25:     0x557fb868a822 - engine_traits_tests::ctor::new_engine_opt_readonly_dir::hf9f029bcb9200ae9
  26:     0x557fb86a2415 - engine_traits_tests::ctor::new_engine_opt_readonly_dir::{{closure}}::h57bfe90a249df0db
  27:     0x557fb869ea78 - core::ops::function::FnOnce::call_once::h50822346e1908cda
  28:     0x557fb9170e5f - core::ops::function::FnOnce::call_once::hdf4f8c58ba86b612
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/ops/function.rs:513:5
  29:     0x557fb9170e5f - test::__rust_begin_short_backtrace::h19769e172355a553
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/test/src/lib.rs:637:18
  30:     0x557fb914357c - test::run_test::{{closure}}::hfe8d724f44426c9e
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/test/src/lib.rs:628:30
  31:     0x557fb914357c - core::ops::function::FnOnce::call_once{{vtable.shim}}::h08e9d704acaf66ac
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/ops/function.rs:513:5
  32:     0x557fb916fe76 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h312fea4ff6db7ecf
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/alloc/src/boxed.rs:2000:9
  33:     0x557fb916fe76 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hdb969e3902e87449
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panic/unwind_safe.rs:271:9
  34:     0x557fb916fe76 - std::panicking::try::do_call::h6da79ecfef558898
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:483:40
  35:     0x557fb916fe76 - std::panicking::try::h7f668fbaf77473b2
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:447:19
  36:     0x557fb916fe76 - std::panic::catch_unwind::ha6924da3c5c9fc14
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panic.rs:137:14
  37:     0x557fb916fe76 - test::run_test_in_process::hb6aceb0c3bf0084e
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/test/src/lib.rs:660:27
  38:     0x557fb916fe76 - test::run_test::run_test_inner::{{closure}}::h1f9d76cb3b5cab45
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/test/src/lib.rs:554:39
  39:     0x557fb913de34 - test::run_test::run_test_inner::{{closure}}::hbb1c64585fff0899
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/test/src/lib.rs:581:37
  40:     0x557fb913de34 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc55a7d34ba091187
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys_common/backtrace.rs:121:18
  41:     0x557fb91437a5 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h5f0678941ebc6010
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/thread/mod.rs:551:17
  42:     0x557fb91437a5 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h7b5b1b1b480c0d0b
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panic/unwind_safe.rs:271:9
  43:     0x557fb91437a5 - std::panicking::try::do_call::h75b027545d7dd24a
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:483:40
  44:     0x557fb91437a5 - std::panicking::try::h3231c5548f9f3483
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:447:19
  45:     0x557fb91437a5 - std::panic::catch_unwind::h4b3465df06d90c4b
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panic.rs:137:14
  46:     0x557fb91437a5 - std::thread::Builder::spawn_unchecked_::{{closure}}::h44dacc2db01da8f5
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/thread/mod.rs:550:30
  47:     0x557fb91437a5 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h8e859a243f1af552
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/ops/function.rs:513:5
  48:     0x557fb93c61e3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h613d5e218c101168
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/alloc/src/boxed.rs:2000:9
  49:     0x557fb93c61e3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hecab0373f4228b53
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/alloc/src/boxed.rs:2000:9
  50:     0x557fb93c61e3 - std::sys::unix::thread::Thread::new::thread_start::hd2791a9cabec1fda
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys/unix/thread.rs:108:17
  51:     0x7effeeccaea7 - start_thread
  52:     0x7effeea9ea2f - clone
  53:                0x0 - <unknown>

---- ctor::new_engine_readonly_dir stdout ----
thread 'ctor::new_engine_readonly_dir' panicked at 'called `Result::unwrap_err()` on an `Ok` value: RocksEngine { db: Db [path=/tmp/tikv-engine-traits-testst1cO1R/readonly], shared_block_cache: false, support_multi_batch_write: false }', components/engine_traits_tests/src/ctor.rs:70:9
stack backtrace:
   0:     0x557fb93bef90 - std::backtrace_rs::backtrace::libunwind::trace::he534b130db6360ed
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x557fb93bef90 - std::backtrace_rs::backtrace::trace_unsynchronized::hc3486e10c7777b38
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x557fb93bef90 - std::sys_common::backtrace::_print_fmt::ha24198a22cf70db0
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x557fb93bef90 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he928616f28db1c44
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x557fb93e3cee - core::fmt::write::hfc4e1f18015528cf
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/fmt/mod.rs:1209:17
   5:     0x557fb93bbaa5 - std::io::Write::write_fmt::h20ebfd4da7aadc9c
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/io/mod.rs:1682:15
   6:     0x557fb93bed55 - std::sys_common::backtrace::_print::hc5210df762c2ee4d
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x557fb93bed55 - std::sys_common::backtrace::print::h01d5ef97fb586ab1
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x557fb93c0a4f - std::panicking::default_hook::{{closure}}::hfaf4dc37dc2875b0
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:267:22
   9:     0x557fb93c070e - std::panicking::default_hook::h22df008dfc46e0e0
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:283:9
  10:     0x557fb916bb07 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h978ad2ab11c40243
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/alloc/src/boxed.rs:2032:9
  11:     0x557fb916bb07 - test::test_main::{{closure}}::hd44c68f6cb8f1f35
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/test/src/lib.rs:135:21
  12:     0x557fb86a64e8 - panic_hook::track_hook::{{closure}}::h178f4b8d48740c3d
  13:     0x557fb86a5094 - std::thread::local::LocalKey<T>::try_with::hdeae8d52e24755b0
  14:     0x557fb86a4d8e - std::thread::local::LocalKey<T>::with::h8d57134e1faeaac1
  15:     0x557fb86a47f5 - panic_hook::track_hook::h4ed5fab76be316d9
  16:     0x557fb86a4b35 - core::ops::function::Fn::call::h71982d9fa0be2d6e
  17:     0x557fb93c116d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::ha8979dc0d5fa3133
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/alloc/src/boxed.rs:2032:9
  18:     0x557fb93c116d - std::panicking::rust_panic_with_hook::h8bb52976cbf68a37
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:692:13
  19:     0x557fb93c0ee7 - std::panicking::begin_panic_handler::{{closure}}::hb6582e9b11a93445
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:579:13
  20:     0x557fb93bf43c - std::sys_common::backtrace::__rust_end_short_backtrace::hd69a588bdd28408e
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys_common/backtrace.rs:137:18
  21:     0x557fb93c0c02 - rust_begin_unwind
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:575:5
  22:     0x557fb860e683 - core::panicking::panic_fmt::hb1806527c2beebe3
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panicking.rs:65:14
  23:     0x557fb860e943 - core::result::unwrap_failed::he2b30c6b959db85a
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/result.rs:1791:5
  24:     0x557fb865ce6d - core::result::Result<T,E>::unwrap_err::h5f1578c1bb039878
  25:     0x557fb868a461 - engine_traits_tests::ctor::new_engine_readonly_dir::h35af3ae73e06356c
  26:     0x557fb86a23e5 - engine_traits_tests::ctor::new_engine_readonly_dir::{{closure}}::h6ed1b70f6467ba96
  27:     0x557fb869fab8 - core::ops::function::FnOnce::call_once::ha6fb31d3ecf5b6d0
  28:     0x557fb9170e5f - core::ops::function::FnOnce::call_once::hdf4f8c58ba86b612
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/ops/function.rs:513:5
  29:     0x557fb9170e5f - test::__rust_begin_short_backtrace::h19769e172355a553
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/test/src/lib.rs:637:18
  30:     0x557fb914357c - test::run_test::{{closure}}::hfe8d724f44426c9e
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/test/src/lib.rs:628:30
  31:     0x557fb914357c - core::ops::function::FnOnce::call_once{{vtable.shim}}::h08e9d704acaf66ac
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/ops/function.rs:513:5
  32:     0x557fb916fe76 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h312fea4ff6db7ecf
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/alloc/src/boxed.rs:2000:9
  33:     0x557fb916fe76 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hdb969e3902e87449
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panic/unwind_safe.rs:271:9
  34:     0x557fb916fe76 - std::panicking::try::do_call::h6da79ecfef558898
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:483:40
  35:     0x557fb916fe76 - std::panicking::try::h7f668fbaf77473b2
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:447:19
  36:     0x557fb916fe76 - std::panic::catch_unwind::ha6924da3c5c9fc14
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panic.rs:137:14
  37:     0x557fb916fe76 - test::run_test_in_process::hb6aceb0c3bf0084e
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/test/src/lib.rs:660:27
  38:     0x557fb916fe76 - test::run_test::run_test_inner::{{closure}}::h1f9d76cb3b5cab45
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/test/src/lib.rs:554:39
  39:     0x557fb913de34 - test::run_test::run_test_inner::{{closure}}::hbb1c64585fff0899
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/test/src/lib.rs:581:37
  40:     0x557fb913de34 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc55a7d34ba091187
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys_common/backtrace.rs:121:18
  41:     0x557fb91437a5 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h5f0678941ebc6010
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/thread/mod.rs:551:17
  42:     0x557fb91437a5 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h7b5b1b1b480c0d0b
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panic/unwind_safe.rs:271:9
  43:     0x557fb91437a5 - std::panicking::try::do_call::h75b027545d7dd24a
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:483:40
  44:     0x557fb91437a5 - std::panicking::try::h3231c5548f9f3483
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:447:19
  45:     0x557fb91437a5 - std::panic::catch_unwind::h4b3465df06d90c4b
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panic.rs:137:14
  46:     0x557fb91437a5 - std::thread::Builder::spawn_unchecked_::{{closure}}::h44dacc2db01da8f5
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/thread/mod.rs:550:30
  47:     0x557fb91437a5 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h8e859a243f1af552
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/ops/function.rs:513:5
  48:     0x557fb93c61e3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h613d5e218c101168
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/alloc/src/boxed.rs:2000:9
  49:     0x557fb93c61e3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hecab0373f4228b53
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/alloc/src/boxed.rs:2000:9
  50:     0x557fb93c61e3 - std::sys::unix::thread::Thread::new::thread_start::hd2791a9cabec1fda
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys/unix/thread.rs:108:17
  51:     0x7effeeccaea7 - start_thread
  52:     0x7effeea9ea2f - clone
  53:                0x0 - <unknown>


failures:
    ctor::new_engine_opt_readonly_dir
    ctor::new_engine_readonly_dir

test result: FAILED. 132 passed; 2 failed; 2 ignored; 0 measured; 0 filtered out; finished in 0.29s

error: test failed, to rerun pass `-p engine_traits_tests --lib`
warning: profile package spec `tirocks-sys` in profile `dev` did not match any packages
   Compiling test_sst_importer v0.1.0 (/data/tikv/components/test_sst_importer)
<jemalloc>: Invalid conf pair: prof:true
    Finished test [unoptimized] target(s) in 2.67s
     Running unittests src/lib.rs (target/debug/deps/api_version-fe32427a89706995)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 17 filtered out; finished in 0.00s
.........

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 21 filtered out; finished in 0.00s


Checking bins for jemalloc
Done, takes 11.38s.
root@bd6dcf1953ec:/data/tikv# echo $?
0
```

**Comment by wuhuizuo** [comment]
failed case:
    ctor::new_engine_opt_readonly_dir
    ctor::new_engine_readonly_dir
