### ISSUE TITLE
test failure:bench_sequence_number_window failed 

### ISSUE THREAD

**Issue by tonyxuqqi** [tikv/tikv#14776]
### What version of TiKV are you using?

master
### Steps to reproduce

make docker_test
### What did you expect?
all test cases pass
### What did happened?
--- STDERR:              engine_traits util::tests::bench_sequence_number_window ---
thread 'util::tests::bench_sequence_number_window' panicked at 'committed_seqno 3568, seqno3567', components/engine_traits/src/util.rs:156:13
stack backtrace:
   0:     0x55fd844faeb0 - std::backtrace_rs::backtrace::libunwind::trace::he534b130db6360ed
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55fd844faeb0 - std::backtrace_rs::backtrace::trace_unsynchronized::hc3486e10c7777b38
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55fd844faeb0 - std::sys_common::backtrace::_print_fmt::ha24198a22cf70db0
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55fd844faeb0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he928616f28db1c44
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55fd8451f59e - core::fmt::write::hfc4e1f18015528cf
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/fmt/mod.rs:1209:17
   5:     0x55fd844f7a55 - std::io::Write::write_fmt::h1fe0ff478ba9434a
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/io/mod.rs:1682:15
   6:     0x55fd844fac75 - std::sys_common::backtrace::_print::hc5210df762c2ee4d
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55fd844fac75 - std::sys_common::backtrace::print::h01d5ef97fb586ab1
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55fd844fc96f - std::panicking::default_hook::{{closure}}::hfaf4dc37dc2875b0
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:267:22
   9:     0x55fd844fc6aa - std::panicking::default_hook::h22df008dfc46e0e0
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:286:9
  10:     0x55fd844fd06c - std::panicking::rust_panic_with_hook::h8bb52976cbf68a37
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:688:13
  11:     0x55fd844fce07 - std::panicking::begin_panic_handler::{{closure}}::hb6582e9b11a93445
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:579:13
  12:     0x55fd844fb35c - std::sys_common::backtrace::__rust_end_short_backtrace::hd69a588bdd28408e
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x55fd844fcb22 - rust_begin_unwind
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:575:5
  14:     0x55fd8402ad23 - core::panicking::panic_fmt::hb1806527c2beebe3
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panicking.rs:65:14
  15:     0x55fd8405115a - engine_traits::util::SequenceNumberWindow::push::h3625a5dab338c18d
  16:     0x55fd8404a209 - engine_traits::util::tests::bench_sequence_number_window::{{closure}}::hb5cc763c799f1020
  17:     0x55fd8404c17b - test::bench::ns_iter_inner::h2be09076e52ace4c
  18:     0x55fd8404c758 - test::bench::Bencher::iter::h03b099343ea2659c
  19:     0x55fd84032a64 - engine_traits::util::tests::bench_sequence_number_window::hcb735c2412c341b3
  20:     0x55fd84049e10 - engine_traits::util::tests::bench_sequence_number_window::{{closure}}::hd93a359c2408c952
  21:     0x55fd84051b20 - core::ops::function::FnOnce::call_once::h1e36baae843aa089
  22:     0x55fd844d2ab5 - test::convert_benchmarks_to_tests::{{closure}}::{{closure}}::{{closure}}::{{closure}}::h12716055f4c7ed09
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/test/src/lib.rs:508:73
  23:     0x55fd844d2ab5 - test::__rust_begin_short_backtrace::h32aa04639f6853ff
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/test/src/lib.rs:637:18
  24:     0x55fd844a507a - test::convert_benchmarks_to_tests::{{closure}}::{{closure}}::{{closure}}::ha74d3f4dc7b5982c
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/test/src/lib.rs:508:41
  25:     0x55fd844a507a - test::bench::Bencher::bench::h49cc84543b7a0bb1
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/test/src/bench.rs:56:22
  26:     0x55fd844a507a - test::bench::run_once::h3fa0d262bef1e1d2
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/test/src/bench.rs:242:5
  27:     0x55fd844a507a - test::convert_benchmarks_to_tests::{{closure}}::{{closure}}::h22085b5db8355689
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/test/src/lib.rs:508:21
  28:     0x55fd844a507a - core::ops::function::FnOnce::call_once{{vtable.shim}}::h2dc8702236d45eac
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/ops/function.rs:513:5
  29:     0x55fd844d2aea - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h312fea4ff6db7ecf
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/alloc/src/boxed.rs:2000:9
  30:     0x55fd844d2aea - test::__rust_begin_short_backtrace::hb48c52ec89163dba
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/test/src/lib.rs:637:18
  31:     0x55fd844a5393 - test::run_test::{{closure}}::hb6f66070f49159ed
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/test/src/lib.rs:620:34
  32:     0x55fd844a5393 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hedad2e997023f271
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/ops/function.rs:513:5
  33:     0x55fd844d1a96 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h312fea4ff6db7ecf
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/alloc/src/boxed.rs:2000:9
  34:     0x55fd844d1a96 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hdb969e3902e87449
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panic/unwind_safe.rs:271:9
  35:     0x55fd844d1a96 - std::panicking::try::do_call::h6da79ecfef558898
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:483:40
  36:     0x55fd844d1a96 - std::panicking::try::h7f668fbaf77473b2
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:447:19
  37:     0x55fd844d1a96 - std::panic::catch_unwind::ha6924da3c5c9fc14
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panic.rs:137:14
  38:     0x55fd844d1a96 - test::run_test_in_process::hb6aceb0c3bf0084e
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/test/src/lib.rs:660:27
  39:     0x55fd844d1a96 - test::run_test::run_test_inner::{{closure}}::h1f9d76cb3b5cab45
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/test/src/lib.rs:554:39
  40:     0x55fd8449f8e4 - test::run_test::run_test_inner::{{closure}}::hbb1c64585fff0899
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/test/src/lib.rs:581:37
  41:     0x55fd8449f8e4 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc55a7d34ba091187
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys_common/backtrace.rs:121:18
  42:     0x55fd844a5255 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h5f0678941ebc6010
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/thread/mod.rs:551:17
  43:     0x55fd844a5255 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h7b5b1b1b480c0d0b
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panic/unwind_safe.rs:271:9
  44:     0x55fd844a5255 - std::panicking::try::do_call::h75b027545d7dd24a
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:483:40
  45:     0x55fd844a5255 - std::panicking::try::h3231c5548f9f3483
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:447:19
  46:     0x55fd844a5255 - std::panic::catch_unwind::h4b3465df06d90c4b
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panic.rs:137:14
  47:     0x55fd844a5255 - std::thread::Builder::spawn_unchecked_::{{closure}}::h44dacc2db01da8f5
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/thread/mod.rs:550:30
  48:     0x55fd844a5255 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h8e859a243f1af552
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/ops/function.rs:513:5
  49:     0x55fd845014b3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h613d5e218c101168
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/alloc/src/boxed.rs:2000:9
  50:     0x55fd845014b3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hecab0373f4228b53
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/alloc/src/boxed.rs:2000:9
  51:     0x55fd845014b3 - std::sys::unix::thread::Thread::new::thread_start::hd2791a9cabec1fda
                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys/unix/thread.rs:108:17
  52:     0x7fdd1638dea5 - start_thread
  53:     0x7fdd15bb0b0d - clone
  54:                0x0 - <unknown>

**Comment by wuhuizuo** [comment]
happened in https://github.com/PingCAP-QE/ci/pull/5157

**Comment by wuhuizuo** [comment]
## Root cause analysis (reproduced again in 2026)

While verifying a CI migration PR — PingCAP-QE/ci#5157 (https://github.com/PingCAP-QE/ci/pull/5157) — this test failed again on a different Jenkins environment. We dug into it; sharing the root cause below.

**Summary:** this is a **race**, not a deterministic logic error. The bench produces `SequenceNumber`s for which `number` and `end_counter` are not consistently ordered, while `SequenceNumberWindow::push` asserts that they are.

### Failure

- Panic at `components/engine_traits/src/util.rs:156`: `committed_seqno 4768, seqno4767`
- The values differ on every run, i.e. it is non-deterministic:
  - `committed_seqno 13763, seqno13762`
  - `committed_seqno 98671, seqno98670`
  - `committed_seqno 4768, seqno4767`

### Where the inconsistency is created

`components/engine_traits/src/util.rs:78-81`:

```rust
pub fn post_write(&mut self, number: u64) {
    self.number = number;                                              // seqno, provided by the caller
    self.end_counter = WRITE_COUNTER_ALLOCATOR.load(Ordering::SeqCst); // snapshot from a *separate* atomic
}
```

`number` is assigned first, then `end_counter` is read from the global write counter. These are two independent atomics sampled at different times, so two writes can end up with `number` and `end_counter` in opposite order.

### Where the assumption is

`components/engine_traits/src/util.rs:155-163` (`push`):

```rust
if let Some(sequence) = sequences.values().max() {
    assert!(
        self.committed_seqno <= sequence.number,   // <-- assumes monotonicity
        "committed_seqno {}, seqno{}", self.committed_seqno, sequence.number
    );
    self.committed_seqno = sequence.number;
}
```

It assumes that committing groups in increasing `end_counter` order also commits non-decreasing `number`s. That does not hold.

### Interleaving that triggers it

With the 16 producer threads in the bench:

```
1. Q: pre_write()               -> start_counter = s_q
2. Q: post_write: number = n_q          (fetch_add, earlier)
3. P: pre_write()               -> start_counter = s_p
4. P: post_write: number = n_p > n_q    (fetch_add, later)
5. P:               end_counter = e_p    (load, earlier)
6. (another pre_write advances the global counter)
7. Q:               end_counter = e_q    (load, later; e_q > e_p)
```

Group `end_counter = e_p` (which carries the larger `number n_p`) commits first → `committed_seqno = n_p`. Then group `end_counter = e_q` (max `number = n_q < n_p`) commits → assertion fails.

### Is this only a test issue?

The bench faithfully reproduces what `pre_write()` / `post_write()` produce. The same non-atomic pairing exists on the write path (e.g. the `disable_wal` path in `raftstore/.../apply.rs`), where multiple apply threads can call `pre_write`/`post_write` concurrently.

Scope note: `SequenceNumberWindow` currently has no other call sites in the repo (only this file's tests), so the impact today is limited to the unit-test job.

### Suggested fix

Make the committed watermark monotonic instead of asserting — a group that commits later may legitimately carry a smaller `number`:

```rust
if let Some(sequence) = sequences.values().max() {
    self.committed_seqno = self.committed_seqno.max(sequence.number);
}
```

Regression test (must live in the same module because the fields are private):

```rust
#[test]
fn test_committed_seqno_monotonic_under_out_of_order_end_counter() {
    let mut w = SequenceNumberWindow::default();
    w.push(SequenceNumber { number: 2, memtable_version: 0, start_counter: 1, end_counter: 2 });
    w.push(SequenceNumber { number: 1, memtable_version: 0, start_counter: 2, end_counter: 3 });
    w.push(SequenceNumber { number: 3, memtable_version: 0, start_counter: 3, end_counter: 4 });
    assert_eq!(w.committed_seqno(), 2);
}
```

Alternatively, if the intended contract is that `number` and `end_counter` must be consistent, the fix belongs in `post_write` (capture both atomically); the current code does not provide that guarantee.

### Introduced by

The whole `SequenceNumber` / `SequenceNumberWindow` machinery and the failing assertion were introduced together by **tikv/tikv#12978** ("raftstore: set seqno in ApplyRes", merged **2022-09-16**, merge commit `fd84225ba`):

- `cbffbc6076` (2022-08-18, *"add bench"*) — added `bench_sequence_number_window`.
- `49bd9e81eb` (2022-09-14, *"add assert"*) — added the assertion at `util.rs:156` that panics:
  ```rust
  assert!(
      self.committed_seqno <= sequence.number,
      "committed_seqno {}, seqno{}", self.committed_seqno, sequence.number
  );
  ```

Before that PR, `components/engine_traits/src/util.rs` contained only `check_key_in_range` (23 lines) — no `SequenceNumber`, no `WRITE_COUNTER_ALLOCATOR`, no window. So both the non-atomic `number`/`end_counter` pairing in `post_write` and the monotonicity assumption in `push` originate from #12978.

Timeline:

| Date | Event |
| --- | --- |
| 2022-08-18 | bench added (#12978, `cbffbc6076`) |
| 2022-09-14 | assertion added (#12978, `49bd9e81eb`) |
| 2022-09-16 | #12978 merged (`fd84225ba`) |
| 2023-05-19 | this issue filed |

### CI note

The `#[bench]` is executed as a regular test by nextest (`cargo nextest run -P ci`), so a benchmark is currently gating the unit-test job — worth addressing separately.
