### ISSUE TITLE
[dr-autosync] tikv flashback to version panic 

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/tikv#14974]
### Steps to reproduce

After switching to backup dc in sync_recover mode,  try use tikv flashback to recover ACID.

### What did you expect?
succeeded.

### What did happened?
sh-4.2# tiup ctl:v6.5.3 tikv --pd  pd3-peer.dr-autosync-hongmei-testbedz4qk6:2379 flashback -v 442278746550698004
Starting component `ctl`: /root/.tiup/components/ctl/v6.5.3/ctl /root/.tiup/components/ctl/v6.5.3/ctl tikv --pd pd3-peer.dr-autosync-hongmei-testbedz4qk6:2379 flashback -v 442278746550698004
thread 'flashback' panicked at 'called `Result::unwrap()` on an `Err` value: Other("[components/pd_client/src/[util.rs:878](http://util.rs:878/)]: invalid store ID 0, not found")', cmd/tikv-ctl/src/[main.rs:820](http://main.rs:820/):62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(3), ...)', cmd/tikv-ctl/src/[main.rs:945](http://main.rs:945/):6
Error: exit status 101

**Comment by mayjiang0203** [comment]
if monitoring or logs are needed, please refer to clinic by cluster-id 7246288782355082500.
Hit it twice till now.

**Comment by mayjiang0203** [comment]
after online recovery, there is still one region that not exist in tikv but exist in pd.

sh-4.2# tiup ctl:v6.5.3 pd -u http://pd3-peer.dr-autosync-hongmei-testbedz4qk6:2379 region 1010
Starting component `ctl`: /root/.tiup/components/ctl/v6.5.3/ctl /root/.tiup/components/ctl/v6.5.3/ctl pd -u http://pd3-peer.dr-autosync-hongmei-testbedz4qk6:2379 region 1010
{
  "id": 1010,
  "start_key": "7480000000000000FF555F728000000000FF0171FE0000000000FA",
  "end_key": "7480000000000000FF555F728000000000FF0361360000000000FA",
  "epoch": {
    "conf_ver": 12,
    "version": 72
  },
  "peers": [
    {
      "id": 1011,
      "store_id": 1,
      "role": 1,
      "role_name": "Learner",
      "is_learner": true
    },
    {
      "id": 1012,
      "store_id": 6,
      "role_name": "Voter"
    },
    {
      "id": 1013,
      "store_id": 5,
      "role_name": "Voter"
    },
    {
      "id": 1014,
      "store_id": 7,
      "role_name": "Voter"
    },
    {
      "id": 1015,
      "store_id": 9,
      "role_name": "Voter"
    },
    {
      "id": 1016,
      "store_id": 8,
      "role_name": "Voter"
    }
  ],
  "leader": {
    "role_name": ""
  },
  "cpu_usage": 0,
  "written_bytes": 0,
  "read_bytes": 0,
  "written_keys": 0,
  "read_keys": 0,
  "approximate_size": 0,
  "approximate_keys": 0
}

sh-4.2# tiup ctl:v6.5.3 tikv --host tikv6-peer:20160 raft region --start 7480000000000000FF555F728000000000FF0171FE0000000000FA --end 7480000000000000FF555F728000000000FF0361360000000000FA
Starting component `ctl`: /root/.tiup/components/ctl/v6.5.3/ctl /root/.tiup/components/ctl/v6.5.3/ctl tikv --host tikv6-peer:20160 raft region --start 7480000000000000FF555F728000000000FF0171FE0000000000FA --end 7480000000000000FF555F728000000000FF0361360000000000FA
{
  "region_infos": {
    "404": {
      "region_id": 404,
      "region_local_state": {
        "region": {
          "id": 404,
          "start_key": "7480000000000000FF555F728000000000FF0171FE0000000000FA",
          "end_key": "7480000000000000FF555F72FFFFFFFFFFFFFFFFFF0000000000FB",
          "region_epoch": {
            "conf_ver": 22,
            "version": 71
          },
          "peers": [
            {
              "id": 405,
              "store_id": 1,
              "role": "Voter"
            },
            {
              "id": 406,
              "store_id": 6,
              "role": "Voter"
            },
            {
              "id": 410,
              "store_id": 8,
              "role": "Voter"
            }
          ]
        }
      },
      "raft_local_state": {
        "hard_state": {
          "term": 19,
          "vote": 406,
          "commit": 29374
        },
        "last_index": 29374
      },
      "raft_apply_state": {
        "applied_index": 29374,
        "commit_index": 29374,
        "commit_term": 19,
        "truncated_state": {
          "index": 29372,
          "term": 18
        }
      }
    }
  }
}
