### ISSUE TITLE
[dr-autosync] during sync_recover, workload report error: Region is unavailable

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/tikv#14975]
### What version of TiKV are you using?

v6.5.3

### Steps to reproduce

a. down backup dc and make cluster work in the async mode for more than 10h with workload running.
b. recover backup dc，restart workload hit error of  "Region is unavailable"

### What did you expect?
no error reported

### What did happened?
[2023/06/20 10:51:08.959 +08:00] [INFO] [utils.go:55] ["current status is "] [curStatus=sync_recover]
java -cp .:lib/mysql-connector-java-5.1.49.jar batch_hy_zd "tiup-peer.e2e-dr-auto-sync-5r-pref-tps-1809605-1-603:3390" "root" "" 30  ecasdb 20
java.sql.SQLException: Region is unavailable
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2439)
        at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1365)
        at batch_hy_zd.getMax(batch_hy_zd.java:193)
        at batch_hy_zd.main(batch_hy_zd.java:69)

test cluster id: 7246458230958436285

**Comment by mayjiang0203** [comment]
should set replication-mode.pause-region-split: true in async mode

**Comment by nolouch** [comment]
ref https://github.com/tikv/tikv/issues/7945
