### ISSUE TITLE
flaky test case: test_gen_split_check_bucket_ranges

### ISSUE THREAD

**Issue by glorv** [tikv/tikv#15862]
### What version of TiKV are you using?

nightly

### What did happened?
I see this case in tikv's ci failed several times.

https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/39508/pipeline/
https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/39502/pipeline/

```
[2023-10-27T08:58:16.947Z] --- TRY 3 STDERR:        tests::integrations raftstore::test_split_region::test_gen_split_check_bucket_ranges ---

[2023-10-27T08:58:16.947Z] thread 'raftstore-5-1::test_gen_split_check_bucket_ranges' panicked at 'assertion failed: `(left == right)`

[2023-10-27T08:58:16.947Z]   left: `0`,

[2023-10-27T08:58:16.947Z]  right: `2`', /home/jenkins/tikv-src/components/test_raftstore/src/cluster.rs:1923:21

[2023-10-27T08:58:16.947Z] stack backtrace:

[2023-10-27T08:58:16.947Z]    0: rust_begin_unwind

[2023-10-27T08:58:16.947Z]              at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:575:5

[2023-10-27T08:58:16.947Z]    1: core::panicking::panic_fmt

[2023-10-27T08:58:16.947Z]              at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panicking.rs:65:14

[2023-10-27T08:58:16.947Z]    2: core::panicking::assert_failed_inner

[2023-10-27T08:58:16.947Z]    3: core::panicking::assert_failed

[2023-10-27T08:58:16.947Z]    4: test_raftstore::cluster::Cluster<T>::send_half_split_region_message::{{closure}}

[2023-10-27T08:58:16.947Z]              at /home/jenkins/tikv-src/components/test_raftstore/src/cluster.rs:1923:21

[2023-10-27T08:58:16.947Z]    5: core::ops::function::FnOnce::call_once{{vtable.shim}}

[2023-10-27T08:58:16.947Z]              at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/ops/function.rs:513:5

[2023-10-27T08:58:16.947Z]    6: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once

[2023-10-27T08:58:16.947Z]    7: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::on_schedule_half_split_region

[2023-10-27T08:58:16.947Z]    8: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::on_casual_msg

[2023-10-27T08:58:16.947Z]    9: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::handle_msgs

[2023-10-27T08:58:16.947Z]   10: <raftstore::store::fsm::store::RaftPoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore::store::fsm::peer::PeerFsm<EK,ER>,raftstore::store::fsm::store::StoreFsm<EK>>>::handle_normal

[2023-10-27T08:58:16.947Z]   11: batch_system::batch::Poller<N,C,Handler>::poll

[2023-10-27T08:58:16.947Z]   12: batch_system::batch::BatchSystem<N,C>::start_poller::{{closure}}

[2023-10-27T08:58:16.947Z]   13: <std::thread::Builder as tikv_util::sys::thread::StdThreadBuildWrapper>::spawn_wrapper::{{closure}}

[2023-10-27T08:58:16.947Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

[2023-10-27T08:58:16.947Z] thread 'raftstore::test_split_region::test_gen_split_check_bucket_ranges' panicked at 'called `Result::unwrap()` on an `Err` value: Disconnected', /home/jenkins/tikv-src/components/test_raftstore/src/cluster.rs:1946:49

[2023-10-27T08:58:16.947Z] stack backtrace:

[2023-10-27T08:58:16.947Z]    0: rust_begin_unwind

[2023-10-27T08:58:16.947Z]              at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:575:5

[2023-10-27T08:58:16.947Z]    1: core::panicking::panic_fmt

[2023-10-27T08:58:16.947Z]              at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panicking.rs:65:14

[2023-10-27T08:58:16.948Z]    2: core::result::unwrap_failed

[2023-10-27T08:58:16.948Z]              at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/result.rs:1791:5

[2023-10-27T08:58:16.948Z]    3: core::result::Result<T,E>::unwrap

[2023-10-27T08:58:16.948Z]              at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/result.rs:1113:23

[2023-10-27T08:58:16.948Z]    4: test_raftstore::cluster::Cluster<T>::send_half_split_region_message

[2023-10-27T08:58:16.948Z]              at /home/jenkins/tikv-src/components/test_raftstore/src/cluster.rs:1946:9

[2023-10-27T08:58:16.948Z]    5: integrations::raftstore::test_split_region::test_gen_split_check_bucket_ranges

[2023-10-27T08:58:16.948Z]              at /home/jenkins/tikv-src/tests/integrations/raftstore/test_split_region.rs:1219:5

[2023-10-27T08:58:16.948Z]    6: integrations::raftstore::test_split_region::test_gen_split_check_bucket_ranges::{{closure}}

[2023-10-27T08:58:16.948Z]              at /home/jenkins/tikv-src/tests/integrations/raftstore/test_split_region.rs:1164:41

[2023-10-27T08:58:16.948Z]    7: core::ops::function::FnOnce::call_once

[2023-10-27T08:58:16.948Z]              at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/ops/function.rs:513:5

[2023-10-27T08:58:16.948Z]    8: test_util::runner::run_test_with_hook::{{closure}}::{{closure}}

[2023-10-27T08:58:16.948Z]    9: core::ops::function::FnOnce::call_once{{vtable.shim}}

[2023-10-27T08:58:16.948Z]   10: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once

[2023-10-27T08:58:16.948Z]              at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/alloc/src/boxed.rs:2000:9

[2023-10-27T08:58:16.948Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by glorv** [comment]
@bufferflies Does this related to your recent changes in region buckets?
