### ISSUE TITLE
Flaky test case raftstore::test_stats::test_query_stats – tests::integrations

### ISSUE THREAD

**Issue by tonyxuqqi** [tikv/tikv#16367]
https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/41683/tests/

tacktrace
thread 'raftstore::test_stats::test_query_stats' panicked at 'assertion failed: flag', tests/integrations/raftstore/test_stats.rs:282:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panicking.rs:65:14
   2: core::panicking::panic
             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panicking.rs:114:5
   3: integrations::raftstore::test_stats::test_raw_query_stats_tmpl::{{closure}}
   4: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/alloc/src/boxed.rs:2032:9
   5: integrations::raftstore::test_stats::test_query_num
             at /home/jenkins/tikv-src/tests/integrations/raftstore/test_stats.rs:600:5
   6: integrations::raftstore::test_stats::test_raw_query_stats_tmpl
             at /home/jenkins/tikv-src/tests/integrations/raftstore/test_stats.rs:294:5
   7: integrations::raftstore::test_stats::test_query_stats
             at /home/jenkins/tikv-src/tests/integrations/raftstore/test_stats.rs:148:5
   8: integrations::raftstore::test_stats::test_query_stats::{{closure}}
             at /home/jenkins/tikv-src/tests/integrations/raftstore/test_stats.rs:147:23
   9: core::ops::function::FnOnce::call_once
             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/ops/function.rs:513:5
  10: test_util::runner::run_test_with_hook::{{closure}}::{{closure}}
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
  12: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/alloc/src/boxed.rs:2000:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by LykxSassinator** [comment]
The CI errors are stale and the details are expired.

Based on nightly branch(commit_id: 653ec843c148e4fadb08c1a5b29de96b430f9058), this flaky test cannot be reproduced currently.

Hold on for it.
