### ISSUE TITLE
TiKV built failed on Manjaro linux

### ISSUE THREAD

**Issue by lance6716** [tikv/tikv#16593]
### What version of TiKV are you using?

master

### What operating system and CPU are you using?

Manjaro

### Steps to reproduce

```
make build
```

### What did you expect?

success

### What did happened?

```
...
  /home/lance/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/05fc3f8/librocksdb_sys/rocksdb/monitoring/perf_flag.cc:19:20: error: ‘PerfFlag’ was not declared in this scope; did you mean ‘CheckPerfFlag’?
     19 | bool CheckPerfFlag(PerfFlag flag) { return perf_flags.test(flag); }
        |                    ^~~~~~~~
        |                    CheckPerfFlag
  /home/lance/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/05fc3f8/librocksdb_sys/rocksdb/monitoring/perf_flag.cc:21:1: error: ‘PerfFlags’ does not name a type
     21 | PerfFlags GetPerfFlags() { return perf_flags; }
        | ^~~~~~~~~
  /home/lance/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/05fc3f8/librocksdb_sys/rocksdb/monitoring/perf_flag.cc:23:6: error: variable or field ‘SetPerfFlags’ declared void
     23 | void SetPerfFlags(PerfFlags flags) { perf_flags = flags; }
        |      ^~~~~~~~~~~~
  /home/lance/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/05fc3f8/librocksdb_sys/rocksdb/monitoring/perf_flag.cc:23:19: error: ‘PerfFlags’ was not declared in this scope
     23 | void SetPerfFlags(PerfFlags flags) { perf_flags = flags; }
        |                   ^~~~~~~~~
  make[4]: *** [CMakeFiles/rocksdb.dir/build.make:1885: CMakeFiles/rocksdb.dir/monitoring/perf_flag.cc.o] Error 1
  make[4]: *** Waiting for unfinished jobs....
  cc1plus: all warnings being treated as errors
  make[4]: *** [CMakeFiles/rocksdb.dir/build.make:555: CMakeFiles/rocksdb.dir/db/db_impl/db_impl.cc.o] Error 1
  make[3]: *** [CMakeFiles/Makefile2:142: CMakeFiles/rocksdb.dir/all] Error 2
  make[2]: *** [CMakeFiles/Makefile2:149: CMakeFiles/rocksdb.dir/rule] Error 2
  make[1]: *** [Makefile:172: rocksdb] Error 2
  thread 'main' panicked at /home/lance/.cargo/git/checkouts/cmake-rs-1b5303aca42ae56b/00e6b22/src/lib.rs:1054:5:

  command did not execute successfully, got: exit status: 2

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**Comment by lance6716** [comment]
I'm using GCC13, maybe I should try to downgrade it to 12 as https://github.com/tikv/tikv/issues/12888

**Comment by lance6716** [comment]
after I switch to gcc 12 `export CC=gcc-12 CXX=g++-12`, new error is

```
  CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
    Could NOT find gflags (missing: GFLAGS_LIBRARIES GFLAGS_INCLUDE_DIR)
  Call Stack (most recent call first):
    /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
    /home/lance/Projects/tikv/target/x86_64-unknown-linux-gnu/debug/build/libtitan_sys-16bebfd88ea769f7/out/build/rocksdb/cmake/modules/Findgflags.cmake:15 (find_package_handle_standard_args)
    /home/lance/Projects/tikv/target/x86_64-unknown-linux-gnu/debug/build/libtitan_sys-16bebfd88ea769f7/out/build/rocksdb/CMakeLists.txt:137 (find_package)

  
     Called from: [4]   /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake
                  [3]   /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake
                  [2]   /home/lance/Projects/tikv/target/x86_64-unknown-linux-gnu/debug/build/libtitan_sys-16bebfd88ea769f7/out/build/rocksdb/cmake/modules/Findgflags.cmake
                  [1]   /home/lance/Projects/tikv/target/x86_64-unknown-linux-gnu/debug/build/libtitan_sys-16bebfd88ea769f7/out/build/rocksdb/CMakeLists.txt
     Returning to         /home/lance/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/05fc3f8/librocksdb_sys/libtitan_sys/titan
     Called from: [1]   /home/lance/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/05fc3f8/librocksdb_sys/libtitan_sys/titan/CMakeLists.txt
  thread 'main' panicked at /home/lance/.cargo/git/checkouts/cmake-rs-1b5303aca42ae56b/00e6b22/src/lib.rs:1054:5:

  command did not execute successfully, got: exit status: 1

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [Makefile:204: build] Error 101
```

**Comment by lance6716** [comment]
I can build after install gflags now

**Comment by AstroProfundis** [comment]
GCC 12.4.0 or newer fails to build on my ArchLinux environment, 12.3.0 works. And it seems to be related to #18001
