### ISSUE TITLE
Flaky test test_endpoint::test_cdc_pipeline_dml

### ISSUE THREAD

**Issue by glorv** [tikv/tikv#17530]
## Bug Report

```
--- TRY 3 STDERR:        cdc::failpoints test_endpoint::test_cdc_pipeline_dml ---

thread 'test_endpoint::test_cdc_pipeline_dml' panicked at components/cdc/tests/failpoints/../mod.rs:111:87:

called `Result::unwrap()` on an `Err` value: ()

stack backtrace:

   0: rust_begin_unwind

             at /rustc/89e2160c4ca5808657ed55392620ed1dbbce78d1/library/std/src/panicking.rs:645:5

   1: core::panicking::panic_fmt

             at /rustc/89e2160c4ca5808657ed55392620ed1dbbce78d1/library/core/src/panicking.rs:72:14

   2: core::result::unwrap_failed

             at /rustc/89e2160c4ca5808657ed55392620ed1dbbce78d1/library/core/src/result.rs:1649:5

   3: core::result::Result<T,E>::unwrap

   4: failpoints::testsuite::create_event_feed::{{closure}}

   5: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call

   6: failpoints::test_endpoint::test_cdc_pipeline_dml

   7: failpoints::test_endpoint::test_cdc_pipeline_dml::{{closure}}

   8: core::ops::function::FnOnce::call_once

   9: test_util::runner::run_test_with_hook::{{closure}}::{{closure}}

  10: core::ops::function::FnOnce::call_once{{vtable.shim}}

  11: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once

             at /rustc/89e2160c4ca5808657ed55392620ed1dbbce78d1/library/alloc/src/boxed.rs:2015:9

note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by glorv** [comment]
duplicated with #17534
