### ISSUE TITLE
flaky test: test_split_region_with_no_valid_split_keys

### ISSUE THREAD

**Issue by glorv** [tikv/tikv#17557]
```
--- TRY 3 STDERR:        tests::failpoints cases::test_split_region::test_split_region_with_no_valid_split_keys ---

thread 'cases::test_split_region::test_split_region_with_no_valid_split_keys' panicked at tests/failpoints/cases/test_split_region.rs:1530:45:

called `Result::unwrap()` on an `Err` value: Timeout

stack backtrace:

   0: rust_begin_unwind

             at /rustc/89e2160c4ca5808657ed55392620ed1dbbce78d1/library/std/src/panicking.rs:645:5

   1: core::panicking::panic_fmt

             at /rustc/89e2160c4ca5808657ed55392620ed1dbbce78d1/library/core/src/panicking.rs:72:14

   2: core::result::unwrap_failed

             at /rustc/89e2160c4ca5808657ed55392620ed1dbbce78d1/library/core/src/result.rs:1649:5

   3: core::result::Result<T,E>::unwrap

   4: failpoints::cases::test_split_region::test_split_region_with_no_valid_split_keys

             at /home/jenkins/tikv-src/tests/failpoints/cases/test_split_region.rs:1530:5

   5: failpoints::cases::test_split_region::test_split_region_with_no_valid_split_keys::{{closure}}

             at /home/jenkins/tikv-src/tests/failpoints/cases/test_split_region.rs:1502:48

   6: core::ops::function::FnOnce::call_once

             at /rustc/89e2160c4ca5808657ed55392620ed1dbbce78d1/library/core/src/ops/function.rs:250:5

   7: test_util::runner::run_test_with_hook::{{closure}}::{{closure}}

   8: core::ops::function::FnOnce::call_once{{vtable.shim}}

   9: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once

             at /rustc/89e2160c4ca5808657ed55392620ed1dbbce78d1/library/alloc/src/boxed.rs:2015:9

note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
https://do.pingcap.net/jenkins/blue/organizations/jenkins/tikv%2Ftikv%2Fpull_unit_test/detail/pull_unit_test/1485/pipeline/84/

This case has been captured as flaky in the last two weeks for more than 60 times.

**Comment by hbisheng** [comment]
https://github.com/tikv/tikv/pull/17919 hit this test failure as well. 

I was able to reproduce this issue locally with a 1% probability (reproduced once in 100 runs). I can take a closer look at this.
