### ISSUE TITLE
Flaky test `tests::failpoints cases::test_replica_stale_read::test_update_apply_index_before_sync_read_state`

### ISSUE THREAD

**Issue by wuhuizuo** [tikv/tikv#17654]
### What version of TiKV are you using?
branch: release-7.5
commit: bba48d87b28a45970c1a9ca11a564a04dda7d290

### What operating system and CPU are you using?

CI @ linux/amd64

### Steps to reproduce

CI run the unit job.

### What did you expect?

CI job passed

### What did happened?

Failed with flaky tests

```log

  TRY 3 ABRT [   4.862s] tests::failpoints cases::test_replica_stale_read::test_update_apply_index_before_sync_read_state



--- TRY 3 STDOUT:        tests::failpoints cases::test_replica_stale_read::test_update_apply_index_before_sync_read_state ---



running 1 test



--- TRY 3 STDERR:        tests::failpoints cases::test_replica_stale_read::test_update_apply_index_before_sync_read_state ---

thread 'raftstore-1-0::test_update_apply_index_before_sync_read_state' panicked at 'failpoint on_step_read_index_msg panic', /rust/registry/src/github.com-1ecc6299db9ec823/fail-0.5.1/src/lib.rs:496:25

stack backtrace:

   0: rust_begin_unwind

             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:575:5

   1: core::panicking::panic_fmt

             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panicking.rs:65:14

   2: fail::FailPoint::eval

   3: fail::eval

   4: raftstore::store::peer::Peer<EK,ER>::step

   5: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::on_raft_message

   6: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::handle_msgs

   7: <raftstore::store::fsm::store::RaftPoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore::store::fsm::peer::PeerFsm<EK,ER>,raftstore::store::fsm::store::StoreFsm<EK>>>::handle_normal

   8: batch_system::batch::Poller<N,C,Handler>::poll

   9: batch_system::batch::BatchSystem<N,C>::start_poller::{{closure}}

  10: <std::thread::Builder as tikv_util::sys::thread::StdThreadBuildWrapper>::spawn_wrapper::{{closure}}

note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

thread 'sched-worker-pool::test_update_apply_index_before_sync_read_state-0' panicked at 'undetermined error: Error(Undetermined("async write on_applied callback is dropped")) cid=4, tag=prewrite, process

                        result=Some(PrewriteResult { result: PrewriteResult { locks: [], min_commit_ts: TimeStamp(0), one_pc_commit_ts: TimeStamp(0) } })', /home/jenkins/tikv-src/src/storage/txn/scheduler.rs:870:25

stack backtrace:

   0: rust_begin_unwind

             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:575:5

   1: core::panicking::panic_fmt

             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panicking.rs:65:14

   2: tikv::storage::txn::scheduler::TxnScheduler<E,L>::on_write_finished

   3: tikv::storage::txn::scheduler::TxnScheduler<E,L>::process_write::{{closure}}

   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

   5: tikv::storage::txn::scheduler::TxnScheduler<E,L>::process::{{closure}}::{{closure}}

   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

   7: <resource_metering::InTags<T> as core::future::future::Future>::poll

   8: tikv::storage::txn::scheduler::TxnScheduler<E,L>::process::{{closure}}

   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

  10: tikv::storage::txn::scheduler::TxnScheduler<E,L>::execute::{{closure}}

  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

  12: <tracker::tls::TrackedFuture<F> as core::future::future::Future>::poll::{{closure}}

  13: std::thread::local::LocalKey<T>::try_with

  14: std::thread::local::LocalKey<T>::with

  15: <tracker::tls::TrackedFuture<F> as core::future::future::Future>::poll

  16: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll

  17: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll

  18: yatp::task::future::RawTask<F>::poll

  19: yatp::task::future::TaskCell::poll

  20: <yatp::task::future::Runner as yatp::pool::runner::Runner>::handle

  21: <tikv_util::yatp_pool::YatpPoolRunner<T> as yatp::pool::runner::Runner>::handle

  22: yatp::pool::worker::WorkerThread<T,R>::run

  23: yatp::pool::builder::LazyBuilder<T>::build::{{closure}}

note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

thread 'cases::test_replica_stale_read::test_update_apply_index_before_sync_read_state' panicked at 'called `Result::unwrap()` on an `Err` value: RpcFailure(RpcStatus { code: 1-CANCELLED, message: "CANCELLED", details: [] })', components/test_raftstore/src/util.rs:1025:59

stack backtrace:

   0: rust_begin_unwind

             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:575:5

   1: core::panicking::panic_fmt

             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panicking.rs:65:14

   2: core::result::unwrap_failed

             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/result.rs:1791:5

   3: core::result::Result<T,E>::unwrap

   4: test_raftstore::util::must_kv_prewrite_with

   5: test_raftstore::util::must_kv_prewrite

   6: test_raftstore::util::must_kv_write

   7: test_raftstore::util::PeerClient::must_kv_write

   8: failpoints::cases::test_replica_stale_read::test_update_apply_index_before_sync_read_state

             at /home/jenkins/tikv-src/tests/failpoints/cases/test_replica_stale_read.rs:240:5

   9: failpoints::cases::test_replica_stale_read::test_update_apply_index_before_sync_read_state::{{closure}}

             at /home/jenkins/tikv-src/tests/failpoints/cases/test_replica_stale_read.rs:204:53

  10: core::ops::function::FnOnce::call_once

             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/ops/function.rs:513:5

  11: test_util::runner::run_test_with_hook::{{closure}}::{{closure}}

  12: core::ops::function::FnOnce::call_once{{vtable.shim}}

  13: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once

             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/alloc/src/boxed.rs:2000:9

note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

thread 'cases::test_replica_stale_read::test_update_apply_index_before_sync_read_state' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', /rust/git/checkouts/yatp-e704b73c3ee279b6/5572a78/src/pool.rs:72:26

stack backtrace:

   0:     0x55f5dea93410 - std::backtrace_rs::backtrace::libunwind::trace::he534b130db6360ed

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5

   1:     0x55f5dea93410 - std::backtrace_rs::backtrace::trace_unsynchronized::hc3486e10c7777b38

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5

   2:     0x55f5dea93410 - std::sys_common::backtrace::_print_fmt::ha24198a22cf70db0

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys_common/backtrace.rs:65:5

   3:     0x55f5dea93410 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he928616f28db1c44

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys_common/backtrace.rs:44:22

   4:     0x55f5deabd47e - core::fmt::write::hfc4e1f18015528cf

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/fmt/mod.rs:1209:17

   5:     0x55f5dea8c385 - std::io::Write::write_fmt::h1fe0ff478ba9434a

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/io/mod.rs:1682:15

   6:     0x55f5dea931d5 - std::sys_common::backtrace::_print::hc5210df762c2ee4d

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys_common/backtrace.rs:47:5

   7:     0x55f5dea931d5 - std::sys_common::backtrace::print::h01d5ef97fb586ab1

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys_common/backtrace.rs:34:9

   8:     0x55f5dea94ecf - std::panicking::default_hook::{{closure}}::hfaf4dc37dc2875b0

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:267:22

   9:     0x55f5dea94c0a - std::panicking::default_hook::h22df008dfc46e0e0

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:286:9

  10:     0x55f5dea955cc - std::panicking::rust_panic_with_hook::h8bb52976cbf68a37

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:688:13

  11:     0x55f5dea95367 - std::panicking::begin_panic_handler::{{closure}}::hb6582e9b11a93445

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:579:13

  12:     0x55f5dea938bc - std::sys_common::backtrace::__rust_end_short_backtrace::hd69a588bdd28408e

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys_common/backtrace.rs:137:18

  13:     0x55f5dea95082 - rust_begin_unwind

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:575:5

  14:     0x55f5d7686833 - core::panicking::panic_fmt::hb1806527c2beebe3

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panicking.rs:65:14

  15:     0x55f5d7686af3 - core::result::unwrap_failed::he2b30c6b959db85a

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/result.rs:1791:5

  16:     0x55f5dd3cb7f7 - core::result::Result<T,E>::unwrap::h2d1b506fff2f1b04

  17:     0x55f5dd429a66 - yatp::pool::ThreadPool<T>::shutdown::h09c534635bed83e4

  18:     0x55f5dd429b4a - <yatp::pool::ThreadPool<T> as core::ops::drop::Drop>::drop::h6417c0abbf7582dd

  19:     0x55f5dd3eab85 - core::ptr::drop_in_place<yatp::pool::ThreadPool<yatp::task::future::TaskCell>>::h23ab8c128870596a

  20:     0x55f5dd3ea555 - core::ptr::drop_in_place<tikv_util::yatp_pool::future_pool::PoolInner>::hdae06e44bacf77b7

  21:     0x55f5dd4187a9 - alloc::sync::Arc<T>::drop_slow::h5f2f45abaef9f0ae

  22:     0x55f5dd41941e - <alloc::sync::Arc<T> as core::ops::drop::Drop>::drop::h5744a8e025b2f796

  23:     0x55f5dd3eb2ba - core::ptr::drop_in_place<alloc::sync::Arc<tikv_util::yatp_pool::future_pool::PoolInner>>::he83721c5f25edc07

  24:     0x55f5dd3ea5ba - core::ptr::drop_in_place<tikv_util::yatp_pool::future_pool::FuturePool>::h6eaa825fe32bb6a4

  25:     0x55f5d9c36126 - core::ptr::drop_in_place<tikv::storage::txn::sched_pool::VanillaQueue>::ha16975dff4539b87

  26:     0x55f5d9c34255 - core::ptr::drop_in_place<tikv::storage::txn::sched_pool::SchedPool>::h38c558354c21e6fa

  27:     0x55f5d9be947b - core::ptr::drop_in_place<tikv::storage::txn::scheduler::TxnSchedulerInner<tikv::server::lock_manager::LockManager>>::h324892b495b0222f

  28:     0x55f5d9a6685c - alloc::sync::Arc<T>::drop_slow::h0b42620b0fb01b99

  29:     0x55f5d9a7f47e - <alloc::sync::Arc<T> as core::ops::drop::Drop>::drop::hf88fe24669a6e917

  30:     0x55f5d9bf48fa - core::ptr::drop_in_place<alloc::sync::Arc<tikv::storage::txn::scheduler::TxnSchedulerInner<tikv::server::lock_manager::LockManager>>>::hef6c41520c5b6ced

  31:     0x55f5d993b5ea - core::ptr::drop_in_place<tikv::storage::txn::scheduler::TxnScheduler<tikv::server::raftkv::RaftKv<engine_rocks::engine::RocksEngine,test_raftstore::transport_simulate::SimulateTransport<raftstore::router::ServerRaftStoreRouter<engine_rocks::engine::RocksEngine,raft_log_engine::engine::RaftLogEngine>>>,tikv::server::lock_manager::LockManager>>::hafb4022b2ddd67dc

  32:     0x55f5d993b206 - core::ptr::drop_in_place<tikv::storage::Storage<tikv::server::raftkv::RaftKv<engine_rocks::engine::RocksEngine,test_raftstore::transport_simulate::SimulateTransport<raftstore::router::ServerRaftStoreRouter<engine_rocks::engine::RocksEngine,raft_log_engine::engine::RaftLogEngine>>>,tikv::server::lock_manager::LockManager,api_version::ApiV1>>::h7d4641ca39791044

  33:     0x55f5d993dd9e - core::ptr::drop_in_place<tikv::server::service::kv::Service<tikv::server::raftkv::RaftKv<engine_rocks::engine::RocksEngine,test_raftstore::transport_simulate::SimulateTransport<raftstore::router::ServerRaftStoreRouter<engine_rocks::engine::RocksEngine,raft_log_engine::engine::RaftLogEngine>>>,tikv::server::lock_manager::LockManager,api_version::ApiV1>>::h0d1babb0c4b8f706

  34:     0x55f5d9954c15 - core::ptr::drop_in_place<tikv::server::server::BuilderFactory<tikv::server::service::kv::Service<tikv::server::raftkv::RaftKv<engine_rocks::engine::RocksEngine,test_raftstore::transport_simulate::SimulateTransport<raftstore::router::ServerRaftStoreRouter<engine_rocks::engine::RocksEngine,raft_log_engine::engine::RaftLogEngine>>>,tikv::server::lock_manager::LockManager,api_version::ApiV1>>>::hc4d453942dcaa52e

  35:     0x55f5d9c42d7b - core::ptr::drop_in_place<alloc::boxed::Box<dyn tikv::server::server::GrpcBuilderFactory>>::h9e39b1f222ed3c97

  36:     0x55f5d9939fc9 - core::ptr::drop_in_place<tikv::server::server::Server<tikv::server::resolve::PdStoreAddrResolver,tikv::server::raftkv::RaftKv<engine_rocks::engine::RocksEngine,test_raftstore::transport_simulate::SimulateTransport<raftstore::router::ServerRaftStoreRouter<engine_rocks::engine::RocksEngine,raft_log_engine::engine::RaftLogEngine>>>>>::h863d80f0ec901ca5

  37:     0x55f5d96c8aef - <test_raftstore::server::ServerCluster as test_raftstore::cluster::Simulator>::stop_node::h5642ecbfba070109

  38:     0x55f5d8c5bbb0 - test_raftstore::cluster::Cluster<T>::stop_node::h86ac7b6ae77fa15e

  39:     0x55f5d8c5f3a5 - test_raftstore::cluster::Cluster<T>::shutdown::h4ca8ed011dddba85

  40:     0x55f5d8c5fbdc - <test_raftstore::cluster::Cluster<T> as core::ops::drop::Drop>::drop::h818e94e8553a44cc

  41:     0x55f5d99cd035 - core::ptr::drop_in_place<test_raftstore::cluster::Cluster<test_raftstore::server::ServerCluster>>::hf8d7b5ec0f4482fd

  42:     0x55f5d796501c - failpoints::cases::test_replica_stale_read::test_update_apply_index_before_sync_read_state::h9a83ec8078337fe0

                               at /home/jenkins/tikv-src/tests/failpoints/cases/test_replica_stale_read.rs:249:1

  43:     0x55f5d7a0e4be - failpoints::cases::test_replica_stale_read::test_update_apply_index_before_sync_read_state::{{closure}}::h4af353fdac946363

                               at /home/jenkins/tikv-src/tests/failpoints/cases/test_replica_stale_read.rs:204:53

  44:     0x55f5d7a0e4be - core::ops::function::FnOnce::call_once::ha8f9d691c6f1730e

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/ops/function.rs:513:5

  45:     0x55f5d9a19415 - test_util::runner::run_test_with_hook::{{closure}}::{{closure}}::h4089a60f4bebbd79

  46:     0x55f5d9a1e814 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h55a73f8cf89ec84c

  47:     0x55f5dbc7c61a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h312fea4ff6db7ecf

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/alloc/src/boxed.rs:2000:9

  48:     0x55f5dbc7c61a - test::__rust_begin_short_backtrace::hb48c52ec89163dba

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/test/src/lib.rs:637:18

  49:     0x55f5dbc4f263 - test::run_test::{{closure}}::hb6f66070f49159ed

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/test/src/lib.rs:620:34

  50:     0x55f5dbc4f263 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hedad2e997023f271

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/ops/function.rs:513:5

  51:     0x55f5dbc7b5c6 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h312fea4ff6db7ecf

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/alloc/src/boxed.rs:2000:9

  52:     0x55f5dbc7b5c6 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hdb969e3902e87449

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panic/unwind_safe.rs:271:9

  53:     0x55f5dbc7b5c6 - std::panicking::try::do_call::h6da79ecfef558898

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:483:40

  54:     0x55f5dbc7b5c6 - std::panicking::try::h7f668fbaf77473b2

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:447:19

  55:     0x55f5dbc7b5c6 - std::panic::catch_unwind::ha6924da3c5c9fc14

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panic.rs:137:14

  56:     0x55f5dbc7b5c6 - test::run_test_in_process::hb6aceb0c3bf0084e

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/test/src/lib.rs:660:27

  57:     0x55f5dbc7b5c6 - test::run_test::run_test_inner::{{closure}}::h1f9d76cb3b5cab45

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/test/src/lib.rs:554:39

  58:     0x55f5dbc49a64 - test::run_test::run_test_inner::{{closure}}::hbb1c64585fff0899

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/test/src/lib.rs:581:37

  59:     0x55f5dbc49a64 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc55a7d34ba091187

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys_common/backtrace.rs:121:18

  60:     0x55f5dbc4f125 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h5f0678941ebc6010

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/thread/mod.rs:551:17

  61:     0x55f5dbc4f125 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h7b5b1b1b480c0d0b

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panic/unwind_safe.rs:271:9

  62:     0x55f5dbc4f125 - std::panicking::try::do_call::h75b027545d7dd24a

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:483:40

  63:     0x55f5dbc4f125 - std::panicking::try::h3231c5548f9f3483

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:447:19

  64:     0x55f5dbc4f125 - std::panic::catch_unwind::h4b3465df06d90c4b

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panic.rs:137:14

  65:     0x55f5dbc4f125 - std::thread::Builder::spawn_unchecked_::{{closure}}::h44dacc2db01da8f5

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/thread/mod.rs:550:30

  66:     0x55f5dbc4f125 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h8e859a243f1af552

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/ops/function.rs:513:5

  67:     0x55f5dea9bae3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h613d5e218c101168

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/alloc/src/boxed.rs:2000:9

  68:     0x55f5dea9bae3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hecab0373f4228b53

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/alloc/src/boxed.rs:2000:9

  69:     0x55f5dea9bae3 - std::sys::unix::thread::Thread::new::thread_start::hd2791a9cabec1fda

                               at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys/unix/thread.rs:108:17

  70:     0x7f8e44418ea5 - start_thread

  71:     0x7f8e43e3f9fd - __clone

  72:                0x0 - <unknown>

thread panicked while panicking. aborting.



error: test run failed

+ gdb -c 'core.*' -batch -ex 'info threads' -ex 'thread apply all bt'

/home/jenkins/agent/tikv-presubmit/unit-test/core.*: No such file or directory.

No threads.

+ exit 1

script returned exit code 1
```

CI build link: https://do.pingcap.net/jenkins/job/tikv/job/tikv/job/release-7.5/job/pull_unit_test/195/

Ref #17653

**Comment by wuhuizuo** [comment]
dup with #17497

**Comment by wuhuizuo** [comment]
dup with https://github.com/tikv/tikv/issues/17497
