### ISSUE TITLE
rate limiter: flaky test "test_rate_limited_hybrid_flow"

### ISSUE THREAD

**Issue by Tristan1900** [tikv/tikv#17883]
## Bug Report

```


running 1 test
test rate_limiter::tests::test_rate_limited_hybrid_flow ... FAILED

failures:

failures:
    rate_limiter::tests::test_rate_limited_hybrid_flow

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 21 filtered out; finished in 2.04s


--- TRY 3 STDERR:        file_system rate_limiter::tests::test_rate_limited_hybrid_flow ---
thread 'rate_limiter::tests::test_rate_limited_hybrid_flow' panicked at components/file_system/src/rate_limiter.rs:817:9:
assertion failed: (write_bytes as f64) >=
    ((write_work * bytes_per_sec / 100) as f64 * duration.as_secs_f64()) *
        0.75
stack backtrace:
   0: rust_begin_unwind
             at /rustc/89e2160c4ca5808657ed55392620ed1dbbce78d1/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/89e2160c4ca5808657ed55392620ed1dbbce78d1/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/89e2160c4ca5808657ed55392620ed1dbbce78d1/library/core/src/panicking.rs:144:5
   3: file_system::rate_limiter::tests::test_rate_limited_hybrid_flow
   4: file_system::rate_limiter::tests::test_rate_limited_hybrid_flow::{{closure}}
   5: core::ops::function::FnOnce::call_once
   6: core::ops::function::FnOnce::call_once
             at /rustc/89e2160c4ca5808657ed55392620ed1dbbce78d1/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by LykxSassinator** [comment]
Dup with https://github.com/tikv/tikv/issues/16434
