### ISSUE TITLE
test raftstore::test_tombstone::test_server_tombstone failed

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#1929]
```
thread 'raftstore::test_tombstone::test_server_tombstone' panicked at 'state: Tombstone region {id: 1 start_key: "" end_key: "" region_epoch {conf_ver: 3 version: 1} peers {id: 1 store_id: 1} peers {id: 2 store_id: 2} peers {id: 3 store_id: 3}} != state: Tombstone region {id: 1 start_key: "" end_key: "" region_epoch {conf_ver: 4 version: 1} peers {id: 1 store_id: 1} peers {id: 3 store_id: 3}}', tests/raftstore/test_tombstone.rs:91
test raftstore::test_transfer_leader::test_node_basic_transfer_leader ... ok
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: tikv::util::panic_hook::track_hook::{{closure}}
             at ./src/util/panic_hook.rs:61
   1: <std::thread::local::LocalKey<T>>::with
             at /checkout/src/libstd/thread/local.rs:253
   2: tikv::util::panic_hook::track_hook
             at ./src/util/panic_hook.rs:55
   3: core::ops::Fn::call
             at /checkout/src/libcore/ops.rs:2511
   4: std::panicking::rust_panic_with_hook
test raftstore::test_transfer_leader::test_server_pd_transfer_leader ... ok
             at /checkout/src/libstd/panicking.rs:550
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: tests::raftstore::test_tombstone::test_tombstone
             at ./tests/raftstore/test_tombstone.rs:91
   8: tests::raftstore::test_tombstone::test_server_tombstone
             at ./tests/raftstore/test_tombstone.rs:125
   9: <F as test::FnBox<T>>::call_box

```

It may be caused that the removed peer receives the GC message before applying ConfChange Remove command.

**Comment by overvenus** [comment]
Another failed case https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/8471/pipeline/167

**Comment by LykxSassinator** [comment]
Given that the current Long Term Support (LTS) versions have resolved this issue, it is now considered outdated and can be safely closed.
