### ISSUE TITLE
test: test_multi_node_lost_majority failed

### ISSUE THREAD

**Issue by AndreMouche** [tikv/tikv#2567]
Hi, test_multi_node_lost_majority failed in CI with the following details(https://circleci.com/gh/pingcap/tikv/7012?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link):

```
thread 'raftstore_cases::test_multi::test_multi_node_lost_majority' panicked at 'called `Result::unwrap()` on an `Err` value: Timeout("request timeout for Duration { secs: 5, nanos: 0 }")', /checkout/src/libcore/result.rs:860:4
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:380
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:396
   4: tikv::util::panic_hook::track_hook::{{closure}}
             at src/util/panic_hook.rs:61
   5: <std::thread::local::LocalKey<T>>::try_with
             at /checkout/src/libstd/thread/local.rs:362
   6: <std::thread::local::LocalKey<T>>::with
             at /checkout/src/libstd/thread/local.rs:276
   7: tikv::util::panic_hook::track_hook
             at src/util/panic_hook.rs:55
   8: core::ops::function::Fn::call
             at /checkout/src/libcore/ops/function.rs:48
   9: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
  10: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:571
  11: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:521
  12: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:497
  13: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
  14: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:31
  15: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:738
  16: <integrations::raftstore::cluster::Cluster<T>>::query_leader
             at tests/raftstore/cluster.rs:281
  17: <integrations::raftstore::cluster::Cluster<T>>::leader_of_region
             at tests/raftstore/cluster.rs:319
  18: integrations::raftstore_cases::test_multi::test_multi_lost_majority
             at tests/raftstore_cases/test_multi.rs:153
  19: integrations::raftstore_cases::test_multi::test_multi_node_lost_majority
             at tests/raftstore_cases/test_multi.rs:298
  20: <F as test::FnBox<T>>::call_box
             at /checkout/src/libtest/lib.rs:1477
             at /checkout/src/libcore/ops/function.rs:143
             at /checkout/src/libtest/lib.rs:138
  21: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
FAILED
```

@siddontang @BusyJay PTAL

**Comment by breeswish** [comment]
This test case is not stable even on my own machine, some times cause failures. Maybe caused by the timeout.

**Comment by LykxSassinator** [comment]
Given that the current Long Term Support (LTS) versions have resolved this issue, it is now considered outdated and can be safely closed.
