### ISSUE TITLE
test_server_leader_change_with_uncommitted_log fails with stale command

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#2649]
```
test raftstore_cases::test_multi::test_server_leader_change_with_uncommitted_log ... thread 'raftstore_cases::test_multi::test_server_leader_change_with_uncommitted_log' panicked at 'header {error {message: "stale command" stale_command {}} current_term: 10}', tests/raftstore_cases/test_multi.rs:405:4
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:380
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:396
   4: tikv::util::panic_hook::track_hook::{{closure}}
             at src/util/panic_hook.rs:61
   5: <std::thread::local::LocalKey<T>>::try_with
             at /checkout/src/libstd/thread/local.rs:362
   6: <std::thread::local::LocalKey<T>>::with
             at /checkout/src/libstd/thread/local.rs:276
   7: tikv::util::panic_hook::track_hook
             at src/util/panic_hook.rs:55
   8: core::ops::function::Fn::call
             at /checkout/src/libcore/ops/function.rs:48
   9: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
  10: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:571
  11: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:521
  12: integrations::raftstore_cases::test_multi::test_leader_change_with_uncommitted_log
             at tests/raftstore_cases/test_multi.rs:405
  13: integrations::raftstore_cases::test_multi::test_server_leader_change_with_uncommitted_log
             at tests/raftstore_cases/test_multi.rs:422
  14: <F as test::FnBox<T>>::call_box
             at /checkout/src/libtest/lib.rs:1477
             at /checkout/src/libcore/ops/function.rs:143
             at /checkout/src/libtest/lib.rs:138
  15: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
FAILED
```

**Comment by overvenus** [comment]
Can't reproduce (tested 7783 times), closed. Feel free to reopen, if it occurs again.
