### ISSUE TITLE
raftstore_cases::test_conf_change::test_node_conf_change_safe failed

### ISSUE THREAD

**Issue by zimulala** [tikv/tikv#2676]
I only rename some functions，and the TiKV branch is the last master.
Related PR #2673

The error log:
```
thread 'raftstore_cases::test_conf_change::test_node_conf_change_safe' panicked at 'called `Result::unwrap()` on an `Err` value: Other(StringError("can\'t get leader of region 1"))', /checkout/src/libcore/result.rs:860:4
test raftstore_cases::test_multi::test_multi_node_latency ... ok
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
test raftstore_cases::test_multi::test_multi_server_base ... ok
test raftstore_cases::test_conf_change::test_node_split_brain ... ok
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:380
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:396
   4: tikv::util::panic_hook::track_hook::{{closure}}
test raftstore_cases::test_multi::test_multi_server_drop_packet ... ok
             at src/util/panic_hook.rs:61
   5: <std::thread::local::LocalKey<T>>::try_with
             at /checkout/src/libstd/thread/local.rs:362
   6: <std::thread::local::LocalKey<T>>::with
             at /checkout/src/libstd/thread/local.rs:276
   7: tikv::util::panic_hook::track_hook
             at src/util/panic_hook.rs:55
   8: core::ops::function::Fn::call
             at /checkout/src/libcore/ops/function.rs:48
   9: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
  10: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:571
  11: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:521
  12: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:497
  13: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
  14: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:31
  15: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:738
  16: <integrations::raftstore::cluster::Cluster<T>>::request
             at tests/raftstore/cluster.rs:524
  17: <integrations::raftstore::cluster::Cluster<T>>::must_put_cf
             at tests/raftstore/cluster.rs:591
  18: <integrations::raftstore::cluster::Cluster<T>>::must_put
             at tests/raftstore/cluster.rs:587
  19: integrations::raftstore_cases::test_conf_change::test_conf_change_safe
             at tests/raftstore_cases/test_conf_change.rs:556
  20: integrations::raftstore_cases::test_conf_change::test_node_conf_change_safe
             at tests/raftstore_cases/test_conf_change.rs:602
  21: <F as test::FnBox<T>>::call_box
             at /checkout/src/libtest/lib.rs:1477
             at /checkout/src/libcore/ops/function.rs:143
             at /checkout/src/libtest/lib.rs:138
  22: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
```

Log: http://45.249.247.133:8080/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_unit_test/runs/191/nodes/20/steps/29/log/?start=0

**Comment by overvenus** [comment]
Base on the log, peer 2 becomes new leader after 3 seconds of isolation the old leader(peer 1), so it seems that `leader_of_region()` went wrong.
https://github.com/pingcap/tikv/blob/9556474d6bc35168e02c86bd4387398901c4ec89/tests/raftstore/cluster.rs#L225-L236

**Comment by LykxSassinator** [comment]
Given that the current Long Term Support (LTS) versions have resolved this issue, it is now considered outdated and can be safely closed.
