### ISSUE TITLE
raftstore_cases::test_split_region::test_server_auto_split_region failed

### ISSUE THREAD

**Issue by zimulala** [tikv/tikv#2779]
Please answer these questions before submitting your issue. Thanks!

1. What version of Rust are you using (`rustc --version`)?
tikv v1.1.0-dev.1 (file:///home/ubuntu/tikv)

My CI is failed.
The error log as follows:
```
test raftstore_cases::test_split_region::test_server_auto_split_region ... thread 'raftstore_cases::test_split_region::test_server_auto_split_region' panicked at 'called `Result::unwrap()` on an `Err` value: Timeout("request timeout for Duration { secs: 5, nanos: 0 }")', libcore/result.rs:916:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: tikv::util::panic_hook::track_hook::{{closure}}
             at src/util/panic_hook.rs:59
   5: <std::thread::local::LocalKey<T>>::try_with
             at /checkout/src/libstd/thread/local.rs:377
   6: <std::thread::local::LocalKey<T>>::with
             at /checkout/src/libstd/thread/local.rs:288
   7: tikv::util::panic_hook::track_hook
             at src/util/panic_hook.rs:53
   8: core::ops::function::Fn::call
             at /checkout/src/libcore/ops/function.rs:73
   9: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:577
  10: std::panicking::begin_panic
             at libstd/panicking.rs:537
  11: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
  12: rust_begin_unwind
             at libstd/panicking.rs:497
  13: core::panicking::panic_fmt
             at libcore/panicking.rs:71
  14: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
  15: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:782
  16: <integrations::raftstore::cluster::Cluster<T>>::query_leader
             at tests/raftstore/cluster.rs:308
  17: <integrations::raftstore::cluster::Cluster<T>>::leader_of_region
             at tests/raftstore/cluster.rs:346
  18: integrations::raftstore_cases::test_split_region::test_auto_split_region
             at tests/raftstore_cases/test_split_region.rs:266
  19: integrations::raftstore_cases::test_split_region::test_server_auto_split_region
             at tests/raftstore_cases/test_split_region.rs:307
  20: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1440
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:817
  21: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
FAILED
```
Full log path : https://circleci.com/gh/pingcap/tikv/8362?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by zimulala** [comment]
PTAL @overvenus

**Comment by LykxSassinator** [comment]
Given that the current Long Term Support (LTS) versions have resolved this issue, it is now considered outdated and can be safely closed
