### ISSUE TITLE
test_node_merge_rollback failed in CI

### ISSUE THREAD

**Issue by AndreMouche** [tikv/tikv#2855]
hi, 
    `test_node_merge_rollback` failed with the following details:
https://circleci.com/gh/pingcap/tikv/8861?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
test failpoints_cases::test_merge::test_node_merge_rollback ... thread 'failpoints_cases::test_merge::test_node_merge_rollback' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `3`', tests/failpoints_cases/test_merge.rs:68:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: failpoints::failpoints_cases::test_merge::test_node_merge_rollback
             at tests/failpoints_cases/test_merge.rs:68
   8: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1440
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:817
   9: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
FAILED
```

**Comment by AndreMouche** [comment]
@BusyJay PTAL

**Comment by LykxSassinator** [comment]
Given that the current Long Term Support (LTS) versions have resolved this issue, it is now considered outdated and can be safely closed.
