### ISSUE TITLE
Test test_node_stale_peer_without_data_right_derive_when_split fails

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#3019]
```
test raftstore_cases::test_stale_peer::test_node_stale_peer_without_data_right_derive_when_split ... thread 'raftstore_cases::test_stale_peer::test_node_stale_peer_without_data_right_derive_when_split' panicked at 'called `Result::unwrap()` on an `Err` value: Timeout("request timeout for Duration { secs: 5, nanos: 0 }")', libcore/result.rs:945:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:349
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:72
   8: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:782
  10: <integrations::raftstore::cluster::Cluster<T>>::must_remove_region
             at tests/raftstore/cluster.rs:884
  11: integrations::raftstore_cases::test_stale_peer::test_stale_peer_without_data
             at tests/raftstore_cases/test_stale_peer.rs:167
  12: integrations::raftstore_cases::test_stale_peer::test_node_stale_peer_without_data_right_derive_when_split
             at tests/raftstore_cases/test_stale_peer.rs:202
  13: integrations::__test::TESTS::{{closure}}
             at tests/raftstore_cases/test_stale_peer.rs:199
  14: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
  15: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1453
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:635
  16: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
```

The log: https://circleci.com/api/v1.1/project/github/overvenus/tikv/385/output/17/0?file=true

**Comment by LykxSassinator** [comment]
Given that the current Long Term Support (LTS) versions have resolved this issue, it is now considered outdated and can be safely closed.
