### ISSUE TITLE
test: test_raft failed frequently on CI

### ISSUE THREAD

**Issue by AndreMouche** [tikv/tikv#3031]
hi, 
     `test_raft` failed frequently on CI with following details(https://circleci.com/gh/pingcap/tikv/9927?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link):
```
test raftstore_cases::test_service::test_raft ... thread 'raftstore_cases::test_service::test_raft' panicked at 'called `Result::unwrap()` on an `Err` value: RpcFinished(Some(RpcStatus { status: Cancelled, details: Some("Cancelled") }))', libcore/result.rs:945:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:349
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:72
   8: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:782
  10: integrations::raftstore_cases::test_service::test_raft
             at tests/raftstore_cases/test_service.rs:482
  11: integrations::__test::TESTS::{{closure}}
             at tests/raftstore_cases/test_service.rs:470
  12: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
  13: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1453
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:635
  14: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
FAILED
```

@overvenus PTAL

**Comment by LykxSassinator** [comment]
This issue is out-of-date and can be closed without any further tracking works.
