### ISSUE TITLE
thread 'raftstore::store::util::tests::test_lease' panicked at 'assertion failed

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#3044]
```
thread 'raftstore::store::util::tests::test_lease' panicked at 'assertion failed: `(left == right)`    left: `Valid`,   right: `Expired`', src/raftstore/store/util.rs:450:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Cc https://github.com/pingcap/tikv/pull/2993#issuecomment-386187785

**Comment by overvenus** [comment]
The backtrace:

```
test raftstore::store::util::tests::test_lease ... thread 'raftstore::store::util::tests::test_lease' panicked at 'assertion failed: `(left == right)`
  left: `Valid`,
 right: `Expired`', src/raftstore/store/util.rs:450:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: tikv::util::panic_hook::track_hook::{{closure}}
             at src/util/panic_hook.rs:59
   5: <std::thread::local::LocalKey<T>>::try_with
             at /checkout/src/libstd/thread/local.rs:290
   6: <std::thread::local::LocalKey<T>>::with
             at /checkout/src/libstd/thread/local.rs:244
   7: tikv::util::panic_hook::track_hook
             at src/util/panic_hook.rs:53
   8: core::ops::function::Fn::call
             at /checkout/src/libcore/ops/function.rs:73
   9: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:403
  10: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:349
  11: tikv::raftstore::store::util::tests::test_lease
             at src/raftstore/store/util.rs:450
  12: tikv::__test::TESTS::{{closure}}
             at src/raftstore/store/util.rs:429
  13: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
  14: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1453
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:635
  15: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
FAILED
```

And the link: https://circleci.com/gh/Librazy/tikv/27?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by overvenus** [comment]
Okay, after I applied the patch,

```diff
diff --git a/src/raftstore/store/util.rs b/src/raftstore/store/util.rs
index 332f821..e8f7f32 100644
--- a/src/raftstore/store/util.rs
+++ b/src/raftstore/store/util.rs
@@ -446,10 +446,14 @@ mod tests {
         assert_eq!(lease.inspect(None), LeaseState::Valid);

         // After lease expired time.
+        let start = monotonic_raw_now();
         thread::sleep(duration.to_std().unwrap());
+        let end = monotonic_raw_now();
         assert_eq!(
-            lease.inspect(Some(monotonic_raw_now())),
-            LeaseState::Expired
+            lease.inspect(Some(end)),
+            LeaseState::Expired,
+            "sleep: {:?}",
+            end - start
         );
         assert_eq!(lease.inspect(None), LeaseState::Expired);
```

I got a panicking message:

```
test raftstore::store::util::tests::test_lease ... thread 'raftstore::store::util::tests::test_lease' panicked at 'assertion failed: `(left == right)`
  left: `Valid`,
 right: `Expired`: sleep: Duration { secs: 1, nanos: 499984399 }', src/raftstore/store/util.rs:452:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
...
```

The `duration` is 1.5s (the lease is 1.5s too), so the thread is put to sleep
at least 1.5s [0], but the message says it only slept 1.49s. It smells like
clock jumps back. The clocksource is `kvm-clock` in the circle VM.

[0] http://pubs.opengroup.org/onlinepubs/9699919799/functions/nanosleep.html

**Comment by overvenus** [comment]
Another failed test:

```
test raftstore::store::util::tests::test_lease ... thread 'raftstore::store::util::tests::test_lease' panicked at 'assertion failed: `(left == right)`
  left: `Valid`,
 right: `Expired`: elapsed monotonic_raw: Duration { secs: 1, nanos: 499637189 }, monotonic: Duration { secs: 1, nanos: 500149657 }', src/raftstore/store/util.rs:627:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: tikv::util::panic_hook::track_hook::{{closure}}
             at src/util/panic_hook.rs:59
   5: <std::thread::local::LocalKey<T>>::try_with
             at /checkout/src/libstd/thread/local.rs:294
   6: <std::thread::local::LocalKey<T>>::with
             at /checkout/src/libstd/thread/local.rs:248
   7: tikv::util::panic_hook::track_hook
             at src/util/panic_hook.rs:53
   8: core::ops::function::Fn::call
             at /checkout/src/libcore/ops/function.rs:73
   9: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:479
  10: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
  11: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:345
  12: tikv::raftstore::store::util::tests::test_lease::sleep_test
             at src/raftstore/store/util.rs:627
  13: tikv::raftstore::store::util::tests::test_lease
             at src/raftstore/store/util.rs:656
  14: tikv::__test::TESTS::{{closure}}
             at src/raftstore/store/util.rs:617
  15: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
  16: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1454
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:640
  17: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:106
FAILED
```

https://github.com/pingcap/tikv/blob/c24136a6eb62388ab15a35e2f683d07fae171cad/src/raftstore/store/util.rs#L619-L635

https://circleci.com/gh/overvenus/tikv/674?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
