### ISSUE TITLE
tests: test_storage_1gc failed

### ISSUE THREAD

**Issue by AndreMouche** [tikv/tikv#3047]
hi,
   `test_storage_1gc` failed randomly on CI with the following details:https://circleci.com/gh/pingcap/tikv/9997?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
test failpoints_cases::test_storage::test_storage_1gc ... thread 'storage-scheduler::test_storage_1gc' panicked at 'assertion failed: res.is_ok()', tests/failpoints_cases/test_storage.rs:46:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:365
   6: failpoints::failpoints_cases::test_storage::test_storage_1gc::{{closure}}
             at tests/failpoints_cases/test_storage.rs:46
   7: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
   8: <F as alloc::boxed::FnBox<A>>::call_box
             at /checkout/src/liballoc/boxed.rs:635
   9: <alloc::boxed::Box<alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$core..marker..Send$u20$$u2b$$u20$$u27$a$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once
             at /checkout/src/liballoc/boxed.rs:655
  10: tikv::storage::txn::scheduler::execute_callback
             at src/storage/txn/scheduler.rs:181
  11: tikv::storage::txn::scheduler::Scheduler::finish_with_err
             at src/storage/txn/scheduler.rs:1052
  12: tikv::storage::txn::scheduler::Scheduler::on_snapshot_finished
             at src/storage/txn/scheduler.rs:1285
  13: <tikv::storage::txn::scheduler::Scheduler as tikv::util::worker::Runnable<tikv::storage::txn::scheduler::Msg>>::run
             at src/storage/txn/scheduler.rs:1417
  14: <tikv::storage::txn::scheduler::Scheduler as tikv::util::worker::Runnable<tikv::storage::txn::scheduler::Msg>>::run_batch
             at src/storage/txn/scheduler.rs:1438
  15: <tikv::util::worker::DefaultRunnerWithTimer<R> as tikv::util::worker::Runnable<T>>::run_batch
             at src/util/worker/mod.rs:121
  16: tikv::util::worker::poll
             at src/util/worker/mod.rs:279
  17: <tikv::util::worker::Worker<T>>::start_with_timer::{{closure}}
             at src/util/worker/mod.rs:357
thread 'failpoints_cases::test_storage::test_storage_1gc' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', libcore/result.rs:945:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:349
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:72
   8: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:782
  10: failpoints::failpoints_cases::test_storage::test_storage_1gc
             at tests/failpoints_cases/test_storage.rs:67
  11: failpoints::__test::TESTS::{{closure}}
             at tests/failpoints_cases/test_storage.rs:29
  12: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
  13: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1453
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:635
  14: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
FAILED
test test_setup ... ok

failures:

failures:
    failpoints_cases::test_storage::test_storage_1gc
```

**Comment by breeswish** [comment]
Seems that our working threads are sometimes not yet ready at that moment.

**Comment by LykxSassinator** [comment]
This case are out-of-date and this issue can be safely closed.
