### ISSUE TITLE
Test test_node_learner_conf_change failed

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#3147]
Backtrace:
```
test raftstore_cases::test_conf_change::test_node_learner_conf_change ... thread 'raftstore_cases::test_conf_change::test_node_learner_conf_change' panicked at 'can't get value Some("v3") for key "k3"', tests/raftstore/util.rs:66:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:349
   6: integrations::raftstore::util::must_get
             at tests/raftstore/util.rs:66
   7: integrations::raftstore::util::must_get_equal
             at tests/raftstore/util.rs:74
   8: integrations::raftstore_cases::test_conf_change::test_learner_conf_change
             at tests/raftstore_cases/test_conf_change.rs:620
   9: integrations::raftstore_cases::test_conf_change::test_node_learner_conf_change
             at tests/raftstore_cases/test_conf_change.rs:687
  10: integrations::__test::TESTS::{{closure}}
             at tests/raftstore_cases/test_conf_change.rs:684
  11: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
  12: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1453
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:635
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
FAILED
```

CI: https://circleci.com/gh/overvenus/tikv/509

The line fails the test:  https://github.com/overvenus/tikv/blob/f4e1903/tests/raftstore_cases/test_conf_change.rs#L620

Note that it has applied #2967 .

**Comment by breeswish** [comment]
@Hicqu PTAL

**Comment by yangwenmai** [comment]
```shell
$ make dev
failures:

failures:
    raftstore_cases::test_conf_change::test_node_learner_conf_change

test result: FAILED. 249 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test integrations'
make[1]: *** [test] Error 101
make: *** [dev] Error 2
```

**Comment by breeswish** [comment]
@yangwenmai You can simply re-run the test. Some tests are just not very stable.

**Comment by hicqu** [comment]
Fixed by #3321.

**Comment by overvenus** [comment]
Failed again https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/1622/nodes/150/steps/1260/log/?start=0

**Comment by 5kbpers** [comment]
Duplicated with https://github.com/tikv/tikv/issues/3147

**Comment by 5kbpers** [comment]
Duplicated with https://github.com/tikv/tikv/issues/7934
