### ISSUE TITLE
Test test_server_auto_adjust_replica failed

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#3162]
Backtrace: 

```
test raftstore_cases::test_conf_change::test_server_auto_adjust_replica ... thread 'raftstore_cases::test_conf_change::test_server_auto_adjust_replica' panicked at 'replica count 5 still not meet 4 after 10 secs', tests/raftstore_cases/test_conf_change.rs:288:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:349
   6: integrations::raftstore_cases::test_conf_change::wait_till_reach_count
             at tests/raftstore_cases/test_conf_change.rs:288
   7: integrations::raftstore_cases::test_conf_change::test_auto_adjust_replica
             at tests/raftstore_cases/test_conf_change.rs:344
   8: integrations::raftstore_cases::test_conf_change::test_server_auto_adjust_replica
             at tests/raftstore_cases/test_conf_change.rs:362
   9: integrations::__test::TESTS::{{closure}}
             at tests/raftstore_cases/test_conf_change.rs:359
  10: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
  11: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1453
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:635
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
FAILED
```

Link:  https://circleci.com/gh/overvenus/tikv/523

**Comment by breeswish** [comment]
https://circleci.com/gh/tikv/tikv/15180

**Comment by hunterlxt** [comment]
The frequency I encountered in the recent PR is very high, about 30%.

**Comment by 5kbpers** [comment]
Set severity to minor since cannot reproduce it.
