### ISSUE TITLE
test: raftstore_cases::test_conf_change::test_learner_with_slow_snapshot panic

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#3216]
```
thread 'raftstore_cases::test_conf_change::test_learner_with_slow_snapshot' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `1`', tests/raftstore_cases/test_conf_change.rs:779:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:349
   6: integrations::raftstore_cases::test_conf_change::test_learner_with_slow_snapshot
             at tests/raftstore_cases/test_conf_change.rs:779
   7: integrations::__test::TESTS::{{closure}}
             at tests/raftstore_cases/test_conf_change.rs:703
   8: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
   9: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1453
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:635
  10: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
```

**Comment by LykxSassinator** [comment]
Given that the current Long Term Support (LTS) versions have resolved this issue, it is now considered outdated and can be safely closed.
