### ISSUE TITLE
test raftstore_cases::test_compact_after_delete::test_node_compact_after_delete failed

### ISSUE THREAD

**Issue by huachaohuang** [tikv/tikv#3217]
raftstore::test_compact_after_delete::test_node_compact_after_delete

```
test raftstore_cases::test_compact_after_delete::test_node_compact_after_delete ... thread 'raftstore_cases::test_compact_after_delete::test_node_compact_after_delete' panicked at 'assertion failed: `(left == right)`
  left: `58672`,
 right: `0`', tests/raftstore_cases/test_compact_after_delete.rs:74:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:349
   6: integrations::raftstore_cases::test_compact_after_delete::test_compact_after_delete
             at tests/raftstore_cases/test_compact_after_delete.rs:74
   7: integrations::raftstore_cases::test_compact_after_delete::test_node_compact_after_delete
             at tests/raftstore_cases/test_compact_after_delete.rs:82
   8: integrations::__test::TESTS::{{closure}}
             at tests/raftstore_cases/test_compact_after_delete.rs:79
   9: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
  10: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1453
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:635
  11: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
```

[build_10982_step_18_container_0.txt](https://github.com/pingcap/tikv/files/2108056/build_10982_step_18_container_0.txt)

**Comment by mahjonp** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/18531/pipeline/230/ Integration Part17
