### ISSUE TITLE
test failpoints_cases::test_merge::test_node_merge_restart  failed

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#3255]
```
test failpoints_cases::test_merge::test_node_merge_restart ... thread 'failpoints_cases::test_merge::test_node_merge_restart' panicked at 'region id: 1004 end_key: "k2" region_epoch {conf_ver: 1 version: 5} peers {id: 1005 store_id: 2} peers {id: 1006 store_id: 1} peers {id: 1007 store_id: 3} is still not merged.', tests/raftstore/pd.rs:817:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:413
   7: failpoints::raftstore::pd::TestPdClient::must_merge
             at tests/raftstore/pd.rs:817
   8: failpoints::failpoints_cases::test_merge::test_node_merge_restart
             at tests/failpoints_cases/test_merge.rs:205
   9: failpoints::__test::TESTS::{{closure}}
             at tests/failpoints_cases/test_merge.rs:119
  10: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
  11: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1451
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:640
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
```

**Comment by Hoverbear** [comment]
I think this is related:

```
Jul 06 11:54:39.592 WARN [region 1004] 1005 skip proposal: Other(StringError("[src/raftstore/store/peer.rs:1538]: log gap (0, 8] is too large, skip merge"))
```

This seems to be due to:

https://github.com/pingcap/tikv/blob/1e45270e93b31f24dfbc030691bcd49fb52cf19a/src/raftstore/store/peer.rs#L1535

Which is calculated by:

https://github.com/pingcap/tikv/blob/1e45270e93b31f24dfbc030691bcd49fb52cf19a/src/raftstore/store/peer.rs#L1523-L1531

Which points to https://github.com/pingcap/raft-rs/pull/83/files#diff-18f3dab6275bbc16b4a102e73378c08bR831.

I noted that considerably more happens in `becomePreCandidate` in https://github.com/coreos/etcd/blob/f7b3017752421bd7ed1c122398b2eab1a0f23853/raft/raft.go#L672-L685 now.

**Comment by overvenus** [comment]
Another failed test. [log.txt](https://github.com/tikv/tikv/files/3161467/log.txt)

**Comment by breeswish** [comment]
https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/7372/nodes/116/steps/579/log/?start=0

**Comment by overvenus** [comment]
Another failed case.

[internal.pingcap.net.txt](https://github.com/tikv/tikv/files/3657098/internal.pingcap.net.txt)

**Comment by NingLin-P** [comment]
Close this issue, since it is duplicated with https://github.com/tikv/tikv/issues/7184
