### ISSUE TITLE
'raftstore_cases::test_transport::test_node_partition_write' panicked

### ISSUE THREAD

**Issue by huachaohuang** [tikv/tikv#3267]
```
'raftstore_cases::test_transport::test_node_partition_write' panicked at 'response header {error {message: "peer is not leader" not_leader {region_id: 1}}} has error', tests/raftstore/cluster.rs:637:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:413
   7: <integrations::raftstore::cluster::Cluster<T>>::get_impl
             at tests/raftstore/cluster.rs:637
   8: <integrations::raftstore::cluster::Cluster<T>>::must_get
             at tests/raftstore/cluster.rs:626
   9: integrations::raftstore_cases::test_transport::test_partition_write
             at tests/raftstore_cases/test_transport.rs:41
  10: integrations::raftstore_cases::test_transport::test_node_partition_write
             at tests/raftstore_cases/test_transport.rs:57
  11: integrations::__test::TESTS::{{closure}}
             at tests/raftstore_cases/test_transport.rs:55
  12: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
  13: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1451
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:640
  14: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
FAILED
```

**Comment by overvenus** [comment]
Hi! Could you provide trace logs? Like this one https://circleci.com/gh/pingcap/tikv/11391

**Comment by gengliqi** [comment]
close because it's too old.
