### ISSUE TITLE
test raftstore_cases::test_merge::test_node_merge_brain_split failed

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#3268]
```
test raftstore_cases::test_merge::test_node_merge_brain_split ... thread 'raftstore_cases::test_merge::test_node_merge_brain_split' panicked at 'region id: 1000 end_key: "k2" region_epoch {conf_ver: 1 version: 2} peers {id: 1001 store_id: 2} peers {id: 1002 store_id: 1} peers {id: 1003 store_id: 3} is still not merged.', tests/raftstore/pd.rs:817:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:413
   7: integrations::raftstore::pd::TestPdClient::must_merge
             at tests/raftstore/pd.rs:817
   8: integrations::raftstore_cases::test_merge::test_node_merge_brain_split
             at tests/raftstore_cases/test_merge.rs:367
   9: integrations::__test::TESTS::{{closure}}
             at tests/raftstore_cases/test_merge.rs:345
  10: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
  11: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1451
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:640
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
FAILED
test raftstore_cases::test_merge::test_node_
```

**Comment by overvenus** [comment]
Another failed test, https://circleci.com/gh/overvenus/tikv/659

**Comment by breeswish** [comment]
Just a list of recently failed tests due to this issue:

https://circleci.com/gh/pingcap/tikv/12005
https://circleci.com/gh/pingcap/tikv/11991
https://circleci.com/gh/pingcap/tikv/11978
https://circleci.com/gh/pingcap/tikv/12003
https://circleci.com/gh/pingcap/tikv/11984
https://circleci.com/gh/pingcap/tikv/11962
https://circleci.com/gh/pingcap/tikv/11953

**Comment by breeswish** [comment]
@BusyJay PTAL
