### ISSUE TITLE
Test test_multi_node_random_latency failed

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#3272]
```
thread 'raftstore_cases::test_multi::test_multi_node_random_latency' panicked at 'need at lease 3 qualified stores, but only got 2', tests/raftstore/cluster.rs:489:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:413
   7: <integrations::raftstore::cluster::Cluster<T>>::assert_quorum
             at tests/raftstore/cluster.rs:489
   8: integrations::raftstore_cases::test_multi::test_multi_base_after_bootstrap
             at tests/raftstore_cases/test_multi.rs:63
   9: integrations::raftstore_cases::test_multi::test_multi_random_latency
             at tests/raftstore_cases/test_multi.rs:235
  10: integrations::raftstore_cases::test_multi::test_multi_node_random_latency
             at tests/raftstore_cases/test_multi.rs:242
  11: integrations::__test::TESTS::{{closure}}
             at tests/raftstore_cases/test_multi.rs:239
  12: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
  13: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1451
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:640
  14: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
```

[log.log](https://github.com/pingcap/tikv/files/2151589/log.log)

**Comment by Connor1996** [comment]
This info is stale, not sure if it is still unstable. Let's close it and reopen it if encounter again.
