### ISSUE TITLE
ci-test failed on test_prevote_reboot_minority_followers

### ISSUE THREAD

**Issue by shizy818** [tikv/tikv#3630]
## Bug Report

**What version of Rust are you using?**

**What operating system and CPU are you using?**

**What did you do?**
run ci test in PR request

**What did you expect to see?**
tests run OK

**What did you see instead?**

```
thread 'raftstore_cases::test_prevote::test_prevote_reboot_minority_followers' panicked at 'called `Result::unwrap()` on an `Err` value: Grpc(BindFail("127.0.0.1", 40828))', libcore/result.rs:945:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:782
  10: <test_raftstore::server::ServerCluster as test_raftstore::cluster::Simulator>::run_node
             at components/test_raftstore/server.rs:191
  11: <test_raftstore::cluster::Cluster<T>>::run_node
             at ./components/test_raftstore/cluster.rs:197
  12: integrations::raftstore_cases::test_prevote::test_prevote::{{closure}}
             at tests/raftstore_cases/test_prevote.rs:104
  13: core::iter::iterator::Iterator::for_each::{{closure}}
             at /checkout/src/libcore/iter/iterator.rs:551
  14: <core::slice::Iter<'a, T> as core::iter::iterator::Iterator>::fold
             at /checkout/src/libcore/slice/mod.rs:2454
  15: core::iter::iterator::Iterator::for_each
             at /checkout/src/libcore/iter/iterator.rs:551
  16: integrations::raftstore_cases::test_prevote::test_prevote
             at tests/raftstore_cases/test_prevote.rs:104
  17: integrations::raftstore_cases::test_prevote::test_prevote_reboot_minority_followers
             at tests/raftstore_cases/test_prevote.rs:212
  18: integrations::__test::TESTS::{{closure}}
             at tests/raftstore_cases/test_prevote.rs:209
  19: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
  20: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1454
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:640
  21: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:106
thread 'raftstore_cases::test_prevote::test_prevote_reboot_minority_followers' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', libcore/result.rs:945:5
stack backtrace:
   0:     0x55dfffcb287e - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h53bc450f4e05b019
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x55dfffcbba66 - std::sys_common::backtrace::print::h04a0ea06a78a82c5
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:     0x55dfffcb6b0d - std::panicking::default_hook::{{closure}}::h13c5ed342ec5a2b6
                               at libstd/panicking.rs:211
   3:     0x55dfffcb6880 - std::panicking::default_hook::h72a62d53239218b1
                               at libstd/panicking.rs:227
   4:     0x55dfffcb717c - std::panicking::rust_panic_with_hook::h60a37fb79e459606
                               at libstd/panicking.rs:475
   5:     0x55dfffcb6d79 - std::panicking::continue_panic_fmt::hb542a58a3d52cb5c
                               at libstd/panicking.rs:390
   6:     0x55dfffcb6c75 - rust_begin_unwind
                               at libstd/panicking.rs:325
   7:     0x55dfffcffe7b - core::panicking::panic_fmt::h68c841fe431ac371
                               at libcore/panicking.rs:77
   8:     0x55dffd0548e2 - core::result::unwrap_failed::h8aec6539ee478311
                               at /checkout/src/libcore/macros.rs:26
   9:     0x55dffd05093e - <core::result::Result<T, E>>::unwrap::hec671cc8f2d83d35
                               at /checkout/src/libcore/result.rs:782
  10:     0x55dffd062f11 - <std::sync::rwlock::RwLock<T> as tikv::util::HandyRwLock<T>>::wl::h51119d372e9c3166
                               at /home/circleci/tikv-ci/src/util/mod.rs:138
  11:     0x55dffd0e1be4 - <test_raftstore::cluster::Cluster<T>>::stop_node::h748ce577a7dbdbf0
                               at /home/circleci/tikv-ci/components/test_raftstore/cluster.rs:205
  12:     0x55dffd0e1628 - <test_raftstore::cluster::Cluster<T>>::shutdown::h6bf917ee6d4685b5
                               at /home/circleci/tikv-ci/components/test_raftstore/cluster.rs:508
  13:     0x55dffd0e1e1d - <test_raftstore::cluster::Cluster<T> as core::ops::drop::Drop>::drop::ha4a9fb9b4fdff1c0
                               at /home/circleci/tikv-ci/components/test_raftstore/cluster.rs:967
  14:     0x55dffcbde8c0 - core::ptr::drop_in_place::h628fb28a860ccc5c
                               at /checkout/src/libcore/ptr.rs:59
  15:     0x55dffcedf96b - integrations::raftstore_cases::test_prevote::test_prevote_reboot_minority_followers::hcf4f47f4aa17b4ce
                               at tests/raftstore_cases/test_prevote.rs:219
  16:     0x55dffcc2b179 - integrations::__test::TESTS::{{closure}}::h60a009302172cd4a
                               at tests/raftstore_cases/test_prevote.rs:209
  17:     0x55dffcbc7bad - core::ops::function::FnOnce::call_once::hce773776a4142d84
                               at /checkout/src/libcore/ops/function.rs:223
  18:     0x55dffe8b7e0e - <F as alloc::boxed::FnBox<A>>::call_box::h1791e880f028d3d5
                               at libtest/lib.rs:1454
                               at /checkout/src/libcore/ops/function.rs:223
                               at /checkout/src/liballoc/boxed.rs:640
  19:     0x55dfffcc6e19 - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:106
  20:     0x55dffe8d913f - std::sys_common::backtrace::__rust_begin_short_backtrace::hc0f0325942c00b52
                               at /checkout/src/libstd/panicking.rs:289
                               at /checkout/src/libstd/panic.rs:392
                               at libtest/lib.rs:1409
                               at /checkout/src/libstd/sys_common/backtrace.rs:136
  21:     0x55dffe8d9b74 - std::panicking::try::do_call::h753b561d689539bb
                               at /checkout/src/libstd/thread/mod.rs:409
                               at /checkout/src/libstd/panic.rs:313
                               at /checkout/src/libstd/panicking.rs:310
  22:     0x55dfffcc6e19 - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:106
  23:     0x55dffe8cd646 - <F as alloc::boxed::FnBox<A>>::call_box::h9e1f0ce96f498f8a
                               at /checkout/src/libstd/panicking.rs:289
                               at /checkout/src/libstd/panic.rs:392
                               at /checkout/src/libstd/thread/mod.rs:408
                               at /checkout/src/liballoc/boxed.rs:640
  24:     0x55dfffca6d8a - std::sys_common::thread::start_thread::hbdf390fd59cb95cd
                               at /checkout/src/liballoc/boxed.rs:650
                               at libstd/sys_common/thread.rs:24
  25:     0x55dfffca4ff5 - std::sys::unix::thread::Thread::new::thread_start::h96884314b12ba24c
                               at libstd/sys/unix/thread.rs:90
  26:     0x2abff5f69183 - start_thread
  27:     0x2abff6492ffc - clone
  28:                0x0 - <unknown>
thread panicked while panicking. aborting.
error: process didn't exit successfully: `/home/circleci/tikv-ci/target/debug/deps/integrations-c6ec0543a63690c2 --nocapture` (signal: 4, SIGILL: illegal instruction)
make[1]: *** [test] Error 101
make[1]: Leaving directory `/home/circleci/tikv-ci'
find fail cases: test_prevote_reboot_minority_followers
```

**Comment by LykxSassinator** [comment]
Given that the current Long Term Support (LTS) versions have resolved this issue, it is now considered outdated and can be safely closed.
