### ISSUE TITLE
test_region_change_observer failed

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#3829]
## Bug Report

https://circleci.com/gh/tikv/tikv/15122

@overvenus @hicqu PTAL

**Comment by MyonKeminta** [comment]
This seems to be my fault. Sorry. I'll take a look.

**Comment by MyonKeminta** [comment]
```
test raftstore_cases::test_region_change_observer::test_region_change_observer ... thread 'raftstore_cases::test_region_change_observer::test_region_change_observer' panicked at 'region id: 1 start_key: "k2" region_epoch {conf_ver: 3 version: 3} peers {id: 1 store_id: 1} peers {id: 10 store_id: 2} is still not merged.', components/test_raftstore/src/pd.rs:830:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:345
   7: test_raftstore::pd::TestPdClient::must_merge
             at components/test_raftstore/src/pd.rs:830
   8: integrations::raftstore_cases::test_region_change_observer::test_region_change_observer_impl
             at tests/raftstore_cases/test_region_change_observer.rs:118
   9: integrations::raftstore_cases::test_region_change_observer::test_region_change_observer
             at tests/raftstore_cases/test_region_change_observer.rs:179
  10: integrations::__test::TESTS::{{closure}}
             at tests/raftstore_cases/test_region_change_observer.rs:177
  11: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
  12: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1454
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:640
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:106
FAILED
```
It seems not to be caused by my code but caused by other bug in `must_merge`.

**Comment by BusyJay** [comment]
Any updates?
