### ISSUE TITLE
 test: test_server_stale_peer_out_of_region failed

### ISSUE THREAD

**Issue by Hijiao** [tikv/tikv#3902]
```
thread 'raftstore::test_stale_peer::test_server_stale_peer_out_of_region' panicked at 'region Some(id: 1 region_epoch {conf_ver: 2 version: 1} peers {id: 1 store_id: 1} peers {id: 2 store_id: 2}) has no peer id: 3 store_id: 3', components/test_raftstore/src/pd.rs:732:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:345
   7: test_raftstore::pd::TestPdClient::must_have_peer
             at components/test_raftstore/src/pd.rs:732
   8: test_raftstore::pd::TestPdClient::must_add_peer
             at components/test_raftstore/src/pd.rs:800
   9: integrations::raftstore::test_stale_peer::test_stale_peer_out_of_region
             at tests/integrations/raftstore/test_stale_peer.rs:50
  10: integrations::raftstore::test_stale_peer::test_server_stale_peer_out_of_region
             at tests/integrations/raftstore/test_stale_peer.rs:105
  11: integrations::__test::TESTS::{{closure}}
             at tests/integrations/raftstore/test_stale_peer.rs:102
  12: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
  13: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1454
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:640
  14: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:106
```

**Comment by Hijiao** [comment]
[test_server_stale_peer_out_of_region.txt](https://github.com/tikv/tikv/files/2661438/test_server_stale_peer_out_of_region.txt)

**Comment by hunterlxt** [comment]
Duplicate bug

https://github.com/tikv/tikv/issues/7183
