### ISSUE TITLE
test coprocessor::endpoint::tests::test_handle_time failed

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#3965]
```
test coprocessor::endpoint::tests::test_handle_time ... thread 'coprocessor::endpoint::tests::test_handle_time' panicked at 'assertion failed: resp[1].get_exec_details().get_handle_time().get_process_ms() >= 1500', src/coprocessor/endpoint.rs:1170:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:409
   6: tikv::coprocessor::endpoint::tests::test_handle_time
             at src/coprocessor/endpoint.rs:1170
   7: tikv::__test::TESTS::{{closure}}
             at src/coprocessor/endpoint.rs:1012
   8: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
   9: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1454
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:640
  10: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:106
FAILED
```

**Comment by breeswish** [comment]
This looks like an old issue fixed in https://github.com/tikv/tikv/pull/3821

Notice that #3821 has changed assertion failure messages to be a more specific one, so the message you post indicates that #3821 is not applied

**Comment by breeswish** [comment]
Looks like since last fix this issue has not occurred recently. Closing for now.
