### ISSUE TITLE
raftstore::test_stale_peer::test_server_stale_peer_without_data_left_derive_when_split failed

### ISSUE THREAD

**Issue by zhouqiang-cl** [tikv/tikv#3969]
## TiKV CI sometimes failed

```
thread 'raftstore::test_stale_peer::test_server_stale_peer_without_data_left_derive_when_split' panicked at 'region Some(id: 1 region_epoch {conf_ver: 1 version: 1} peers {id: 1 store_id: 1}) has no peer id: 2 store_id: 2', components/test_raftstore/src/pd.rs:732:9

note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

stack backtrace:

   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace

             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49

   1: std::sys_common::backtrace::print

             at libstd/sys_common/backtrace.rs:71

             at libstd/sys_common/backtrace.rs:59

   2: std::panicking::default_hook::{{closure}}

             at libstd/panicking.rs:211

   3: std::panicking::default_hook

             at libstd/panicking.rs:227

   4: std::panicking::rust_panic_with_hook

             at libstd/panicking.rs:475

   5: std::panicking::continue_panic_fmt

             at libstd/panicking.rs:390

   6: std::panicking::begin_panic_fmt

             at libstd/panicking.rs:345

   7: test_raftstore::pd::TestPdClient::must_have_peer

             at components/test_raftstore/src/pd.rs:732

   8: test_raftstore::pd::TestPdClient::must_add_peer

             at components/test_raftstore/src/pd.rs:800

   9: integrations::raftstore::test_stale_peer::test_stale_peer_without_data

             at tests/integrations/raftstore/test_stale_peer.rs:131

  10: integrations::raftstore::test_stale_peer::test_server_stale_peer_without_data_left_derive_when_split

             at tests/integrations/raftstore/test_stale_peer.rs:207

  11: integrations::__test::TESTS::{{closure}}

             at tests/integrations/raftstore/test_stale_peer.rs:204

  12: core::ops::function::FnOnce::call_once

             at /checkout/src/libcore/ops/function.rs:223

  13: <F as alloc::boxed::FnBox<A>>::call_box

             at libtest/lib.rs:1454

             at /checkout/src/libcore/ops/function.rs:223

             at /checkout/src/liballoc/boxed.rs:640
```

**Comment by zhouqiang-cl** [comment]
and some other errors seem the same
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikvstability_test/detail/tikvstability_test/36/pipeline/52

**Comment by sticnarf** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/7553/pipeline
It is still unstable.

**Comment by sticnarf** [comment]
@Connor1996 PTAL
The test fails a lot of times recently.

**Comment by Connor1996** [comment]
Duplicated with https://github.com/tikv/tikv/issues/7576
