### ISSUE TITLE
cases::test_conf_change::test_write_after_destroy fails on CI

### ISSUE THREAD

**Issue by hicqu** [tikv/tikv#4193]
**What did you expect to see?**
All tests pass correctly.

**What did you see instead?**
The case [fails](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/1387/pipeline).

**Comment by siddontang** [comment]
```
test cases::test_conf_change::test_write_after_destroy ... thread 'cases::test_conf_change::test_write_after_destroy' panicked at 'region Some(id: 1 region_epoch {conf_ver: 2 version: 1} peers {id: 1 store_id: 1} peers {id: 2 store_id: 2}) has no peer id: 3 store_id: 3', components/test_raftstore/src/pd.rs:744:9

note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

stack backtrace:

   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace

             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49

   1: std::sys_common::backtrace::_print

             at src/libstd/sys_common/backtrace.rs:71

   2: std::panicking::default_hook::{{closure}}

             at src/libstd/sys_common/backtrace.rs:59

             at src/libstd/panicking.rs:211

   3: std::panicking::default_hook

             at src/libstd/panicking.rs:227

   4: std::panicking::rust_panic_with_hook

             at src/libstd/panicking.rs:491

   5: std::panicking::continue_panic_fmt

             at src/libstd/panicking.rs:398

   6: std::panicking::begin_panic_fmt

             at src/libstd/panicking.rs:353

   7: test_raftstore::pd::TestPdClient::must_have_peer

             at components/test_raftstore/src/pd.rs:744

   8: test_raftstore::pd::TestPdClient::must_add_peer

             at components/test_raftstore/src/pd.rs:840

   9: failpoints::cases::test_conf_change::test_write_after_destroy

             at tests/failpoints/cases/test_conf_change.rs:108

  10: failpoints::cases::test_conf_change::test_write_after_destroy::{{closure}}

             at tests/failpoints/cases/test_conf_change.rs:86

  11: core::ops::function::FnOnce::call_once

             at /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/libcore/ops/function.rs:238

  12: <F as alloc::boxed::FnBox<A>>::call_box

             at src/libtest/lib.rs:1471

             at /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/libcore/ops/function.rs:238

             at /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/liballoc/boxed.rs:673

  13: __rust_maybe_catch_panic

             at src/libpanic_unwind/lib.rs:102

FAILED
```

**Comment by hicqu** [comment]
It fails at `pd_client.must_add_peer(r1, new_peer(3, 3))`. This logic is not changed in a long time, so close it as stable.
