### ISSUE TITLE
test raftstore::test_conf_change::test_node_auto_adjust_replica failed

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#4225]
## Bug Report

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/1527/pipeline

```
test raftstore::test_conf_change::test_node_auto_adjust_replica ... thread 'raftstore::test_conf_change::test_node_auto_adjust_replica' panicked at 'replica count 5 still not meet 4 after 10 secs', tests/integrations/raftstore/test_conf_change.rs:272:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:491
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:398
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:353
   7: integrations::raftstore::test_conf_change::wait_till_reach_count
             at tests/integrations/raftstore/test_conf_change.rs:272
   8: integrations::raftstore::test_conf_change::test_auto_adjust_replica
             at tests/integrations/raftstore/test_conf_change.rs:328
   9: integrations::raftstore::test_conf_change::test_node_auto_adjust_replica
             at tests/integrations/raftstore/test_conf_change.rs:339
  10: integrations::raftstore::test_conf_change::test_node_auto_adjust_replica::{{closure}}
             at tests/integrations/raftstore/test_conf_change.rs:336
  11: core::ops::function::FnOnce::call_once
             at /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/libcore/ops/function.rs:238
  12: <F as alloc::boxed::FnBox<A>>::call_box
             at src/libtest/lib.rs:1471
             at /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/libcore/ops/function.rs:238
             at /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/liballoc/boxed.rs:673
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
FAILED
```

**Comment by 5kbpers** [comment]
Duplicate with https://github.com/tikv/tikv/issues/4225
