### ISSUE TITLE
tests: test_restart_leader_insecure failed

### ISSUE THREAD

**Issue by zhangjinpeng1987** [tikv/tikv#4258]
## Bug Report
```
test pd::test_rpc_client::test_restart_leader_insecure ... thread 'pd::test_rpc_client::test_restart_leader_insecure' panicked at 'called `Result::unwrap()` on an `Err` value: Other(StringError("[src/pd/client.rs:67]: endpoints are invalid"))', src/libcore/result.rs:1009:5

note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:

   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace

             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49

   1: std::sys_common::backtrace::_print

             at src/libstd/sys_common/backtrace.rs:71

   2: std::panicking::default_hook::{{closure}}

             at src/libstd/sys_common/backtrace.rs:59

             at src/libstd/panicking.rs:211

   3: std::panicking::default_hook

             at src/libstd/panicking.rs:227

   4: std::panicking::rust_panic_with_hook

             at src/libstd/panicking.rs:491

   5: std::panicking::continue_panic_fmt

             at src/libstd/panicking.rs:398

   6: rust_begin_unwind

             at src/libstd/panicking.rs:325

   7: core::panicking::panic_fmt

             at src/libcore/panicking.rs:95

   8: core::result::unwrap_failed

             at /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/libcore/macros.rs:26

   9: <core::result::Result<T, E>>::unwrap

             at /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/libcore/result.rs:808

  10: integrations::pd::test_rpc_client::new_client

             at tests/integrations/pd/test_rpc_client.rs:45

  11: integrations::pd::test_rpc_client::restart_leader

             at tests/integrations/pd/test_rpc_client.rs:272

  12: integrations::pd::test_rpc_client::test_restart_leader_insecure

             at tests/integrations/pd/test_rpc_client.rs:311

  13: integrations::pd::test_rpc_client::test_restart_leader_insecure::{{closure}}

             at tests/integrations/pd/test_rpc_client.rs:309

  14: core::ops::function::FnOnce::call_once

             at /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/libcore/ops/function.rs:238

  15: <F as alloc::boxed::FnBox<A>>::call_box

             at src/libtest/lib.rs:1471

             at /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/libcore/ops/function.rs:238

             at /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/liballoc/boxed.rs:673

  16: __rust_maybe_catch_panic

             at src/libpanic_unwind/lib.rs:102

FAILED
```

Log:
```
2019/02/22 17:48:45.859 service.rs:271: [INFO] [Service] members_resp header {cluster_id: 42} members {name: "pd0" member_id: 100 peer_urls: "127.0.0.1:14205" client_urls: "127.0.0.1:14205"} members {name: "pd1" member_id: 101 peer_urls: "127.0.0.1:13916" client_urls: "127.0.0.1:13916"} members {name: "pd2" member_id: 102 peer_urls: "127.0.0.1:13916" client_urls: "127.0.0.1:13916"} leader {name: "pd2" member_id: 102 peer_urls: "127.0.0.1:13916" client_urls: "127.0.0.1:13916"}

2019/02/22 17:48:46.865 util.rs:408: [INFO] connecting to PD endpoint: "127.0.0.1:14205"

2019/02/22 17:48:46.867 util.rs:408: [INFO] connecting to PD endpoint: "127.0.0.1:13916"

2019/02/22 17:48:46.869 client.rs:62: [WARN] validate PD endpoints failed: Other(StringError("[src/pd/util.rs:361]: duplicate PD endpoint 127.0.0.1:13916"))

2019/02/22 17:48:47.169 util.rs:408: [INFO] connecting to PD endpoint: "127.0.0.1:14205"

2019/02/22 17:48:47.170 util.rs:408: [INFO] connecting to PD endpoint: "127.0.0.1:13916"

2019/02/22 17:48:47.171 client.rs:62: [WARN] validate PD endpoints failed: Other(StringError("[src/pd/util.rs:361]: duplicate PD endpoint 127.0.0.1:13916"))

2019/02/22 17:48:47.472 util.rs:408: [INFO] connecting to PD endpoint: "127.0.0.1:14205"

2019/02/22 17:48:47.473 util.rs:408: [INFO] connecting to PD endpoint: "127.0.0.1:13916"

2019/02/22 17:48:47.474 client.rs:62: [WARN] validate PD endpoints failed: Other(StringError("[src/pd/util.rs:361]: duplicate PD endpoint 127.0.0.1:13916"))

2019/02/22 17:48:47.775 util.rs:408: [INFO] connecting to PD endpoint: "127.0.0.1:14205"

2019/02/22 17:48:47.776 util.rs:408: [INFO] connecting to PD endpoint: "127.0.0.1:13916"

2019/02/22 17:48:47.777 client.rs:62: [WARN] validate PD endpoints failed: Other(StringError("[src/pd/util.rs:361]: duplicate PD endpoint 127.0.0.1:13916"))

2019/02/22 17:48:48.077 util.rs:408: [INFO] connecting to PD endpoint: "127.0.0.1:14205"

2019/02/22 17:48:48.079 util.rs:408: [INFO] connecting to PD endpoint: "127.0.0.1:13916"

2019/02/22 17:48:48.080 client.rs:62: [WARN] validate PD endpoints failed: Other(StringError("[src/pd/util.rs:361]: duplicate PD endpoint 127.0.0.1:13916"))

2019/02/22 17:48:48.380 util.rs:408: [INFO] connecting to PD endpoint: "127.0.0.1:14205"

2019/02/22 17:48:48.382 util.rs:408: [INFO] connecting to PD endpoint: "127.0.0.1:13916"

2019/02/22 17:48:48.383 client.rs:62: [WARN] validate PD endpoints failed: Other(StringError("[src/pd/util.rs:361]: duplicate PD endpoint 127.0.0.1:13916"))

2019/02/22 17:48:48.683 util.rs:408: [INFO] connecting to PD endpoint: "127.0.0.1:14205"

2019/02/22 17:48:48.685 util.rs:408: [INFO] connecting to PD endpoint: "127.0.0.1:13916"

2019/02/22 17:48:48.686 client.rs:62: [WARN] validate PD endpoints failed: Other(StringError("[src/pd/util.rs:361]: duplicate PD endpoint 127.0.0.1:13916"))

2019/02/22 17:48:48.986 util.rs:408: [INFO] connecting to PD endpoint: "127.0.0.1:14205"

2019/02/22 17:48:48.987 util.rs:408: [INFO] connecting to PD endpoint: "127.0.0.1:13916"

2019/02/22 17:48:48.989 client.rs:62: [WARN] validate PD endpoints failed: Other(StringError("[src/pd/util.rs:361]: duplicate PD endpoint 127.0.0.1:13916"))

2019/02/22 17:48:49.289 util.rs:408: [INFO] connecting to PD endpoint: "127.0.0.1:14205"

2019/02/22 17:48:49.290 util.rs:408: [INFO] connecting to PD endpoint: "127.0.0.1:13916"

2019/02/22 17:48:49.291 client.rs:62: [WARN] validate PD endpoints failed: Other(StringError("[src/pd/util.rs:361]: duplicate PD endpoint 127.0.0.1:13916"))

2019/02/22 17:48:49.591 util.rs:408: [INFO] connecting to PD endpoint: "127.0.0.1:14205"

2019/02/22 17:48:49.592 util.rs:408: [INFO] connecting to PD endpoint: "127.0.0.1:13916"

2019/02/22 17:48:49.594 client.rs:62: [WARN] validate PD endpoints failed: Other(StringError("[src/pd/util.rs:361]: duplicate PD endpoint 127.0.0.1:13916"))

+ status=1
```

**Comment by gengliqi** [comment]
close because it's too old.
