### ISSUE TITLE
test: test_sst_writer(I guess) failed with assertion failed in rocksdb

### ISSUE THREAD

**Issue by ICEYSELF** [tikv/tikv#4295]
## Bug Report

**What version of Rust are you using?**
`rustc 1.32.0-nightly (14997d56a 2018-12-05)`, it was downloaded by cargo automatically when first time running `cargo build`

**What operating system and CPU are you using?**
```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
stepping	: 9
microcode	: 0x70
cpu MHz		: 3100.093
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 5424.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
stepping	: 9
microcode	: 0x70
cpu MHz		: 2912.891
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 2
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 5424.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
stepping	: 9
microcode	: 0x70
cpu MHz		: 3100.018
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 2
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 5424.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
stepping	: 9
microcode	: 0x70
cpu MHz		: 3100.051
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 2
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 5424.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
```
operating system(uname -a): `Linux icey-self 4.15.0-29deepin-generic #31 SMP Fri Jul 27 07:12:08 UTC 2018 x86_64 GNU/Linux`

**What did you do?**
I cloned the latest code of TiKV and tried to build it, and then test it out. However, during `cargo test`, an assertion failure occured in a rocksdb C file

**What did you expect to see?**
tests passing

**What did you see instead?**
```
...
test import::engine::tests::test_write ... ok
test import::import_mode::tests::test_import_mode_switcher ... ok
tikv-637fffa71e85eb5f: /home/icey/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/5f49f9e/librocksdb_sys/rocksdb/env/env_encryption.cc:672: virtual rocksdb::Status rocksdb::EncryptedEnv::GetFileSize(const string&, uint64_t*): Assertion `*file_size >= prefixLength' failed.
```

I used `rust-gdb` to run the test program again, and got the following stacktrace:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff7212231 in __GI_abort () at abort.c:79
#2  0x00007ffff72099da in __assert_fail_base (fmt=0x7ffff735cd48 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x5555596cfd0f "*file_size >= prefixLength", 
    file=file@entry=0x5555596cfc70 "/home/icey/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/5f49f9e/librocksdb_sys/rocksdb/env/env_encryption.cc", line=line@entry=672, 
    function=function@entry=0x5555596cff60 <rocksdb::EncryptedEnv::GetFileSize(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long*)::__PRETTY_FUNCTION__> "virtual rocksdb::Status rocksdb::EncryptedEnv::GetFileSize(const string&, uint64_t*)") at assert.c:92
#3  0x00007ffff7209a52 in __GI___assert_fail (assertion=0x5555596cfd0f "*file_size >= prefixLength", 
    file=0x5555596cfc70 "/home/icey/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/5f49f9e/librocksdb_sys/rocksdb/env/env_encryption.cc", line=672, 
    function=0x5555596cff60 <rocksdb::EncryptedEnv::GetFileSize(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long*)::__PRETTY_FUNCTION__> "virtual rocksdb::Status rocksdb::EncryptedEnv::GetFileSize(const string&, uint64_t*)") at assert.c:101
#4  0x0000555558a01a9e in rocksdb::EncryptedEnv::GetFileSize (this=0x7fffeac00120, fname=..., file_size=0x7fff703a3210)
    at /home/icey/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/5f49f9e/librocksdb_sys/rocksdb/env/env_encryption.cc:672
#5  0x000055555892b36d in rocksdb::ExternalSstFileIngestionJob::GetIngestedFileInfo (this=0x7fff703a3ec0, external_file=..., 
    file_to_ingest=0x7fff703a31a0, sv=0x7fffeace7c40)
    at /home/icey/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/5f49f9e/librocksdb_sys/rocksdb/db/external_sst_file_ingestion_job.cc:294
#6  0x00005555589294f7 in rocksdb::ExternalSstFileIngestionJob::Prepare (this=0x7fff703a3ec0, external_files_paths=..., 
    next_file_number=13, sv=0x7fffeace7c40)
    at /home/icey/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/5f49f9e/librocksdb_sys/rocksdb/db/external_sst_file_ingestion_job.cc:40
#7  0x00005555588939fd in rocksdb::DBImpl::IngestExternalFile (this=0x7fffeacce000, column_family=0x7fffead103c0, 
    external_files=..., ingestion_options=...)
    at /home/icey/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/5f49f9e/librocksdb_sys/rocksdb/db/db_impl.cc:2946
#8  0x0000555558850e23 in crocksdb_ingest_external_file_cf (db=0x7fffeac12100, handle=0x7fffeac120e0, file_list=0x7fffeac12348, 
    list_len=1, opt=0x7fffeac12338, errptr=0x7fff703a5a28) at crocksdb/c.cc:3562
#9  0x00005555587f124b in rocksdb::rocksdb::DB::ingest_external_file_cf::hf08c858fe61bae82 (self=0x7fffead0b590, 
    cf=0x7fffeacf7130, opt=0x7fff703a6c38, files=&[&str](len: 1) = {...})
    at /home/icey/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/5f49f9e/src/rocksdb.rs:1388
#10 0x000055555691dcdf in tikv::import::engine::tests::test_sst_writer_with::h03d74018224e7dd2 (value_size=1, 
    cf_names=&[&str](len: 1) = {...}, security_cfg=0x7fff703a7770) at src/import/engine.rs:427
#11 0x000055555691f29e in tikv::import::engine::tests::test_sst_writer::h5eb3cbf69f1efd1f () at src/import/engine.rs:371
#12 0x0000555556c96e2a in tikv::import::engine::tests::test_sst_writer::_$u7b$$u7b$closure$u7d$$u7d$::h708cb56bdf5b1f97 ()
    at src/import/engine.rs:365
#13 0x00005555563c304e in core::ops::function::FnOnce::call_once::h84d3fa16289ef89b ()
    at /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/libcore/ops/function.rs:238
#14 0x000055555902f3ff in test::run_test::_$u7b$$u7b$closure$u7d$$u7d$::hf7bc6d3f462f99c0 () at src/libtest/lib.rs:1471
#15 core::ops::function::FnOnce::call_once::h9712cf50102df637 ()
    at /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/libcore/ops/function.rs:238
#16 _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::heaac3d9881a6c305 ()
    at /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/liballoc/boxed.rs:673
#17 0x000055555954f9ea in __rust_maybe_catch_panic () at src/libpanic_unwind/lib.rs:102
#18 0x0000555559027284 in std::panicking::try::h39ee07934c2c9c2b ()
    at /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/libstd/panicking.rs:289
#19 std::panic::catch_unwind::hdcb2e666c1f12cb0 () at /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/libstd/panic.rs:398
#20 test::run_test::run_test_inner::_$u7b$$u7b$closure$u7d$$u7d$::h25eb5d51f4c07f55 () at src/libtest/lib.rs:1426
#21 std::sys_common::backtrace::__rust_begin_short_backtrace::hacddd867d68d526f ()
    at /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/libstd/sys_common/backtrace.rs:136
#22 0x0000555559028215 in std::thread::Builder::spawn_unchecked::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h95ed740423fc8339 () at /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/libstd/thread/mod.rs:477
#23 _$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::hdc8a9981b0c78ffc () at /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/libstd/panic.rs:319
#24 std::panicking::try::do_call::hdee5b3fcbccef59e ()
    at /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/libstd/panicking.rs:310
#25 0x000055555954f9ea in __rust_maybe_catch_panic () at src/libpanic_unwind/lib.rs:102
#26 0x000055555902f2dd in std::panicking::try::hfc86bf33c7b82a11 ()
    at /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/libstd/panicking.rs:289
#27 std::panic::catch_unwind::hd4d4f236dcdb94df () at /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/libstd/panic.rs:398
#28 std::thread::Builder::spawn_unchecked::_$u7b$$u7b$closure$u7d$$u7d$::h591fa5360682252a ()
    at /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/libstd/thread/mod.rs:476
#29 _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h6e7b1f5771d564f4 ()
    at /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/liballoc/boxed.rs:673
#30 0x000055555954360e in _$LT$alloc..boxed..Box$LT$$LP$dyn$u20$alloc..boxed..FnBox$LT$A$C$$u20$Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$RP$$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::hb8f4ee9bdf46e5d9 ()
    at /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/liballoc/boxed.rs:683
#31 std::sys_common::thread::start_thread::h938451c06a28c9dd () at src/libstd/sys_common/thread.rs:24
#32 std::sys::unix::thread::Thread::new::thread_start::h809dab03f76374f4 () at src/libstd/sys/unix/thread.rs:90
#33 0x00007ffff7bc15aa in start_thread (arg=0x7fff703ab700) at pthread_create.c:463
#34 0x00007ffff72d2cbf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

I will provide core dump file if needed

**Comment by DorianZheng** [comment]
#4296

**Comment by ICEYSELF** [comment]
The test is passing now, thx

**Comment by ice1000** [comment]
Thanks for reporting!
