### ISSUE TITLE
test buffer::tests::test_vec_reallocate failed

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#4318]
## Bug Report

```
test buffer::tests::test_vec_reallocate ... thread 'main' panicked at 'realloc test realloc enough', components/codec/src/buffer.rs:465:13

stack backtrace:

   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace

             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39

   1: std::sys_common::backtrace::_print

             at src/libstd/sys_common/backtrace.rs:71

   2: std::panicking::default_hook::{{closure}}

             at src/libstd/sys_common/backtrace.rs:59

             at src/libstd/panicking.rs:197

   3: std::panicking::default_hook

             at src/libstd/panicking.rs:211

   4: std::panicking::rust_panic_with_hook

             at src/libstd/panicking.rs:474

   5: std::panicking::begin_panic

             at /rustc/a9da8fc9c267c08cfdb8cf5b39da14f154d12939/src/libstd/panicking.rs:408

   6: codec::buffer::tests::test_vec_reallocate

             at components/codec/src/buffer.rs:465

   7: codec::buffer::tests::test_vec_reallocate::{{closure}}

             at components/codec/src/buffer.rs:409

   8: core::ops::function::FnOnce::call_once

             at /rustc/a9da8fc9c267c08cfdb8cf5b39da14f154d12939/src/libcore/ops/function.rs:231

   9: <F as alloc::boxed::FnBox<A>>::call_box

             at src/libtest/lib.rs:1513

             at /rustc/a9da8fc9c267c08cfdb8cf5b39da14f154d12939/src/libcore/ops/function.rs:231

             at /rustc/a9da8fc9c267c08cfdb8cf5b39da14f154d12939/src/liballoc/boxed.rs:749

  10: __rust_maybe_catch_panic

             at src/libpanic_unwind/lib.rs:87

  11: test::run_test::run_test_inner::{{closure}}

             at /rustc/a9da8fc9c267c08cfdb8cf5b39da14f154d12939/src/libstd/panicking.rs:272

             at /rustc/a9da8fc9c267c08cfdb8cf5b39da14f154d12939/src/libstd/panic.rs:388

             at src/libtest/lib.rs:1468

  12: test::run_test::run_test_inner

             at src/libtest/lib.rs:1490

  13: test::run_test

             at src/libtest/lib.rs:1509

  14: test::run_tests_console

             at src/libtest/lib.rs:1167

             at src/libtest/lib.rs:972

  15: test::test_main

             at src/libtest/lib.rs:293

  16: test::test_main_static

             at src/libtest/lib.rs:327

  17: codec::main

  18: std::rt::lang_start::{{closure}}

             at /rustc/a9da8fc9c267c08cfdb8cf5b39da14f154d12939/src/libstd/rt.rs:64

  19: std::panicking::try::do_call

             at src/libstd/rt.rs:49

             at src/libstd/panicking.rs:293

  20: __rust_maybe_catch_panic

             at src/libpanic_unwind/lib.rs:87

  21: std::rt::lang_start_internal

             at src/libstd/panicking.rs:272

             at src/libstd/panic.rs:388

             at src/libstd/rt.rs:48
```

**Comment by breeswish** [comment]
This test relies on the behaviour that jemalloc realloc the address. Maybe the new member of our team can help us find a solution to reliably letting jemalloc realloc. @siddontang

**Comment by nrc** [comment]
See also https://github.com/tikv/tikv/pull/4300#issuecomment-470319267

**Comment by breeswish** [comment]
Not occurred for a while. Closing for now.
