### ISSUE TITLE
add `rocksdb` into "Checking your prerequisites"?

### ISSUE THREAD

**Issue by bradyjoestar** [tikv/tikv#4431]
I have tried to build tikv on a new machine, I failed many times.

Finally  I found the reason of it is that I don't have the prerequisites of `rocksdb` on my machine.

Maybe it's better to add it into "Checking your prerequisites" in README.md?

```
### Checking your prerequisites

To build TiKV you'll need to at least have the following installed:

* `git` - Version control
* `rustup` - Rust toolchain manager
* `awk` - Pattern scanning/processing language
* `cmake` - Build tool (required for gRPC)
* `go` - Programming language (required for gRPC)
* `make` - Build tool (run common workflows)
* `clang` or `gcc` - C compiler toolchain
```

**Comment by BusyJay** [comment]
Can you provide the failure logs? Rocksdb is not required. Actually it's supposed to build rocksdb from source, which is part of rocksdb-rs dependency.

**Comment by bradyjoestar** [comment]
As you said , I  installed rocksdb-rs dependency and it succeed. 

I follow the steps in `rocksdb-c++` and install these following library, and it worked. 
```
Linux - Ubuntu

Upgrade your gcc to version at least 4.8 to get C++11 support.
Install gflags. First, try: sudo apt-get install libgflags-dev If this doesn't work and you're using Ubuntu, here's a nice tutorial: (http://askubuntu.com/questions/312173/installing-gflags-12-04)
Install snappy. This is usually as easy as: sudo apt-get install libsnappy-dev.
Install zlib. Try: sudo apt-get install zlib1g-dev.
Install bzip2: sudo apt-get install libbz2-dev.
Install lz4: sudo apt-get install liblz4-dev.
Install zstandard: sudo apt-get install libzstd-dev.
```

maybe we should tell users that they should install `rocksdb-dependency`? Thank you for your reply.

**Comment by BusyJay** [comment]
snappy, zlib, bzip2, lz4 and zstandard are also compiled from source too, you are not required to pre-install any of those. And gflags should not be required as we only build the rocksdb library instead of ldb utils. Can you provide your system information?

**Comment by bradyjoestar** [comment]
root@ip-172-31-30-204:/home/ubuntu# cat /proc/version
Linux version 4.15.0-1032-aws (buildd@lcy01-amd64-025) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #34-Ubuntu SMP Thu Jan 17 15:18:09 UTC 2019
root@ip-172-31-30-204:/home/ubuntu# uname -a
Linux ip-172-31-30-204 4.15.0-1032-aws #34-Ubuntu SMP Thu Jan 17 15:18:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
root@ip-172-31-30-204:/home/ubuntu# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
root@ip-172-31-30-204:/home/ubuntu#

**Comment by bradyjoestar** [comment]
error Info

```
error: failed to run custom build command for `librocksdb_sys v0.1.0 (https://github.com/pingcap/rust-rocksdb.git#5f49f9ef)`
process didn't exit successfully: `/home/ubuntu/tikv/target/debug/build/librocksdb_sys-f1ddbe94de4940d5/build-script-build` (exit code: 101)
--- stdout
("CARGO", "/root/.rustup/toolchains/nightly-2019-03-05-x86_64-unknown-linux-gnu/bin/cargo")
("CARGO_CFG_DEBUG_ASSERTIONS", "")
("CARGO_CFG_PROC_MACRO", "")
("CARGO_CFG_TARGET_ARCH", "x86_64")
("CARGO_CFG_TARGET_ENDIAN", "little")
("CARGO_CFG_TARGET_ENV", "gnu")
("CARGO_CFG_TARGET_FAMILY", "unix")
("CARGO_CFG_TARGET_FEATURE", "fxsr,mmx,sse,sse2")
("CARGO_CFG_TARGET_HAS_ATOMIC", "16,32,64,8,cas,ptr")
("CARGO_CFG_TARGET_OS", "linux")
("CARGO_CFG_TARGET_POINTER_WIDTH", "64")
("CARGO_CFG_TARGET_THREAD_LOCAL", "")
("CARGO_CFG_TARGET_VENDOR", "unknown")
("CARGO_CFG_UNIX", "")
("CARGO_FEATURE_DEFAULT", "1")
("CARGO_FEATURE_PORTABLE", "1")
("CARGO_FEATURE_SSE", "1")
("CARGO_HOME", "/root/.cargo")
("CARGO_MAKEFLAGS", "--jobserver-fds=3,5 -j --jobserver-auth=3,5 -j")
("CARGO_MANIFEST_DIR", "/root/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/5f49f9e/librocksdb_sys")
("CARGO_MANIFEST_LINKS", "rocksdb")
("CARGO_PKG_AUTHORS", "Jay Lee <busyjaylee@gmail.com>")
("CARGO_PKG_DESCRIPTION", "")
("CARGO_PKG_HOMEPAGE", "")
("CARGO_PKG_NAME", "librocksdb_sys")
("CARGO_PKG_REPOSITORY", "")
("CARGO_PKG_VERSION", "0.1.0")
("CARGO_PKG_VERSION_MAJOR", "0")
("CARGO_PKG_VERSION_MINOR", "1")
("CARGO_PKG_VERSION_PATCH", "0")
("CARGO_PKG_VERSION_PRE", "")
("DEBUG", "true")
("DEP_BZIP2_INCLUDE", "/home/ubuntu/tikv/target/debug/build/bzip2-sys-70b070a9807554e5/out/include")
("DEP_BZIP2_ROOT", "/home/ubuntu/tikv/target/debug/build/bzip2-sys-70b070a9807554e5/out")
("DEP_LZ4_ROOT", "/home/ubuntu/tikv/target/debug/build/lz4-sys-5cbf0a43ecd21e31/out")
("DEP_SNAPPY_ROOT", "/home/ubuntu/tikv/target/debug/build/snappy-sys-a1ccc69cfa7871e8/out/build")
("DEP_ZSTD_ROOT", "/home/ubuntu/tikv/target/debug/build/zstd-sys-f9f9010ebb05506c/out")
("DEP_Z_INCLUDE", "/home/ubuntu/tikv/target/debug/build/libz-sys-aa1984fcb2cc8720/out/include")
("DEP_Z_ROOT", "/home/ubuntu/tikv/target/debug/build/libz-sys-aa1984fcb2cc8720/out")
("DYLD_LIBRARY_PATH", ":/lib")
("GOPATH", "/root/go")
("GOROOT", "/root/.go")
("HOME", "/root")
("HOST", "x86_64-unknown-linux-gnu")
("LANG", "C.UTF-8")
("LD_LIBRARY_PATH", "/home/ubuntu/tikv/target/debug/deps:/root/.rustup/toolchains/nightly-2019-03-05-x86_64-unknown-linux-gnu/lib:/root/.rustup/toolchains/nightly-2019-03-05-x86_64-unknown-linux-gnu/lib")
("LESSCLOSE", "/usr/bin/lesspipe %s %s")
("LESSOPEN", "| /usr/bin/lesspipe %s")
("LOGNAME", "root")
("LOG_LEVEL", "DEBUG")
("LS_COLORS", "rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:")
("MAIL", "/var/mail/root")
("MAKEFLAGS", "")
("MAKELEVEL", "1")
("MAKE_TERMERR", "/dev/pts/0")
("MAKE_TERMOUT", "/dev/pts/0")
("MFLAGS", "")
("NUM_JOBS", "4")
("OLDPWD", "/home/ubuntu")
("OPT_LEVEL", "0")
("OUT_DIR", "/home/ubuntu/tikv/target/debug/build/librocksdb_sys-27b45ddf2d5bcc99/out")
("PATH", "/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/root/.go/bin:/root/go/bin:/root/.cargo/bin")
("PROFILE", "debug")
("PWD", "/home/ubuntu/tikv")
("RUSTC", "rustc")
("RUSTDOC", "rustdoc")
("RUSTUP_HOME", "/root/.rustup")
("RUSTUP_TOOLCHAIN", "nightly-2019-03-05-x86_64-unknown-linux-gnu")
("RUST_BACKTRACE", "1")
("RUST_RECURSION_COUNT", "1")
("SHELL", "/bin/bash")
("SHLVL", "2")
("SSL_CERT_DIR", "/usr/lib/ssl/certs")
("SSL_CERT_FILE", "/usr/lib/ssl/certs/ca-certificates.crt")
("SUDO_COMMAND", "/bin/su")
("SUDO_GID", "1000")
("SUDO_UID", "1000")
("SUDO_USER", "ubuntu")
("TARGET", "x86_64-unknown-linux-gnu")
("TERM", "xterm-256color")
("TIKV_BUILD_GIT_BRANCH", "master")
("TIKV_BUILD_GIT_HASH", "93919cba048bd713a04141f01bef871199cf4c73")
("TIKV_BUILD_RUSTC_VERSION", "rustc 1.35.0-nightly (a9da8fc9c 2019-03-04)")
("TIKV_BUILD_TIME", "2019-03-25 03:31:57")
("USER", "root")
("USERNAME", "root")
("_", "/root/.cargo/bin/cargo")
running: "cmake" "/root/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/5f49f9e/librocksdb_sys/rocksdb" "-DPORTABLE=ON" "-DFORCE_SSE42=ON" "-DWITH_ZLIB=ON" "-DWITH_BZ2=ON" "-DWITH_LZ4=ON" "-DWITH_ZSTD=ON" "-DWITH_SNAPPY=ON" "-DCMAKE_INSTALL_PREFIX=/home/ubuntu/tikv/target/debug/build/librocksdb_sys-27b45ddf2d5bcc99/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Debug"
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Found snappy: /home/ubuntu/tikv/target/debug/build/snappy-sys-a1ccc69cfa7871e8/out/build/libsnappy.a  
-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/tikv/target/debug/build/librocksdb_sys-27b45ddf2d5bcc99/out/build/CMakeFiles/CMakeOutput.log".

--- stderr
CMake Warning at CMakeLists.txt:75 (find_package):
  By not providing "Findgflags.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gflags", but
  CMake did not find one.

  Could not find a package configuration file provided by "gflags" with any
  of the following names:

    gflagsConfig.cmake
    gflags-config.cmake

  Add the installation prefix of "gflags" to CMAKE_PREFIX_PATH or set
  "gflags_DIR" to a directory containing one of the above files.  If "gflags"
  provides a separate development package or SDK, be sure it has been
  installed.


CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find zlib (missing: ZLIB_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/Findzlib.cmake:17 (find_package_handle_standard_args)
  CMakeLists.txt:91 (find_package)


thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.35/src/lib.rs:778:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:336
   7: cmake::fail
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.35/src/lib.rs:778
   8: cmake::run
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.35/src/lib.rs:759
   9: cmake::Config::build
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.35/src/lib.rs:611
  10: build_script_build::build_rocksdb
             at ./build.rs:86
  11: build_script_build::main
             at ./build.rs:23
  12: std::rt::lang_start::{{closure}}
             at /rustc/a9da8fc9c267c08cfdb8cf5b39da14f154d12939/src/libstd/rt.rs:64
  13: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  14: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  15: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  16: std::rt::lang_start
             at /rustc/a9da8fc9c267c08cfdb8cf5b39da14f154d12939/src/libstd/rt.rs:64
  17: main
  18: __libc_start_main

```

**Comment by Hoverbear** [comment]
The error is a missing zlib. You need `zlib1g-dev` or similar installed on Ubuntu
