### ISSUE TITLE
test_server_transfer_leader_safe fails

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#4506]
## Bug Report

```
test raftstore::test_conf_change::test_server_transfer_leader_safe ... thread 'main' panicked at 'region Some(Region { id: 1, start_key: [], end_key: [], region_epoch: Some(RegionEpoch { conf_ver: 1, version: 1, unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 4 } }), peers: [Peer { id: 1, store_id: 1, is_learner: false, unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 4 } }], unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 14 } }) has no peer Peer { id: 2, store_id: 2, is_learner: false, unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } }', components/test_raftstore/src/pd.rs:744:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:336
   7: test_raftstore::pd::TestPdClient::must_have_peer
             at components/test_raftstore/src/pd.rs:744
   8: test_raftstore::pd::TestPdClient::must_add_peer
             at components/test_raftstore/src/pd.rs:840
   9: integrations::raftstore::test_conf_change::test_transfer_leader_safe
             at tests/integrations/raftstore/test_conf_change.rs:588
  10: integrations::raftstore::test_conf_change::test_server_transfer_leader_safe
             at tests/integrations/raftstore/test_conf_change.rs:714
  11: integrations::raftstore::test_conf_change::test_server_transfer_leader_safe::{{closure}}
             at tests/integrations/raftstore/test_conf_change.rs:710
  12: core::ops::function::FnOnce::call_once
             at /rustc/a9da8fc9c267c08cfdb8cf5b39da14f154d12939/src/libcore/ops/function.rs:231
  13: <F as alloc::boxed::FnBox<A>>::call_box
             at src/libtest/lib.rs:1513
             at /rustc/a9da8fc9c267c08cfdb8cf5b39da14f154d12939/src/libcore/ops/function.rs:231
             at /rustc/a9da8fc9c267c08cfdb8cf5b39da14f154d12939/src/liballoc/boxed.rs:749
  14: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  15: test::run_test::run_test_inner::{{closure}}
             at /rustc/a9da8fc9c267c08cfdb8cf5b39da14f154d12939/src/libstd/panicking.rs:272
             at /rustc/a9da8fc9c267c08cfdb8cf5b39da14f154d12939/src/libstd/panic.rs:388
             at src/libtest/lib.rs:1468
  16: test::run_test::run_test_inner
             at src/libtest/lib.rs:1490
  17: test::run_test
             at src/libtest/lib.rs:1509
  18: test::run_tests_console
             at src/libtest/lib.rs:1167
             at src/libtest/lib.rs:972
  19: test::test_main
             at src/libtest/lib.rs:293
  20: test::test_main_static
             at src/libtest/lib.rs:327
  21: integrations::main
  22: std::rt::lang_start::{{closure}}
             at /rustc/a9da8fc9c267c08cfdb8cf5b39da14f154d12939/src/libstd/rt.rs:64
  23: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  24: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  25: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
                          at src/libstd/rt.rs:48
               26: std::rt::lang_start
                          at /rustc/a9da8fc9c267c08cfdb8cf5b39da14f154d12939/src/libstd/rt.rs:64
               27: main
               28: __libc_start_main
               29: <unknown>
             FAILED
```
Link: https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/3156/pipeline

Logs are lost due to #4505

**Comment by overvenus** [comment]
Another failed test https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/3172/pipeline

**Comment by youjiali1995** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/13697/pipeline

**Comment by BusyJay** [comment]
Duplicated with #7425.
