### ISSUE TITLE
test_server_read_leader_with_unapplied_log fails

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#4507]
## Bug Report

```
test raftstore::test_multi::test_server_read_leader_with_unapplied_log ... thread 'main' panicked at 'read should be dropped immediately, but got RaftCmdResponse { header: Some(RaftResponseHeader { error: None, uuid: [], current_term: 8, unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } }), responses: [Response { cmd_type: Get, get: Some(GetResponse { value: [118], unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } }), put: None, delete: None, snap: None, prewrite: None, delte_range: None, ingest_sst: None, unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } }], admin_response: None, status_response: None, unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } }', tests/integrations/raftstore/test_multi.rs:562:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:336
   7: integrations::raftstore::test_multi::test_read_leader_with_unapplied_log
             at tests/integrations/raftstore/test_multi.rs:562
   8: integrations::raftstore::test_multi::test_server_read_leader_with_unapplied_log
             at tests/integrations/raftstore/test_multi.rs:583
   9: integrations::raftstore::test_multi::test_server_read_leader_with_unapplied_log::{{closure}}
             at tests/integrations/raftstore/test_multi.rs:581
  10: core::ops::function::FnOnce::call_once
             at /rustc/a9da8fc9c267c08cfdb8cf5b39da14f154d12939/src/libcore/ops/function.rs:231
  11: <F as alloc::boxed::FnBox<A>>::call_box
             at src/libtest/lib.rs:1513
             at /rustc/a9da8fc9c267c08cfdb8cf5b39da14f154d12939/src/libcore/ops/function.rs:231
             at /rustc/a9da8fc9c267c08cfdb8cf5b39da14f154d12939/src/liballoc/boxed.rs:749
  12: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  13: test::run_test::run_test_inner::{{closure}}
             at /rustc/a9da8fc9c267c08cfdb8cf5b39da14f154d12939/src/libstd/panicking.rs:272
             at /rustc/a9da8fc9c267c08cfdb8cf5b39da14f154d12939/src/libstd/panic.rs:388
             at src/libtest/lib.rs:1468
  14: test::run_test::run_test_inner
             at src/libtest/lib.rs:1490
  15: test::run_test
             at src/libtest/lib.rs:1509
  16: test::run_tests_console
             at src/libtest/lib.rs:1167
             at src/libtest/lib.rs:972
  17: test::test_main
             at src/libtest/lib.rs:293
  18: test::test_main_static
             at src/libtest/lib.rs:327
  19: integrations::main
  20: std::rt::lang_start::{{closure}}
             at /rustc/a9da8fc9c267c08cfdb8cf5b39da14f154d12939/src/libstd/rt.rs:64
  21: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  22: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  23: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  24: std::rt::lang_start
             at /rustc/a9da8fc9c267c08cfdb8cf5b39da14f154d12939/src/libstd/rt.rs:64
  25: main
  26: __libc_start_main
  27: <unknown>
```

Link: https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/3156/pipeline

Logs are lost due to #4505

**Comment by zhangjinpeng1987** [comment]
Duplicated with https://github.com/tikv/tikv/issues/5611, close this one.

**Comment by BusyJay** [comment]
Duplicated with #7426.
