### ISSUE TITLE
Fuzz test failed for tikv::coprocessor::codec::mysql::Duration

### ISSUE THREAD

**Issue by whoiscc** [tikv/tikv#4609]
## Bug Report

**What version of TiKV are you using?**

3.0.0-beta.1

**What operating system and CPU are you using?**

macOS 10.14.4

**What did you do?**

The new fuzz tests added by WIP PR #4608 failed. The fuzz test looks like this:

```rust
fn fuzz_duration(
    t: tikv::coprocessor::codec::mysql::Duration,
    mut cursor: Cursor<&[u8]>,
) -> Result<(), Error> {
    use tikv::coprocessor::codec::mysql::DurationEncoder;
    let _ = t.fsp();
    let _ = t.clone().set_fsp(cursor.read_as_u8()?);
    let _ = t.hours();
    let _ = t.minutes();
    let _ = t.secs();
    let _ = t.micro_secs();
    let _ = t.nano_secs();
    let _ = t.to_secs();
    let _ = t.is_zero();
    let _ = t.to_decimal();
    let _ = t.clone().round_frac(cursor.read_as_i8()?);
    let mut v = Vec::new();
    let _ = v.encode_duration(&t);
    Ok(())
}

pub fn fuzz_coprocessor_codec_duration_from_nanos(data: &[u8]) -> Result<(), Error> {
    use tikv::coprocessor::codec::mysql::Duration;
    let mut cursor = Cursor::new(data);
    let nanos = cursor.read_as_i64()?;
    let fsp = cursor.read_as_i8()?;
    fuzz_duration(Duration::from_nanos(nanos, fsp)?, cursor)
}
```

The crash log:

```
thread '<unnamed>' panicked at 'attempt to negate with overflow', /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libcore/num/mod.rs:1894:21
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
==53535== ERROR: libFuzzer: deadly signal
    #0 0x111779707 in __sanitizer_print_stack_trace (lib__rustc__clang_rt.asan_osx_dynamic.dylib:x86_64+0x68707)
    #1 0x10bc7e87b in fuzzer::Fuzzer::CrashCallback() (fuzz_coprocessor_codec_duration_from_nanos:x86_64+0x105b7387b)
    #2 0x10bc7e82d in fuzzer::Fuzzer::StaticCrashSignalCallback() (fuzz_coprocessor_codec_duration_from_nanos:x86_64+0x105b7382d)
    #3 0x10bcbf477 in fuzzer::CrashHandler(int, __siginfo*, void*) (fuzz_coprocessor_codec_duration_from_nanos:x86_64+0x105bb4477)
    #4 0x7fff590abb5c in _sigtramp (libsystem_platform.dylib:x86_64+0x4b5c)
    #5 0x10c379ddf in anon.1a1ea8a681c65673f54e7ec62d58dbd6.27 (fuzz_coprocessor_codec_duration_from_nanos:x86_64+0x10626eddf)
    #6 0x10bcf382e in __rust_maybe_catch_panic (fuzz_coprocessor_codec_duration_from_nanos:x86_64+0x105be882e)
    #7 0x10bc7d01e in std::panicking::try::hd4964c260fccd748 (fuzz_coprocessor_codec_duration_from_nanos:x86_64+0x105b7201e)
    #8 0x10bc7cab2 in LLVMFuzzerTestOneInput (fuzz_coprocessor_codec_duration_from_nanos:x86_64+0x105b71ab2)
    #9 0x10bc7ffda in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (fuzz_coprocessor_codec_duration_from_nanos:x86_64+0x105b74fda)
    #10 0x10bc7f9d9 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) (fuzz_coprocessor_codec_duration_from_nanos:x86_64+0x105b749d9)
    #11 0x10bc81601 in fuzzer::Fuzzer::MutateAndTestOne() (fuzz_coprocessor_codec_duration_from_nanos:x86_64+0x105b76601)
    #12 0x10bc828b1 in fuzzer::Fuzzer::Loop(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) (fuzz_coprocessor_codec_duration_from_nanos:x86_64+0x105b778b1)
    #13 0x10bcadaf8 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (fuzz_coprocessor_codec_duration_from_nanos:x86_64+0x105ba2af8)
    #14 0x10bcd01b9 in main (fuzz_coprocessor_codec_duration_from_nanos:x86_64+0x105bc51b9)
    #15 0x7fff58ec63d4 in start (libdyld.dylib:x86_64+0x163d4)

NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 1 CMP- DE: "\x00\x00\x00\x00\x00\x00\x00\x80"-; base unit: b9e12e36e3a6480ed8fed7d7a9686e8e063a8857
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x80,0x5,0x0,
\x00\x00\x00\x00\x00\x00\x00\x80\x05\x00
artifact_prefix='./'; Test unit written to ./crash-e51d5a69f4e0a5b60dd0905561f210f8def00109
Base64: AAAAAAAAAIAFAA==
Running fuzzer failed: Libfuzzer exited with code Some(77)
Error: 1
```

**Comment by ice1000** [comment]
> note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

Could you please rerun with the env var?

**Comment by ice1000** [comment]
> note: Run with RUST_BACKTRACE=1 environment variable to display a backtrace.
> 
> Could you please rerun with the env var?

... and show us the printed stacktrace?

**Comment by whoiscc** [comment]
```
thread '<unnamed>' panicked at 'attempt to negate with overflow', /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libcore/num/mod.rs:1894:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: tikv::coprocessor::codec::mysql::duration::Duration::from_nanos
  10: fuzz_targets::fuzz_coprocessor_codec_duration_from_nanos
  11: rust_fuzzer_test_input
  12: __rust_maybe_catch_panic
  13: std::panicking::try
  14: LLVMFuzzerTestOneInput
  15: _ZN6fuzzer6Fuzzer15ExecuteCallbackEPKhm
  16: _ZN6fuzzer6Fuzzer6RunOneEPKhmbPNS_9InputInfoEPb
  17: _ZN6fuzzer6Fuzzer16MutateAndTestOneEv
  18: _ZN6fuzzer6Fuzzer4LoopERKNSt3__16vectorINS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS_16fuzzer_allocatorIS8_EEEE
  19: _ZN6fuzzer12FuzzerDriverEPiPPPcPFiPKhmE
  20: main
```

**Comment by whoiscc** [comment]
The code there looks like this:

```rust
pub fn from_nanos(nanos: i64, fsp: i8) -> Result<Duration> {
        let neg = nanos < 0;
        let nanos = nanos.abs();
        // ...
```

The max negative i64 value is not handled properly, I think.

**Comment by breeswish** [comment]
Good job! @AndreMouche  PTAL

@iosmanthus You can also take a look.

**Comment by iosmanthus** [comment]
> Good job! @AndreMouche PTAL
> 
> @iosmanthus You can also take a look.

OK! Thanks for reminding! 😆

**Comment by iosmanthus** [comment]
> The code there looks like this:
> 
> ```rust
> pub fn from_nanos(nanos: i64, fsp: i8) -> Result<Duration> {
>         let neg = nanos < 0;
>         let nanos = nanos.abs();
>         // ...
> ```
> 
> The max negative i64 value is not handled properly, I think.

Yeah! We should use [`i64::check_abs(self) -> Option<i64>`](https://doc.rust-lang.org/std/primitive.i8.html#method.checked_abs) instead.

**Comment by BusyJay** [comment]
@iosmanthus was it fixed?

**Comment by iosmanthus** [comment]
Yes! @BusyJay
