### ISSUE TITLE
Fuzz test failed for tikv::coprocessor::codec::mysql::Duration::parse

### ISSUE THREAD

**Issue by whoiscc** [tikv/tikv#4610]
## Bug Report

**What version of TiKV are you using?**

3.0.0-beta.1

**What operating system and CPU are you using?**

macOS 10.14.4

**What did you do?**

The fuzz test added by WIP PR #4608 failed. This is the test:

```rust
pub fn fuzz_coprocessor_codec_duration_from_parse(data: &[u8]) -> Result<(), Error> {
    use std::io::Read;
    use tikv::coprocessor::codec::mysql::Duration;
    let mut cursor = Cursor::new(data);
    let fsp = cursor.read_as_i8()?;
    let mut buf: [u8; 32] = [b' '; 32];
    cursor.read_exact(&mut buf)?;
    let d = Duration::parse(&buf, fsp)?;
    fuzz_duration(d, cursor)
}
```

This is the error report:

```
thread '<unnamed>' panicked at 'attempt to multiply with overflow', src/coprocessor/codec/mysql/duration.rs:191:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: tikv::coprocessor::codec::mysql::duration::Duration::parse
  10: fuzz_targets::fuzz_coprocessor_codec_duration_from_parse
  11: rust_fuzzer_test_input
  12: __rust_maybe_catch_panic
  13: std::panicking::try
  14: LLVMFuzzerTestOneInput
  15: _ZN6fuzzer6Fuzzer15ExecuteCallbackEPKhm
  16: _ZN6fuzzer6Fuzzer6RunOneEPKhmbPNS_9InputInfoEPb
  17: _ZN6fuzzer6Fuzzer16MutateAndTestOneEv
  18: _ZN6fuzzer6Fuzzer4LoopERKNSt3__16vectorINS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS_16fuzzer_allocatorIS8_EEEE
  19: _ZN6fuzzer12FuzzerDriverEPiPPPcPFiPKhmE
  20: main
==56552== ERROR: libFuzzer: deadly signal
    #0 0x1166d1707 in __sanitizer_print_stack_trace (lib__rustc__clang_rt.asan_osx_dynamic.dylib:x86_64+0x68707)
    #1 0x110bd583b in fuzzer::Fuzzer::CrashCallback() (fuzz_coprocessor_codec_duration_from_parse:x86_64+0x105b7383b)
    #2 0x110bd57ed in fuzzer::Fuzzer::StaticCrashSignalCallback() (fuzz_coprocessor_codec_duration_from_parse:x86_64+0x105b737ed)
    #3 0x110c16437 in fuzzer::CrashHandler(int, __siginfo*, void*) (fuzz_coprocessor_codec_duration_from_parse:x86_64+0x105bb4437)
    #4 0x7fff590abb5c in _sigtramp (libsystem_platform.dylib:x86_64+0x4b5c)
    #5 0x3500000bd0  (<unknown module>)
    #6 0x110c4a7ee in __rust_maybe_catch_panic (fuzz_coprocessor_codec_duration_from_parse:x86_64+0x105be87ee)
    #7 0x110bd3fde in std::panicking::try::hd4964c260fccd748 (fuzz_coprocessor_codec_duration_from_parse:x86_64+0x105b71fde)
    #8 0x110bd3a72 in LLVMFuzzerTestOneInput (fuzz_coprocessor_codec_duration_from_parse:x86_64+0x105b71a72)
    #9 0x110bd6f9a in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (fuzz_coprocessor_codec_duration_from_parse:x86_64+0x105b74f9a)
    #10 0x110bd6999 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) (fuzz_coprocessor_codec_duration_from_parse:x86_64+0x105b74999)
    #11 0x110bd85c1 in fuzzer::Fuzzer::MutateAndTestOne() (fuzz_coprocessor_codec_duration_from_parse:x86_64+0x105b765c1)
    #12 0x110bd9871 in fuzzer::Fuzzer::Loop(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) (fuzz_coprocessor_codec_duration_from_parse:x86_64+0x105b77871)
    #13 0x110c04ab8 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (fuzz_coprocessor_codec_duration_from_parse:x86_64+0x105ba2ab8)
    #14 0x110c27179 in main (fuzz_coprocessor_codec_duration_from_parse:x86_64+0x105bc5179)
    #15 0x7fff58ec63d4 in start (libdyld.dylib:x86_64+0x163d4)

NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 2 ChangeBit-CopyPart-; base unit: 4744b705bce806db21998c6b5c000865f87bf51a
0xff,0x35,0x35,0x35,0x35,0x35,0x35,0x35,0x35,0x30,0x30,0x30,0x30,0x30,0x30,0x30,0x20,0x30,0x30,0x30,0x30,0x30,0x30,0x30,0x30,0x30,0x30,0x30,0x32,0x33,0x35,0x35,0x35,0x0,0x1,
\xff555555550000000 0000000000023555\x00\x01
artifact_prefix='./'; Test unit written to ./crash-eda52eca653e470cf2fed7ad070b4f09e122dab9
Base64: /zU1NTU1NTU1MDAwMDAwMCAwMDAwMDAwMDAwMDIzNTU1AAE=
Running fuzzer failed: Libfuzzer exited with code Some(77)
Error: 1
```

**Comment by iosmanthus** [comment]
From my perspective, the bug is caused by delaying the check of the value of the `hour/minute/second` to `Duration::new`. 
1. the following code never checks the value of `hour/minute/second` until calling `Duration::new`
https://github.com/tikv/tikv/blob/d4f238d09dd3a3d0555d50d8fbcf49e9da6fbb4f/src/coprocessor/codec/mysql/duration.rs#L165-L188
2. do the checking here:
https://github.com/tikv/tikv/blob/d4f238d09dd3a3d0555d50d8fbcf49e9da6fbb4f/src/coprocessor/codec/mysql/duration.rs#L122-L129

I will fix it! Thanks for reminding! 😊

**Comment by iosmanthus** [comment]
Fixed in https://github.com/tikv/tikv/pull/4497, I do the check while parsing the format string.
