### ISSUE TITLE
Running cargo bench causes panic

### ISSUE THREAD

**Issue by rleungx** [tikv/tikv#4766]
```
bench_set/SetConfig { factory: Server, nodes: 1, value_size: 4096 }
                        time:   [114.80 us 117.99 us 122.75 us]
                        change: [-6.6331% -0.9310% +5.2660%] (p = 0.77 > 0.05)
                        No change in performance detected.
Found 2 outliers among 10 measurements (20.00%)
  1 (10.00%) low mild
  1 (10.00%) high mild
Benchmarking bench_set/SetConfig { factory: Server, nodes: 3, value_size: 8 }: Warming up for 3.0000 sthread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic
             at src/libcore/panicking.rs:49
   9: raftstore::prepare_cluster
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libcore/macros.rs:12
             at benches/raftstore/mod.rs:26
  10: <criterion::routine::Function<F,T> as criterion::routine::Routine<T>>::warm_up
             at benches/raftstore/mod.rs:42
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libcore/ops/function.rs:148
             at /rust/registry/src/github.com-1ecc6299db9ec823/criterion-0.2.11/src/routine.rs:169
  11: criterion::routine::Routine::sample
             at /rust/registry/src/github.com-1ecc6299db9ec823/criterion-0.2.11/src/routine.rs:82
  12: raftstore::bench_raft_cluster
             at /rust/registry/src/github.com-1ecc6299db9ec823/criterion-0.2.11/src/analysis/mod.rs:77
             at /rust/registry/src/github.com-1ecc6299db9ec823/criterion-0.2.11/src/benchmark.rs:691
             at /rust/registry/src/github.com-1ecc6299db9ec823/criterion-0.2.11/src/lib.rs:1266
             at /rust/registry/src/github.com-1ecc6299db9ec823/criterion-0.2.11/src/lib.rs:1148
             at benches/raftstore/mod.rs:134
  13: raftstore::main
             at benches/raftstore/mod.rs:178
  14: std::rt::lang_start::{{closure}}
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libstd/rt.rs:64
  15: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  17: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  18: main
  19: __libc_start_main
  20: <unknown>
```

**Comment by zhouqiang-cl** [comment]
@rleungx Did this has been fixed

**Comment by rleungx** [comment]
Can not reproduce in the latest master. I'm going to close it for now and feel free to reopen it if the problem still exists.
