### ISSUE TITLE
test: test_local_read_cache failed

### ISSUE THREAD

**Issue by kennytm** [tikv/tikv#4776]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/4923/pipeline

```
thread 'raftstore::test_lease_read::test_local_read_cache' panicked at 'response header { error { message: "region is not found" region_not_found { region_id: 1 } } } has error', components/test_raftstore/src/cluster.rs:681:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:336
   7: test_raftstore::cluster::Cluster<T>::must_put_cf
             at ./<::std::macros::panic macros>:8
   8: test_raftstore::cluster::Cluster<T>::must_put
             at ./components/test_raftstore/src/cluster.rs:670
   9: integrations::raftstore::test_lease_read::test_local_read_cache
             at tests/integrations/raftstore/test_lease_read.rs:429
  10: integrations::raftstore::test_lease_read::test_local_read_cache::{{closure}}
             at tests/integrations/raftstore/test_lease_read.rs:408
  11: core::ops::function::FnOnce::call_once
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libcore/ops/function.rs:231
  12: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/liballoc/boxed.rs:704
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  14: test::run_test::run_test_inner::{{closure}}
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libstd/panicking.rs:272
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libstd/panic.rs:388
             at src/libtest/lib.rs:1468
test raftstore::test_lease_read::test_local_read_cache ... FAILED
```

```
2019/05/26 19:19:41.665 pd.rs:544: [DEBG] [region 1] schedule AddPeer { peer: Left(id: 10000 store_id: 2), policy: TillSuccess } to id: 2 store_id: 2, region: id: 1 region_epoch { conf_ver: 2 version: 1 } peers { id: 1 store_id: 1 } peers { id: 3 store_id: 3 }
2019/05/26 19:19:41.666 pd.rs:551: [INFO] try to change peer, peer: id: 10000 store_id: 2, change_type: AddNode, region_id: 1
2019/05/26 19:19:41.666 pd.rs:821: [ERRO] send request failed, err: "Disconnected(..)", cmd_type: ChangePeer, region_id: 1
2019/05/26 19:19:42.166 pd.rs:544: [DEBG] [region 1] schedule AddPeer { peer: Left(id: 10000 store_id: 2), policy: TillSuccess } to id: 2 store_id: 2, region: id: 1 region_epoch { conf_ver: 2 version: 1 } peers { id: 1 store_id: 1 } peers { id: 3 store_id: 3 }
2019/05/26 19:19:42.167 pd.rs:551: [INFO] try to change peer, peer: id: 10000 store_id: 2, change_type: AddNode, region_id: 1
2019/05/26 19:19:42.167 pd.rs:821: [ERRO] send request failed, err: "Disconnected(..)", cmd_type: ChangePeer, region_id: 1
```

**Comment by breeswish** [comment]
Meet the same error as well:

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/4948/pipeline

**Comment by kennytm** [comment]
Test case is modified in #4789. Will close next week if no longer reproducible.
