### ISSUE TITLE
test_prevote_partition_leader_in_minority_detect_in_majority failed

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#4902]
## Bug Report

```
thread 'raftstore::test_prevote::test_prevote_partition_leader_in_minority_detect_in_majority' panicked at 'failed to transfer leader to [1] id: 1 store_id: 1', components/test_raftstore/src/cluster.rs:809:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:336
   7: test_raftstore::cluster::Cluster<T>::must_transfer_leader
             at ./<::std::macros::panic macros>:8
   8: integrations::raftstore::test_prevote::test_prevote
             at tests/integrations/raftstore/test_prevote.rs:54
   9: integrations::raftstore::test_prevote::test_prevote_partition_leader_in_minority_detect_in_majority
             at tests/integrations/raftstore/test_prevote.rs:162
  10: integrations::raftstore::test_prevote::test_prevote_partition_leader_in_minority_detect_in_majority::{{closure}}
             at tests/integrations/raftstore/test_prevote.rs:158
  11: core::ops::function::FnOnce::call_once
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libcore/ops/function.rs:231
  12: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/liballoc/boxed.rs:704
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  14: test::run_test::run_test_inner::{{closure}}
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libstd/panicking.rs:272
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libstd/panic.rs:388
             at src/libtest/lib.rs:1468
test raftstore::test_prevote::test_prevote_partition_leader_in_minority_detect_in_majority ... FAILED
test storage::test_storage::test_txn_store_commit_illegal_tso ... ok
```

**Comment by hicqu** [comment]
Seems it's stale. Close it.
