### ISSUE TITLE
Panic on force send commit merge during shutdown 

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#5032]
## Bug Report

During commit merge, target region sends a `MergeResult` to source region and unwrap the result. It causes a panic during shut down, source region may be stopped before target region sends the message.  

     
https://github.com/tikv/tikv/blob/e17843a7a498c94a1db64b2831c911c46de00359/src/raftstore/store/fsm/peer.rs#L1958-L1967

```
thread 'raftstore-2-0::test_node_merge_reject_request_snapshot' panicked at 'called `Result::unwrap()` on an `Err` value: "Disconnected(..)"', src/libcore/result.rs:999:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:212
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:382
   8: rust_begin_unwind
             at src/libstd/panicking.rs:309
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
  11: core::result::Result<T,E>::unwrap
  12: tikv::raftstore::store::fsm::peer::PeerFsmDelegate<T,C>::on_ready_commit_merge
  13: tikv::raftstore::store::fsm::peer::PeerFsmDelegate<T,C>::on_ready_result
  14: tikv::raftstore::store::fsm::peer::PeerFsmDelegate<T,C>::on_apply_res
  15: tikv::raftstore::store::fsm::peer::PeerFsmDelegate<T,C>::handle_msgs
  16: <tikv::raftstore::store::fsm::store::RaftPoller<T,C> as tikv::raftstore::store::fsm::batch::PollHandler<tikv::raftstore::store::fsm::peer::PeerFsm,tikv::raftstore::store::fsm::store::StoreFsm>>::handle_normal
  17: tikv::raftstore::store::fsm::batch::Poller<N,C,Handler>::poll
  18: tikv::raftstore::store::fsm::batch::BatchSystem<N,C>::spawn::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Log: https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/6390/nodes/110/steps/661/log/?start=0

**Comment by Connor1996** [comment]
Fix in https://github.com/tikv/tikv/pull/4595
