### ISSUE TITLE
test: test cases::test_merge::test_node_request_snapshot_reject_merge failed

### ISSUE THREAD

**Issue by 5kbpers** [tikv/tikv#5054]
```
thread 'raftstore-1-0::test_node_request_snapshot_reject_merge' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:999:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:212
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:382
   8: rust_begin_unwind
             at src/libstd/panicking.rs:309
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
  11: core::result::Result<T,E>::unwrap
  12: <test_raftstore::transport_simulate::RecvSnapshotFilter as test_raftstore::transport_simulate::Filter>::before
  13: test_raftstore::transport_simulate::filter_send
  14: <test_raftstore::transport_simulate::SimulateTransport<C> as tikv::server::transport::RaftStoreRouter>::send_raft_msg
  15: <test_raftstore::node::ChannelTransport as tikv::raftstore::store::transport::Transport>::send
  16: <test_raftstore::transport_simulate::SimulateTransport<C> as tikv::raftstore::store::transport::Transport>::send::{{closure}}
  17: test_raftstore::transport_simulate::filter_send
  18: <test_raftstore::transport_simulate::SimulateTransport<C> as tikv::raftstore::store::transport::Transport>::send
  19: tikv::raftstore::store::peer::Peer::send_raft_message
  20: tikv::raftstore::store::peer::Peer::send
  21: tikv::raftstore::store::peer::Peer::handle_raft_ready_append
  22: tikv::raftstore::store::fsm::peer::PeerFsmDelegate<T,C>::collect_ready
  23: <tikv::raftstore::store::fsm::store::RaftPoller<T,C> as tikv::raftstore::store::fsm::batch::PollHandler<tikv::raftstore::store::fsm::peer::PeerFsm,tikv::raftstore::store::fsm::store::StoreFsm>>::handle_normal
  24: tikv::raftstore::store::fsm::batch::Poller<N,C,Handler>::poll
  25: tikv::raftstore::store::fsm::batch::BatchSystem<N,C>::spawn::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'cases::test_merge::test_node_request_snapshot_reject_merge' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/libcore/result.rs:999:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:212
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:382
   8: rust_begin_unwind
             at src/libstd/panicking.rs:309
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
  11: core::result::Result<T,E>::unwrap
  12: tikv::raftstore::store::fsm::batch::BatchSystem<N,C>::shutdown
  13: tikv::raftstore::store::fsm::store::RaftBatchSystem::shutdown
  14: tikv::server::node::Node<C>::stop_store
  15: tikv::server::node::Node<C>::stop
  16: <test_raftstore::node::NodeCluster as test_raftstore::cluster::Simulator>::stop_node
  17: test_raftstore::cluster::Cluster<T>::stop_node
             at ./components/test_raftstore/src/cluster.rs:215
  18: test_raftstore::cluster::Cluster<T>::shutdown
             at ./components/test_raftstore/src/cluster.rs:523
  19: <test_raftstore::cluster::Cluster<T> as core::ops::drop::Drop>::drop
             at ./components/test_raftstore/src/cluster.rs:1019
  20: core::ptr::real_drop_in_place
             at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libcore/ptr/mod.rs:197
  21: failpoints::cases::test_merge::test_node_request_snapshot_reject_merge
             at tests/failpoints/cases/test_merge.rs:470
  22: failpoints::cases::test_merge::test_node_request_snapshot_reject_merge::{{closure}}
             at tests/failpoints/cases/test_merge.rs:434
  23: core::ops::function::FnOnce::call_once
             at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libcore/ops/function.rs:231
  24: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/liballoc/boxed.rs:746
  25: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  26: std::panicking::try
             at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libstd/panicking.rs:273
  27: std::panic::catch_unwind
             at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libstd/panic.rs:388
  28: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:1466
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'raftstore-2-1::test_node_request_snapshot_reject_merge' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:999:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:212
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:382
   8: rust_begin_unwind
             at src/libstd/panicking.rs:309
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
  11: core::result::Result<T,E>::unwrap
  12: <test_raftstore::node::ChannelTransport as tikv::raftstore::store::transport::Transport>::send
  13: <test_raftstore::transport_simulate::SimulateTransport<C> as tikv::raftstore::store::transport::Transport>::send::{{closure}}
  14: test_raftstore::transport_simulate::filter_send
  15: <test_raftstore::transport_simulate::SimulateTransport<C> as tikv::raftstore::store::transport::Transport>::send
  16: tikv::raftstore::store::peer::Peer::send_raft_message
  17: tikv::raftstore::store::peer::Peer::send
  18: tikv::raftstore::store::peer::Peer::post_raft_ready_append
  19: tikv::raftstore::store::fsm::peer::PeerFsmDelegate<T,C>::post_raft_ready_append
  20: tikv::raftstore::store::fsm::store::RaftPoller<T,C>::handle_raft_ready
  21: <tikv::raftstore::store::fsm::store::RaftPoller<T,C> as tikv::raftstore::store::fsm::batch::PollHandler<tikv::raftstore::store::fsm::peer::PeerFsm,tikv::raftstore::store::fsm::store::StoreFsm>>::end
  22: tikv::raftstore::store::fsm::batch::Poller<N,C,Handler>::poll
  23: tikv::raftstore::store::fsm::batch::BatchSystem<N,C>::spawn::{{closure}}
```

**Comment by mapleFU** [comment]
I meet the same problem, and I will list some logs below:

* https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/6492/nodes/110/steps/658/log/?start=0
* https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/6480/nodes/110/steps/596/log/?start=0
