### ISSUE TITLE
test: test server::raft_client::test_raft_client_reconnect failed

### ISSUE THREAD

**Issue by 5kbpers** [tikv/tikv#5073]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/6616/pipeline

```
thread 'server::raft_client::test_raft_client_reconnect' panicked at 'assertion failed: (0..100).map(|_|

                 raft_client.send(1, &addr,

                                  RaftMessage::new())).collect::<Result<(),

                                                                        _>>().is_err()', tests/integrations/server/raft_client.rs:130:5

stack backtrace:

test raftstore::test_split_region::test_server_base_split_region_left_derive ... ok

   0: backtrace::backtrace::libunwind::trace

             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88

   1: backtrace::backtrace::trace_unsynchronized

             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66

   2: std::sys_common::backtrace::_print

             at src/libstd/sys_common/backtrace.rs:47

   3: std::sys_common::backtrace::print

             at src/libstd/sys_common/backtrace.rs:36

   4: std::panicking::default_hook::{{closure}}

             at src/libstd/panicking.rs:198

   5: std::panicking::default_hook

             at src/libstd/panicking.rs:212

   6: std::panicking::rust_panic_with_hook

             at src/libstd/panicking.rs:475

   7: std::panicking::begin_panic

   8: integrations::server::raft_client::test_raft_client_reconnect

             at tests/integrations/server/raft_client.rs:130

   9: integrations::server::raft_client::test_raft_client_reconnect::{{closure}}

             at tests/integrations/server/raft_client.rs:89

  10: core::ops::function::FnOnce::call_once

             at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libcore/ops/function.rs:231

  11: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once

             at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/liballoc/boxed.rs:746

  12: __rust_maybe_catch_panic

             at src/libpanic_unwind/lib.rs:82

  13: std::panicking::try

             at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libstd/panicking.rs:273

  14: std::panic::catch_unwind

             at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libstd/panic.rs:388

  15: test::run_test::run_test_inner::{{closure}}

             at src/libtest/lib.rs:1466
```

**Comment by 5kbpers** [comment]
@zyh-hust PTAL

**Comment by zyh-hust** [comment]
I am modifying
