### ISSUE TITLE
`raftstore::test_multi::test_multi_server_random_restart` spuriously failed

### ISSUE THREAD

**Issue by kennytm** [tikv/tikv#5188]
```
thread 'raftstore::test_multi::test_multi_server_random_restart' panicked at 'can't get value Some("\\000\\353\\367\\207\\376") for key 32', components/test_raftstore/src/util.rs:53:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:212
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:382
   8: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:337
   9: test_raftstore::util::must_get
  10: test_raftstore::util::must_get_equal
  11: integrations::raftstore::test_multi::test_multi_random_restart
             at tests/integrations/raftstore/test_multi.rs:158
  12: integrations::raftstore::test_multi::test_multi_server_random_restart
             at tests/integrations/raftstore/test_multi.rs:298
  13: integrations::raftstore::test_multi::test_multi_server_random_restart::{{closure}}
             at tests/integrations/raftstore/test_multi.rs:295
  14: core::ops::function::FnOnce::call_once
             at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libcore/ops/function.rs:231
  15: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/liballoc/boxed.rs:746
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  17: std::panicking::try
             at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libstd/panicking.rs:273
  18: std::panic::catch_unwind
             at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libstd/panic.rs:388
  19: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:1466
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test raftstore::test_multi::test_multi_server_random_restart ... FAILED
```

Full CI log: https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/7298/nodes/122/log/?start=0

**Comment by zhouqiang-cl** [comment]
Long time no update. I will close it
