### ISSUE TITLE
test storage::test_raft_storage::test_auto_gc panic 

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#5206]
## Bug Report

**What version of TiKV are you using?**

Commit: 995257ddb1c926cfce638663b66c92809064eedd

**What operating system and CPU are you using?**

MacOSX

**What did you do?**

```
make dev
```

**What did you expect to see?**

Test passed

**What did you see instead?**

```
thread 'storage::test_raft_storage::test_auto_gc' panicked at 'assertion failed: value.is_none()', tests/integrations/storage/test_raft_storage.rs:242:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:212
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
   7: <alloc::collections::CollectionAllocErr as core::convert::From<core::alloc::AllocErr>>::from
   8: integrations::storage::test_raft_storage::check_data
             at tests/integrations/storage/test_raft_storage.rs:242
   9: integrations::storage::test_raft_storage::test_auto_gc
             at tests/integrations/storage/test_raft_storage.rs:349
  10: integrations::storage::test_raft_storage::test_auto_gc::{{closure}}
             at tests/integrations/storage/test_raft_storage.rs:248
  11: core::ops::function::FnOnce::call_once
             at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libcore/ops/function.rs:231
  12: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/liballoc/boxed.rs:746
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  14: std::panicking::try
             at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libstd/panicking.rs:273
  15: std::panic::catch_unwind
             at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libstd/panic.rs:388
  16: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:1466
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by MyonKeminta** [comment]
Is there any log?

**Comment by MyonKeminta** [comment]
https://github.com/tikv/tikv/pull/5212 is trying to fix this.
