### ISSUE TITLE
test raftstore::test_merge::test_node_merge_with_slow_learner failed

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#5207]
## Bug Report

**What version of TiKV are you using?**

Commit: 995257ddb1c926cfce638663b66c92809064eedd

**What operating system and CPU are you using?**

MacOSX

**What did you do?**

```
make dev
```

**What did you expect to see?**

Test passed

**What did you see instead?**

```
thread 'raftstore::test_merge::test_node_merge_with_slow_learner' panicked at 'region Some(id: 1 region_epoch {conf_ver: 2 version: 1} peers {id: 1 store_id: 1} peers {id: 1000 store_id: 2}) has no peer id: 2 store_id: 2 is_learner: true', components/test_raftstore/src/pd.rs:734:9
stack backtrace:
test raftstore::test_multi::test_multi_node_latency ... ok
   0: backtrace::backtrace::libunwind::trace
             at /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:212
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:382
   8: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:337
   9: test_raftstore::pd::TestPdClient::schedule_operator
  10: test_raftstore::pd::TestPdClient::schedule_operator
  11: integrations::raftstore::test_merge::test_node_merge_with_slow_learner
             at tests/integrations/raftstore/test_merge.rs:113
  12: integrations::raftstore::test_merge::test_node_merge_with_slow_learner::{{closure}}
             at tests/integrations/raftstore/test_merge.rs:106
test raftstore::test_multi::test_multi_node_random_latency ... ok
  13: core::ops::function::FnOnce::call_once
             at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libcore/ops/function.rs:231
  14: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/liballoc/boxed.rs:746
  15: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  16: std::panicking::try
             at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libstd/panicking.rs:273
  17: std::panic::catch_unwind
             at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libstd/panic.rs:388
  18: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:1466
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by hicqu** [comment]
Closed with #5719.
