### ISSUE TITLE
util::tests::test_delete_all_files_in_range can fail

### ISSUE THREAD

**Issue by sticnarf** [tikv/tikv#5239]
I once ran `make dev` and saw this test failed.

I rerun the test a few times but cannot see the error again. However, I think such a test shouldn't be unstable like the raftstore tests. Perhaps we should be cautious about it because it's possibly a bug in the engine.

Log:

```
     Running target/debug/deps/engine-dbc05506e3da2e40

running 24 tests
test rocks::util::config::compaction_style_serde::tests::test_serde ... ok
test rocks::util::config::compaction_pri_serde::tests::test_serde ... ok
test rocks::util::config::rate_limiter_mode_serde::tests::test_serde ... ok
test rocks::util::config::recovery_mode_serde::tests::test_serde ... ok
test rocks::util::config::tests::test_parse_compression_type ... ok
test rocks::util::io_limiter::tests::test_io_limiter ... ok
test rocks::sst::tests::test_smoke ... ok
test rocks::tests::test_scan ... ok
test rocks::util::security::tests::test_encrypted_env_from_cipher_file ... ok
test rocks::util::tests::test_cfs_diff ... ok
test rocks::tests::test_peekable ... ok
test rocks::tests::test_base ... ok
test rocks::util::tests::test_compression_ratio ... ok
test rocks::util::engine_metrics::tests::test_flush ... ok
test rocks::util::tests::test_prepare_sst_for_ingestion ... ok
test rocks::util::tests::test_prepare_sst_for_ingestion_titan ... ok
test rocks::util::tests::test_compact_files_in_range ... ok
thread 'util::tests::test_delete_all_files_in_range' panicked at 'assertion failed: `(left == right)`
  left: `[107, 52]`,
 right: `[107, 50]`', components/engine/src/util.rs:141:17
stack backtrace:
test rocks::util::io_limiter::tests::test_limit_writer ... ok
test rocks::util::metrics_flusher::tests::test_metrics_flusher ... ok
test util::tests::test_delete_range_prefix_bloom_case ... ok
test rocks::util::tests::test_new_engine_opt ... ok
test util::tests::test_delete_all_in_range_not_use_delete_range ... ok
test util::tests::test_delete_all_in_range_use_delete_range ... ok
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:339
   9: engine::util::tests::check_data
             at components/engine/src/util.rs:141
  10: engine::util::tests::test_delete_all_files_in_range
             at components/engine/src/util.rs:243
  11: engine::util::tests::test_delete_all_files_in_range::{{closure}}
             at components/engine/src/util.rs:209
  12: core::ops::function::FnOnce::call_once
             at /rustc/311376d30dc1cfa622142a9f50317b1e0cb4608a/src/libcore/ops/function.rs:231
  13: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/311376d30dc1cfa622142a9f50317b1e0cb4608a/src/liballoc/boxed.rs:766
  14: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  15: std::panicking::try
             at /rustc/311376d30dc1cfa622142a9f50317b1e0cb4608a/src/libstd/panicking.rs:275
  16: std::panic::catch_unwind
             at /rustc/311376d30dc1cfa622142a9f50317b1e0cb4608a/src/libstd/panic.rs:394
  17: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:1472
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test util::tests::test_delete_all_files_in_range ... FAILED

failures:

failures:
    util::tests::test_delete_all_files_in_range

test result: FAILED. 23 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by zhangjinpeng1987** [comment]
Is this issue still exist?

**Comment by sticnarf** [comment]
It's quite an old issue and I have no way to reproduce it. I'm not sure if it still exists.

**Comment by Little-Wallace** [comment]
I think you can not reproduce it because RocksDB has refactor the code of DeleteRange...

**Comment by Connor1996** [comment]
> I think you can not reproduce it because RocksDB has refactor the code of DeleteRange...

It failed on `delete_files_in_range` not `delete_range`

**Comment by yiwu-arbug** [comment]
Shall we close if this is not reproducible?

**Comment by Connor1996** [comment]
The stack is stale and duplicated with https://github.com/tikv/tikv/issues/7694
