### ISSUE TITLE
decouple gc worker from Storage

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#5398]
## Question

I find that the Storage only bypass `async_gc` function to GC worker for outside GC, so I think it is better to decouple GC worker from Storage and let outside call GC worker directly. 

This can simplify Storage dependence because GC worker depends on raftstore. Maybe this can decrease compiling time too.

**Comment by FateTHarlaown** [comment]
Hi,I'm new in tikv :). 
Does this mean we should move the `GCWorker` from  `Storage` to `Service`, and call it directly in `future_gc` ?

**Comment by siddontang** [comment]
Thanks @FateTHarlaown 

Mostly it is 'Yes', you can have a try. 

You can ask @MyonKeminta for help if necessary.

**Comment by FateTHarlaown** [comment]
@MyonKeminta  I meet some problems and myabe need some advice....
The GCWorker was definded in `src/storage/gc_worker.rs`. To decouple, I think the defination file  should be moved to `src/server/service/` and inited  and called from `Service`, but the test `test_storage_gcworker_busy` was write together with `Storage` in `tests/failponts/cases/test_storage.rs`. I'm not sure how to deal with these cases, maybe create a new test file?

**Comment by MyonKeminta** [comment]
@FateTHarlaown Thansk for your help! Feel free to create new file for it, since it's not suitable for any existing files.

**Comment by MyonKeminta** [comment]
@FateTHarlaown There seems to be an mistake. `GCWorker` can be moved to `src/server` but not `src/server/service`, since `src/server/service` contains only gRPC services, and `GCWorker` is an inner module. Please note it.

**Comment by FateTHarlaown** [comment]
@MyonKeminta Thanks. I realized I made a mistake when I want to move it.......

**Comment by MyonKeminta** [comment]
@FateTHarlaown The structure of the config is being changed in another PR. I suggest you don't change config for now, and leave it for our further work.

**Comment by FateTHarlaown** [comment]
@MyonKeminta I found `SyncTestStorage` also called `Storage:: async_gc` in `SyncTestStorage::gc`. At fist, I thougt it was also a kind of  `Storage`(for test)  and try to move `gc` outside，but I found it was depended by many tests  and I must change a lot to do this . I don't how to deal with  `SyncTestStorage`, mybe just add `GCWorker` member to it，and directly `GCWorker` rather its `Storage` member ?

**Comment by MyonKeminta** [comment]
If it's hard to remove `SyncTestStorage::gc`, I think it's ok to add GCWorker member to SyncTestStorage. At least I think it's ok in your first PR (to reduce the PR's size). If necessary, we can continue refactoring `SyncTestStorage` later.

**Comment by FateTHarlaown** [comment]
@MyonKeminta I found it can't pass the test `test_client_stop`. I have no idea about the reason ,  so I check out  master branch, but it failed  again. Does this case has some requirements for my local environment?

**Comment by MyonKeminta** [comment]
@overvenus PTAL about the failing test

**Comment by overvenus** [comment]
Hi @FateTHarlaown 

The test failed due to receive request timeout, usually it should be fast, less than 100ms. I don't have any idea why it fails, could you paste the test log?

**Comment by FateTHarlaown** [comment]
@overvenus Thanks a lot for your help!
I run `make dev` in master branch, git status is 
```
 ~/src/tikv   master ⍟1  git status                                                                                                                                                                                                        2 ↵  10:23:10
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

`make dev` output is 
```
 ~/src/tikv   master ⍟1  make dev                                                                                                                                                                                                SIGPIPE(13) ↵  10:28:06
info: component 'rustfmt' for target 'x86_64-apple-darwin' is up to date
info: component 'clippy' for target 'x86_64-apple-darwin' is up to date
    Finished dev [unoptimized + debuginfo] target(s) in 0.72s
export DYLD_LIBRARY_PATH=":/lib" && \
	export LOG_LEVEL=DEBUG && \
	export RUST_BACKTRACE=1 && \
	cargo test --no-default-features --features " jemalloc sse failpoints" --all  -- --nocapture && \
	cargo test --no-default-features --features " jemalloc sse failpoints" --all --bench misc  -- --nocapture  && \
	if [[ "`uname`" == "Linux" ]]; then \
		export MALLOC_CONF=prof:true,prof_active:false && \
		cargo test --no-default-features --features " jemalloc sse failpoints,mem-profiling"  --bin tikv-server -- --nocapture --ignored; \
	fi
    Finished dev [unoptimized + debuginfo] target(s) in 0.43s
     Running target/debug/deps/backup-e8071beaaab64e1c

running 9 tests
test endpoint::tests::test_cancel ... ok
test endpoint::tests::test_scan_error ... ok
test endpoint::tests::test_adjust_thread_pool_size ... ok
test endpoint::tests::test_seek_range ... ok
test endpoint::tests::test_thread_pool_shutdown_when_idle ... ok
test writer::tests::test_writer ... ok
test endpoint::tests::test_handle_backup_task ... ok
thread 'service::tests::test_client_stop' panicked at 'called `Result::unwrap()` on an `Err` value: Timeout', src/libcore/result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  11: core::result::Result<T,E>::unwrap
             at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/result.rs:933
  12: backup::service::tests::test_client_stop
             at components/backup/src/service.rs:149
  13: backup::service::tests::test_client_stop::{{closure}}
             at components/backup/src/service.rs:107
  14: core::ops::function::FnOnce::call_once
             at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/ops/function.rs:227
  15: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/liballoc/boxed.rs:922
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  17: std::panicking::try
             at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panicking.rs:275
  18: std::panic::catch_unwind
             at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panic.rs:394
  19: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:1413
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test service::tests::test_client_stop ... FAILED
test endpoint::tests::test_busy ... ok

failures:

failures:
    service::tests::test_client_stop

test result: FAILED. 8 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```
I can't find some information about the reason.

**Comment by FateTHarlaown** [comment]
@overvenus  I fetched the latest master branch and moved the repo to a ubuntu pc, then it passed the tests. It seems that this was caused by my local mac os environment(though I have not find the reason...).

**Comment by overvenus** [comment]
@FateTHarlaown 

It occurred to me that the timeout may be caused by the env var `http_proxy`!

```bash
$ http_proxy=http://127.0.0.1:1234 cargo test -p backup
    Finished dev [unoptimized + debuginfo] target(s) in 0.25s
     Running /home/stn/tikv/target/debug/deps/backup-819e20533e8a5c6b

running 9 tests
test endpoint::tests::test_adjust_thread_pool_size ... ok
test endpoint::tests::test_cancel ... ok
test endpoint::tests::test_handle_backup_task ... ok
test endpoint::tests::test_scan_error ... ok
test endpoint::tests::test_seek_range ... ok
test endpoint::tests::test_thread_pool_shutdown_when_idle ... ok
test endpoint::tests::test_busy ... ok
test service::tests::test_client_stop ... FAILED
test writer::tests::test_writer ... ok

failures:

---- service::tests::test_client_stop stdout ----
thread 'service::tests::test_client_stop' panicked at 'called `Result::unwrap()` on an `Err` value: Timeout', src/libcore/result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
``` 

You can try `unset http_proxy` before running `make dev`.
