### ISSUE TITLE
unstable test: cases::test_replica_read::test_wait_for_apply_index'

### ISSUE THREAD

**Issue by disksing** [tikv/tikv#5467]
I ran into it in a unrelated PR. Detail is here: https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/9016/pipeline

```
thread 'cases::test_replica_read::test_wait_for_apply_index' panicked at 'region Some(id: 1 region_epoch { conf_ver: 2 version: 1 } peers { id: 1 store_id: 1 } peers { id: 2 store_id: 2 }) has no peer id: 3 store_id: 3', components/test_raftstore/src/pd.rs:749:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:339
   9: test_raftstore::pd::TestPdClient::must_have_peer
             at components/test_raftstore/src/pd.rs:749
  10: test_raftstore::pd::TestPdClient::must_add_peer
             at components/test_raftstore/src/pd.rs:845
  11: failpoints::cases::test_replica_read::test_wait_for_apply_index
             at tests/failpoints/cases/test_replica_read.rs:29
  12: failpoints::cases::test_replica_read::test_wait_for_apply_index::{{closure}}
             at tests/failpoints/cases/test_replica_read.rs:15
  13: core::ops::function::FnOnce::call_once
             at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/ops/function.rs:227
  14: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/liballoc/boxed.rs:922
  15: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  16: std::panicking::try
             at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panicking.rs:275
  17: std::panic::catch_unwind
             at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panic.rs:394
  18: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:1413
```

[internal.pingcap.net.txt](https://github.com/tikv/tikv/files/3616199/internal.pingcap.net.txt)

**Comment by NingLin-P** [comment]
The test was panicked at `must_add_peer` of peer 3, and not even enter the test logic! And the test panicked because peer 2 bind to the same port as peer 1 (maybe because the grpc server of peer 1 drop silently), and msg that peer 2 send to peer 1 were eventually received by itself. Which cause conf change request are alway rejected.

some log:
```
node.rs:159: [INFO] put store to PD, store: id: 1 address: "127.0.0.1:44505" version: "4.0.0-alpha"
node.rs:159: [INFO] put store to PD, store: id: 2 address: "127.0.0.1:44505" version: "4.0.0-alpha"
peer.rs:853: [DEBG] handle raft message, to_peer_id: 1, from_peer_id: 2, message_type: MsgHeartbeatResponse, peer_id: 2, region_id: 1
peer.rs:933: [WARN] store not match, ignore it, my_store_id: 2, to_store_id: 1, region_id: 1
```

**Comment by NingLin-P** [comment]
Close this issue, because it is duplicated with https://github.com/tikv/tikv/issues/7184
