### ISSUE TITLE
test_merge_with_slow_promote fails

### ISSUE THREAD

**Issue by tabokie** [tikv/tikv#5484]
unit test failure at local server disappears in CI. Test runs on local branch which makes no modification to raftstore module. That said, a good unit test should always break deterministically.

**branch**: https://github.com/tabokie/tikv/tree/5babe2fe05657c19bbd926ea82bc29ad3c7f38b8 (from #5382)
**trace**:

```
thread 'raftstore::test_merge::test_merge_with_slow_promote' panicked at 'assertion failed: `(left == right)`
  left: `InvalidAdmin`,
 right: `TransferLeader`: header { error { message: "EpochNotMatch current epoch of region 1000 is conf_ver: 3 version: 2, but you sent conf_ver: 3 version: 4" epoch_not_match { current_regions { id: 1000 end_key: 6B32 region_epoch { conf_ver: 3 version: 2 } peers { id: 1001 store_id: 1 } peers { id: 1002 store_id: 2 } peers { id: 1003 store_id: 3 } } current_regions { id: 1000 end_key: 6B32 region_epoch { conf_ver: 3 version: 2 } peers { id: 1001 store_id: 1 } peers { id: 1002 store_id: 2 } peers { id: 1003 store_id: 3 } } } } }', components/test_raftstore/src/cluster.rs:799:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:339
   9: test_raftstore::cluster::Cluster<T>::transfer_leader
             at ./<::std::macros::panic macros>:9
  10: test_raftstore::cluster::Cluster<T>::must_transfer_leader
             at ./components/test_raftstore/src/cluster.rs:817
  11: integrations::raftstore::test_merge::test_merge_with_slow_promote
             at tests/integrations/raftstore/test_merge.rs:734
  12: integrations::raftstore::test_merge::test_merge_with_slow_promote::{{closure}}
             at tests/integrations/raftstore/test_merge.rs:705
  13: core::ops::function::FnOnce::call_once
             at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/ops/function.rs:227
  14: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/liballoc/boxed.rs:922
  15: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  16: std::panicking::try
             at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panicking.rs:275
  17: std::panic::catch_unwind
             at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panic.rs:394
  18: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:1413
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by tabokie** [comment]
dup

**Comment by gengliqi** [comment]
close because it's too old.
