### ISSUE TITLE
storage::test_raft_storage::test_auto_gc, panicked at 'called `Result::unwrap()` on an `Err` value: Txn(Engine(Request(message: "stale command")))', src/libcore/result.rs:1165:5

### ISSUE THREAD

**Issue by H-ZeX** [tikv/tikv#5499]
The log is here 
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/9145/pipeline/142/

**Comment by tabokie** [comment]
[Another failure](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/10196/pipeline/145):
```
[2019-10-15T06:37:24.788Z] thread 'storage::test_raft_storage::test_auto_gc' panicked at 'called `Result::unwrap()` on an `Err` value: Txn(Engine(Request(message: "stale command")))', src/libcore/result.rs:1165:5
[2019-10-15T06:37:24.788Z] stack backtrace:
[2019-10-15T06:37:25.718Z]    0: backtrace::backtrace::libunwind::trace
[2019-10-15T06:37:25.718Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
[2019-10-15T06:37:25.718Z]    1: backtrace::backtrace::trace_unsynchronized
[2019-10-15T06:37:25.718Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
[2019-10-15T06:37:25.718Z]    2: std::sys_common::backtrace::_print
[2019-10-15T06:37:25.718Z]              at src/libstd/sys_common/backtrace.rs:47
[2019-10-15T06:37:25.718Z]    3: std::sys_common::backtrace::print
[2019-10-15T06:37:25.718Z]              at src/libstd/sys_common/backtrace.rs:36
[2019-10-15T06:37:25.718Z]    4: std::panicking::default_hook::{{closure}}
[2019-10-15T06:37:25.718Z]              at src/libstd/panicking.rs:200
[2019-10-15T06:37:25.718Z]    5: std::panicking::default_hook
[2019-10-15T06:37:25.718Z]              at src/libstd/panicking.rs:214
[2019-10-15T06:37:25.718Z]    6: std::panicking::rust_panic_with_hook
[2019-10-15T06:37:25.718Z]              at src/libstd/panicking.rs:477
[2019-10-15T06:37:25.718Z]    7: std::panicking::continue_panic_fmt
[2019-10-15T06:37:25.718Z]              at src/libstd/panicking.rs:384
[2019-10-15T06:37:25.718Z]    8: rust_begin_unwind
[2019-10-15T06:37:25.718Z]              at src/libstd/panicking.rs:311
[2019-10-15T06:37:25.718Z]    9: core::panicking::panic_fmt
[2019-10-15T06:37:25.718Z]              at src/libcore/panicking.rs:85
[2019-10-15T06:37:25.718Z]   10: core::result::unwrap_failed
[2019-10-15T06:37:25.718Z]              at src/libcore/result.rs:1165
[2019-10-15T06:37:25.718Z]   11: core::result::Result<T,E>::unwrap
[2019-10-15T06:37:25.718Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/result.rs:933
[2019-10-15T06:37:25.718Z]   12: integrations::storage::test_raft_storage::check_data
[2019-10-15T06:37:25.718Z]              at tests/integrations/storage/test_raft_storage.rs:236
[2019-10-15T06:37:25.718Z]   13: integrations::storage::test_raft_storage::test_auto_gc
[2019-10-15T06:37:25.718Z]              at tests/integrations/storage/test_raft_storage.rs:336
[2019-10-15T06:37:25.718Z]   14: integrations::storage::test_raft_storage::test_auto_gc::{{closure}}
[2019-10-15T06:37:25.718Z]              at tests/integrations/storage/test_raft_storage.rs:248
[2019-10-15T06:37:25.718Z]   15: core::ops::function::FnOnce::call_once
[2019-10-15T06:37:25.718Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/ops/function.rs:227
[2019-10-15T06:37:25.718Z]   16: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
[2019-10-15T06:37:25.718Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/liballoc/boxed.rs:922
[2019-10-15T06:37:25.718Z]   17: __rust_maybe_catch_panic
[2019-10-15T06:37:25.718Z]              at src/libpanic_unwind/lib.rs:80
[2019-10-15T06:37:25.718Z]   18: std::panicking::try
[2019-10-15T06:37:25.718Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panicking.rs:275
[2019-10-15T06:37:25.718Z]   19: std::panic::catch_unwind
[2019-10-15T06:37:25.718Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panic.rs:394
[2019-10-15T06:37:25.718Z]   20: test::run_test::run_test_inner::{{closure}}
[2019-10-15T06:37:25.718Z]              at src/libtest/lib.rs:1413
[2019-10-15T06:37:25.718Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2019-10-15T06:37:32.278Z] test storage::test_raft_storage::test_auto_gc ... FAILED
```

**Comment by tabokie** [comment]
duplicate with #6400, closing it now.
