### ISSUE TITLE
test pd::tests::test_collect_stats failed 

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#5579]
## Bug Report

```
thread 'raftstore::store::worker::pd::tests::test_collect_stats' panicked at 'assertion failed: total_cpu_usages > 90', src/raftstore/store/worker/pd.rs:1106:9
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::default_hook
   2: panic_hook::track_hook::{{closure}}
   3: core::num::<impl usize>::overflowing_mul
   4: core::num::<impl usize>::overflowing_mul
   5: panic_hook::track_hook
   6: core::ops::function::Fn::call
   7: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
   8: aho_corasick::packed::teddy::runtime::Teddy::verify_bucket::match_from_span
   9: tikv::raftstore::store::worker::pd::tests::test_collect_stats
             at src/raftstore/store/worker/pd.rs:1106
  10: tikv::raftstore::store::worker::pd::tests::test_collect_stats::{{closure}}
             at src/raftstore/store/worker/pd.rs:1092
  11: core::ops::function::FnOnce::call_once
             at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/ops/function.rs:227
  12: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/liballoc/boxed.rs:922
  13: panic_unwind::dwarf::eh::read_encoded_pointer
  14: std::panicking::try
             at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panicking.rs:275
  15: std::panic::catch_unwind
             at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panic.rs:394
  16: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:1413
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by nolouch** [comment]
@lhy1024 Can you take a look?

**Comment by lhy1024** [comment]
I am very sorry that I didn't find the panic after 2000 times tests by a script. It is difficult to recurrent. 
In theory, It is valid to read `total_cpu_usages` from proc file, and the interval is sufficient to obtain the information. 
Do we have more info about the panic?

**Comment by MyonKeminta** [comment]
It may easily fail when CPU resource is not enough. For example, I tries to run it in a 1 core VM, while running the shell command `while true; do :; done` in another terminal, then I always got:
```
$ ./raftstore-9068f28701cac9b7  test_collect_stats

running 1 test
test store::worker::pd::tests::test_collect_stats ... FAILED

failures:

---- store::worker::pd::tests::test_collect_stats stdout ----
thread 'main' panicked at 'expect cpu usage > 90, got 49', components/raftstore/src/store/worker/pd.rs:1408:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    store::worker::pd::tests::test_collect_stats

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 123 filtered out
```

I think this is the problem. @lhy1024 
...and I'm not sure if it's really a problem.

**Comment by MyonKeminta** [comment]
I think if it rarely or never happens in our CI environment, we can just ignore it. I can't come out with any idea to make this test more stable, except to make sure there's enough CPU in CI environment.
