### ISSUE TITLE
test_backup_and_import failed

### ISSUE THREAD

**Issue by zhouqiang-cl** [tikv/tikv#5601]
2019-10-09T09:45:59.358Z] thread 'test_backup::test_backup_and_import' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1165:5

[2019-10-09T09:45:59.358Z] stack backtrace:

[2019-10-09T09:45:59.358Z]    0: backtrace::backtrace::libunwind::trace

[2019-10-09T09:45:59.358Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88

[2019-10-09T09:45:59.358Z]    1: backtrace::backtrace::trace_unsynchronized

[2019-10-09T09:45:59.358Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66

[2019-10-09T09:45:59.358Z]    2: std::sys_common::backtrace::_print

[2019-10-09T09:45:59.358Z]              at src/libstd/sys_common/backtrace.rs:47

[2019-10-09T09:45:59.358Z]    3: std::sys_common::backtrace::print

[2019-10-09T09:45:59.358Z]              at src/libstd/sys_common/backtrace.rs:36

[2019-10-09T09:45:59.358Z]    4: std::panicking::default_hook::{{closure}}

[2019-10-09T09:45:59.358Z]              at src/libstd/panicking.rs:200

[2019-10-09T09:45:59.358Z]    5: std::panicking::default_hook

[2019-10-09T09:45:59.358Z]              at src/libstd/panicking.rs:214

[2019-10-09T09:45:59.358Z]    6: std::panicking::rust_panic_with_hook

[2019-10-09T09:45:59.358Z]              at src/libstd/panicking.rs:477

[2019-10-09T09:45:59.358Z]    7: std::panicking::continue_panic_fmt

[2019-10-09T09:45:59.358Z]              at src/libstd/panicking.rs:384

[2019-10-09T09:45:59.358Z]    8: rust_begin_unwind

[2019-10-09T09:45:59.358Z]              at src/libstd/panicking.rs:311

[2019-10-09T09:45:59.358Z]    9: core::panicking::panic_fmt

[2019-10-09T09:45:59.358Z]              at src/libcore/panicking.rs:85

[2019-10-09T09:45:59.358Z]   10: core::result::unwrap_failed

[2019-10-09T09:45:59.358Z]              at src/libcore/result.rs:1165

[2019-10-09T09:45:59.358Z]   11: core::result::Result<T,E>::unwrap

[2019-10-09T09:45:59.358Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/result.rs:933

[2019-10-09T09:45:59.358Z]   12: test_util::logging::init_log_for_test::{{closure}}

[2019-10-09T09:45:59.358Z]              at components/test_util/src/logging.rs:99

[2019-10-09T09:45:59.358Z]   13: core::option::Option<T>::map

[2019-10-09T09:45:59.358Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/option.rs:447

[2019-10-09T09:45:59.358Z]   14: test_util::logging::init_log_for_test

[2019-10-09T09:45:59.358Z]              at components/test_util/src/logging.rs:99

[2019-10-09T09:45:59.358Z]   15: integrations::init::{{closure}}

[2019-10-09T09:45:59.358Z]              at components/backup/tests/integrations/mod.rs:9

[2019-10-09T09:45:59.358Z]   16: std::sync::once::Once::call_once::{{closure}}

[2019-10-09T09:45:59.358Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/sync/once.rs:225

[2019-10-09T09:45:59.358Z]   17: std::sync::once::Once::call_inner

[2019-10-09T09:45:59.358Z]              at src/libstd/sync/once.rs:392

[2019-10-09T09:45:59.358Z]   18: std::sync::once::Once::call_once

[2019-10-09T09:45:59.358Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/sync/once.rs:225

[2019-10-09T09:45:59.358Z]   19: integrations::init

[2019-10-09T09:45:59.358Z]              at components/backup/tests/integrations/mod.rs:8

[2019-10-09T09:45:59.358Z]   20: integrations::test_backup::TestSuite::new

[2019-10-09T09:45:59.358Z]              at components/backup/tests/integrations/test_backup.rs:37

[2019-10-09T09:45:59.358Z]   21: integrations::test_backup::test_backup_and_import

[2019-10-09T09:45:59.358Z]              at components/backup/tests/integrations/test_backup.rs:162

[2019-10-09T09:45:59.358Z]   22: integrations::test_backup::test_backup_and_import::{{closure}}

[2019-10-09T09:45:59.358Z]              at components/backup/tests/integrations/test_backup.rs:161

[2019-10-09T09:45:59.358Z]   23: core::ops::function::FnOnce::call_once

[2019-10-09T09:45:59.358Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/ops/function.rs:227

[2019-10-09T09:45:59.358Z]   24: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once

[2019-10-09T09:45:59.358Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/liballoc/boxed.rs:922

[2019-10-09T09:45:59.358Z]   25: __rust_maybe_catch_panic

[2019-10-09T09:45:59.358Z]              at src/libpanic_unwind/lib.rs:80

[2019-10-09T09:45:59.358Z]   26: std::panicking::try

[2019-10-09T09:45:59.358Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panicking.rs:275

[2019-10-09T09:45:59.358Z]   27: std::panic::catch_unwind

[2019-10-09T09:45:59.358Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panic.rs:394

[2019-10-09T09:45:59.358Z]   28: test::run_test::run_test_inner::{{closure}}

[2019-10-09T09:45:59.358Z]              at src/libtest/lib.rs:1413

[2019-10-09T09:45:59.358Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

[2019-10-09T09:45:59.358Z] test test_backup::test_backup_and_import ... FAILED

**Comment by zhouqiang-cl** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/9970/pipeline/

**Comment by overvenus** [comment]
The actual backtrace:
```
[2019-10-11T03:25:30.233Z] running 1 test
[2019-10-11T03:25:31.185Z] thread 'test_backup::test_backup_and_import' panicked at 'message: "stale command"', components/backup/tests/integrations/test_backup.rs:100:9
[2019-10-11T03:25:31.185Z] stack backtrace:
[2019-10-11T03:25:31.747Z]    0: backtrace::backtrace::libunwind::trace
[2019-10-11T03:25:31.747Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
[2019-10-11T03:25:31.747Z]    1: backtrace::backtrace::trace_unsynchronized
[2019-10-11T03:25:31.747Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
[2019-10-11T03:25:31.747Z]    2: std::sys_common::backtrace::_print
[2019-10-11T03:25:31.747Z]              at src/libstd/sys_common/backtrace.rs:47
[2019-10-11T03:25:31.747Z]    3: std::sys_common::backtrace::print
[2019-10-11T03:25:31.747Z]              at src/libstd/sys_common/backtrace.rs:36
[2019-10-11T03:25:31.747Z]    4: std::panicking::default_hook::{{closure}}
[2019-10-11T03:25:31.747Z]              at src/libstd/panicking.rs:200
[2019-10-11T03:25:31.747Z]    5: std::panicking::default_hook
[2019-10-11T03:25:31.747Z]              at src/libstd/panicking.rs:214
[2019-10-11T03:25:31.747Z]    6: std::panicking::rust_panic_with_hook
[2019-10-11T03:25:31.747Z]              at src/libstd/panicking.rs:477
[2019-10-11T03:25:31.747Z]    7: std::panicking::continue_panic_fmt
[2019-10-11T03:25:31.747Z]              at src/libstd/panicking.rs:384
[2019-10-11T03:25:31.747Z]    8: std::panicking::begin_panic_fmt
[2019-10-11T03:25:31.747Z]              at src/libstd/panicking.rs:339
[2019-10-11T03:25:31.747Z]    9: integrations::test_backup::TestSuite::must_kv_prewrite
[2019-10-11T03:25:31.747Z]              at components/backup/tests/integrations/test_backup.rs:100
[2019-10-11T03:25:31.747Z]   10: integrations::test_backup::test_backup_and_import
[2019-10-11T03:25:31.747Z]              at components/backup/tests/integrations/test_backup.rs:175
[2019-10-11T03:25:31.747Z]   11: integrations::test_backup::test_backup_and_import::{{closure}}
[2019-10-11T03:25:31.747Z]              at components/backup/tests/integrations/test_backup.rs:161
[2019-10-11T03:25:31.747Z]   12: core::ops::function::FnOnce::call_once
[2019-10-11T03:25:31.748Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/ops/function.rs:227
[2019-10-11T03:25:31.748Z]   13: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
[2019-10-11T03:25:31.748Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/liballoc/boxed.rs:922
[2019-10-11T03:25:31.748Z]   14: __rust_maybe_catch_panic
[2019-10-11T03:25:31.748Z]              at src/libpanic_unwind/lib.rs:80
[2019-10-11T03:25:31.748Z]   15: std::panicking::try
[2019-10-11T03:25:31.748Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panicking.rs:275
[2019-10-11T03:25:31.748Z]   16: std::panic::catch_unwind
[2019-10-11T03:25:31.748Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panic.rs:394
[2019-10-11T03:25:31.748Z]   17: test::run_test::run_test_inner::{{closure}}
[2019-10-11T03:25:31.748Z]              at src/libtest/lib.rs:1413
[2019-10-11T03:25:31.748Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2019-10-11T03:25:31.748Z] test test_backup::test_backup_and_import ... FAILED
[2019-10-11T03:25:31.748Z] 
[2019-10-11T03:25:31.748Z] failures:
[2019-10-11T03:25:31.748Z] 
[2019-10-11T03:25:31.748Z] failures:
[2019-10-11T03:25:31.748Z]     test_backup::test_backup_and_import
```

Cc @NingLin-P
