### ISSUE TITLE
raftstore::test_conf_change::test_server_split_brain panick

### ISSUE THREAD

**Issue by H-ZeX** [tikv/tikv#5602]
raftstore::test_conf_change::test_server_split_brain

```
[2020-03-09T11:00:46.124Z] test raftstore::test_conf_change::test_server_split_brain ... thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Other("[components/test_raftstore/src/cluster.rs:287]: can\'t get leader of region 1")', src/libcore/result.rs:1188:5

[2020-03-09T11:00:46.124Z] stack backtrace:

[2020-03-09T11:00:46.124Z]    0: backtrace::backtrace::libunwind::trace

[2020-03-09T11:00:46.124Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88

[2020-03-09T11:00:46.124Z]    1: backtrace::backtrace::trace_unsynchronized

[2020-03-09T11:00:46.124Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66

[2020-03-09T11:00:46.124Z]    2: std::sys_common::backtrace::_print_fmt

[2020-03-09T11:00:46.124Z]              at src/libstd/sys_common/backtrace.rs:84

[2020-03-09T11:00:46.124Z]    3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt

[2020-03-09T11:00:46.124Z]              at src/libstd/sys_common/backtrace.rs:61

[2020-03-09T11:00:46.124Z]    4: core::fmt::write

[2020-03-09T11:00:46.124Z]              at src/libcore/fmt/mod.rs:1025

[2020-03-09T11:00:46.124Z]    5: std::io::Write::write_fmt

[2020-03-09T11:00:46.124Z]              at src/libstd/io/mod.rs:1426

[2020-03-09T11:00:46.124Z]    6: std::sys_common::backtrace::_print

[2020-03-09T11:00:46.124Z]              at src/libstd/sys_common/backtrace.rs:65

[2020-03-09T11:00:46.124Z]    7: std::sys_common::backtrace::print

[2020-03-09T11:00:46.124Z]              at src/libstd/sys_common/backtrace.rs:50

[2020-03-09T11:00:46.124Z]    8: std::panicking::default_hook::{{closure}}

[2020-03-09T11:00:46.124Z]              at src/libstd/panicking.rs:193

[2020-03-09T11:00:46.124Z]    9: std::panicking::default_hook

[2020-03-09T11:00:46.125Z]              at src/libstd/panicking.rs:210

[2020-03-09T11:00:46.125Z]   10: std::panicking::rust_panic_with_hook

[2020-03-09T11:00:46.125Z]              at src/libstd/panicking.rs:471

[2020-03-09T11:00:46.125Z]   11: rust_begin_unwind

[2020-03-09T11:00:46.125Z]              at src/libstd/panicking.rs:375

[2020-03-09T11:00:46.125Z]   12: core::panicking::panic_fmt

[2020-03-09T11:00:46.125Z]              at src/libcore/panicking.rs:84

[2020-03-09T11:00:46.125Z]   13: core::result::unwrap_failed

[2020-03-09T11:00:46.125Z]              at src/libcore/result.rs:1188

[2020-03-09T11:00:46.125Z]   14: core::result::Result<T,E>::unwrap

[2020-03-09T11:00:46.125Z]   15: test_raftstore::cluster::Cluster<T>::request

[2020-03-09T11:00:46.125Z]   16: test_raftstore::cluster::Cluster<T>::must_put_cf

[2020-03-09T11:00:46.125Z]              at ./components/test_raftstore/src/cluster.rs:685

[2020-03-09T11:00:46.125Z]   17: test_raftstore::cluster::Cluster<T>::must_put

[2020-03-09T11:00:46.125Z]              at ./components/test_raftstore/src/cluster.rs:681

[2020-03-09T11:00:46.125Z]   18: integrations::raftstore::test_conf_change::test_split_brain

[2020-03-09T11:00:46.125Z]              at tests/integrations/raftstore/test_conf_change.rs:439

[2020-03-09T11:00:46.125Z]   19: integrations::raftstore::test_conf_change::test_server_split_brain

[2020-03-09T11:00:46.125Z]              at tests/integrations/raftstore/test_conf_change.rs:498

[2020-03-09T11:00:46.125Z]   20: integrations::raftstore::test_conf_change::test_server_split_brain::{{closure}}

[2020-03-09T11:00:46.125Z]              at tests/integrations/raftstore/test_conf_change.rs:495

[2020-03-09T11:00:46.125Z]   21: core::ops::function::FnOnce::call_once

[2020-03-09T11:00:46.125Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ops/function.rs:232

[2020-03-09T11:00:46.125Z]   22: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once

[2020-03-09T11:00:46.125Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/liballoc/boxed.rs:1022

[2020-03-09T11:00:46.125Z]   23: __rust_maybe_catch_panic

[2020-03-09T11:00:46.125Z]              at src/libpanic_unwind/lib.rs:78

[2020-03-09T11:00:46.125Z]   24: std::panicking::try

[2020-03-09T11:00:46.125Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panicking.rs:270

[2020-03-09T11:00:46.125Z]   25: std::panic::catch_unwind

[2020-03-09T11:00:46.125Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panic.rs:394

[2020-03-09T11:00:46.125Z]   26: test::run_test_in_process

[2020-03-09T11:00:46.125Z]              at src/libtest/lib.rs:567

[2020-03-09T11:00:46.125Z]   27: test::run_test::run_test_inner::{{closure}}

[2020-03-09T11:00:46.125Z]              at src/libtest/lib.rs:474

[2020-03-09T11:00:46.125Z]   28: test::run_test::run_test_inner

[2020-03-09T11:00:46.125Z]              at src/libtest/lib.rs:495

[2020-03-09T11:00:46.125Z]   29: test::run_test

[2020-03-09T11:00:46.125Z]              at src/libtest/lib.rs:531

[2020-03-09T11:00:46.125Z]   30: test::run_tests

[2020-03-09T11:00:46.125Z]              at src/libtest/lib.rs:300

[2020-03-09T11:00:46.125Z]   31: test::console::run_tests_console

[2020-03-09T11:00:46.125Z]              at src/libtest/console.rs:295

[2020-03-09T11:00:46.125Z]   32: test::test_main

[2020-03-09T11:00:46.125Z]              at src/libtest/lib.rs:121

[2020-03-09T11:00:46.125Z]   33: test::test_main_static

[2020-03-09T11:00:46.125Z]              at src/libtest/lib.rs:140

[2020-03-09T11:00:46.125Z]   34: integrations::main

[2020-03-09T11:00:46.125Z]   35: std::rt::lang_start::{{closure}}

[2020-03-09T11:00:46.125Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/rt.rs:67

[2020-03-09T11:00:46.125Z]   36: std::rt::lang_start_internal::{{closure}}

[2020-03-09T11:00:46.125Z]              at src/libstd/rt.rs:52

[2020-03-09T11:00:46.125Z]   37: std::panicking::try::do_call

[2020-03-09T11:00:46.125Z]              at src/libstd/panicking.rs:292

[2020-03-09T11:00:46.125Z]   38: __rust_maybe_catch_panic

[2020-03-09T11:00:46.125Z]              at src/libpanic_unwind/lib.rs:78

[2020-03-09T11:00:46.125Z]   39: std::panicking::try

[2020-03-09T11:00:46.125Z]              at src/libstd/panicking.rs:270

[2020-03-09T11:00:46.125Z]   40: std::panic::catch_unwind

[2020-03-09T11:00:46.125Z]              at src/libstd/panic.rs:394

[2020-03-09T11:00:46.125Z]   41: std::rt::lang_start_internal

[2020-03-09T11:00:46.125Z]              at src/libstd/rt.rs:51

[2020-03-09T11:00:46.125Z]   42: std::rt::lang_start

[2020-03-09T11:00:46.125Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/rt.rs:67

[2020-03-09T11:00:46.125Z]   43: main

[2020-03-09T11:00:46.125Z]   44: __libc_start_main

[2020-03-09T11:00:46.125Z]   45: <unknown>

[2020-03-09T11:00:46.125Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

[2020-03-09T11:00:46.125Z] FAILED

[2020-03-09T11:00:47.538Z] test raftstore::test_multi::test_multi_server_leader_crash ... ok

[2020-03-09T11:00:47.796Z] test raftstore::test_service::test_mvcc_basic ... ok

[2020-03-09T11:01:00.146Z] test raftstore::test_split_region::test_server_auto_split_region ... ok

[2020-03-09T11:01:22.047Z] test server::lock_manager::test_detect_deadlock_when_transfer_region ... ok

[2020-03-09T11:01:22.047Z] 

[2020-03-09T11:01:22.047Z] failures:

[2020-03-09T11:01:22.047Z] 

[2020-03-09T11:01:22.047Z] failures:

[2020-03-09T11:01:22.047Z]     raftstore::test_conf_change::test_server_split_brain
```

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/18367/pipeline/227

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further failure regarding this issue has been reported, it can be safely closed.
