### ISSUE TITLE
raftstore::test_conf_change::test_server_safe_conf_change failed

### ISSUE THREAD

**Issue by zhouqiang-cl** [tikv/tikv#5604]
thread 'raftstore::test_conf_change::test_server_safe_conf_change' panicked at 'failed to transfer leader to [1] id: 1 store_id: 1', components/test_raftstore/src/cluster.rs:815:17

[2019-10-09T13:23:17.133Z] stack backtrace:

[2019-10-09T13:23:17.133Z]    0: backtrace::backtrace::libunwind::trace

[2019-10-09T13:23:17.133Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88

[2019-10-09T13:23:17.133Z]    1: backtrace::backtrace::trace_unsynchronized

[2019-10-09T13:23:17.133Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66

[2019-10-09T13:23:17.133Z]    2: std::sys_common::backtrace::_print

[2019-10-09T13:23:17.133Z]              at src/libstd/sys_common/backtrace.rs:47

[2019-10-09T13:23:17.133Z]    3: std::sys_common::backtrace::print

[2019-10-09T13:23:17.133Z]              at src/libstd/sys_common/backtrace.rs:36

[2019-10-09T13:23:17.133Z]    4: std::panicking::default_hook::{{closure}}

[2019-10-09T13:23:17.133Z]              at src/libstd/panicking.rs:200

[2019-10-09T13:23:17.133Z]    5: std::panicking::default_hook

[2019-10-09T13:23:17.133Z]              at src/libstd/panicking.rs:214

[2019-10-09T13:23:17.133Z]    6: std::panicking::rust_panic_with_hook

[2019-10-09T13:23:17.133Z]              at src/libstd/panicking.rs:477

[2019-10-09T13:23:17.133Z]    7: std::panicking::continue_panic_fmt

[2019-10-09T13:23:17.133Z]              at src/libstd/panicking.rs:384

[2019-10-09T13:23:17.133Z]    8: std::panicking::begin_panic_fmt

[2019-10-09T13:23:17.133Z]              at src/libstd/panicking.rs:339

[2019-10-09T13:23:17.133Z]    9: test_raftstore::cluster::Cluster<T>::must_transfer_leader

[2019-10-09T13:23:17.133Z]              at ./<::std::macros::panic macros>:9

[2019-10-09T13:23:17.133Z]   10: integrations::raftstore::test_conf_change::test_conf_change_safe

[2019-10-09T13:23:17.133Z]              at tests/integrations/raftstore/test_conf_change.rs:549

[2019-10-09T13:23:17.133Z] test raftstore::test_multi::test_node_read_leader_with_unapplied_log ... FAILED

[2019-10-09T13:23:17.133Z]   11: integrations::raftstore::test_conf_change::test_server_safe_conf_change

[2019-10-09T13:23:17.133Z]              at tests/integrations/raftstore/test_conf_change.rs:728

[2019-10-09T13:23:17.133Z]   12: integrations::raftstore::test_conf_change::test_server_safe_conf_change::{{closure}}

[2019-10-09T13:23:17.133Z]              at tests/integrations/raftstore/test_conf_change.rs:725

[2019-10-09T13:23:17.133Z]   13: core::ops::function::FnOnce::call_once

[2019-10-09T13:23:17.133Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/ops/function.rs:227

[2019-10-09T13:23:17.133Z]   14: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once

[2019-10-09T13:23:17.133Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/liballoc/boxed.rs:922

[2019-10-09T13:23:17.133Z]   15: __rust_maybe_catch_panic

[2019-10-09T13:23:17.133Z]              at src/libpanic_unwind/lib.rs:80

[2019-10-09T13:23:17.133Z]   16: std::panicking::try

[2019-10-09T13:23:17.133Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panicking.rs:275

[2019-10-09T13:23:17.133Z]   17: std::panic::catch_unwind

[2019-10-09T13:23:17.133Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panic.rs:394

[2019-10-09T13:23:17.133Z]   18: test::run_test::run_test_inner::{{closure}}

[2019-10-09T13:23:17.133Z]              at src/libtest/lib.rs:1413

**Comment by zhouqiang-cl** [comment]
https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_continue_test/runs/88/nodes/20/steps/32/log/?start=0
