### ISSUE TITLE
raftstore::test_multi::test_server_read_leader_with_unapplied_log failed

### ISSUE THREAD

**Issue by zhouqiang-cl** [tikv/tikv#5606]
hread 'raftstore::test_multi::test_server_read_leader_with_unapplied_log' panicked at 'called `Result::unwrap()` on an `Err` value: Timeout("request timeout for 5s")', src/libcore/result.rs:1165:5

[2019-10-09T13:23:13.861Z] stack backtrace:

[2019-10-09T13:23:13.861Z]    0: backtrace::backtrace::libunwind::trace

[2019-10-09T13:23:13.861Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88

[2019-10-09T13:23:13.861Z]    1: backtrace::backtrace::trace_unsynchronized

[2019-10-09T13:23:13.861Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66

[2019-10-09T13:23:13.861Z]    2: std::sys_common::backtrace::_print

[2019-10-09T13:23:13.861Z]              at src/libstd/sys_common/backtrace.rs:47

[2019-10-09T13:23:13.861Z]    3: std::sys_common::backtrace::print

[2019-10-09T13:23:13.861Z]              at src/libstd/sys_common/backtrace.rs:36

[2019-10-09T13:23:13.861Z]    4: std::panicking::default_hook::{{closure}}

[2019-10-09T13:23:13.861Z]              at src/libstd/panicking.rs:200

[2019-10-09T13:23:13.861Z]    5: std::panicking::default_hook

[2019-10-09T13:23:13.861Z]              at src/libstd/panicking.rs:214

[2019-10-09T13:23:13.861Z]    6: std::panicking::rust_panic_with_hook

[2019-10-09T13:23:13.861Z]              at src/libstd/panicking.rs:477

[2019-10-09T13:23:13.861Z]    7: std::panicking::continue_panic_fmt

[2019-10-09T13:23:13.861Z]              at src/libstd/panicking.rs:384

[2019-10-09T13:23:13.861Z]    8: rust_begin_unwind

[2019-10-09T13:23:13.861Z]              at src/libstd/panicking.rs:311

[2019-10-09T13:23:13.861Z]    9: core::panicking::panic_fmt

[2019-10-09T13:23:13.861Z]              at src/libcore/panicking.rs:85

[2019-10-09T13:23:13.861Z]   10: core::result::unwrap_failed

[2019-10-09T13:23:13.861Z]              at src/libcore/result.rs:1165

[2019-10-09T13:23:13.861Z]   11: core::result::Result<T,E>::unwrap

[2019-10-09T13:23:13.861Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/result.rs:933

[2019-10-09T13:23:13.861Z]   12: test_raftstore::cluster::Cluster<T>::transfer_leader

[2019-10-09T13:23:13.861Z]              at ./components/test_raftstore/src/cluster.rs:796

[2019-10-09T13:23:13.861Z]   13: test_raftstore::cluster::Cluster<T>::must_transfer_leader

[2019-10-09T13:23:13.861Z]              at ./components/test_raftstore/src/cluster.rs:817

[2019-10-09T13:23:13.861Z]   14: integrations::raftstore::test_multi::test_read_leader_with_unapplied_log

[2019-10-09T13:23:13.861Z]              at tests/integrations/raftstore/test_multi.rs:543

[2019-10-09T13:23:13.861Z]   15: integrations::raftstore::test_multi::test_server_read_leader_with_unapplied_log

[2019-10-09T13:23:13.861Z]              at tests/integrations/raftstore/test_multi.rs:573

[2019-10-09T13:23:13.861Z]   16: integrations::raftstore::test_multi::test_server_read_leader_with_unapplied_log::{{closure}}

[2019-10-09T13:23:13.861Z]              at tests/integrations/raftstore/test_multi.rs:571

[2019-10-09T13:23:13.861Z]   17: core::ops::function::FnOnce::call_once

[2019-10-09T13:23:13.861Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/ops/function.rs:227

[2019-10-09T13:23:13.861Z]   18: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once

[2019-10-09T13:23:13.861Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/liballoc/boxed.rs:922

[2019-10-09T13:23:13.861Z]   19: __rust_maybe_catch_panic

[2019-10-09T13:23:13.861Z]              at src/libpanic_unwind/lib.rs:80

[2019-10-09T13:23:13.861Z]   20: std::panicking::try

[2019-10-09T13:23:13.861Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panicking.rs:275

[2019-10-09T13:23:13.861Z]   21: std::panic::catch_unwind

[2019-10-09T13:23:13.861Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panic.rs:394

[2019-10-09T13:23:13.861Z]   22: test::run_test::run_test_inner::{{closure}}

[2019-10-09T13:23:13.861Z]              at src/libtest/lib.rs:1413

**Comment by zhouqiang-cl** [comment]
https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_continue_test/runs/88/nodes/20/steps/32/log/?start=0
