### ISSUE TITLE
raftstore::test_prevote::test_node_create_peer_from_pre_vote failed

### ISSUE THREAD

**Issue by zhouqiang-cl** [tikv/tikv#5607]
[2019-10-09T13:23:06.973Z] thread 'raftstore::test_prevote::test_node_create_peer_from_pre_vote' panicked at 'can't get value Some("v1") for key 6B31', components/test_raftstore/src/util.rs:55:5

[2019-10-09T13:23:06.973Z] stack backtrace:

[2019-10-09T13:23:07.536Z]    0: backtrace::backtrace::libunwind::trace

[2019-10-09T13:23:07.536Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88

[2019-10-09T13:23:07.536Z]    1: backtrace::backtrace::trace_unsynchronized

[2019-10-09T13:23:07.536Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66

[2019-10-09T13:23:07.536Z]    2: std::sys_common::backtrace::_print

[2019-10-09T13:23:07.536Z]              at src/libstd/sys_common/backtrace.rs:47

[2019-10-09T13:23:07.536Z]    3: std::sys_common::backtrace::print

[2019-10-09T13:23:07.536Z]              at src/libstd/sys_common/backtrace.rs:36

[2019-10-09T13:23:07.536Z]    4: std::panicking::default_hook::{{closure}}

[2019-10-09T13:23:07.536Z]              at src/libstd/panicking.rs:200

[2019-10-09T13:23:07.536Z]    5: std::panicking::default_hook

[2019-10-09T13:23:07.536Z]              at src/libstd/panicking.rs:214

[2019-10-09T13:23:07.536Z]    6: std::panicking::rust_panic_with_hook

[2019-10-09T13:23:07.536Z]              at src/libstd/panicking.rs:477

[2019-10-09T13:23:07.536Z]    7: std::panicking::continue_panic_fmt

[2019-10-09T13:23:07.536Z]              at src/libstd/panicking.rs:384

[2019-10-09T13:23:07.536Z]    8: std::panicking::begin_panic_fmt

[2019-10-09T13:23:07.536Z]              at src/libstd/panicking.rs:339

[2019-10-09T13:23:07.536Z]    9: test_raftstore::util::must_get

[2019-10-09T13:23:07.536Z]              at components/test_raftstore/src/util.rs:55

[2019-10-09T13:23:07.536Z]   10: test_raftstore::util::must_get_equal

[2019-10-09T13:23:07.536Z]              at components/test_raftstore/src/util.rs:63

[2019-10-09T13:23:07.536Z]   11: integrations::raftstore::test_prevote::test_create_peer_from_pre_vote

[2019-10-09T13:23:07.536Z]              at tests/integrations/raftstore/test_prevote.rs:291

[2019-10-09T13:23:07.536Z]   12: integrations::raftstore::test_prevote::test_node_create_peer_from_pre_vote

[2019-10-09T13:23:07.536Z]              at tests/integrations/raftstore/test_prevote.rs:298

[2019-10-09T13:23:07.536Z]   13: integrations::raftstore::test_prevote::test_node_create_peer_from_pre_vote::{{closure}}

[2019-10-09T13:23:07.536Z]              at tests/integrations/raftstore/test_prevote.rs:295

[2019-10-09T13:23:07.793Z]   14: core::ops::function::FnOnce::call_once

[2019-10-09T13:23:07.793Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/ops/function.rs:227

[2019-10-09T13:23:07.793Z]   15: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once

[2019-10-09T13:23:07.793Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/liballoc/boxed.rs:922

[2019-10-09T13:23:07.793Z]   16: __rust_maybe_catch_panic

[2019-10-09T13:23:07.793Z]              at src/libpanic_unwind/lib.rs:80

[2019-10-09T13:23:07.793Z]   17: std::panicking::try

[2019-10-09T13:23:07.793Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panicking.rs:275

[2019-10-09T13:23:07.793Z]   18: std::panic::catch_unwind

[2019-10-09T13:23:07.793Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panic.rs:394

[2019-10-09T13:23:07.793Z]   19: test::run_test::run_test_inner::{{closure}}

[2019-10-09T13:23:07.793Z]              at src/libtest/lib.rs:1413

**Comment by zhouqiang-cl** [comment]
https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_continue_test/runs/89/nodes/20/steps/32/log/?start=0
