### ISSUE TITLE
test_server_update_region_size failed

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#5637]
```
[2019-10-11T14:00:22.860Z] thread 'raftstore::test_update_region_size::test_server_update_region_size' panicked at 'assertion failed: `(left != right)`
[2019-10-11T14:00:22.860Z]   left: `30039`,
[2019-10-11T14:00:22.860Z]  right: `30039`', tests/integrations/raftstore/test_update_region_size.rs:66:5
[2019-10-11T14:00:22.860Z] stack backtrace:
[2019-10-11T14:00:23.448Z]    0: backtrace::backtrace::libunwind::trace
[2019-10-11T14:00:23.448Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
[2019-10-11T14:00:23.448Z]    1: backtrace::backtrace::trace_unsynchronized
[2019-10-11T14:00:23.448Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
[2019-10-11T14:00:23.448Z]    2: std::sys_common::backtrace::_print
[2019-10-11T14:00:23.448Z]              at src/libstd/sys_common/backtrace.rs:47
[2019-10-11T14:00:23.448Z]    3: std::sys_common::backtrace::print
[2019-10-11T14:00:23.448Z]              at src/libstd/sys_common/backtrace.rs:36
[2019-10-11T14:00:23.448Z]    4: std::panicking::default_hook::{{closure}}
[2019-10-11T14:00:23.448Z]              at src/libstd/panicking.rs:200
[2019-10-11T14:00:23.448Z]    5: std::panicking::default_hook
[2019-10-11T14:00:23.448Z]              at src/libstd/panicking.rs:214
[2019-10-11T14:00:23.448Z]    6: std::panicking::rust_panic_with_hook
[2019-10-11T14:00:23.448Z]              at src/libstd/panicking.rs:477
[2019-10-11T14:00:23.448Z]    7: std::panicking::continue_panic_fmt
[2019-10-11T14:00:23.448Z]              at src/libstd/panicking.rs:384
[2019-10-11T14:00:23.448Z]    8: std::panicking::begin_panic_fmt
[2019-10-11T14:00:23.448Z]              at src/libstd/panicking.rs:339
[2019-10-11T14:00:23.448Z]    9: integrations::raftstore::test_update_region_size::test_update_region_size
[2019-10-11T14:00:23.448Z]              at tests/integrations/raftstore/test_update_region_size.rs:66
[2019-10-11T14:00:23.448Z]   10: integrations::raftstore::test_update_region_size::test_server_update_region_size
[2019-10-11T14:00:23.448Z]              at tests/integrations/raftstore/test_update_region_size.rs:73
[2019-10-11T14:00:23.448Z]   11: integrations::raftstore::test_update_region_size::test_server_update_region_size::{{closure}}
[2019-10-11T14:00:23.448Z]              at tests/integrations/raftstore/test_update_region_size.rs:70
[2019-10-11T14:00:23.448Z]   12: core::ops::function::FnOnce::call_once
[2019-10-11T14:00:23.448Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/ops/function.rs:227
[2019-10-11T14:00:23.448Z]   13: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
[2019-10-11T14:00:23.448Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/liballoc/boxed.rs:922
[2019-10-11T14:00:23.448Z]   14: __rust_maybe_catch_panic
[2019-10-11T14:00:23.448Z]              at src/libpanic_unwind/lib.rs:80
[2019-10-11T14:00:23.448Z]   15: std::panicking::try
[2019-10-11T14:00:23.448Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panicking.rs:275
[2019-10-11T14:00:23.448Z]   16: std::panic::catch_unwind
[2019-10-11T14:00:23.448Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panic.rs:394
[2019-10-11T14:00:23.448Z]   17: test::run_test::run_test_inner::{{closure}}
[2019-10-11T14:00:23.448Z]              at src/libtest/lib.rs:1413
[2019-10-11T14:00:23.448Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace
```

Log: https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/10050/nodes/102/steps/1187/log/?start=0

**Comment by LykxSassinator** [comment]
Given that the current Long Term Support (LTS) versions have resolved this issue, it is now considered outdated and can be safely closed.
