### ISSUE TITLE
test_delay_split_region failed

### ISSUE THREAD

**Issue by tabokie** [tikv/tikv#5676]
```
[2019-10-16T09:43:42.618Z] thread 'raftstore::test_split_region::test_delay_split_region' panicked at 'can't get value None for key 6B34', components/test_raftstore/src/util.rs:55:5
[2019-10-16T09:43:42.618Z] stack backtrace:
[2019-10-16T09:43:42.875Z]    0: backtrace::backtrace::libunwind::trace
[2019-10-16T09:43:42.875Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
[2019-10-16T09:43:42.875Z]    1: backtrace::backtrace::trace_unsynchronized
[2019-10-16T09:43:42.875Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
[2019-10-16T09:43:42.875Z]    2: std::sys_common::backtrace::_print
[2019-10-16T09:43:42.875Z]              at src/libstd/sys_common/backtrace.rs:47
[2019-10-16T09:43:42.875Z]    3: std::sys_common::backtrace::print
[2019-10-16T09:43:42.875Z]              at src/libstd/sys_common/backtrace.rs:36
[2019-10-16T09:43:42.875Z]    4: std::panicking::default_hook::{{closure}}
[2019-10-16T09:43:42.875Z]              at src/libstd/panicking.rs:200
[2019-10-16T09:43:42.875Z]    5: std::panicking::default_hook
[2019-10-16T09:43:42.875Z]              at src/libstd/panicking.rs:214
[2019-10-16T09:43:42.875Z]    6: std::panicking::rust_panic_with_hook
[2019-10-16T09:43:42.875Z]              at src/libstd/panicking.rs:477
[2019-10-16T09:43:42.875Z]    7: std::panicking::continue_panic_fmt
[2019-10-16T09:43:42.875Z]              at src/libstd/panicking.rs:384
[2019-10-16T09:43:42.875Z]    8: std::panicking::begin_panic_fmt
[2019-10-16T09:43:42.875Z]              at src/libstd/panicking.rs:339
[2019-10-16T09:43:42.875Z]    9: test_raftstore::util::must_get
[2019-10-16T09:43:42.875Z]              at components/test_raftstore/src/util.rs:55
[2019-10-16T09:43:42.875Z]   10: test_raftstore::util::must_get_none
[2019-10-16T09:43:42.875Z]              at components/test_raftstore/src/util.rs:67
[2019-10-16T09:43:42.875Z]   11: integrations::raftstore::test_split_region::check_cluster
[2019-10-16T09:43:42.875Z]              at tests/integrations/raftstore/test_split_region.rs:286
[2019-10-16T09:43:42.875Z]   12: integrations::raftstore::test_split_region::test_delay_split_region
[2019-10-16T09:43:42.875Z]              at tests/integrations/raftstore/test_split_region.rs:325
[2019-10-16T09:43:42.875Z]   13: integrations::raftstore::test_split_region::test_delay_split_region::{{closure}}
[2019-10-16T09:43:42.875Z]              at tests/integrations/raftstore/test_split_region.rs:295
[2019-10-16T09:43:42.875Z]   14: core::ops::function::FnOnce::call_once
[2019-10-16T09:43:42.875Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/ops/function.rs:227
[2019-10-16T09:43:42.875Z]   15: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
[2019-10-16T09:43:42.875Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/liballoc/boxed.rs:922
[2019-10-16T09:43:42.875Z]   16: __rust_maybe_catch_panic
[2019-10-16T09:43:42.875Z]              at src/libpanic_unwind/lib.rs:80
[2019-10-16T09:43:42.875Z]   17: std::panicking::try
[2019-10-16T09:43:42.875Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panicking.rs:275
[2019-10-16T09:43:42.875Z]   18: std::panic::catch_unwind
[2019-10-16T09:43:42.875Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panic.rs:394
[2019-10-16T09:43:42.875Z]   19: test::run_test::run_test_inner::{{closure}}
[2019-10-16T09:43:42.875Z]              at src/libtest/lib.rs:1413
```
see also: https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/10279/pipeline/167

**Comment by H-ZeX** [comment]
another fail case: 
https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/10917/nodes/341/steps/1362/log/?start=0
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/10917/pipeline

**Comment by mahjonp** [comment]
another fail case: https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/12091/pipeline/286

**Comment by youjiali1995** [comment]
It's too unstable.😭

**Comment by gengliqi** [comment]
Duplicated with https://github.com/tikv/tikv/issues/7107
