### ISSUE TITLE
test_node_merge_brain_split failed

### ISSUE THREAD

**Issue by zhangjinpeng1987** [tikv/tikv#5690]
```
thread 'raftstore::test_merge::test_node_merge_brain_split' panicked at 'assertion failed: `(left == right)`
  left: `InvalidAdmin`,
 right: `TransferLeader`: header { error { message: "EpochNotMatch current epoch of region 1 is conf_ver: 1 version: 2, but you sent conf_ver: 1 version: 4" epoch_not_match { current_regions { id: 1 start_key: 6B32 region_epoch { conf_ver: 1 version: 2 } peers { id: 1 store_id: 1 } peers { id: 2 store_id: 2 } peers { id: 3 store_id: 3 } } current_regions { id: 1000 end_key: 6B32 region_epoch { conf_ver: 2 version: 3 } peers { id: 1001 store_id: 1 } peers { id: 1002 store_id: 2 } peers { id: 1003 store_id: 3 } } } } }', components/test_raftstore/src/cluster.rs:799:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: std::thread::local::fast::Key<T>::try_initialize
   9: test_raftstore::cluster::Cluster<T>::transfer_leader
             at ./<::std::macros::panic macros>:9
  10: test_raftstore::cluster::Cluster<T>::must_transfer_leader
             at ./components/test_raftstore/src/cluster.rs:817
```

**Comment by gengliqi** [comment]
already fixed
