### ISSUE TITLE
test_backup::test_backup_meta failed

### ISSUE THREAD

**Issue by 5kbpers** [tikv/tikv#5786]
[2019-11-01T07:14:26.881Z] thread 'test_backup::test_backup_meta' panicked at 'message: "peer is not leader for region 1, leader may None" not_leader { region_id: 1 }', components/backup/tests/integrations/test_backup.rs:135:9
[2019-11-01T07:14:26.881Z] stack backtrace:
[2019-11-01T07:14:27.448Z]    0: backtrace::backtrace::libunwind::trace
[2019-11-01T07:14:27.448Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
[2019-11-01T07:14:27.448Z]    1: backtrace::backtrace::trace_unsynchronized
[2019-11-01T07:14:27.449Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
[2019-11-01T07:14:27.449Z]    2: std::sys_common::backtrace::_print
[2019-11-01T07:14:27.449Z]              at src/libstd/sys_common/backtrace.rs:47
[2019-11-01T07:14:27.449Z]    3: std::sys_common::backtrace::print
[2019-11-01T07:14:27.449Z]              at src/libstd/sys_common/backtrace.rs:36
[2019-11-01T07:14:27.449Z]    4: std::panicking::default_hook::{{closure}}
[2019-11-01T07:14:27.449Z]              at src/libstd/panicking.rs:200
[2019-11-01T07:14:27.449Z]    5: std::panicking::default_hook
[2019-11-01T07:14:27.449Z]              at src/libstd/panicking.rs:214
[2019-11-01T07:14:27.449Z]    6: std::panicking::rust_panic_with_hook
[2019-11-01T07:14:27.449Z]              at src/libstd/panicking.rs:477
[2019-11-01T07:14:27.449Z]    7: std::panicking::continue_panic_fmt
[2019-11-01T07:14:27.449Z]              at src/libstd/panicking.rs:384
[2019-11-01T07:14:27.449Z]    8: std::panicking::begin_panic_fmt
[2019-11-01T07:14:27.449Z]              at src/libstd/panicking.rs:339
[2019-11-01T07:14:27.449Z]    9: integrations::test_backup::TestSuite::must_kv_prewrite
[2019-11-01T07:14:27.449Z]              at components/backup/tests/integrations/test_backup.rs:135
[2019-11-01T07:14:27.449Z]   10: integrations::test_backup::test_backup_meta
[2019-11-01T07:14:27.449Z]              at components/backup/tests/integrations/test_backup.rs:361
[2019-11-01T07:14:27.449Z]   11: integrations::test_backup::test_backup_meta::{{closure}}
[2019-11-01T07:14:27.449Z]              at components/backup/tests/integrations/test_backup.rs:347
[2019-11-01T07:14:27.998Z]   12: core::ops::function::FnOnce::call_once
[2019-11-01T07:14:27.999Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/ops/function.rs:227
[2019-11-01T07:14:27.999Z]   13: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
[2019-11-01T07:14:27.999Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/liballoc/boxed.rs:922
[2019-11-01T07:14:27.999Z]   14: __rust_maybe_catch_panic
[2019-11-01T07:14:27.999Z]              at src/libpanic_unwind/lib.rs:80
[2019-11-01T07:14:27.999Z]   15: std::panicking::try
[2019-11-01T07:14:27.999Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panicking.rs:275
[2019-11-01T07:14:27.999Z]   16: std::panic::catch_unwind
[2019-11-01T07:14:27.999Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panic.rs:394
[2019-11-01T07:14:27.999Z]   17: test::run_test::run_test_inner::{{closure}}
[2019-11-01T07:14:27.999Z]              at src/libtest/lib.rs:1413
[2019-11-01T07:14:27.999Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2019-11-01T07:14:35.660Z] test test_backup::test_backup_and_import ... ok
[2019-11-01T07:14:35.660Z] test test_backup::test_backup_meta ... FAILED
[2019-11-01T07:14:35.660Z] 
[2019-11-01T07:14:35.660Z] failures:
[2019-11-01T07:14:35.660Z] 
[2019-11-01T07:14:35.660Z] failures:
[2019-11-01T07:14:35.660Z]     test_backup::test_backup_meta
[2019-11-01T07:14:35.660Z] 
[2019-11-01T07:14:35.660Z] test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

**Comment by 5kbpers** [comment]
https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/10985/nodes/323/steps/1309/log/?start=0
