### ISSUE TITLE
unstable test test_backup::test_backup_meta

### ISSUE THREAD

**Issue by MyonKeminta** [tikv/tikv#5814]
## Bug Report

Unstable test: test_backup::test_backup_meta

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/11192/pipeline

```
[2019-11-05T06:40:38.894Z] running 2 tests

[2019-11-05T06:40:53.824Z] thread 'test_backup::test_backup_meta' panicked at 'called `Result::unwrap()` on an `Err` value: Other("[components/test_raftstore/src/cluster.rs:286]: can\'t get leader of region 1")', src/libcore/result.rs:1165:5

[2019-11-05T06:40:53.824Z] stack backtrace:

[2019-11-05T06:40:53.824Z]    0: backtrace::backtrace::libunwind::trace

[2019-11-05T06:40:53.824Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88

[2019-11-05T06:40:53.824Z]    1: backtrace::backtrace::trace_unsynchronized

[2019-11-05T06:40:53.824Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66

[2019-11-05T06:40:53.824Z]    2: std::sys_common::backtrace::_print

[2019-11-05T06:40:53.824Z]              at src/libstd/sys_common/backtrace.rs:47

[2019-11-05T06:40:53.824Z]    3: std::sys_common::backtrace::print

[2019-11-05T06:40:53.824Z]              at src/libstd/sys_common/backtrace.rs:36

[2019-11-05T06:40:53.824Z]    4: std::panicking::default_hook::{{closure}}

[2019-11-05T06:40:53.824Z]              at src/libstd/panicking.rs:200

[2019-11-05T06:40:53.824Z]    5: std::panicking::default_hook

[2019-11-05T06:40:53.824Z]              at src/libstd/panicking.rs:214

[2019-11-05T06:40:53.824Z]    6: std::panicking::rust_panic_with_hook

[2019-11-05T06:40:53.824Z]              at src/libstd/panicking.rs:477

[2019-11-05T06:40:53.824Z]    7: std::panicking::continue_panic_fmt

[2019-11-05T06:40:53.824Z]              at src/libstd/panicking.rs:384

[2019-11-05T06:40:53.824Z]    8: rust_begin_unwind

[2019-11-05T06:40:53.824Z]              at src/libstd/panicking.rs:311

[2019-11-05T06:40:53.824Z]    9: core::panicking::panic_fmt

[2019-11-05T06:40:53.824Z]              at src/libcore/panicking.rs:85

[2019-11-05T06:40:53.824Z]   10: core::result::unwrap_failed

[2019-11-05T06:40:53.824Z]              at src/libcore/result.rs:1165

[2019-11-05T06:40:53.824Z]   11: core::result::Result<T,E>::unwrap

[2019-11-05T06:40:53.824Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/result.rs:933

[2019-11-05T06:40:53.824Z]   12: test_raftstore::cluster::Cluster<T>::request

[2019-11-05T06:40:53.824Z]              at ./components/test_raftstore/src/cluster.rs:596

[2019-11-05T06:40:53.824Z]   13: test_raftstore::cluster::Cluster<T>::must_put_cf

[2019-11-05T06:40:53.824Z]              at ./components/test_raftstore/src/cluster.rs:684

[2019-11-05T06:40:53.824Z]   14: test_raftstore::cluster::Cluster<T>::must_put

[2019-11-05T06:40:53.824Z]              at ./components/test_raftstore/src/cluster.rs:680

[2019-11-05T06:40:53.824Z]   15: integrations::test_backup::TestSuite::new

[2019-11-05T06:40:53.825Z]              at components/backup/tests/integrations/test_backup.rs:87

[2019-11-05T06:40:53.825Z]   16: integrations::test_backup::test_backup_meta

[2019-11-05T06:40:53.825Z]              at components/backup/tests/integrations/test_backup.rs:352

[2019-11-05T06:40:53.825Z]   17: integrations::test_backup::test_backup_meta::{{closure}}

[2019-11-05T06:40:53.825Z]              at components/backup/tests/integrations/test_backup.rs:351

[2019-11-05T06:40:53.825Z]   18: core::ops::function::FnOnce::call_once

[2019-11-05T06:40:53.825Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/ops/function.rs:227

[2019-11-05T06:40:54.129Z]   19: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once

[2019-11-05T06:40:54.129Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/liballoc/boxed.rs:922

[2019-11-05T06:40:54.129Z]   20: __rust_maybe_catch_panic

[2019-11-05T06:40:54.129Z]              at src/libpanic_unwind/lib.rs:80

[2019-11-05T06:40:54.129Z]   21: std::panicking::try

[2019-11-05T06:40:54.129Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panicking.rs:275

[2019-11-05T06:40:54.129Z]   22: std::panic::catch_unwind

[2019-11-05T06:40:54.129Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panic.rs:394

[2019-11-05T06:40:54.129Z]   23: test::run_test::run_test_inner::{{closure}}

[2019-11-05T06:40:54.129Z]              at src/libtest/lib.rs:1413

[2019-11-05T06:40:54.129Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

[2019-11-05T06:40:57.309Z] test test_backup::test_backup_and_import ... ok

[2019-11-05T06:40:57.641Z] test test_backup::test_backup_meta ... FAILED
```

**Comment by MyonKeminta** [comment]
@overvenus PTAL

**Comment by gengliqi** [comment]
another case
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/13333/pipeline/131

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further feedback regarding this issue has been reported, it can be safely closed.
