### ISSUE TITLE
storage::test_raftkv::test_read_on_replica failed

### ISSUE THREAD

**Issue by gengliqi** [tikv/tikv#6072]
storage::test_raftkv::test_read_on_replica

```
[2019-11-27T08:52:37.118Z] thread 'storage::test_raftkv::test_read_on_replica' panicked at 'called `Result::unwrap()` on an `Err` value: Request(Error { message: "stale command", not_leader: None, region_not_found: None, key_not_in_region: None, epoch_not_match: None, server_is_busy: None, stale_command: Some(StaleCommand), store_not_match: None, raft_entry_too_large: None })', src/libcore/result.rs:1165:5
[2019-11-27T08:52:37.118Z] stack backtrace:
[2019-11-27T08:52:37.680Z] test raftstore::test_stale_peer::test_node_stale_peer_out_of_region ... ok
[2019-11-27T08:52:37.937Z]    0: backtrace::backtrace::libunwind::trace
[2019-11-27T08:52:37.937Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
[2019-11-27T08:52:37.937Z]    1: backtrace::backtrace::trace_unsynchronized
[2019-11-27T08:52:37.937Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
[2019-11-27T08:52:37.937Z]    2: std::sys_common::backtrace::_print
[2019-11-27T08:52:37.938Z]              at src/libstd/sys_common/backtrace.rs:47
[2019-11-27T08:52:37.938Z]    3: std::sys_common::backtrace::print
[2019-11-27T08:52:37.938Z]              at src/libstd/sys_common/backtrace.rs:36
[2019-11-27T08:52:37.938Z]    4: std::panicking::default_hook::{{closure}}
[2019-11-27T08:52:37.938Z]              at src/libstd/panicking.rs:200
[2019-11-27T08:52:37.938Z]    5: std::panicking::default_hook
[2019-11-27T08:52:37.938Z]              at src/libstd/panicking.rs:214
[2019-11-27T08:52:37.938Z]    6: std::panicking::rust_panic_with_hook
[2019-11-27T08:52:37.938Z]              at src/libstd/panicking.rs:477
[2019-11-27T08:52:37.938Z]    7: std::panicking::continue_panic_fmt
[2019-11-27T08:52:37.938Z]              at src/libstd/panicking.rs:384
[2019-11-27T08:52:37.938Z]    8: rust_begin_unwind
[2019-11-27T08:52:37.938Z]              at src/libstd/panicking.rs:311
[2019-11-27T08:52:37.938Z]    9: core::panicking::panic_fmt
[2019-11-27T08:52:37.938Z]              at src/libcore/panicking.rs:85
[2019-11-27T08:52:37.938Z]   10: core::result::unwrap_failed
[2019-11-27T08:52:37.938Z]              at src/libcore/result.rs:1165
[2019-11-27T08:52:37.938Z]   11: core::result::Result<T,E>::unwrap
[2019-11-27T08:52:37.938Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/result.rs:933
[2019-11-27T08:52:37.938Z]   12: integrations::storage::test_raftkv::assert_has
[2019-11-27T08:52:37.938Z]              at tests/integrations/storage/test_raftkv.rs:278
[2019-11-27T08:52:37.938Z]   13: integrations::storage::test_raftkv::test_read_on_replica
[2019-11-27T08:52:37.938Z]              at tests/integrations/storage/test_raftkv.rs:188
[2019-11-27T08:52:37.938Z]   14: integrations::storage::test_raftkv::test_read_on_replica::{{closure}}
[2019-11-27T08:52:37.938Z]              at tests/integrations/storage/test_raftkv.rs:132
[2019-11-27T08:52:37.938Z]   15: core::ops::function::FnOnce::call_once
[2019-11-27T08:52:37.938Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/ops/function.rs:227
[2019-11-27T08:52:37.938Z]   16: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
[2019-11-27T08:52:37.938Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/liballoc/boxed.rs:922
[2019-11-27T08:52:37.938Z]   17: __rust_maybe_catch_panic
[2019-11-27T08:52:37.938Z]              at src/libpanic_unwind/lib.rs:80
[2019-11-27T08:52:37.938Z]   18: std::panicking::try
[2019-11-27T08:52:37.938Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panicking.rs:275
[2019-11-27T08:52:37.938Z]   19: std::panic::catch_unwind
[2019-11-27T08:52:37.938Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panic.rs:394
[2019-11-27T08:52:37.938Z]   20: test::run_test::run_test_inner::{{closure}}
[2019-11-27T08:52:37.938Z]              at src/libtest/lib.rs:1413
[2019-11-27T08:52:37.938Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2019-11-27T08:52:37.938Z] test storage::test_raftkv::test_read_on_replica ... FAILED
```
https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/13156/nodes/213/steps/1198/log/?start=0

**Comment by mahjonp** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/18461/pipeline/230 integration Part17

**Comment by glorv** [comment]
Latest Failed Cases:
https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/18994/consoleFull
https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/18993/consoleFull

**Comment by 5kbpers** [comment]
@glorv the failed test of them is `raftstore::test_stale_peer::test_node_stale_peer_out_of_region`, please open another issue.

**Comment by mahjonp** [comment]
OK, I will open another issue.
