### ISSUE TITLE
coprocessor::test_select::test_cache failed

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#6114]
## Bug Report

```
[2019-11-30T06:01:14.681Z] thread 'coprocessor::test_select::test_cache' panicked at 'assertion failed: `(left == right)`

[2019-11-30T06:01:14.681Z]   left: `[26, 78, 26, 76, 3, 128, 0, 0, 0, 0, 0, 0, 1, 2, 12, 110, 97, 109, 101, 58, 48, 8, 4, 3, 128, 0, 0, 0, 0, 0, 0, 2, 2, 12, 110, 97, 109, 101, 58, 52, 8, 6, 3, 128, 0, 0, 0, 0, 0, 0, 4, 2, 12, 110, 97, 109, 101, 58, 51, 8, 2, 3, 128, 0, 0, 0, 0, 0, 0, 5, 2, 12, 110, 97, 109, 101, 58, 49, 8, 8, 40, 4, 48, 0, 66, 6, 8, 0, 16, 4, 24, 1, 72, 0]`,

[2019-11-30T06:01:14.681Z]  right: `[26, 78, 26, 76, 3, 128, 0, 0, 0, 0, 0, 0, 1, 2, 12, 110, 97, 109, 101, 58, 48, 8, 4, 3, 128, 0, 0, 0, 0, 0, 0, 2, 2, 12, 110, 97, 109, 101, 58, 52, 8, 6, 3, 128, 0, 0, 0, 0, 0, 0, 4, 2, 12, 110, 97, 109, 101, 58, 51, 8, 2, 3, 128, 0, 0, 0, 0, 0, 0, 5, 2, 12, 110, 97, 109, 101, 58, 49, 8, 8, 40, 4, 48, 0, 66, 8, 8, 192, 132, 61, 16, 4, 24, 1, 72, 0]`', tests/integrations/coprocessor/test_select.rs:1646:5

[2019-11-30T06:01:14.681Z] stack backtrace:

[2019-11-30T06:01:15.242Z]    0: backtrace::backtrace::libunwind::trace

[2019-11-30T06:01:15.242Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88

[2019-11-30T06:01:15.242Z]    1: backtrace::backtrace::trace_unsynchronized

[2019-11-30T06:01:15.242Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66

[2019-11-30T06:01:15.242Z]    2: std::sys_common::backtrace::_print

[2019-11-30T06:01:15.242Z]              at src/libstd/sys_common/backtrace.rs:47

[2019-11-30T06:01:15.242Z]    3: std::sys_common::backtrace::print

[2019-11-30T06:01:15.242Z]              at src/libstd/sys_common/backtrace.rs:36

[2019-11-30T06:01:15.242Z]    4: std::panicking::default_hook::{{closure}}

[2019-11-30T06:01:15.242Z]              at src/libstd/panicking.rs:200

[2019-11-30T06:01:15.242Z]    5: std::panicking::default_hook

[2019-11-30T06:01:15.242Z]              at src/libstd/panicking.rs:214

[2019-11-30T06:01:15.242Z]    6: std::panicking::rust_panic_with_hook

[2019-11-30T06:01:15.242Z]              at src/libstd/panicking.rs:477

[2019-11-30T06:01:15.242Z]    7: std::panicking::continue_panic_fmt

[2019-11-30T06:01:15.242Z]              at src/libstd/panicking.rs:384

[2019-11-30T06:01:15.242Z]    8: std::panicking::begin_panic_fmt

[2019-11-30T06:01:15.242Z]              at src/libstd/panicking.rs:339

[2019-11-30T06:01:15.242Z]    9: integrations::coprocessor::test_select::test_cache

[2019-11-30T06:01:15.242Z]              at tests/integrations/coprocessor/test_select.rs:1646

[2019-11-30T06:01:15.242Z]   10: integrations::coprocessor::test_select::test_cache::{{closure}}

[2019-11-30T06:01:15.242Z]              at tests/integrations/coprocessor/test_select.rs:1611

[2019-11-30T06:01:15.242Z]   11: core::ops::function::FnOnce::call_once

[2019-11-30T06:01:15.242Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/ops/function.rs:227

[2019-11-30T06:01:15.242Z]   12: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once

[2019-11-30T06:01:15.242Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/liballoc/boxed.rs:922

[2019-11-30T06:01:15.242Z]   13: __rust_maybe_catch_panic

[2019-11-30T06:01:15.242Z]              at src/libpanic_unwind/lib.rs:80

[2019-11-30T06:01:15.242Z]   14: std::panicking::try

[2019-11-30T06:01:15.242Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panicking.rs:275

[2019-11-30T06:01:15.242Z]   15: std::panic::catch_unwind

[2019-11-30T06:01:15.242Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panic.rs:394

[2019-11-30T06:01:15.242Z]   16: test::run_test::run_test_inner::{{closure}}

[2019-11-30T06:01:15.242Z]              at src/libtest/lib.rs:1413

[2019-11-30T06:01:15.242Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

[2019-11-30T06:01:15.498Z] test coprocessor::test_select::test_cache ... FAILED

[2019-11-30T06:01:18.010Z] test raftstore::test_lease_read::test_one_node_renew_lease ... ok

[2019-11-30T06:01:19.374Z] test pd::test_rpc_client::test_region_heartbeat_on_leader_change ... ok

[2019-11-30T06:01:19.374Z] test raftstore::test_prevote::test_node_create_peer_from_pre_vote ... ok

[2019-11-30T06:01:23.542Z] test raftstore::test_stale_peer::test_server_stale_peer_without_data_right_derive_when_split ... ok

[2019-11-30T06:01:24.103Z] test raftstore::test_snap::test_node_huge_snapshot ... ok

[2019-11-30T06:01:27.369Z] test storage::test_storage::test_isolation_inc ... ok

[2019-11-30T06:01:27.369Z] 

[2019-11-30T06:01:27.369Z] failures:

[2019-11-30T06:01:27.369Z] 

[2019-11-30T06:01:27.369Z] failures:

[2019-11-30T06:01:27.369Z]     coprocessor::test_select::test_cache
```

**Comment by breeswish** [comment]
False alert. Close.
