### ISSUE TITLE
test_detect_deadlock_when_shuffle_region failed

### ISSUE THREAD

**Issue by rleungx** [tikv/tikv#6153]
## Bug Report
test_detect_deadlock_when_shuffle_region failed

<details>

```
[2019-12-04T03:00:58.887Z] thread 'server::lock_manager::test_detect_deadlock_when_shuffle_region' panicked at 'message: "stale command"', tests/integrations/server/lock_manager.rs:38:5
[2019-12-04T03:00:58.887Z] stack backtrace:
[2019-12-04T03:00:59.449Z]    0: backtrace::backtrace::libunwind::trace
[2019-12-04T03:00:59.450Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
[2019-12-04T03:00:59.450Z]    1: backtrace::backtrace::trace_unsynchronized
[2019-12-04T03:00:59.450Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
[2019-12-04T03:00:59.450Z]    2: std::sys_common::backtrace::_print
[2019-12-04T03:00:59.450Z]              at src/libstd/sys_common/backtrace.rs:47
[2019-12-04T03:00:59.450Z]    3: std::sys_common::backtrace::print
[2019-12-04T03:00:59.450Z]              at src/libstd/sys_common/backtrace.rs:36
[2019-12-04T03:00:59.450Z]    4: std::panicking::default_hook::{{closure}}
[2019-12-04T03:00:59.450Z]              at src/libstd/panicking.rs:200
[2019-12-04T03:00:59.450Z]    5: std::panicking::default_hook
[2019-12-04T03:00:59.450Z]              at src/libstd/panicking.rs:214
[2019-12-04T03:00:59.450Z]    6: std::panicking::rust_panic_with_hook
[2019-12-04T03:00:59.450Z]              at src/libstd/panicking.rs:477
[2019-12-04T03:00:59.450Z]    7: std::panicking::continue_panic_fmt
[2019-12-04T03:00:59.450Z]              at src/libstd/panicking.rs:384
[2019-12-04T03:00:59.450Z]    8: std::panicking::begin_panic_fmt
[2019-12-04T03:00:59.450Z]              at src/libstd/panicking.rs:339
[2019-12-04T03:00:59.450Z]    9: integrations::server::lock_manager::must_acquire_pessimistic_lock
[2019-12-04T03:00:59.450Z]              at tests/integrations/server/lock_manager.rs:38
[2019-12-04T03:00:59.450Z]   10: integrations::server::lock_manager::must_deadlock
[2019-12-04T03:00:59.450Z]              at tests/integrations/server/lock_manager.rs:46
[2019-12-04T03:00:59.450Z]   11: integrations::server::lock_manager::test_detect_deadlock_when_shuffle_region
[2019-12-04T03:00:59.450Z]              at tests/integrations/server/lock_manager.rs:136
[2019-12-04T03:00:59.450Z]   12: integrations::server::lock_manager::test_detect_deadlock_when_shuffle_region::{{closure}}
[2019-12-04T03:00:59.450Z]              at tests/integrations/server/lock_manager.rs:116
[2019-12-04T03:00:59.450Z]   13: core::ops::function::FnOnce::call_once
[2019-12-04T03:00:59.450Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/ops/function.rs:227
[2019-12-04T03:00:59.450Z]   14: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
[2019-12-04T03:00:59.450Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/liballoc/boxed.rs:922
[2019-12-04T03:00:59.450Z]   15: __rust_maybe_catch_panic
[2019-12-04T03:00:59.450Z]              at src/libpanic_unwind/lib.rs:80
[2019-12-04T03:00:59.450Z]   16: std::panicking::try
[2019-12-04T03:00:59.450Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panicking.rs:275
[2019-12-04T03:00:59.450Z]   17: std::panic::catch_unwind
[2019-12-04T03:00:59.450Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panic.rs:394
[2019-12-04T03:00:59.450Z]   18: test::run_test::run_test_inner::{{closure}}
[2019-12-04T03:00:59.450Z]              at src/libtest/lib.rs:1413
[2019-12-04T03:00:59.450Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2019-12-04T03:01:01.964Z] test server::lock_manager::test_detect_deadlock_when_shuffle_region ... FAILED
```

</details>

**Comment by youjiali1995** [comment]
It's unstable. I'll take a look today.
