### ISSUE TITLE
unstable test: test_server_transfer_leader_safe

### ISSUE THREAD

**Issue by Little-Wallace** [tikv/tikv#6178]
### What version of TiKV are you using?

master

### Steps to reproduce

CI failed at test `raftstore::test_conf_change::test_server_transfer_leader_safe`
```
[2019-12-06T08:05:31.116Z] thread 'raftstore::test_conf_change::test_server_transfer_leader_safe' panicked at 'assertion failed: `(left == right)`
[2019-12-06T08:05:31.116Z]   left: `1`,
[2019-12-06T08:05:31.116Z]  right: `3`', tests/integrations/raftstore/test_conf_change.rs:636:5
[2019-12-06T08:05:31.116Z] stack backtrace:
[2019-12-06T08:05:31.679Z]    0: backtrace::backtrace::libunwind::trace
[2019-12-06T08:05:31.679Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
[2019-12-06T08:05:31.679Z]    1: backtrace::backtrace::trace_unsynchronized
[2019-12-06T08:05:31.679Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
[2019-12-06T08:05:31.679Z]    2: std::sys_common::backtrace::_print
[2019-12-06T08:05:31.679Z]              at src/libstd/sys_common/backtrace.rs:47
[2019-12-06T08:05:31.679Z]    3: std::sys_common::backtrace::print
[2019-12-06T08:05:31.679Z]              at src/libstd/sys_common/backtrace.rs:36
[2019-12-06T08:05:31.679Z]    4: std::panicking::default_hook::{{closure}}
[2019-12-06T08:05:31.679Z]              at src/libstd/panicking.rs:200
[2019-12-06T08:05:31.679Z]    5: std::panicking::default_hook
[2019-12-06T08:05:31.679Z]              at src/libstd/panicking.rs:214
[2019-12-06T08:05:31.679Z]    6: std::panicking::rust_panic_with_hook
[2019-12-06T08:05:31.679Z]              at src/libstd/panicking.rs:477
[2019-12-06T08:05:31.679Z]    7: std::panicking::continue_panic_fmt
[2019-12-06T08:05:31.679Z]              at src/libstd/panicking.rs:384
[2019-12-06T08:05:31.679Z]    8: std::panicking::begin_panic_fmt
[2019-12-06T08:05:31.679Z]              at src/libstd/panicking.rs:339
[2019-12-06T08:05:31.679Z]    9: integrations::raftstore::test_conf_change::test_transfer_leader_safe
[2019-12-06T08:05:31.679Z]              at tests/integrations/raftstore/test_conf_change.rs:636
[2019-12-06T08:05:31.679Z]   10: integrations::raftstore::test_conf_change::test_server_transfer_leader_safe
[2019-12-06T08:05:31.679Z]              at tests/integrations/raftstore/test_conf_change.rs:763
[2019-12-06T08:05:31.679Z]   11: integrations::raftstore::test_conf_change::test_server_transfer_leader_safe::{{closure}}
[2019-12-06T08:05:31.679Z]              at tests/integrations/raftstore/test_conf_change.rs:759
[2019-12-06T08:05:31.679Z]   12: core::ops::function::FnOnce::call_once
[2019-12-06T08:05:31.679Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/ops/function.rs:227
[2019-12-06T08:05:31.679Z]   13: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
[2019-12-06T08:05:31.679Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/liballoc/boxed.rs:922
[2019-12-06T08:05:31.679Z]   14: __rust_maybe_catch_panic
[2019-12-06T08:05:31.679Z]              at src/libpanic_unwind/lib.rs:80
[2019-12-06T08:05:31.680Z]   15: std::panicking::try
[2019-12-06T08:05:31.680Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panicking.rs:275
[2019-12-06T08:05:31.680Z]   16: std::panic::catch_unwind
[2019-12-06T08:05:31.680Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panic.rs:394
[2019-12-06T08:05:31.680Z]   17: test::run_test::run_test_inner::{{closure}}
[2019-12-06T08:05:31.680Z]              at src/libtest/lib.rs:1413
[2019-12-06T08:05:31.680Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further feedback regarding this issue has been reported, it can be safely closed.
