### ISSUE TITLE
test server::lock_manager::test_detect_deadlock_when_shuffle_region failed

### ISSUE THREAD

**Issue by 5kbpers** [tikv/tikv#6226]
## Bug Report
```
 [2019-12-12T09:12:20.001Z] thread 'server::lock_manager::test_detect_deadlock_when_shuffle_region' panicked at 'called `Result::unwrap()` on an `Err` value: Other("[components/test_raftstore/src/cluster.rs:287]: can\'t get leader of region 1")', src/libcore/result.rs:1165:5
[2019-12-12T09:12:20.001Z] stack backtrace:
[2019-12-12T09:12:20.932Z]    0: backtrace::backtrace::libunwind::trace
[2019-12-12T09:12:20.932Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
[2019-12-12T09:12:20.932Z]    1: backtrace::backtrace::trace_unsynchronized
[2019-12-12T09:12:20.932Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
[2019-12-12T09:12:20.932Z]    2: std::sys_common::backtrace::_print
[2019-12-12T09:12:20.932Z]              at src/libstd/sys_common/backtrace.rs:47
[2019-12-12T09:12:20.932Z]    3: std::sys_common::backtrace::print
[2019-12-12T09:12:20.932Z]              at src/libstd/sys_common/backtrace.rs:36
[2019-12-12T09:12:20.932Z]    4: std::panicking::default_hook::{{closure}}
[2019-12-12T09:12:20.932Z]              at src/libstd/panicking.rs:200
[2019-12-12T09:12:20.932Z]    5: std::panicking::default_hook
[2019-12-12T09:12:20.932Z]              at src/libstd/panicking.rs:214
[2019-12-12T09:12:20.932Z]    6: std::panicking::rust_panic_with_hook
[2019-12-12T09:12:20.932Z]              at src/libstd/panicking.rs:477
[2019-12-12T09:12:20.932Z]    7: std::panicking::continue_panic_fmt
[2019-12-12T09:12:20.932Z]              at src/libstd/panicking.rs:384
[2019-12-12T09:12:20.932Z]    8: rust_begin_unwind
[2019-12-12T09:12:20.932Z]              at src/libstd/panicking.rs:311
[2019-12-12T09:12:20.932Z]    9: core::panicking::panic_fmt
[2019-12-12T09:12:20.932Z]              at src/libcore/panicking.rs:85
[2019-12-12T09:12:20.932Z]   10: core::result::unwrap_failed
[2019-12-12T09:12:20.932Z]              at src/libcore/result.rs:1165
[2019-12-12T09:12:20.932Z]   11: core::result::Result<T,E>::unwrap
[2019-12-12T09:12:20.932Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/result.rs:933
[2019-12-12T09:12:20.932Z]   12: test_raftstore::cluster::Cluster<T>::transfer_leader
[2019-12-12T09:12:20.932Z]              at ./components/test_raftstore/src/cluster.rs:806
[2019-12-12T09:12:20.932Z]   13: test_raftstore::cluster::Cluster<T>::must_transfer_leader
[2019-12-12T09:12:20.932Z]              at ./components/test_raftstore/src/cluster.rs:827
[2019-12-12T09:12:20.932Z]   14: integrations::server::lock_manager::must_transfer_leader
[2019-12-12T09:12:20.932Z]              at tests/integrations/server/lock_manager.rs:100
[2019-12-12T09:12:20.932Z]   15: integrations::server::lock_manager::test_detect_deadlock_when_shuffle_region
[2019-12-12T09:12:20.932Z]              at tests/integrations/server/lock_manager.rs:135
[2019-12-12T09:12:20.932Z]   16: integrations::server::lock_manager::test_detect_deadlock_when_shuffle_region::{{closure}}
[2019-12-12T09:12:20.932Z]              at tests/integrations/server/lock_manager.rs:118
[2019-12-12T09:12:20.932Z]   17: core::ops::function::FnOnce::call_once
[2019-12-12T09:12:20.932Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/ops/function.rs:227
[2019-12-12T09:12:20.932Z]   18: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
[2019-12-12T09:12:20.932Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/liballoc/boxed.rs:922
[2019-12-12T09:12:20.932Z]   19: __rust_maybe_catch_panic
[2019-12-12T09:12:20.932Z]              at src/libpanic_unwind/lib.rs:80
[2019-12-12T09:12:20.933Z]   20: std::panicking::try
[2019-12-12T09:12:20.933Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panicking.rs:275
[2019-12-12T09:12:20.933Z]   21: std::panic::catch_unwind
[2019-12-12T09:12:20.933Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panic.rs:394
[2019-12-12T09:12:20.933Z]   22: test::run_test::run_test_inner::{{closure}}
[2019-12-12T09:12:20.933Z]              at src/libtest/lib.rs:1413
[2019-12-12T09:12:20.933Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2019-12-12T09:12:21.189Z] test server::lock_manager::test_detect_deadlock_when_shuffle_region ... FAILED
[2019-12-12T09:12:21.189Z] 
[2019-12-12T09:12:21.189Z] failures:
[2019-12-12T09:12:21.189Z] 
[2019-12-12T09:12:21.189Z] failures:
[2019-12-12T09:12:21.189Z]     server::lock_manager::test_detect_deadlock_when_shuffle_region
[2019-12-12T09:12:21.189Z] 
```
https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/14297/nodes/205/steps/1335/log/?start=0

**Comment by youjiali1995** [comment]
Failed due to `test_raftstore::cluster::Cluster<T>::must_transfer_leader`.

**Comment by youjiali1995** [comment]
I think it's not related to the test, so I will close it.
