### ISSUE TITLE
Test test_server_down_peers_with_hibernate_regions fails

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#6247]
## Bug Report

```
[2019-12-16T05:54:50.740Z] thread 'raftstore::test_region_heartbeat::test_server_down_peers_with_hibernate_regions' panicked at 'failed to transfer leader to [1] id: 2 store_id: 2', components/test_raftstore/src/cluster.rs:825:17
[2019-12-16T05:54:50.740Z] stack backtrace:
[2019-12-16T05:54:50.740Z]    0: backtrace::backtrace::libunwind::trace
[2019-12-16T05:54:50.740Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
[2019-12-16T05:54:50.740Z]    1: backtrace::backtrace::trace_unsynchronized
[2019-12-16T05:54:50.740Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
[2019-12-16T05:54:50.740Z]    2: std::sys_common::backtrace::_print
[2019-12-16T05:54:50.740Z]              at src/libstd/sys_common/backtrace.rs:47
[2019-12-16T05:54:50.740Z]    3: std::sys_common::backtrace::print
[2019-12-16T05:54:50.740Z]              at src/libstd/sys_common/backtrace.rs:36
[2019-12-16T05:54:50.740Z]    4: std::panicking::default_hook::{{closure}}
[2019-12-16T05:54:50.740Z]              at src/libstd/panicking.rs:200
[2019-12-16T05:54:50.740Z]    5: std::panicking::default_hook
[2019-12-16T05:54:50.740Z]              at src/libstd/panicking.rs:214
[2019-12-16T05:54:50.740Z]    6: std::panicking::rust_panic_with_hook
[2019-12-16T05:54:50.740Z]              at src/libstd/panicking.rs:477
[2019-12-16T05:54:50.740Z]    7: std::panicking::continue_panic_fmt
[2019-12-16T05:54:50.740Z]              at src/libstd/panicking.rs:384
[2019-12-16T05:54:50.740Z]    8: std::panicking::begin_panic_fmt
[2019-12-16T05:54:50.740Z]              at src/libstd/panicking.rs:339
[2019-12-16T05:54:50.740Z]    9: test_raftstore::cluster::Cluster<T>::must_transfer_leader
[2019-12-16T05:54:50.740Z]              at ./<::std::macros::panic macros>:9
[2019-12-16T05:54:50.740Z]   10: integrations::raftstore::test_region_heartbeat::test_down_peers
[2019-12-16T05:54:50.740Z]              at tests/integrations/raftstore/test_region_heartbeat.rs:62
[2019-12-16T05:54:50.740Z]   11: integrations::raftstore::test_region_heartbeat::test_server_down_peers_with_hibernate_regions
[2019-12-16T05:54:50.740Z]              at tests/integrations/raftstore/test_region_heartbeat.rs:84
[2019-12-16T05:54:50.740Z]   12: integrations::raftstore::test_region_heartbeat::test_server_down_peers_with_hibernate_regions::{{closure}}
[2019-12-16T05:54:50.740Z]              at tests/integrations/raftstore/test_region_heartbeat.rs:78
[2019-12-16T05:54:50.740Z]   13: core::ops::function::FnOnce::call_once
[2019-12-16T05:54:50.740Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/ops/function.rs:227
[2019-12-16T05:54:50.740Z]   14: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
[2019-12-16T05:54:50.740Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/liballoc/boxed.rs:922
[2019-12-16T05:54:50.740Z]   15: __rust_maybe_catch_panic
[2019-12-16T05:54:50.740Z]              at src/libpanic_unwind/lib.rs:80
[2019-12-16T05:54:50.740Z]   16: std::panicking::try
[2019-12-16T05:54:50.740Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panicking.rs:275
[2019-12-16T05:54:50.740Z]   17: std::panic::catch_unwind
[2019-12-16T05:54:50.740Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panic.rs:394
[2019-12-16T05:54:50.740Z]   18: test::run_test::run_test_inner::{{closure}}
[2019-12-16T05:54:50.740Z]              at src/libtest/lib.rs:1413
[2019-12-16T05:54:50.740Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

[internal.pingcap.net.txt](https://github.com/tikv/tikv/files/3966307/internal.pingcap.net.txt)

**Comment by BusyJay** [comment]
It seems to work well in my local environment and CI now. Feel free to reopen if it still exists.
