### ISSUE TITLE
test case test_detect_deadlock_when_shuffle_region is not stable

### ISSUE THREAD

**Issue by hicqu** [tikv/tikv#6263]
### What version of TiKV are you using?
master.

### What did happened?
```
[2019-12-17T09:07:19.855Z] thread 'server::lock_manager::test_detect_deadlock_when_shuffle_region' panicked at 'failed to transfer leader to [1] id: 2 store_id: 2', components/test_raftstore/src/cluster.rs:825:17
[2019-12-17T09:07:19.855Z] stack backtrace:
[2019-12-17T09:07:19.855Z]    0: backtrace::backtrace::libunwind::trace
[2019-12-17T09:07:19.855Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
[2019-12-17T09:07:19.855Z]    1: backtrace::backtrace::trace_unsynchronized
[2019-12-17T09:07:19.855Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
[2019-12-17T09:07:19.855Z]    2: std::sys_common::backtrace::_print
[2019-12-17T09:07:19.855Z]              at src/libstd/sys_common/backtrace.rs:47
[2019-12-17T09:07:19.855Z]    3: std::sys_common::backtrace::print
[2019-12-17T09:07:19.855Z]              at src/libstd/sys_common/backtrace.rs:36
[2019-12-17T09:07:19.855Z]    4: std::panicking::default_hook::{{closure}}
[2019-12-17T09:07:19.855Z]              at src/libstd/panicking.rs:200
[2019-12-17T09:07:19.855Z]    5: std::panicking::default_hook
[2019-12-17T09:07:19.855Z]              at src/libstd/panicking.rs:214
[2019-12-17T09:07:19.855Z]    6: std::panicking::rust_panic_with_hook
[2019-12-17T09:07:19.855Z]              at src/libstd/panicking.rs:477
[2019-12-17T09:07:19.855Z]    7: std::panicking::continue_panic_fmt
[2019-12-17T09:07:19.855Z]              at src/libstd/panicking.rs:384
[2019-12-17T09:07:19.855Z]    8: std::panicking::begin_panic_fmt
[2019-12-17T09:07:19.855Z]              at src/libstd/panicking.rs:339
[2019-12-17T09:07:19.855Z]    9: test_raftstore::cluster::Cluster<T>::must_transfer_leader
[2019-12-17T09:07:19.855Z]              at ./<::std::macros::panic macros>:9
[2019-12-17T09:07:19.855Z]   10: integrations::server::lock_manager::must_transfer_leader
[2019-12-17T09:07:19.855Z]              at tests/integrations/server/lock_manager.rs:100
[2019-12-17T09:07:19.855Z]   11: integrations::server::lock_manager::test_detect_deadlock_when_shuffle_region
[2019-12-17T09:07:19.855Z]              at tests/integrations/server/lock_manager.rs:135
[2019-12-17T09:07:19.855Z]   12: integrations::server::lock_manager::test_detect_deadlock_when_shuffle_region::{{closure}}
[2019-12-17T09:07:19.855Z]              at tests/integrations/server/lock_manager.rs:118
[2019-12-17T09:07:19.855Z]   13: core::ops::function::FnOnce::call_once
[2019-12-17T09:07:19.855Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/ops/function.rs:227
[2019-12-17T09:07:19.855Z]   14: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
[2019-12-17T09:07:19.855Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/liballoc/boxed.rs:922
[2019-12-17T09:07:19.855Z]   15: __rust_maybe_catch_panic
[2019-12-17T09:07:19.855Z]              at src/libpanic_unwind/lib.rs:80
[2019-12-17T09:07:19.855Z]   16: std::panicking::try
[2019-12-17T09:07:19.855Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panicking.rs:275
[2019-12-17T09:07:19.855Z]   17: std::panic::catch_unwind
[2019-12-17T09:07:19.855Z]              at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panic.rs:394
[2019-12-17T09:07:19.855Z]   18: test::run_test::run_test_inner::{{closure}}
[2019-12-17T09:07:19.855Z]              at src/libtest/lib.rs:1413
[2019-12-17T09:07:19.855Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2019-12-17T09:07:20.416Z] test raftstore::test_split_region::test_server_auto_split_region ... ok
[2019-12-17T09:07:22.313Z] test server::lock_manager::test_detect_deadlock_when_shuffle_region ... FAILED
```

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further feedback regarding this issue has been reported, it can be safely closed.
