### ISSUE TITLE
Test test_auto_gc failed 

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#6400]
storage::test_raft_storage::test_auto_gc

## Bug Report

```
[2020-01-03T05:48:31.892Z] test storage::test_raft_storage::test_auto_gc ... thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Txn(Engine(Request(message: "stale command")))', src/libcore/result.rs:1188:5

[2020-01-03T05:48:31.892Z] stack backtrace:

[2020-01-03T05:48:32.148Z]    0: backtrace::backtrace::libunwind::trace

[2020-01-03T05:48:32.148Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88

[2020-01-03T05:48:32.148Z]    1: backtrace::backtrace::trace_unsynchronized

[2020-01-03T05:48:32.148Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66

[2020-01-03T05:48:32.148Z]    2: std::sys_common::backtrace::_print_fmt

[2020-01-03T05:48:32.148Z]              at src/libstd/sys_common/backtrace.rs:84

[2020-01-03T05:48:32.148Z]    3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt

[2020-01-03T05:48:32.148Z]              at src/libstd/sys_common/backtrace.rs:61

[2020-01-03T05:48:32.148Z]    4: core::fmt::write

[2020-01-03T05:48:32.148Z]              at src/libcore/fmt/mod.rs:1025

[2020-01-03T05:48:32.148Z]    5: std::io::Write::write_fmt

[2020-01-03T05:48:32.148Z]              at src/libstd/io/mod.rs:1426

[2020-01-03T05:48:32.148Z]    6: std::sys_common::backtrace::_print

[2020-01-03T05:48:32.148Z]              at src/libstd/sys_common/backtrace.rs:65

[2020-01-03T05:48:32.148Z]    7: std::sys_common::backtrace::print

[2020-01-03T05:48:32.148Z]              at src/libstd/sys_common/backtrace.rs:50

[2020-01-03T05:48:32.148Z]    8: std::panicking::default_hook::{{closure}}

[2020-01-03T05:48:32.148Z]              at src/libstd/panicking.rs:193

[2020-01-03T05:48:32.148Z]    9: std::panicking::default_hook

[2020-01-03T05:48:32.148Z]              at src/libstd/panicking.rs:210

[2020-01-03T05:48:32.148Z]   10: std::panicking::rust_panic_with_hook

[2020-01-03T05:48:32.148Z]              at src/libstd/panicking.rs:471

[2020-01-03T05:48:32.148Z]   11: rust_begin_unwind

[2020-01-03T05:48:32.148Z]              at src/libstd/panicking.rs:375

[2020-01-03T05:48:32.148Z]   12: core::panicking::panic_fmt

[2020-01-03T05:48:32.148Z]              at src/libcore/panicking.rs:84

[2020-01-03T05:48:32.148Z]   13: core::result::unwrap_failed

[2020-01-03T05:48:32.148Z]              at src/libcore/result.rs:1188

[2020-01-03T05:48:32.148Z]   14: core::result::Result<T,E>::unwrap

[2020-01-03T05:48:32.148Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/result.rs:956

[2020-01-03T05:48:32.148Z]   15: integrations::storage::test_raft_storage::check_data

[2020-01-03T05:48:32.148Z]              at tests/integrations/storage/test_raft_storage.rs:236

[2020-01-03T05:48:32.148Z]   16: integrations::storage::test_raft_storage::test_auto_gc

[2020-01-03T05:48:32.148Z]              at tests/integrations/storage/test_raft_storage.rs:336

[2020-01-03T05:48:32.148Z]   17: integrations::storage::test_raft_storage::test_auto_gc::{{closure}}

[2020-01-03T05:48:32.148Z]              at tests/integrations/storage/test_raft_storage.rs:248

[2020-01-03T05:48:32.148Z]   18: core::ops::function::FnOnce::call_once

[2020-01-03T05:48:32.148Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ops/function.rs:232

[2020-01-03T05:48:32.405Z]   19: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once

[2020-01-03T05:48:32.405Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/liballoc/boxed.rs:1022

[2020-01-03T05:48:32.405Z]   20: __rust_maybe_catch_panic

[2020-01-03T05:48:32.405Z]              at src/libpanic_unwind/lib.rs:78

[2020-01-03T05:48:32.405Z]   21: std::panicking::try

[2020-01-03T05:48:32.405Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panicking.rs:270

[2020-01-03T05:48:32.405Z]   22: std::panic::catch_unwind

[2020-01-03T05:48:32.405Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panic.rs:394

[2020-01-03T05:48:32.405Z]   23: test::run_test_in_process

[2020-01-03T05:48:32.405Z]              at src/libtest/lib.rs:567

[2020-01-03T05:48:32.405Z]   24: test::run_test::run_test_inner::{{closure}}

[2020-01-03T05:48:32.405Z]              at src/libtest/lib.rs:474

[2020-01-03T05:48:32.405Z]   25: test::run_test::run_test_inner

[2020-01-03T05:48:32.405Z]              at src/libtest/lib.rs:495

[2020-01-03T05:48:32.405Z]   26: test::run_test

[2020-01-03T05:48:32.405Z]              at src/libtest/lib.rs:531

[2020-01-03T05:48:32.405Z]   27: test::run_tests

[2020-01-03T05:48:32.405Z]              at src/libtest/lib.rs:300

[2020-01-03T05:48:32.405Z]   28: test::console::run_tests_console

[2020-01-03T05:48:32.405Z]              at src/libtest/console.rs:295

[2020-01-03T05:48:32.405Z]   29: test::test_main

[2020-01-03T05:48:32.405Z]              at src/libtest/lib.rs:121

[2020-01-03T05:48:32.405Z]   30: test::test_main_static

[2020-01-03T05:48:32.405Z]              at src/libtest/lib.rs:140

[2020-01-03T05:48:32.405Z]   31: integrations::main

[2020-01-03T05:48:32.405Z]   32: std::rt::lang_start::{{closure}}

[2020-01-03T05:48:32.405Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/rt.rs:67

[2020-01-03T05:48:32.405Z]   33: std::rt::lang_start_internal::{{closure}}

[2020-01-03T05:48:32.405Z]              at src/libstd/rt.rs:52

[2020-01-03T05:48:32.405Z]   34: std::panicking::try::do_call

[2020-01-03T05:48:32.405Z]              at src/libstd/panicking.rs:292

[2020-01-03T05:48:32.405Z]   35: __rust_maybe_catch_panic

[2020-01-03T05:48:32.405Z]              at src/libpanic_unwind/lib.rs:78

[2020-01-03T05:48:32.405Z]   36: std::panicking::try

[2020-01-03T05:48:32.405Z]              at src/libstd/panicking.rs:270

[2020-01-03T05:48:32.405Z]   37: std::panic::catch_unwind

[2020-01-03T05:48:32.405Z]              at src/libstd/panic.rs:394

[2020-01-03T05:48:32.405Z]   38: std::rt::lang_start_internal

[2020-01-03T05:48:32.405Z]              at src/libstd/rt.rs:51

[2020-01-03T05:48:32.405Z]   39: std::rt::lang_start

[2020-01-03T05:48:32.405Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/rt.rs:67

[2020-01-03T05:48:32.405Z]   40: main

[2020-01-03T05:48:32.405Z]   41: __libc_start_main

[2020-01-03T05:48:32.405Z]   42: <unknown>

[2020-01-03T05:48:32.405Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/15703/pipeline

I think we should retry on stale command errors.

**Comment by mahjonp** [comment]
recent: https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/18645/pipeline #Integration Part20
