### ISSUE TITLE
test_reserve_space_for_recover fails

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#6517]
tests::test_reserve_space_for_recover

## Bug Report

```

[2020-02-03T11:00:11.948Z] test tests::test_reserve_space_for_recover ... thread 'main' panicked at 'assertion failed: `(left == right)`

[2020-02-03T11:00:11.948Z]   left: `581632`,

[2020-02-03T11:00:11.948Z]  right: `65536`', components/tikv_util/src/lib.rs:783:9

[2020-02-03T11:00:11.948Z] stack backtrace:

[2020-02-03T11:00:12.204Z]    0: backtrace::backtrace::libunwind::trace

[2020-02-03T11:00:12.204Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88

[2020-02-03T11:00:12.204Z]    1: backtrace::backtrace::trace_unsynchronized

[2020-02-03T11:00:12.204Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66

[2020-02-03T11:00:12.204Z]    2: std::sys_common::backtrace::_print_fmt

[2020-02-03T11:00:12.204Z]              at src/libstd/sys_common/backtrace.rs:84

[2020-02-03T11:00:12.204Z]    3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt

[2020-02-03T11:00:12.205Z]              at src/libstd/sys_common/backtrace.rs:61

[2020-02-03T11:00:12.205Z]    4: core::fmt::write

[2020-02-03T11:00:12.205Z]              at src/libcore/fmt/mod.rs:1025

[2020-02-03T11:00:12.205Z]    5: std::io::Write::write_fmt

[2020-02-03T11:00:12.205Z]              at src/libstd/io/mod.rs:1426

[2020-02-03T11:00:12.205Z]    6: std::sys_common::backtrace::_print

[2020-02-03T11:00:12.205Z]              at src/libstd/sys_common/backtrace.rs:65

[2020-02-03T11:00:12.205Z]    7: std::sys_common::backtrace::print

[2020-02-03T11:00:12.205Z]              at src/libstd/sys_common/backtrace.rs:50

[2020-02-03T11:00:12.205Z]    8: std::panicking::default_hook::{{closure}}

[2020-02-03T11:00:12.205Z]              at src/libstd/panicking.rs:193

[2020-02-03T11:00:12.205Z]    9: std::panicking::default_hook

[2020-02-03T11:00:12.205Z]              at src/libstd/panicking.rs:210

[2020-02-03T11:00:12.205Z]   10: panic_hook::track_hook::{{closure}}

[2020-02-03T11:00:12.205Z]              at components/panic_hook/src/lib.rs:48

[2020-02-03T11:00:12.205Z]   11: std::thread::local::LocalKey<T>::try_with

[2020-02-03T11:00:12.205Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/thread/local.rs:262

[2020-02-03T11:00:12.205Z]   12: std::thread::local::LocalKey<T>::with

[2020-02-03T11:00:12.205Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/thread/local.rs:239

[2020-02-03T11:00:12.205Z]   13: panic_hook::track_hook

[2020-02-03T11:00:12.205Z]              at components/panic_hook/src/lib.rs:42

[2020-02-03T11:00:12.205Z]   14: core::ops::function::Fn::call

[2020-02-03T11:00:12.205Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ops/function.rs:72

[2020-02-03T11:00:12.205Z]   15: std::panicking::rust_panic_with_hook

[2020-02-03T11:00:12.205Z]              at src/libstd/panicking.rs:475

[2020-02-03T11:00:12.205Z]   16: rust_begin_unwind

[2020-02-03T11:00:12.205Z]              at src/libstd/panicking.rs:375

[2020-02-03T11:00:12.205Z]   17: std::panicking::begin_panic_fmt

[2020-02-03T11:00:12.205Z]              at src/libstd/panicking.rs:326

[2020-02-03T11:00:12.205Z]   18: tikv_util::tests::test_reserve_space_for_recover

[2020-02-03T11:00:12.205Z]              at components/tikv_util/src/lib.rs:783

[2020-02-03T11:00:12.205Z]   19: tikv_util::tests::test_reserve_space_for_recover::{{closure}}

[2020-02-03T11:00:12.205Z]              at components/tikv_util/src/lib.rs:771

[2020-02-03T11:00:12.205Z]   20: core::ops::function::FnOnce::call_once

[2020-02-03T11:00:12.205Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ops/function.rs:232

[2020-02-03T11:00:12.205Z]   21: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once

[2020-02-03T11:00:12.205Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/liballoc/boxed.rs:1022

[2020-02-03T11:00:12.205Z]   22: __rust_maybe_catch_panic

[2020-02-03T11:00:12.205Z]              at src/libpanic_unwind/lib.rs:78

[2020-02-03T11:00:12.205Z]   23: std::panicking::try

[2020-02-03T11:00:12.205Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panicking.rs:270

[2020-02-03T11:00:12.205Z]   24: std::panic::catch_unwind

[2020-02-03T11:00:12.205Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panic.rs:394

[2020-02-03T11:00:12.205Z]   25: test::run_test_in_process

[2020-02-03T11:00:12.205Z]              at src/libtest/lib.rs:567

[2020-02-03T11:00:12.205Z]   26: test::run_test::run_test_inner::{{closure}}

[2020-02-03T11:00:12.205Z]              at src/libtest/lib.rs:474

[2020-02-03T11:00:12.205Z]   27: test::run_test::run_test_inner

[2020-02-03T11:00:12.205Z]              at src/libtest/lib.rs:495

[2020-02-03T11:00:12.205Z]   28: test::run_test

[2020-02-03T11:00:12.205Z]              at src/libtest/lib.rs:531

[2020-02-03T11:00:12.205Z]   29: test::run_tests

[2020-02-03T11:00:12.205Z]              at src/libtest/lib.rs:300

[2020-02-03T11:00:12.205Z]   30: test::console::run_tests_console

[2020-02-03T11:00:12.205Z]              at src/libtest/console.rs:295

[2020-02-03T11:00:12.205Z]   31: test::test_main

[2020-02-03T11:00:12.205Z]              at src/libtest/lib.rs:121

[2020-02-03T11:00:12.205Z]   32: test::test_main_static

[2020-02-03T11:00:12.205Z]              at src/libtest/lib.rs:140

[2020-02-03T11:00:12.205Z]   33: tikv_util::main

[2020-02-03T11:00:12.205Z]   34: std::rt::lang_start::{{closure}}

[2020-02-03T11:00:12.205Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/rt.rs:67

[2020-02-03T11:00:12.205Z]   35: std::rt::lang_start_internal::{{closure}}

[2020-02-03T11:00:12.205Z]              at src/libstd/rt.rs:52

[2020-02-03T11:00:12.205Z]   36: std::panicking::try::do_call

[2020-02-03T11:00:12.205Z]              at src/libstd/panicking.rs:292

[2020-02-03T11:00:12.205Z]   37: __rust_maybe_catch_panic

[2020-02-03T11:00:12.205Z]              at src/libpanic_unwind/lib.rs:78

[2020-02-03T11:00:12.205Z]   38: std::panicking::try

[2020-02-03T11:00:12.205Z]              at src/libstd/panicking.rs:270

[2020-02-03T11:00:12.205Z]   39: std::panic::catch_unwind

[2020-02-03T11:00:12.205Z]              at src/libstd/panic.rs:394

[2020-02-03T11:00:12.205Z]   40: std::rt::lang_start_internal

[2020-02-03T11:00:12.205Z]              at src/libstd/rt.rs:51

[2020-02-03T11:00:12.205Z]   41: std::rt::lang_start

[2020-02-03T11:00:12.205Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/rt.rs:67

[2020-02-03T11:00:12.205Z]   42: main

[2020-02-03T11:00:12.205Z]   43: __libc_start_main

[2020-02-03T11:00:12.205Z]   44: <unknown>

[2020-02-03T11:00:12.205Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

[2020-02-03T11:00:12.205Z] FAILED
```

Based on commit  ed953bd3feffce8c51a3c562ca4b78c24e3a4dcc

**Comment by mahjonp** [comment]
Another one: https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/18227/consoleText
