### ISSUE TITLE
test cases::test_storage::test_scheduler_leader_change_twice ... thread 'main' panicked at 'failed to transfer leader to [1] id: 1 store_id: 1'

### ISSUE THREAD

**Issue by mahjonp** [tikv/tikv#6741]
cases::test_storage::test_scheduler_leader_change_twice

[2020-02-29T08:46:44.226Z] test cases::test_storage::test_scheduler_leader_change_twice ... thread 'main' panicked at 'failed to transfer leader to [1] id: 1 store_id: 1', components/test_raftstore/src/cluster.rs:836:17

[2020-02-29T08:46:44.226Z] stack backtrace:

[2020-02-29T08:46:44.226Z]    0: backtrace::backtrace::libunwind::trace

[2020-02-29T08:46:44.226Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88

[2020-02-29T08:46:44.226Z]    1: backtrace::backtrace::trace_unsynchronized

[2020-02-29T08:46:44.226Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66

[2020-02-29T08:46:44.226Z]    2: std::sys_common::backtrace::_print_fmt

[2020-02-29T08:46:44.226Z]              at src/libstd/sys_common/backtrace.rs:84

[2020-02-29T08:46:44.226Z]    3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt

[2020-02-29T08:46:44.226Z]              at src/libstd/sys_common/backtrace.rs:61

[2020-02-29T08:46:44.226Z]    4: core::fmt::write

[2020-02-29T08:46:44.226Z]              at src/libcore/fmt/mod.rs:1025

[2020-02-29T08:46:44.226Z]    5: std::io::Write::write_fmt

[2020-02-29T08:46:44.226Z]              at src/libstd/io/mod.rs:1426

[2020-02-29T08:46:44.226Z]    6: std::sys_common::backtrace::_print

[2020-02-29T08:46:44.226Z]              at src/libstd/sys_common/backtrace.rs:65

[2020-02-29T08:46:44.226Z]    7: std::sys_common::backtrace::print

[2020-02-29T08:46:44.226Z]              at src/libstd/sys_common/backtrace.rs:50

[2020-02-29T08:46:44.226Z]    8: std::panicking::default_hook::{{closure}}

[2020-02-29T08:46:44.226Z]              at src/libstd/panicking.rs:193

[2020-02-29T08:46:44.226Z]    9: std::panicking::default_hook

[2020-02-29T08:46:44.226Z]              at src/libstd/panicking.rs:210

[2020-02-29T08:46:44.226Z]   10: std::panicking::rust_panic_with_hook

[2020-02-29T08:46:44.226Z]              at src/libstd/panicking.rs:471

[2020-02-29T08:46:44.226Z]   11: rust_begin_unwind

[2020-02-29T08:46:44.226Z]              at src/libstd/panicking.rs:375

[2020-02-29T08:46:44.226Z]   12: std::panicking::begin_panic_fmt

[2020-02-29T08:46:44.226Z]              at src/libstd/panicking.rs:326

[2020-02-29T08:46:44.226Z]   13: test_raftstore::cluster::Cluster<T>::must_transfer_leader

[2020-02-29T08:46:44.226Z]              at ./<::std::macros::panic macros>:9

[2020-02-29T08:46:44.226Z]   14: failpoints::cases::test_storage::test_scheduler_leader_change_twice

[2020-02-29T08:46:44.226Z]              at tests/failpoints/cases/test_storage.rs:29

[2020-02-29T08:46:44.226Z]   15: failpoints::cases::test_storage::test_scheduler_leader_change_twice::{{closure}}

[2020-02-29T08:46:44.226Z]              at tests/failpoints/cases/test_storage.rs:22

[2020-02-29T08:46:44.226Z]   16: core::ops::function::FnOnce::call_once

[2020-02-29T08:46:44.226Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ops/function.rs:232

[2020-02-29T08:46:44.226Z]   17: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once

[2020-02-29T08:46:44.226Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/liballoc/boxed.rs:1022

[2020-02-29T08:46:44.226Z]   18: __rust_maybe_catch_panic

[2020-02-29T08:46:44.226Z]              at src/libpanic_unwind/lib.rs:78

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17902/pipeline/203

**Comment by mahjonp** [comment]
so any update? @hicqu

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further feedback regarding this issue has been reported, it can be safely closed.
