### ISSUE TITLE
coredump: rocksdb::DBImpl::CloseHelper __cxa_pure_virtual in CI

### ISSUE THREAD

**Issue by mahjonp** [tikv/tikv#6742]
# Bug Report
```
(gdb) bt
#0  0x00007f0ab87dc207 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007f0ab87dd8f8 in __GI_abort () at abort.c:90
#2  0x00005613f38ece15 in __gnu_cxx::__verbose_terminate_handler() ()
#3  0x00005613f38111e6 in __cxxabiv1::__terminate(void (*)()) ()
#4  0x00005613f3811213 in std::terminate() ()
#5  0x00005613f380ecff in __cxa_pure_virtual ()
#6  0x00005613f348e190 in rocksdb::DBImpl::CloseHelper (this=0x7f0ab80c9800)
    at /rust/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/6191b41/librocksdb_sys/rocksdb/db/db_impl/db_impl.cc:572
#7  0x00005613f348e558 in rocksdb::DBImpl::~DBImpl (this=0x7f0ab80c9800, __in_chrg=<optimized out>)
    at /rust/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/6191b41/librocksdb_sys/rocksdb/db/db_impl/db_impl.cc:609
#8  0x00005613f348e8e8 in rocksdb::DBImpl::~DBImpl (this=0x7f0ab80c9800, __in_chrg=<optimized out>)
    at /rust/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/6191b41/librocksdb_sys/rocksdb/db/db_impl/db_impl.cc:611
#9  0x00005613f3429fcd in crocksdb_close (db=0x7f0ab80f6460) at crocksdb/c.cc:698
#10 0x00005613f2fc5d73 in _$LT$rocksdb..rocksdb..DB$u20$as$u20$core..ops..drop..Drop$GT$::drop::h3c918f8d80142cc5 () at /rust/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/6191b41/src/rocksdb.rs:1934
#11 0x00005613f2eed4a1 in core::ptr::real_drop_in_place::h8d7bc5d5d62857b8 ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ptr/mod.rs:182
#12 0x00005613f2ec8658 in drop_in_place<rocksdb::rocksdb::DB> ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ptr/mod.rs:172
#13 alloc::sync::Arc$LT$T$GT$::drop_slow::hb2cfc823fa0d89bb ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/liballoc/sync.rs:735
#14 0x00005613f2ec87e3 in _$LT$alloc..sync..Arc$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$::drop::h278be82bdd91d9ec () at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/liballoc/sync.rs:1263
#15 0x00005613f15ee827 in core::ptr::real_drop_in_place::hdee06d6b3001bb8e ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ptr/mod.rs:182
#16 0x00005613f15a0159 in core::ptr::real_drop_in_place::h28954ee7fd6c55d2 ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ptr/mod.rs:182
#17 0x00005613f15d4d06 in core::ptr::real_drop_in_place::ha2e3cea959cd8497 ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ptr/mod.rs:182
#18 0x00005613f15ed0f6 in core::ptr::real_drop_in_place::hda6f422cb11af0f8 ()
---Type <return> to continue, or q <return> to quit---
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ptr/mod.rs:182
#19 0x00005613f15e80a4 in core::ptr::real_drop_in_place::hcef964e8449d16f2 ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ptr/mod.rs:182
#20 0x00005613f15f4526 in core::ptr::real_drop_in_place::hecadd6257aa00fe8 ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ptr/mod.rs:182
#21 0x00005613f15dd92d in core::ptr::real_drop_in_place::hb638126c27583259 ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ptr/mod.rs:182
#22 0x00005613f15cf7e6 in core::ptr::real_drop_in_place::h96c317f5760f6fc9 ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ptr/mod.rs:182
#23 0x00005613f46922a7 in core::ptr::real_drop_in_place::h4b47cfb85ae4fe20 ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ptr/mod.rs:182
#24 0x00005613f469273d in core::ptr::real_drop_in_place::h5cad9c93cff75606 ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ptr/mod.rs:182
#25 0x00005613f46a9447 in drop_in_place<(&[u8], alloc::boxed::Box<CloneableHandler>)> ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ptr/mod.rs:172
#26 core::ptr::_$LT$impl$u20$$BP$mut$u20$T$GT$::drop_in_place::h88971d7e4d8ed109 ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ptr/mod.rs:2466
#27 0x00005613f46743d5 in hashbrown::raw::Bucket$LT$T$GT$::drop::h41fb69215d99b38f ()
    at /cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.6.2/src/raw/mod.rs:307
#28 0x00005613f46724e7 in _$LT$hashbrown..raw..RawTable$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$::drop::h02363c1874138929 ()
    at /cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.6.2/src/raw/mod.rs:1041
#29 0x00005613f4694797 in core::ptr::real_drop_in_place::hdedf369bc740d132 ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ptr/mod.rs:182
#30 0x00005613f469471d in core::ptr::real_drop_in_place::hd91805967d910833 ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ptr/mod.rs:182
#31 0x00005613f4693a26 in core::ptr::real_drop_in_place::h9ae42323f881973a ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ptr/mod.rs:182
#32 0x00005613f4691ca6 in core::ptr::real_drop_in_place::h1f5e78867674f290 ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ptr/mod.rs:182
#33 0x00005613f4698287 in drop_in_place<core::cell::UnsafeCell<std::collections::hash::map::HashMap<&[u8], alloc::boxed::Box<CloneableHandler>, std::collections::hash::map::RandomState>>> ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ptr/mod.rs:172
#34 alloc::sync::Arc$LT$T$GT$::drop_slow::h535828eae9a706c2 ()
---Type <return> to continue, or q <return> to quit---
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/liballoc/sync.rs:735
#35 0x00005613f469d283 in _$LT$alloc..sync..Arc$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$::drop::h70e046557b751da9 () at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/liballoc/sync.rs:1263
#36 0x00005613f4692eb7 in core::ptr::real_drop_in_place::h72f12c927859bd4c ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ptr/mod.rs:182
#37 0x00005613f4692666 in core::ptr::real_drop_in_place::h597d6efaace48a5e ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ptr/mod.rs:182
#38 0x00005613f46bd2aa in grpcio::server::request_call::hc3069f4a818f26b1 ()
    at /rust/registry/src/github.com-1ecc6299db9ec823/grpcio-0.5.0-alpha.5/src/server.rs:438
#39 0x00005613f468e2b2 in grpcio::task::callback::Request::resolve::h3b2e47461a9a30e9 ()
    at /rust/registry/src/github.com-1ecc6299db9ec823/grpcio-0.5.0-alpha.5/src/task/callback.rs:36
#40 0x00005613f469092d in grpcio::task::CallTag::resolve::h616d1d358329d065 ()
    at /rust/registry/src/github.com-1ecc6299db9ec823/grpcio-0.5.0-alpha.5/src/task/mod.rs:187
#41 0x00005613f46bae14 in grpcio::env::poll_queue::h045dc3786f99ece9 ()
    at /rust/registry/src/github.com-1ecc6299db9ec823/grpcio-0.5.0-alpha.5/src/env.rs:41
#42 0x00005613f46bba96 in grpcio::env::EnvBuilder::build::_$u7b$$u7b$closure$u7d$$u7d$::h4f88d46cea83e6de () at /rust/registry/src/github.com-1ecc6299db9ec823/grpcio-0.5.0-alpha.5/src/env.rs:95
#43 0x00005613f46a4596 in std::sys_common::backtrace::__rust_begin_short_backtrace::h2f0550034505a716 () at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/sys_common/backtrace.rs:136
#44 0x00005613f46a7657 in std::thread::Builder::spawn_unchecked::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h6eda5c21cce508df ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/thread/mod.rs:469
#45 0x00005613f46a4017 in _$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::h420eebe405cbfeae ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panic.rs:318
#46 0x00005613f46a7802 in std::panicking::try::do_call::hcb1797ad9ac26aa5 ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panicking.rs:292
#47 0x00005613f495bf1a in __rust_maybe_catch_panic () at src/libpanic_unwind/lib.rs:78
#48 0x00005613f46a7750 in std::panicking::try::h4eecdafda9029e06 ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panicking.rs:270
#49 0x00005613f46a6baa in std::panic::catch_unwind::hdec57120d98b91ec ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panic.rs:394
#50 0x00005613f46a7478 in std::thread::Builder::spawn_unchecked::_$u7b$$u7b$closure$u7d$$u7d$::h0a544f6309d03d9e () at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/thread/mod.rs:468

#51 0x00005613f4691497 in core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h3816da2a08d3ec8d ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ops/function.rs:232
#52 0x00005613f493fd9f in _$LT$alloc..boxed..Box$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::hbabfae4f70ab9609 ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/liballoc/boxed.rs:1022
#53 0x00005613f495afe0 in call_once<(),alloc::boxed::Box<FnOnce<()>>> ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/liballoc/boxed.rs:1022
#54 start_thread () at src/libstd/sys_common/thread.rs:13
#55 std::sys::unix::thread::Thread::new::thread_start::h3f42d1616b825de5 ()
    at src/libstd/sys/unix/thread.rs:80
#56 0x00007f0ab919cdd5 in start_thread (arg=0x7f0a90dff700) at pthread_create.c:307
#57 0x00007f0ab88a3ead in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by zhangjinpeng1987** [comment]
Seems the RocksDB is not close in time in the test?

**Comment by mahjonp** [comment]
Seems there was a similar issue in history: https://github.com/tikv/tikv/issues/1604
