### ISSUE TITLE
test raftstore::test_transfer_leader::test_server_transfer_leader_during_snapshot ... thread 'main' panicked

### ISSUE THREAD

**Issue by mahjonp** [tikv/tikv#7011]
raftstore::test_transfer_leader::test_server_transfer_leader_during_snapshot

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/18122/pipeline/234

Integration Part29

```
test raftstore::test_transfer_leader::test_server_transfer_leader_during_snapshot ... thread 'main' panicked at 'region Some(id: 1 region_epoch { conf_ver: 2 version: 1 } peers { id: 1 store_id: 1 } peers { id: 2 store_id: 2 }) has no peer id: 3 store_id: 3', components/test_raftstore/src/pd.rs:761:9

[2020-03-04T20:34:42.002Z] stack backtrace:

[2020-03-04T20:34:42.002Z]    0: backtrace::backtrace::libunwind::trace

[2020-03-04T20:34:42.002Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88

[2020-03-04T20:34:42.002Z]    1: backtrace::backtrace::trace_unsynchronized

[2020-03-04T20:34:42.002Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66

[2020-03-04T20:34:42.002Z]    2: std::sys_common::backtrace::_print_fmt

[2020-03-04T20:34:42.002Z]              at src/libstd/sys_common/backtrace.rs:84

[2020-03-04T20:34:42.002Z]    3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt

[2020-03-04T20:34:42.002Z]              at src/libstd/sys_common/backtrace.rs:61

[2020-03-04T20:34:42.002Z]    4: core::fmt::write

[2020-03-04T20:34:42.002Z]              at src/libcore/fmt/mod.rs:1025

[2020-03-04T20:34:42.002Z]    5: std::io::Write::write_fmt

[2020-03-04T20:34:42.002Z]              at src/libstd/io/mod.rs:1426

[2020-03-04T20:34:42.002Z]    6: std::sys_common::backtrace::_print

[2020-03-04T20:34:42.002Z]              at src/libstd/sys_common/backtrace.rs:65

[2020-03-04T20:34:42.002Z]    7: std::sys_common::backtrace::print

[2020-03-04T20:34:42.002Z]              at src/libstd/sys_common/backtrace.rs:50

[2020-03-04T20:34:42.002Z]    8: std::panicking::default_hook::{{closure}}

[2020-03-04T20:34:42.002Z]              at src/libstd/panicking.rs:193

[2020-03-04T20:34:42.002Z]    9: std::panicking::default_hook

[2020-03-04T20:34:42.002Z]              at src/libstd/panicking.rs:210

[2020-03-04T20:34:42.002Z]   10: std::panicking::rust_panic_with_hook

[2020-03-04T20:34:42.002Z]              at src/libstd/panicking.rs:471

[2020-03-04T20:34:42.002Z]   11: rust_begin_unwind

[2020-03-04T20:34:42.002Z]              at src/libstd/panicking.rs:375

[2020-03-04T20:34:42.002Z]   12: std::panicking::begin_panic_fmt

[2020-03-04T20:34:42.002Z]              at src/libstd/panicking.rs:326

[2020-03-04T20:34:42.003Z]   13: test_raftstore::pd::TestPdClient::must_have_peer

[2020-03-04T20:34:42.003Z]              at components/test_raftstore/src/pd.rs:761

[2020-03-04T20:34:42.003Z]   14: test_raftstore::pd::TestPdClient::must_add_peer

[2020-03-04T20:34:42.003Z]              at components/test_raftstore/src/pd.rs:858

[2020-03-04T20:34:42.003Z]   15: integrations::raftstore::test_transfer_leader::test_transfer_leader_during_snapshot

[2020-03-04T20:34:42.003Z]              at tests/integrations/raftstore/test_transfer_leader.rs:145

[2020-03-04T20:34:42.003Z]   16: integrations::raftstore::test_transfer_leader::test_server_transfer_leader_during_snapshot

[2020-03-04T20:34:42.003Z]              at tests/integrations/raftstore/test_transfer_leader.rs:162

[2020-03-04T20:34:42.003Z]   17: integrations::raftstore::test_transfer_leader::test_server_transfer_leader_during_snapshot::{{closure}}

[2020-03-04T20:34:42.003Z]              at tests/integrations/raftstore/test_transfer_leader.rs:160

[2020-03-04T20:34:42.003Z]   18: core::ops::function::FnOnce::call_once

[2020-03-04T20:34:42.003Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ops/function.rs:232

[2020-03-04T20:34:42.003Z]   19: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once

[2020-03-04T20:34:42.003Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/liballoc/boxed.rs:1022

[2020-03-04T20:34:42.003Z]   20: __rust_maybe_catch_panic

[2020-03-04T20:34:42.003Z]              at src/libpanic_unwind/lib.rs:78

[2020-03-04T20:34:42.003Z]   21: std::panicking::try

[2020-03-04T20:34:42.003Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panicking.rs:270

[2020-03-04T20:34:42.003Z]   22: std::panic::catch_unwind

[2020-03-04T20:34:42.003Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panic.rs:394

[2020-03-04T20:34:42.003Z]   23: test::run_test_in_process

[2020-03-04T20:34:42.003Z]              at src/libtest/lib.rs:567

[2020-03-04T20:34:42.003Z]   24: test::run_test::run_test_inner::{{closure}}

[2020-03-04T20:34:42.003Z]              at src/libtest/lib.rs:474

[2020-03-04T20:34:42.003Z]   25: test::run_test::run_test_inner

[2020-03-04T20:34:42.003Z]              at src/libtest/lib.rs:495

[2020-03-04T20:34:42.003Z]   26: test::run_test

[2020-03-04T20:34:42.003Z]              at src/libtest/lib.rs:531

[2020-03-04T20:34:42.003Z]   27: test::run_tests

[2020-03-04T20:34:42.003Z]              at src/libtest/lib.rs:300

[2020-03-04T20:34:42.003Z]   28: test::console::run_tests_console

[2020-03-04T20:34:42.003Z]              at src/libtest/console.rs:295

[2020-03-04T20:34:42.003Z]   29: test::test_main

[2020-03-04T20:34:42.003Z]              at src/libtest/lib.rs:121

[2020-03-04T20:34:42.003Z]   30: test::test_main_static

[2020-03-04T20:34:42.003Z]              at src/libtest/lib.rs:140

[2020-03-04T20:34:42.003Z]   31: integrations::main

[2020-03-04T20:34:42.003Z]   32: std::rt::lang_start::{{closure}}

[2020-03-04T20:34:42.003Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/rt.rs:67

[2020-03-04T20:34:42.003Z]   33: std::rt::lang_start_internal::{{closure}}

[2020-03-04T20:34:42.003Z]              at src/libstd/rt.rs:52

[2020-03-04T20:34:42.003Z]   34: std::panicking::try::do_call

[2020-03-04T20:34:42.003Z]              at src/libstd/panicking.rs:292

[2020-03-04T20:34:42.003Z]   35: __rust_maybe_catch_panic

[2020-03-04T20:34:42.003Z]              at src/libpanic_unwind/lib.rs:78

[2020-03-04T20:34:42.003Z]   36: std::panicking::try

[2020-03-04T20:34:42.003Z]              at src/libstd/panicking.rs:270

[2020-03-04T20:34:42.003Z]   37: std::panic::catch_unwind

[2020-03-04T20:34:42.003Z]              at src/libstd/panic.rs:394

[2020-03-04T20:34:42.003Z]   38: std::rt::lang_start_internal

[2020-03-04T20:34:42.003Z]              at src/libstd/rt.rs:51

[2020-03-04T20:34:42.003Z]   39: std::rt::lang_start

[2020-03-04T20:34:42.003Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/rt.rs:67

[2020-03-04T20:34:42.003Z]   40: main

[2020-03-04T20:34:42.003Z]   41: __libc_start_main

[2020-03-04T20:34:42.003Z]   42: <unknown>

[2020-03-04T20:34:42.003Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

[2020-03-04T20:34:54.176Z] FAILED

[2020-03-04T20:34:54.176Z] 

[2020-03-04T20:34:54.176Z] failures:

[2020-03-04T20:34:54.176Z] 

[2020-03-04T20:34:54.176Z] failures:

[2020-03-04T20:34:54.176Z]     raftstore::test_transfer_leader::test_server_transfer_leader_during_snapshot

[2020-03-04T20:34:54.176Z] 
```

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further feedback regarding this issue has been reported, it can be safely closed.
