### ISSUE TITLE
test test_cdc::test_cdc_not_leader ... thread 'main' panicked

### ISSUE THREAD

**Issue by mahjonp** [tikv/tikv#7043]
test_cdc::test_cdc_not_leader

```
[2020-03-09T03:05:09.375Z] running 1 test

[2020-03-09T03:05:12.045Z] test test_cdc::test_cdc_not_leader ... thread 'main' panicked at 'assertion failed: !suite.obs.get(&leader.get_store_id()).unwrap().is_subscribed(1)', components/cdc/tests/integrations/test_cdc.rs:436:5

[2020-03-09T03:05:12.045Z] stack backtrace:

[2020-03-09T03:05:12.972Z]    0: backtrace::backtrace::libunwind::trace

[2020-03-09T03:05:12.972Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88

[2020-03-09T03:05:12.972Z]    1: backtrace::backtrace::trace_unsynchronized

[2020-03-09T03:05:12.972Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66

[2020-03-09T03:05:12.972Z]    2: std::sys_common::backtrace::_print_fmt

[2020-03-09T03:05:12.972Z]              at src/libstd/sys_common/backtrace.rs:84

[2020-03-09T03:05:12.972Z]    3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt

[2020-03-09T03:05:12.972Z]              at src/libstd/sys_common/backtrace.rs:61

[2020-03-09T03:05:12.972Z]    4: core::fmt::write

[2020-03-09T03:05:12.972Z]              at src/libcore/fmt/mod.rs:1025

[2020-03-09T03:05:12.972Z]    5: std::io::Write::write_fmt

[2020-03-09T03:05:12.972Z]              at src/libstd/io/mod.rs:1426

[2020-03-09T03:05:12.972Z]    6: std::sys_common::backtrace::_print

[2020-03-09T03:05:12.972Z]              at src/libstd/sys_common/backtrace.rs:65

[2020-03-09T03:05:12.972Z]    7: std::sys_common::backtrace::print

[2020-03-09T03:05:12.972Z]              at src/libstd/sys_common/backtrace.rs:50

[2020-03-09T03:05:12.972Z]    8: std::panicking::default_hook::{{closure}}

[2020-03-09T03:05:12.972Z]              at src/libstd/panicking.rs:193

[2020-03-09T03:05:12.972Z]    9: std::panicking::default_hook

[2020-03-09T03:05:12.972Z]              at src/libstd/panicking.rs:210

[2020-03-09T03:05:12.972Z]   10: std::panicking::rust_panic_with_hook

[2020-03-09T03:05:12.972Z]              at src/libstd/panicking.rs:471

[2020-03-09T03:05:12.972Z]   11: std::panicking::begin_panic

[2020-03-09T03:05:12.972Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panicking.rs:404

[2020-03-09T03:05:12.972Z]   12: integrations::test_cdc::test_cdc_not_leader

[2020-03-09T03:05:12.972Z]              at components/cdc/tests/integrations/test_cdc.rs:436

[2020-03-09T03:05:12.972Z]   13: integrations::test_cdc::test_cdc_not_leader::{{closure}}

[2020-03-09T03:05:12.972Z]              at components/cdc/tests/integrations/test_cdc.rs:344

[2020-03-09T03:05:12.972Z]   14: core::ops::function::FnOnce::call_once

[2020-03-09T03:05:12.972Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ops/function.rs:232

[2020-03-09T03:05:12.972Z]   15: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once

[2020-03-09T03:05:12.972Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/liballoc/boxed.rs:1022

[2020-03-09T03:05:12.972Z]   16: __rust_maybe_catch_panic

[2020-03-09T03:05:12.972Z]              at src/libpanic_unwind/lib.rs:78

[2020-03-09T03:05:12.972Z]   17: std::panicking::try

[2020-03-09T03:05:12.972Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panicking.rs:270

[2020-03-09T03:05:12.972Z]   18: std::panic::catch_unwind

[2020-03-09T03:05:12.972Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panic.rs:394

[2020-03-09T03:05:12.972Z]   19: test::run_test_in_process

[2020-03-09T03:05:12.972Z]              at src/libtest/lib.rs:567

[2020-03-09T03:05:12.972Z]   20: test::run_test::run_test_inner::{{closure}}

[2020-03-09T03:05:12.972Z]              at src/libtest/lib.rs:474

[2020-03-09T03:05:12.972Z]   21: test::run_test::run_test_inner

[2020-03-09T03:05:12.972Z]              at src/libtest/lib.rs:495

[2020-03-09T03:05:12.972Z]   22: test::run_test

[2020-03-09T03:05:12.972Z]              at src/libtest/lib.rs:531

[2020-03-09T03:05:12.972Z]   23: test::run_tests

[2020-03-09T03:05:12.972Z]              at src/libtest/lib.rs:300

[2020-03-09T03:05:12.972Z]   24: test::console::run_tests_console

[2020-03-09T03:05:12.972Z]              at src/libtest/console.rs:295

[2020-03-09T03:05:12.972Z]   25: test::test_main

[2020-03-09T03:05:12.972Z]              at src/libtest/lib.rs:121

[2020-03-09T03:05:12.972Z]   26: test::test_main_static

[2020-03-09T03:05:12.972Z]              at src/libtest/lib.rs:140

[2020-03-09T03:05:12.972Z]   27: integrations::main

[2020-03-09T03:05:12.972Z]   28: std::rt::lang_start::{{closure}}

[2020-03-09T03:05:12.972Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/rt.rs:67

[2020-03-09T03:05:12.972Z]   29: std::rt::lang_start_internal::{{closure}}

[2020-03-09T03:05:12.972Z]              at src/libstd/rt.rs:52

[2020-03-09T03:05:12.972Z]   30: std::panicking::try::do_call

[2020-03-09T03:05:12.972Z]              at src/libstd/panicking.rs:292

[2020-03-09T03:05:12.972Z]   31: __rust_maybe_catch_panic

[2020-03-09T03:05:12.972Z]              at src/libpanic_unwind/lib.rs:78

[2020-03-09T03:05:12.972Z]   32: std::panicking::try

[2020-03-09T03:05:12.972Z]              at src/libstd/panicking.rs:270

[2020-03-09T03:05:12.972Z]   33: std::panic::catch_unwind

[2020-03-09T03:05:12.972Z]              at src/libstd/panic.rs:394

[2020-03-09T03:05:12.972Z]   34: std::rt::lang_start_internal

[2020-03-09T03:05:12.972Z]              at src/libstd/rt.rs:51

[2020-03-09T03:05:12.972Z]   35: std::rt::lang_start

[2020-03-09T03:05:12.972Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/rt.rs:67

[2020-03-09T03:05:12.972Z]   36: main

[2020-03-09T03:05:12.972Z]   37: __libc_start_main

[2020-03-09T03:05:12.972Z]   38: <unknown>

[2020-03-09T03:05:12.972Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

[2020-03-09T03:05:12.972Z] FAILED

[2020-03-09T03:05:12.972Z] 

[2020-03-09T03:05:12.972Z] failures:

[2020-03-09T03:05:12.972Z] 

[2020-03-09T03:05:12.972Z] failures:

[2020-03-09T03:05:12.972Z]     test_cdc::test_cdc_not_leader
```

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further feedback regarding this issue has been reported, it can be safely closed.
