### ISSUE TITLE
test server::lock_manager::test_detect_deadlock_when_merge_region ... thread 'main' panicked

### ISSUE THREAD

**Issue by mahjonp** [tikv/tikv#7066]
server::lock_manager::test_detect_deadlock_when_merge_region

https://internal.pingcap.net/idc-jenkins/view/ghpr_tikv/job/tikv_ghpr_test/18457/consoleFull

```
06:19:14  test server::lock_manager::test_detect_deadlock_when_merge_region ... thread 'main' panicked at 'failed to transfer leader to [1004] id: 1005 store_id: 1', components/test_raftstore/src/cluster.rs:836:17
06:19:14  stack backtrace:
06:19:14     0: backtrace::backtrace::libunwind::trace
06:19:14               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
06:19:14     1: backtrace::backtrace::trace_unsynchronized
06:19:14               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
06:19:14     2: std::sys_common::backtrace::_print_fmt
06:19:14               at src/libstd/sys_common/backtrace.rs:84
06:19:14     3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
06:19:14               at src/libstd/sys_common/backtrace.rs:61
06:19:14     4: core::fmt::write
06:19:14               at src/libcore/fmt/mod.rs:1025
06:19:14     5: std::io::Write::write_fmt
06:19:14               at src/libstd/io/mod.rs:1426
06:19:14     6: std::sys_common::backtrace::_print
06:19:14               at src/libstd/sys_common/backtrace.rs:65
06:19:14     7: std::sys_common::backtrace::print
06:19:14               at src/libstd/sys_common/backtrace.rs:50
06:19:14     8: std::panicking::default_hook::{{closure}}
06:19:14               at src/libstd/panicking.rs:193
06:19:14     9: std::panicking::default_hook
06:19:14               at src/libstd/panicking.rs:210
06:19:14    10: std::panicking::rust_panic_with_hook
06:19:14               at src/libstd/panicking.rs:471
06:19:14    11: rust_begin_unwind
06:19:14               at src/libstd/panicking.rs:375
06:19:14    12: std::panicking::begin_panic_fmt
06:19:14               at src/libstd/panicking.rs:326
06:19:14    13: test_raftstore::cluster::Cluster<T>::must_transfer_leader
06:19:14               at ./<::std::macros::panic macros>:9
06:19:14    14: integrations::server::lock_manager::must_transfer_leader
06:19:14               at tests/integrations/server/lock_manager.rs:129
06:19:14    15: integrations::server::lock_manager::test_detect_deadlock_when_merge_region
06:19:14               at tests/integrations/server/lock_manager.rs:275
06:19:14    16: integrations::server::lock_manager::test_detect_deadlock_when_merge_region::{{closure}}
06:19:14               at tests/integrations/server/lock_manager.rs:246
06:19:14    17: core::ops::function::FnOnce::call_once
06:19:14               at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ops/function.rs:232
06:19:14    18: test_util::runner::run_test_with_hook::{{closure}}::{{closure}}
06:19:14               at components/test_util/src/runner.rs:64
06:19:14    19: core::ops::function::FnOnce::call_once{{vtable.shim}}
06:19:14               at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ops/function.rs:232
06:19:14    20: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
06:19:14               at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/liballoc/boxed.rs:1022
06:19:14    21: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
06:19:14               at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/liballoc/boxed.rs:1022
06:19:14    22: __rust_maybe_catch_panic
06:19:14               at src/libpanic_unwind/lib.rs:78
06:19:14    23: std::panicking::try
06:19:14               at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panicking.rs:270
06:19:14    24: std::panic::catch_unwind
06:19:14               at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panic.rs:394
06:19:14    25: test::run_test_in_process
06:19:14               at src/libtest/lib.rs:567
06:19:14    26: test::run_test::run_test_inner::{{closure}}
06:19:14               at src/libtest/lib.rs:474
06:19:14    27: test::run_test::run_test_inner
06:19:14               at src/libtest/lib.rs:495
06:19:14    28: test::run_test
06:19:14               at src/libtest/lib.rs:524
06:19:14    29: test::run_tests
06:19:14               at src/libtest/lib.rs:300
06:19:14    30: test::console::run_tests_console
06:19:14               at src/libtest/console.rs:295
06:19:14    31: test::test_main
06:19:14               at src/libtest/lib.rs:121
06:19:14    32: test_util::runner::run_test_with_hook
06:19:14               at components/test_util/src/runner.rs:79
06:19:14    33: test_util::runner::run_tests
06:19:14               at components/test_util/src/runner.rs:13
06:19:14    34: integrations::main
06:19:14    35: std::rt::lang_start::{{closure}}
06:19:14               at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/rt.rs:67
06:19:14    36: std::rt::lang_start_internal::{{closure}}
06:19:14               at src/libstd/rt.rs:52
06:19:14    37: std::panicking::try::do_call
06:19:14               at src/libstd/panicking.rs:292
06:19:14    38: __rust_maybe_catch_panic
06:19:14               at src/libpanic_unwind/lib.rs:78
06:19:14    39: std::panicking::try
06:19:14               at src/libstd/panicking.rs:270
06:19:14    40: std::panic::catch_unwind
06:19:14               at src/libstd/panic.rs:394
06:19:14    41: std::rt::lang_start_internal
06:19:14               at src/libstd/rt.rs:51
06:19:14    42: std::rt::lang_start
06:19:14               at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/rt.rs:67
06:19:14    43: main
06:19:14    44: __libc_start_main
06:19:14    45: <unknown>
06:19:14  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further feedback regarding this issue has been reported, it can be safely closed.
