### ISSUE TITLE
raftstore::test_snap::test_node_snapshot_with_append

### ISSUE THREAD

**Issue by mahjonp** [tikv/tikv#7067]
raftstore::test_snap::test_node_snapshot_with_append

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/18457/pipeline/235 Integration Part22

```
[2020-03-11T06:18:52.400Z] test raftstore::test_snap::test_node_snapshot_with_append ... thread 'main' panicked at 'failed to transfer leader to [1] id: 1 store_id: 1', components/test_raftstore/src/cluster.rs:836:17

[2020-03-11T06:18:52.400Z] stack backtrace:

[2020-03-11T06:18:52.400Z]    0: backtrace::backtrace::libunwind::trace

[2020-03-11T06:18:52.400Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88

[2020-03-11T06:18:52.400Z]    1: backtrace::backtrace::trace_unsynchronized

[2020-03-11T06:18:52.400Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66

[2020-03-11T06:18:52.400Z]    2: std::sys_common::backtrace::_print_fmt

[2020-03-11T06:18:52.400Z]              at src/libstd/sys_common/backtrace.rs:84

[2020-03-11T06:18:52.400Z]    3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt

[2020-03-11T06:18:52.400Z]              at src/libstd/sys_common/backtrace.rs:61

[2020-03-11T06:18:52.400Z]    4: core::fmt::write

[2020-03-11T06:18:52.400Z]              at src/libcore/fmt/mod.rs:1025

[2020-03-11T06:18:52.400Z]    5: std::io::Write::write_fmt

[2020-03-11T06:18:52.400Z]              at src/libstd/io/mod.rs:1426

[2020-03-11T06:18:52.400Z]    6: std::sys_common::backtrace::_print

[2020-03-11T06:18:52.400Z]              at src/libstd/sys_common/backtrace.rs:65

[2020-03-11T06:18:52.400Z]    7: std::sys_common::backtrace::print

[2020-03-11T06:18:52.400Z]              at src/libstd/sys_common/backtrace.rs:50

[2020-03-11T06:18:52.400Z]    8: std::panicking::default_hook::{{closure}}

[2020-03-11T06:18:52.400Z]              at src/libstd/panicking.rs:193

[2020-03-11T06:18:52.400Z]    9: std::panicking::default_hook

[2020-03-11T06:18:52.400Z]              at src/libstd/panicking.rs:210

[2020-03-11T06:18:52.400Z]   10: std::panicking::rust_panic_with_hook

[2020-03-11T06:18:52.400Z]              at src/libstd/panicking.rs:471

[2020-03-11T06:18:52.400Z]   11: rust_begin_unwind

[2020-03-11T06:18:52.400Z]              at src/libstd/panicking.rs:375

[2020-03-11T06:18:52.400Z]   12: std::panicking::begin_panic_fmt

[2020-03-11T06:18:52.400Z]              at src/libstd/panicking.rs:326

[2020-03-11T06:18:52.400Z]   13: test_raftstore::cluster::Cluster<T>::must_transfer_leader

[2020-03-11T06:18:52.400Z]              at ./<::std::macros::panic macros>:9

[2020-03-11T06:18:52.400Z]   14: integrations::raftstore::test_snap::test_snapshot_with_append

[2020-03-11T06:18:52.400Z]              at tests/integrations/raftstore/test_snap.rs:418

[2020-03-11T06:18:52.400Z]   15: integrations::raftstore::test_snap::test_node_snapshot_with_append

[2020-03-11T06:18:52.400Z]              at tests/integrations/raftstore/test_snap.rs:438

[2020-03-11T06:18:52.400Z]   16: integrations::raftstore::test_snap::test_node_snapshot_with_append::{{closure}}

[2020-03-11T06:18:52.400Z]              at tests/integrations/raftstore/test_snap.rs:436

[2020-03-11T06:18:52.400Z]   17: core::ops::function::FnOnce::call_once

[2020-03-11T06:18:52.400Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ops/function.rs:232

[2020-03-11T06:18:52.400Z]   18: test_util::runner::run_test_with_hook::{{closure}}::{{closure}}

[2020-03-11T06:18:52.400Z]              at components/test_util/src/runner.rs:64

[2020-03-11T06:18:52.400Z]   19: core::ops::function::FnOnce::call_once{{vtable.shim}}

[2020-03-11T06:18:52.400Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ops/function.rs:232

[2020-03-11T06:18:52.400Z]   20: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once

[2020-03-11T06:18:52.400Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/liballoc/boxed.rs:1022

[2020-03-11T06:18:52.400Z]   21: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once

[2020-03-11T06:18:52.400Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/liballoc/boxed.rs:1022

[2020-03-11T06:18:52.400Z]   22: __rust_maybe_catch_panic

[2020-03-11T06:18:52.400Z]              at src/libpanic_unwind/lib.rs:78

[2020-03-11T06:18:52.400Z]   23: std::panicking::try

[2020-03-11T06:18:52.400Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panicking.rs:270

[2020-03-11T06:18:52.400Z]   24: std::panic::catch_unwind

[2020-03-11T06:18:52.400Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panic.rs:394

[2020-03-11T06:18:52.400Z]   25: test::run_test_in_process

[2020-03-11T06:18:52.400Z]              at src/libtest/lib.rs:567

[2020-03-11T06:18:52.400Z]   26: test::run_test::run_test_inner::{{closure}}

[2020-03-11T06:18:52.400Z]              at src/libtest/lib.rs:474

[2020-03-11T06:18:52.400Z]   27: test::run_test::run_test_inner

[2020-03-11T06:18:52.400Z]              at src/libtest/lib.rs:495

[2020-03-11T06:18:52.400Z]   28: test::run_test

[2020-03-11T06:18:52.400Z]              at src/libtest/lib.rs:524

[2020-03-11T06:18:52.401Z]   29: test::run_tests

[2020-03-11T06:18:52.401Z]              at src/libtest/lib.rs:300

[2020-03-11T06:18:52.401Z]   30: test::console::run_tests_console

[2020-03-11T06:18:52.401Z]              at src/libtest/console.rs:295

[2020-03-11T06:18:52.401Z]   31: test::test_main

[2020-03-11T06:18:52.401Z]              at src/libtest/lib.rs:121

[2020-03-11T06:18:52.401Z]   32: test_util::runner::run_test_with_hook

[2020-03-11T06:18:52.401Z]              at components/test_util/src/runner.rs:79

[2020-03-11T06:18:52.401Z]   33: test_util::runner::run_tests

[2020-03-11T06:18:52.401Z]              at components/test_util/src/runner.rs:13

[2020-03-11T06:18:52.401Z]   34: integrations::main

[2020-03-11T06:18:52.401Z]   35: std::rt::lang_start::{{closure}}

[2020-03-11T06:18:52.401Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/rt.rs:67

[2020-03-11T06:18:52.401Z]   36: std::rt::lang_start_internal::{{closure}}

[2020-03-11T06:18:52.401Z]              at src/libstd/rt.rs:52

[2020-03-11T06:18:52.401Z]   37: std::panicking::try::do_call

[2020-03-11T06:18:52.401Z]              at src/libstd/panicking.rs:292

[2020-03-11T06:18:52.401Z]   38: __rust_maybe_catch_panic

[2020-03-11T06:18:52.401Z]              at src/libpanic_unwind/lib.rs:78

[2020-03-11T06:18:52.401Z]   39: std::panicking::try

[2020-03-11T06:18:52.401Z]              at src/libstd/panicking.rs:270

[2020-03-11T06:18:52.401Z]   40: std::panic::catch_unwind

[2020-03-11T06:18:52.401Z]              at src/libstd/panic.rs:394

[2020-03-11T06:18:52.401Z]   41: std::rt::lang_start_internal

[2020-03-11T06:18:52.401Z]              at src/libstd/rt.rs:51

[2020-03-11T06:18:52.401Z]   42: std::rt::lang_start

[2020-03-11T06:18:52.401Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/rt.rs:67

[2020-03-11T06:18:52.401Z]   43: main

[2020-03-11T06:18:52.401Z]   44: __libc_start_main

[2020-03-11T06:18:52.401Z]   45: <unknown>

[2020-03-11T06:18:52.401Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

[2020-03-11T06:18:52.401Z] FAILED

[2020-03-11T06:19:04.597Z] test raftstore::test_stale_peer::test_stale_learner ... ok

[2020-03-11T06:19:05.963Z] test storage::test_storage::test_isolation_inc ... ok

[2020-03-11T06:19:05.963Z] 

[2020-03-11T06:19:05.963Z] failures:

[2020-03-11T06:19:05.963Z] 

[2020-03-11T06:19:05.963Z] failures:

[2020-03-11T06:19:05.963Z]     raftstore::test_snap::test_node_snapshot_with_append
```

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further feedback regarding this issue has been reported, it can be safely closed.
