### ISSUE TITLE
test raftstore::test_snap::test_node_cf_snapshot ... thread 'test-pd-worker' panicked

### ISSUE THREAD

**Issue by mahjonp** [tikv/tikv#7079]
raftstore::test_snap::test_node_cf_snapshot

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/18544/pipeline/226 Integration Part13
```
[2020-03-12T09:18:31.658Z] test raftstore::test_snap::test_node_cf_snapshot ... thread 'test-pd-worker' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/macros/mod.rs:15:40

[2020-03-12T09:18:31.658Z] stack backtrace:

[2020-03-12T09:18:32.227Z]    0: backtrace::backtrace::libunwind::trace

[2020-03-12T09:18:32.227Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88

[2020-03-12T09:18:32.227Z]    1: backtrace::backtrace::trace_unsynchronized

[2020-03-12T09:18:32.227Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66

[2020-03-12T09:18:32.227Z]    2: std::sys_common::backtrace::_print_fmt

[2020-03-12T09:18:32.227Z]              at src/libstd/sys_common/backtrace.rs:84

[2020-03-12T09:18:32.227Z]    3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt

[2020-03-12T09:18:32.227Z]              at src/libstd/sys_common/backtrace.rs:61

[2020-03-12T09:18:32.227Z]    4: core::fmt::write

[2020-03-12T09:18:32.227Z]              at src/libcore/fmt/mod.rs:1025

[2020-03-12T09:18:32.227Z]    5: std::io::Write::write_fmt

[2020-03-12T09:18:32.227Z]              at src/libstd/io/mod.rs:1426

[2020-03-12T09:18:32.227Z]    6: std::sys_common::backtrace::_print

[2020-03-12T09:18:32.227Z]              at src/libstd/sys_common/backtrace.rs:65

[2020-03-12T09:18:32.227Z]    7: std::sys_common::backtrace::print

[2020-03-12T09:18:32.227Z]              at src/libstd/sys_common/backtrace.rs:50

[2020-03-12T09:18:32.227Z]    8: std::panicking::default_hook::{{closure}}

[2020-03-12T09:18:32.227Z]              at src/libstd/panicking.rs:193

[2020-03-12T09:18:32.227Z]    9: std::panicking::default_hook

[2020-03-12T09:18:32.227Z]              at src/libstd/panicking.rs:210

[2020-03-12T09:18:32.227Z]   10: std::panicking::rust_panic_with_hook

[2020-03-12T09:18:32.227Z]              at src/libstd/panicking.rs:471

[2020-03-12T09:18:32.227Z]   11: rust_begin_unwind

[2020-03-12T09:18:32.227Z]              at src/libstd/panicking.rs:375

[2020-03-12T09:18:32.227Z]   12: core::panicking::panic_fmt

[2020-03-12T09:18:32.227Z]              at src/libcore/panicking.rs:84

[2020-03-12T09:18:32.227Z]   13: core::panicking::panic

[2020-03-12T09:18:32.227Z]              at src/libcore/panicking.rs:51

[2020-03-12T09:18:32.227Z]   14: core::option::Option<T>::unwrap

[2020-03-12T09:18:32.227Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/macros/mod.rs:15

[2020-03-12T09:18:32.227Z]   15: <test_raftstore::pd::TestPdClient as pd_client::PdClient>::handle_region_heartbeat_response

[2020-03-12T09:18:32.227Z]              at components/test_raftstore/src/pd.rs:1091

[2020-03-12T09:18:32.227Z]   16: raftstore::store::worker::pd::Runner<T>::schedule_heartbeat_receiver

[2020-03-12T09:18:32.227Z]              at ./components/raftstore/src/store/worker/pd.rs:705

[2020-03-12T09:18:32.227Z]   17: <raftstore::store::worker::pd::Runner<T> as tikv_util::worker::future::Runnable<raftstore::store::worker::pd::Task>>::run

[2020-03-12T09:18:32.227Z]              at ./components/raftstore/src/store/worker/pd.rs:847

[2020-03-12T09:18:32.227Z]   18: tikv_util::worker::future::poll::{{closure}}

[2020-03-12T09:18:32.227Z]              at ./components/tikv_util/src/worker/future.rs:108

[2020-03-12T09:18:32.227Z]   19: <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll

[2020-03-12T09:18:32.227Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/stream/for_each.rs:46

[2020-03-12T09:18:32.227Z]   20: futures::task_impl::Spawn<T>::poll_future_notify::{{closure}}

[2020-03-12T09:18:32.227Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:329

[2020-03-12T09:18:32.227Z]   21: futures::task_impl::Spawn<T>::enter::{{closure}}

[2020-03-12T09:18:32.227Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:399

[2020-03-12T09:18:32.227Z]   22: futures::task_impl::std::set

[2020-03-12T09:18:32.227Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/std/mod.rs:83

[2020-03-12T09:18:32.227Z]   23: futures::task_impl::Spawn<T>::enter

[2020-03-12T09:18:32.227Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:399

[2020-03-12T09:18:32.227Z]   24: futures::task_impl::Spawn<T>::poll_fn_notify

[2020-03-12T09:18:32.227Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:291

[2020-03-12T09:18:32.228Z]   25: futures::task_impl::Spawn<T>::poll_future_notify

[2020-03-12T09:18:32.228Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:329

[2020-03-12T09:18:32.228Z]   26: tokio_core::reactor::Core::run::{{closure}}::{{closure}}::{{closure}}::{{closure}}::{{closure}}

[2020-03-12T09:18:32.228Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:236

[2020-03-12T09:18:32.228Z]   27: futures::future::lazy::Lazy<F,R>::get

[2020-03-12T09:18:32.228Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/lazy.rs:64

[2020-03-12T09:18:32.228Z]   28: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll

[2020-03-12T09:18:32.228Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/lazy.rs:82

[2020-03-12T09:18:32.228Z]   29: futures::task_impl::Spawn<T>::poll_future_notify::{{closure}}

[2020-03-12T09:18:32.228Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:329

[2020-03-12T09:18:32.228Z]   30: futures::task_impl::Spawn<T>::enter::{{closure}}

[2020-03-12T09:18:32.228Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:399

[2020-03-12T09:18:32.228Z]   31: futures::task_impl::std::set

[2020-03-12T09:18:32.228Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/std/mod.rs:83

[2020-03-12T09:18:32.228Z]   32: futures::task_impl::Spawn<T>::enter

[2020-03-12T09:18:32.228Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:399

[2020-03-12T09:18:32.228Z]   33: futures::task_impl::Spawn<T>::poll_fn_notify

[2020-03-12T09:18:32.228Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:291

[2020-03-12T09:18:32.228Z]   34: futures::task_impl::Spawn<T>::poll_future_notify

[2020-03-12T09:18:32.228Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:329

[2020-03-12T09:18:32.228Z]   35: tokio_current_thread::Entered<P>::block_on::{{closure}}

[2020-03-12T09:18:32.228Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.6/src/lib.rs:494

[2020-03-12T09:18:32.228Z]   36: tokio_current_thread::Borrow<U>::enter::{{closure}}::{{closure}}

[2020-03-12T09:18:32.228Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.6/src/lib.rs:788

[2020-03-12T09:18:32.228Z]   37: tokio_current_thread::CurrentRunner::set_spawn

[2020-03-12T09:18:32.228Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.6/src/lib.rs:825

[2020-03-12T09:18:32.228Z]   38: tokio_current_thread::Borrow<U>::enter::{{closure}}

[2020-03-12T09:18:32.228Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.6/src/lib.rs:788

[2020-03-12T09:18:32.228Z]   39: std::thread::local::LocalKey<T>::try_with

[2020-03-12T09:18:32.228Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/thread/local.rs:262

[2020-03-12T09:18:32.228Z]   40: std::thread::local::LocalKey<T>::with

[2020-03-12T09:18:32.228Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/thread/local.rs:239

[2020-03-12T09:18:32.228Z]   41: tokio_current_thread::Borrow<U>::enter

[2020-03-12T09:18:32.228Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.6/src/lib.rs:786

[2020-03-12T09:18:32.228Z]   42: tokio_current_thread::Entered<P>::block_on

[2020-03-12T09:18:32.228Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.6/src/lib.rs:491

[2020-03-12T09:18:32.228Z]   43: tokio_core::reactor::Core::run::{{closure}}::{{closure}}::{{closure}}::{{closure}}

[2020-03-12T09:18:32.228Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:234

[2020-03-12T09:18:32.228Z]   44: tokio_timer::timer::handle::with_default::{{closure}}

[2020-03-12T09:18:32.228Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/timer/handle.rs:101

[2020-03-12T09:18:32.228Z]   45: std::thread::local::LocalKey<T>::try_with

[2020-03-12T09:18:32.228Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/thread/local.rs:262

[2020-03-12T09:18:32.228Z]   46: std::thread::local::LocalKey<T>::with

[2020-03-12T09:18:32.228Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/thread/local.rs:239

[2020-03-12T09:18:32.228Z]   47: tokio_timer::timer::handle::with_default

[2020-03-12T09:18:32.228Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/timer/handle.rs:84

[2020-03-12T09:18:32.228Z]   48: tokio_core::reactor::Core::run::{{closure}}::{{closure}}::{{closure}}

[2020-03-12T09:18:32.228Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:233

[2020-03-12T09:18:32.228Z]   49: tokio_executor::global::with_default::{{closure}}

[2020-03-12T09:18:32.228Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.8/src/global.rs:209

[2020-03-12T09:18:32.228Z]   50: std::thread::local::LocalKey<T>::try_with

[2020-03-12T09:18:32.228Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/thread/local.rs:262

[2020-03-12T09:18:32.228Z]   51: std::thread::local::LocalKey<T>::with

[2020-03-12T09:18:32.228Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/thread/local.rs:239

[2020-03-12T09:18:32.228Z]   52: tokio_executor::global::with_default

[2020-03-12T09:18:32.228Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.8/src/global.rs:178

[2020-03-12T09:18:32.228Z]   53: tokio_core::reactor::Core::run::{{closure}}::{{closure}}

[2020-03-12T09:18:32.228Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:232

[2020-03-12T09:18:32.228Z]   54: tokio_reactor::with_default::{{closure}}

[2020-03-12T09:18:32.228Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.9/src/lib.rs:237

[2020-03-12T09:18:32.228Z]   55: std::thread::local::LocalKey<T>::try_with

[2020-03-12T09:18:32.228Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/thread/local.rs:262

[2020-03-12T09:18:32.228Z]   56: std::thread::local::LocalKey<T>::with

[2020-03-12T09:18:32.228Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/thread/local.rs:239

[2020-03-12T09:18:32.228Z]   57: tokio_reactor::with_default

[2020-03-12T09:18:32.228Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.9/src/lib.rs:217

[2020-03-12T09:18:32.228Z]   58: tokio_core::reactor::Core::run::{{closure}}

[2020-03-12T09:18:32.228Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:231

[2020-03-12T09:18:32.228Z]   59: scoped_tls::ScopedKey<T>::set

[2020-03-12T09:18:32.228Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.2/src/lib.rs:155

[2020-03-12T09:18:32.228Z]   60: tokio_core::reactor::Core::run

[2020-03-12T09:18:32.228Z]              at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:230

[2020-03-12T09:18:32.228Z]   61: tikv_util::worker::future::poll

[2020-03-12T09:18:32.228Z]              at ./components/tikv_util/src/worker/future.rs:114

[2020-03-12T09:18:32.228Z]   62: tikv_util::worker::future::Worker<T>::start::{{closure}}

[2020-03-12T09:18:32.228Z]              at ./components/tikv_util/src/worker/future.rs:145

[2020-03-12T09:18:32.228Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further feedback regarding this issue has been reported, it can be safely closed.
