### ISSUE TITLE
test raftstore::test_hibernate::test_proposal_prevent_sleep ... thread 'main' panicked

### ISSUE THREAD

**Issue by mahjonp** [tikv/tikv#7080]
raftstore::test_hibernate::test_proposal_prevent_sleep

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/18554/pipeline/230  Integration Part17

```
[2020-03-12T10:57:20.617Z] test raftstore::test_hibernate::test_proposal_prevent_sleep ... thread 'main' panicked at 'region Some(id: 1 region_epoch { conf_ver: 1 version: 1 } peers { id: 1 store_id: 1 } peers { id: 2 store_id: 2 } peers { id: 3 store_id: 3 }) has peer id: 3 store_id: 3', components/test_raftstore/src/pd.rs:762:9

[2020-03-12T10:57:20.617Z] stack backtrace:

[2020-03-12T10:57:20.617Z]    0: backtrace::backtrace::libunwind::trace

[2020-03-12T10:57:20.617Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88

[2020-03-12T10:57:20.617Z]    1: backtrace::backtrace::trace_unsynchronized

[2020-03-12T10:57:20.617Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66

[2020-03-12T10:57:20.617Z]    2: std::sys_common::backtrace::_print_fmt

[2020-03-12T10:57:20.617Z]              at src/libstd/sys_common/backtrace.rs:84

[2020-03-12T10:57:20.617Z]    3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt

[2020-03-12T10:57:20.617Z]              at src/libstd/sys_common/backtrace.rs:61

[2020-03-12T10:57:20.617Z]    4: core::fmt::write

[2020-03-12T10:57:20.617Z]              at src/libcore/fmt/mod.rs:1025

[2020-03-12T10:57:20.617Z]    5: std::io::Write::write_fmt

[2020-03-12T10:57:20.617Z]              at src/libstd/io/mod.rs:1426

[2020-03-12T10:57:20.617Z]    6: std::sys_common::backtrace::_print

[2020-03-12T10:57:20.617Z]              at src/libstd/sys_common/backtrace.rs:65

[2020-03-12T10:57:20.617Z]    7: std::sys_common::backtrace::print

[2020-03-12T10:57:20.617Z]              at src/libstd/sys_common/backtrace.rs:50

[2020-03-12T10:57:20.617Z]    8: std::panicking::default_hook::{{closure}}

[2020-03-12T10:57:20.617Z]              at src/libstd/panicking.rs:193

[2020-03-12T10:57:20.617Z]    9: std::panicking::default_hook

[2020-03-12T10:57:20.617Z]              at src/libstd/panicking.rs:210

[2020-03-12T10:57:20.617Z]   10: std::panicking::rust_panic_with_hook

[2020-03-12T10:57:20.617Z]              at src/libstd/panicking.rs:471

[2020-03-12T10:57:20.617Z]   11: rust_begin_unwind

[2020-03-12T10:57:20.617Z]              at src/libstd/panicking.rs:375

[2020-03-12T10:57:20.617Z]   12: std::panicking::begin_panic_fmt

[2020-03-12T10:57:20.617Z]              at src/libstd/panicking.rs:326

[2020-03-12T10:57:20.617Z]   13: test_raftstore::pd::TestPdClient::must_none_peer

[2020-03-12T10:57:20.617Z]   14: integrations::raftstore::test_hibernate::test_proposal_prevent_sleep

[2020-03-12T10:57:20.617Z]              at tests/integrations/raftstore/test_hibernate.rs:102

[2020-03-12T10:57:20.617Z]   15: integrations::raftstore::test_hibernate::test_proposal_prevent_sleep::{{closure}}

[2020-03-12T10:57:20.617Z]              at tests/integrations/raftstore/test_hibernate.rs:14

[2020-03-12T10:57:20.617Z]   16: core::ops::function::FnOnce::call_once

[2020-03-12T10:57:20.617Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ops/function.rs:232

[2020-03-12T10:57:20.617Z]   17: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once

[2020-03-12T10:57:20.617Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/liballoc/boxed.rs:1022

[2020-03-12T10:57:20.617Z]   18: __rust_maybe_catch_panic

[2020-03-12T10:57:20.617Z]              at src/libpanic_unwind/lib.rs:78

[2020-03-12T10:57:20.617Z]   19: std::panicking::try

[2020-03-12T10:57:20.617Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panicking.rs:270

[2020-03-12T10:57:20.617Z]   20: std::panic::catch_unwind

[2020-03-12T10:57:20.617Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panic.rs:394

[2020-03-12T10:57:20.617Z]   21: test::run_test_in_process

[2020-03-12T10:57:20.617Z]              at src/libtest/lib.rs:567

[2020-03-12T10:57:20.617Z]   22: test::run_test::run_test_inner::{{closure}}

[2020-03-12T10:57:20.617Z]              at src/libtest/lib.rs:474

[2020-03-12T10:57:20.617Z]   23: test::run_test::run_test_inner

[2020-03-12T10:57:20.618Z]              at src/libtest/lib.rs:495

[2020-03-12T10:57:20.618Z]   24: test::run_test

[2020-03-12T10:57:20.618Z]              at src/libtest/lib.rs:531

[2020-03-12T10:57:20.618Z]   25: test::run_tests

[2020-03-12T10:57:20.618Z]              at src/libtest/lib.rs:300

[2020-03-12T10:57:20.618Z]   26: test::console::run_tests_console

[2020-03-12T10:57:20.618Z]              at src/libtest/console.rs:295

[2020-03-12T10:57:20.618Z]   27: test::test_main

[2020-03-12T10:57:20.618Z]              at src/libtest/lib.rs:121

[2020-03-12T10:57:20.618Z]   28: test::test_main_static

[2020-03-12T10:57:20.618Z]              at src/libtest/lib.rs:140

[2020-03-12T10:57:20.618Z]   29: integrations::main

[2020-03-12T10:57:20.618Z]   30: std::rt::lang_start::{{closure}}

[2020-03-12T10:57:20.618Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/rt.rs:67

[2020-03-12T10:57:20.618Z]   31: std::rt::lang_start_internal::{{closure}}

[2020-03-12T10:57:20.618Z]              at src/libstd/rt.rs:52

[2020-03-12T10:57:20.618Z]   32: std::panicking::try::do_call

[2020-03-12T10:57:20.618Z]              at src/libstd/panicking.rs:292

[2020-03-12T10:57:20.618Z]   33: __rust_maybe_catch_panic

[2020-03-12T10:57:20.618Z]              at src/libpanic_unwind/lib.rs:78

[2020-03-12T10:57:20.618Z]   34: std::panicking::try

[2020-03-12T10:57:20.618Z]              at src/libstd/panicking.rs:270

[2020-03-12T10:57:20.618Z]   35: std::panic::catch_unwind

[2020-03-12T10:57:20.618Z]              at src/libstd/panic.rs:394

[2020-03-12T10:57:20.618Z]   36: std::rt::lang_start_internal

[2020-03-12T10:57:20.618Z]              at src/libstd/rt.rs:51

[2020-03-12T10:57:20.618Z]   37: std::rt::lang_start

[2020-03-12T10:57:20.618Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/rt.rs:67

[2020-03-12T10:57:20.618Z]   38: main

[2020-03-12T10:57:20.618Z]   39: __libc_start_main

[2020-03-12T10:57:20.618Z]   40: <unknown>

[2020-03-12T10:57:20.618Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

[2020-03-12T10:57:20.618Z] FAILED

[2020-03-12T10:57:22.511Z] test raftstore::test_multi::test_multi_server_random_restart ... ok

[2020-03-12T10:57:22.768Z] test raftstore::test_service::test_rawkv ... ok

[2020-03-12T10:57:24.137Z] test raftstore::test_split_region::test_server_quick_election_after_split ... ok

[2020-03-12T10:57:50.650Z] test storage::test_raft_storage::test_auto_gc ... ok

[2020-03-12T10:57:50.907Z] test storage::test_storage::test_txn_store_scan ... ok

[2020-03-12T10:57:50.907Z] 

[2020-03-12T10:57:50.907Z] failures:

[2020-03-12T10:57:50.907Z] 

[2020-03-12T10:57:50.907Z] failures:

[2020-03-12T10:57:50.907Z]     raftstore::test_hibernate::test_proposal_prevent_sleep
```

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further feedback regarding this issue has been reported, it can be safely closed.
