### ISSUE TITLE
test raftstore::test_snap::test_server_concurrent_snap ... thread 'raftstore-3-0' panicked

### ISSUE THREAD

**Issue by mahjonp** [tikv/tikv#7081]
raftstore::test_snap::test_server_concurrent_snap

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/18521/pipeline/232 Integration Part19

```
[2020-03-12T04:42:37.873Z] test raftstore::test_snap::test_server_concurrent_snap ... thread 'raftstore-3-0' panicked at 'applied(6) is out of range [prev_applied(0), committed(0), raft_id: 1003, region_id: 1000', /rust/git/checkouts/raft-rs-841f8a6db665c5c0/afabefa/src/raft_log.rs:259:13

[2020-03-12T04:42:37.873Z] stack backtrace:

[2020-03-12T04:42:38.437Z]    0: backtrace::backtrace::libunwind::trace

[2020-03-12T04:42:38.437Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88

[2020-03-12T04:42:38.437Z]    1: backtrace::backtrace::trace_unsynchronized

[2020-03-12T04:42:38.437Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66

[2020-03-12T04:42:38.437Z]    2: std::sys_common::backtrace::_print_fmt

[2020-03-12T04:42:38.437Z]              at src/libstd/sys_common/backtrace.rs:84

[2020-03-12T04:42:38.437Z]    3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt

[2020-03-12T04:42:38.437Z]              at src/libstd/sys_common/backtrace.rs:61

[2020-03-12T04:42:38.437Z]    4: core::fmt::write

[2020-03-12T04:42:38.437Z]              at src/libcore/fmt/mod.rs:1025

[2020-03-12T04:42:38.437Z]    5: std::io::Write::write_fmt

[2020-03-12T04:42:38.437Z]              at src/libstd/io/mod.rs:1426

[2020-03-12T04:42:38.437Z]    6: std::sys_common::backtrace::_print

[2020-03-12T04:42:38.437Z]              at src/libstd/sys_common/backtrace.rs:65

[2020-03-12T04:42:38.437Z]    7: std::sys_common::backtrace::print

[2020-03-12T04:42:38.437Z]              at src/libstd/sys_common/backtrace.rs:50

[2020-03-12T04:42:38.437Z]    8: std::panicking::default_hook::{{closure}}

[2020-03-12T04:42:38.437Z]              at src/libstd/panicking.rs:193

[2020-03-12T04:42:38.437Z]    9: std::panicking::default_hook

[2020-03-12T04:42:38.437Z]              at src/libstd/panicking.rs:210

[2020-03-12T04:42:38.437Z]   10: std::panicking::rust_panic_with_hook

[2020-03-12T04:42:38.437Z]              at src/libstd/panicking.rs:471

[2020-03-12T04:42:38.437Z]   11: rust_begin_unwind

[2020-03-12T04:42:38.437Z]              at src/libstd/panicking.rs:375

[2020-03-12T04:42:38.437Z]   12: std::panicking::begin_panic_fmt

[2020-03-12T04:42:38.437Z]              at src/libstd/panicking.rs:326

[2020-03-12T04:42:38.437Z]   13: raft::raft_log::RaftLog<T>::applied_to

[2020-03-12T04:42:38.437Z]              at ./<::std::macros::panic macros>:9

[2020-03-12T04:42:38.437Z]   14: raft::raft::Raft<T>::commit_apply

[2020-03-12T04:42:38.437Z]              at /rust/git/checkouts/raft-rs-841f8a6db665c5c0/afabefa/src/raft.rs:647

[2020-03-12T04:42:38.437Z]   15: raft::raw_node::RawNode<T>::commit_apply

[2020-03-12T04:42:38.437Z]              at /rust/git/checkouts/raft-rs-841f8a6db665c5c0/afabefa/src/raw_node.rs:263

[2020-03-12T04:42:38.438Z]   16: raft::raw_node::RawNode<T>::advance_apply

[2020-03-12T04:42:38.438Z]              at /rust/git/checkouts/raft-rs-841f8a6db665c5c0/afabefa/src/raw_node.rs:429

[2020-03-12T04:42:38.438Z]   17: raftstore::store::peer::Peer::handle_raft_ready_apply

[2020-03-12T04:42:38.438Z]              at ./components/raftstore/src/store/peer.rs:1391

[2020-03-12T04:42:38.438Z]   18: raftstore::store::fsm::peer::PeerFsmDelegate<T,C>::post_raft_ready_append

[2020-03-12T04:42:38.438Z]              at ./components/raftstore/src/store/fsm/peer.rs:611

[2020-03-12T04:42:38.438Z]   19: raftstore::store::fsm::store::RaftPoller<T,C>::handle_raft_ready

[2020-03-12T04:42:38.438Z]              at ./components/raftstore/src/store/fsm/store.rs:553

[2020-03-12T04:42:38.438Z]   20: <raftstore::store::fsm::store::RaftPoller<T,C> as batch_system::batch::PollHandler<raftstore::store::fsm::peer::PeerFsm<engine_rocks::engine::RocksEngine>,raftstore::store::fsm::store::StoreFsm>>::end

[2020-03-12T04:42:38.438Z]              at ./components/raftstore/src/store/fsm/store.rs:688

[2020-03-12T04:42:38.438Z]   21: batch_system::batch::Poller<N,C,Handler>::poll

[2020-03-12T04:42:38.438Z]              at ./components/batch-system/src/batch.rs:329

[2020-03-12T04:42:38.438Z]   22: batch_system::batch::BatchSystem<N,C>::spawn::{{closure}}

[2020-03-12T04:42:38.438Z]              at ./components/batch-system/src/batch.rs:392

[2020-03-12T04:42:38.438Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

[2020-03-12T04:42:43.694Z] thread 'main' panicked at 'can't get value Some("v11") for key 6B3131', components/test_raftstore/src/util.rs:57:5
```

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further feedback regarding this issue has been reported, it can be safely closed.
