### ISSUE TITLE
test cases::test_merge::test_node_merge_recover_snapshot ... thread 'main' panicked

### ISSUE THREAD

**Issue by mahjonp** [tikv/tikv#7092]
cases::test_merge::test_node_merge_recover_snapshot

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/18615/pipeline/114 #Failpoints Part1

```
[2020-03-13T08:39:43.614Z] test cases::test_merge::test_node_merge_recover_snapshot ... thread 'main' panicked at 'request timeout', components/test_raftstore/src/cluster.rs:626:9

[2020-03-13T08:39:43.614Z] stack backtrace:

[2020-03-13T08:39:44.176Z]    0: backtrace::backtrace::libunwind::trace

[2020-03-13T08:39:44.176Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88

[2020-03-13T08:39:44.176Z]    1: backtrace::backtrace::trace_unsynchronized

[2020-03-13T08:39:44.176Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66

[2020-03-13T08:39:44.176Z]    2: std::sys_common::backtrace::_print_fmt

[2020-03-13T08:39:44.176Z]              at src/libstd/sys_common/backtrace.rs:84

[2020-03-13T08:39:44.176Z]    3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt

[2020-03-13T08:39:44.176Z]              at src/libstd/sys_common/backtrace.rs:61

[2020-03-13T08:39:44.176Z]    4: core::fmt::write

[2020-03-13T08:39:44.176Z]              at src/libcore/fmt/mod.rs:1025

[2020-03-13T08:39:44.176Z]    5: std::io::Write::write_fmt

[2020-03-13T08:39:44.176Z]              at src/libstd/io/mod.rs:1426

[2020-03-13T08:39:44.176Z]    6: std::sys_common::backtrace::_print

[2020-03-13T08:39:44.176Z]              at src/libstd/sys_common/backtrace.rs:65

[2020-03-13T08:39:44.176Z]    7: std::sys_common::backtrace::print

[2020-03-13T08:39:44.176Z]              at src/libstd/sys_common/backtrace.rs:50

[2020-03-13T08:39:44.176Z]    8: std::panicking::default_hook::{{closure}}

[2020-03-13T08:39:44.176Z]              at src/libstd/panicking.rs:193

[2020-03-13T08:39:44.176Z]    9: std::panicking::default_hook

[2020-03-13T08:39:44.176Z]              at src/libstd/panicking.rs:210

[2020-03-13T08:39:44.176Z]   10: std::panicking::rust_panic_with_hook

[2020-03-13T08:39:44.176Z]              at src/libstd/panicking.rs:471

[2020-03-13T08:39:44.176Z]   11: std::panicking::begin_panic

[2020-03-13T08:39:44.176Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panicking.rs:404

[2020-03-13T08:39:44.176Z]   12: test_raftstore::cluster::Cluster<T>::request

[2020-03-13T08:39:44.176Z]              at ./<::std::macros::panic macros>:3

[2020-03-13T08:39:44.176Z]   13: test_raftstore::cluster::Cluster<T>::must_put_cf

[2020-03-13T08:39:44.176Z]              at ./components/test_raftstore/src/cluster.rs:696

[2020-03-13T08:39:44.176Z]   14: test_raftstore::cluster::Cluster<T>::must_put

[2020-03-13T08:39:44.176Z]              at ./components/test_raftstore/src/cluster.rs:692

[2020-03-13T08:39:44.176Z]   15: failpoints::cases::test_merge::test_node_merge_recover_snapshot

[2020-03-13T08:39:44.176Z]              at tests/failpoints/cases/test_merge.rs:404

[2020-03-13T08:39:44.176Z]   16: failpoints::cases::test_merge::test_node_merge_recover_snapshot::{{closure}}

[2020-03-13T08:39:44.176Z]              at tests/failpoints/cases/test_merge.rs:369

[2020-03-13T08:39:44.176Z]   17: core::ops::function::FnOnce::call_once

[2020-03-13T08:39:44.176Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ops/function.rs:232

[2020-03-13T08:39:44.176Z]   18: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once

[2020-03-13T08:39:44.176Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/liballoc/boxed.rs:1022

[2020-03-13T08:39:44.176Z]   19: __rust_maybe_catch_panic

[2020-03-13T08:39:44.176Z]              at src/libpanic_unwind/lib.rs:78

[2020-03-13T08:39:44.176Z]   20: std::panicking::try

[2020-03-13T08:39:44.176Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panicking.rs:270

[2020-03-13T08:39:44.176Z]   21: std::panic::catch_unwind

[2020-03-13T08:39:44.176Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panic.rs:394

[2020-03-13T08:39:44.176Z]   22: test::run_test_in_process

[2020-03-13T08:39:44.176Z]              at src/libtest/lib.rs:567

[2020-03-13T08:39:44.176Z]   23: test::run_test::run_test_inner::{{closure}}

[2020-03-13T08:39:44.176Z]              at src/libtest/lib.rs:474

[2020-03-13T08:39:44.176Z]   24: test::run_test::run_test_inner

[2020-03-13T08:39:44.176Z]              at src/libtest/lib.rs:495

[2020-03-13T08:39:44.176Z]   25: test::run_test

[2020-03-13T08:39:44.176Z]              at src/libtest/lib.rs:531

[2020-03-13T08:39:44.176Z]   26: test::run_tests

[2020-03-13T08:39:44.176Z]              at src/libtest/lib.rs:300

[2020-03-13T08:39:44.176Z]   27: test::console::run_tests_console

[2020-03-13T08:39:44.176Z]              at src/libtest/console.rs:295

[2020-03-13T08:39:44.176Z]   28: test::test_main

[2020-03-13T08:39:44.176Z]              at src/libtest/lib.rs:121

[2020-03-13T08:39:44.177Z]   29: test::test_main_static

[2020-03-13T08:39:44.177Z]              at src/libtest/lib.rs:140

[2020-03-13T08:39:44.177Z]   30: failpoints::main

[2020-03-13T08:39:44.177Z]   31: std::rt::lang_start::{{closure}}

[2020-03-13T08:39:44.177Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/rt.rs:67

[2020-03-13T08:39:44.177Z]   32: std::rt::lang_start_internal::{{closure}}

[2020-03-13T08:39:44.177Z]              at src/libstd/rt.rs:52

[2020-03-13T08:39:44.177Z]   33: std::panicking::try::do_call

[2020-03-13T08:39:44.177Z]              at src/libstd/panicking.rs:292

[2020-03-13T08:39:44.177Z]   34: __rust_maybe_catch_panic

[2020-03-13T08:39:44.177Z]              at src/libpanic_unwind/lib.rs:78

[2020-03-13T08:39:44.177Z]   35: std::panicking::try

[2020-03-13T08:39:44.177Z]              at src/libstd/panicking.rs:270

[2020-03-13T08:39:44.177Z]   36: std::panic::catch_unwind

[2020-03-13T08:39:44.177Z]              at src/libstd/panic.rs:394

[2020-03-13T08:39:44.177Z]   37: std::rt::lang_start_internal

[2020-03-13T08:39:44.177Z]              at src/libstd/rt.rs:51

[2020-03-13T08:39:44.177Z]   38: std::rt::lang_start

[2020-03-13T08:39:44.177Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/rt.rs:67

[2020-03-13T08:39:44.177Z]   39: main

[2020-03-13T08:39:44.177Z]   40: __libc_start_main

[2020-03-13T08:39:44.177Z]   41: <unknown>

[2020-03-13T08:39:44.177Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further feedback regarding this issue has been reported, it can be safely closed.
