### ISSUE TITLE
`rocksdb background error` when `make dev`

### ISSUE THREAD

**Issue by Yiyiyimu** [tikv/tikv#7911]
## Question

When following [contributing guideline](https://github.com/tikv/tikv/blob/master/CONTRIBUTING.md) and try to build from master branch, `make build` runs smoothly, but `make dev` keeps failing on the same point.

OS: WSL2

## Logging
```
<other sucessful tests>
test raftstore::test_conf_change::test_node_after_remove_itself ... ok
test raftstore::test_conf_change::test_node_auto_adjust_replica ... ok
test raftstore::test_compact_log::test_node_compact_size_limit ... ok
thread '<unnamed>' panicked at 'rocksdb background error. db: kv, reason: compaction, error: IO error: No such file or directoryWhile open a file for random read: /tmp/test_clusterujiX9N/db/000024.sst: No such file or directory', components/engine_rocks/src/event_listener.rs:66:13
stack backtrace:
test raftstore::test_conf_change::test_node_pd_conf_change ... ok
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:373
  13: <engine_rocks::event_listener::RocksEventListener as rocksdb::event_listener::EventListener>::on_background_error
             at components/engine_rocks/src/event_listener.rs:66
  14: rocksdb::event_listener::on_background_error
             at /home/shuyang/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/002ff06/src/event_listener.rs:254
  15: _ZN24crocksdb_eventlistener_t17OnBackgroundErrorEN7rocksdb21BackgroundErrorReasonEPNS0_6StatusE
             at crocksdb/c.cc:2177
  16: _ZN7rocksdb12EventHelpers23NotifyOnBackgroundErrorERKSt6vectorISt10shared_ptrINS_13EventListenerEESaIS4_EENS_21BackgroundErrorReasonEPNS_6StatusEPNS_17InstrumentedMutexEPb
             at /home/shuyang/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/002ff06/librocksdb_sys/rocksdb/db/event_helpers.cc:53
  17: _ZN7rocksdb12ErrorHandler10SetBGErrorERKNS_6StatusENS_21BackgroundErrorReasonE
             at /home/shuyang/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/002ff06/librocksdb_sys/rocksdb/db/error_handler.cc:219
  18: _ZN7rocksdb6DBImpl20BackgroundCompactionEPbPNS_10JobContextEPNS_9LogBufferEPNS0_19PrepickedCompactionENS_3Env8PriorityE
             at /home/shuyang/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/002ff06/librocksdb_sys/rocksdb/db/db_impl/db_impl_compaction_flush.cc:2797
  19: _ZN7rocksdb6DBImpl24BackgroundCallCompactionEPNS0_19PrepickedCompactionENS_3Env8PriorityE
             at /home/shuyang/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/002ff06/librocksdb_sys/rocksdb/db/db_impl/db_impl_compaction_flush.cc:2316
  20: _ZN7rocksdb6DBImpl16BGWorkCompactionEPv
             at /home/shuyang/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/002ff06/librocksdb_sys/rocksdb/db/db_impl/db_impl_compaction_flush.cc:2091
  21: _ZSt13__invoke_implIvRPFvPvEJRS0_EET_St14__invoke_otherOT0_DpOT1_
             at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/invoke.h:60
  22: _ZSt8__invokeIRPFvPvEJRS0_EENSt15__invoke_resultIT_JDpT0_EE4typeEOS6_DpOS7_
             at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/invoke.h:95
  23: _ZNSt5_BindIFPFvPvES0_EE6__callIvJEJLm0EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE
             at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/functional:467
  24: _ZNSt5_BindIFPFvPvES0_EEclIJEvEET0_DpOT_
             at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/functional:549
  25: _ZNSt17_Function_handlerIFvvESt5_BindIFPFvPvES2_EEE9_M_invokeERKSt9_Any_data
             at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/std_function.h:316
  26: _ZNKSt8functionIFvvEEclEv
             at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/std_function.h:706
  27: _ZN7rocksdb14ThreadPoolImpl4Impl8BGThreadEm
             at /home/shuyang/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/002ff06/librocksdb_sys/rocksdb/util/threadpool_imp.cc:266
  28: _ZN7rocksdb14ThreadPoolImpl4Impl15BGThreadWrapperEPv
             at /home/shuyang/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/002ff06/librocksdb_sys/rocksdb/util/threadpool_imp.cc:307
  29: _ZSt13__invoke_implIPvPFS0_S0_EJPN7rocksdb16BGThreadMetadataEEET_St14__invoke_otherOT0_DpOT1_
             at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/invoke.h:60
  30: _ZSt8__invokeIPFPvS0_EJPN7rocksdb16BGThreadMetadataEEENSt15__invoke_resultIT_JDpT0_EE4typeEOS7_DpOS8_
             at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/invoke.h:95
  31: _ZNSt6thread8_InvokerISt5tupleIJPFPvS2_EPN7rocksdb16BGThreadMetadataEEEE9_M_invokeIJLm0ELm1EEEEDTclsr3stdE8__invokespcl10_S_declvalIXT_EEEEESt12_Index_tupleIJXspT_EEE
             at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/thread:234
  32: _ZNSt6thread8_InvokerISt5tupleIJPFPvS2_EPN7rocksdb16BGThreadMetadataEEEEclEv
             at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/thread:243
  33: _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJPFPvS3_EPN7rocksdb16BGThreadMetadataEEEEEE6_M_runEv
             at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/thread:186
  34: execute_native_thread_routine
  35: start_thread
  36: __clone
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: test failed, to rerun pass '-p tests --test integrations'

Caused by:
  process didn't exit successfully: `path/tikv/target/debug/deps/integrations-5aebe178b3a2251e --nocapture` (signal: 11, SIGSEGV: invalid memory reference)
Makefile:225: recipe for target 'run-test' failed
make[1]: *** [run-test] Error 101
make[1]: Leaving directory 'path/tikv'
Makefile:115: recipe for target 'dev' failed
make: *** [dev] Error 2
```

**Comment by 5kbpers** [comment]
@Connor1996 @yiwu-arbug PTAL
