### ISSUE TITLE
make build failed on master branch

### ISSUE THREAD

**Issue by gotoxu** [tikv/tikv#8153]
## Bug Report

Make build failed on master branch. The detailed information is listed below, it seems that it should be a bug of the rust language itself. Does tikv need to upgrade the rust toolchain? Compile in release mode can be successful.

### What version of TiKV are you using?
master branch
commit: 2623695a49b88ad7602fbca597c1c1191a5d962f

### What operating system and CPU are you using?
OS: 
```shell
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.8.2003 (Core)
Release:        7.8.2003
Codename:       Core
```
CPU*32: 
```shell
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 85
model name      : Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz
stepping        : 4
microcode       : 0x2006906
cpu MHz         : 2399.926
cache size      : 11264 KB
physical id     : 0
siblings        : 16
core id         : 0
cpu cores       : 8
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 invpcid_single intel_ppin intel_pt ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke md_clear spec_ctrl intel_stibp flush_l1d
bogomips        : 4200.00
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
```

### Steps to reproduce
```shell
> git clone https://github.com/tikv/tikv.git
> cd tikv
> RUST_BACKTRACE=1 make build
```

### What did you expect?
build succeed.

### What did happened?
```shell
cargo build --no-default-features --features "jemalloc portable sse protobuf-codec"
   Compiling cdc v0.0.1 (/root/tikv/components/cdc)
   Compiling cmd v0.0.1 (/root/tikv/cmd)
thread 'rustc' panicked at 'index out of bounds: the len is 998 but the index is 18791998', /rustc/b2e36e6c2d229126b59e892c9147fbb68115d292/src/librustc_hir/definitions.rs:58:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (b2e36e6c2 2020-04-22) running on x86_64-unknown-linux-gnu

note: compiler flags: -C bitcode-in-rlib=no -C codegen-units=4 -C debuginfo=1 -C overflow-checks=off -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: could not compile 'cdc'.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [Makefile:119: build] Error 101
 ✘ ⚡ root@db-test-10-101-31-65  ~/tikv   master  RUST_BACKTRACE=1 make build
cargo build --no-default-features --features "jemalloc portable sse protobuf-codec"
   Compiling cdc v0.0.1 (/root/tikv/components/cdc)
   Compiling cmd v0.0.1 (/root/tikv/cmd)
thread 'rustc' panicked at 'index out of bounds: the len is 998 but the index is 18791998', /rustc/b2e36e6c2d229126b59e892c9147fbb68115d292/src/librustc_hir/definitions.rs:58:20
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: rustc_driver::report_ice
  11: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /root/.rustup/toolchains/nightly-2020-04-23-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/boxed.rs:1022
  12: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}
             at /root/.rustup/toolchains/nightly-2020-04-23-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libproc_macro/bridge/client.rs:305
  13: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:515
  14: rust_begin_unwind
             at src/libstd/panicking.rs:419
  15: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  16: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:69
  17: rustc_middle::dep_graph::dep_node::<impl rustc_query_system::dep_graph::dep_node::DepNodeParams<rustc_middle::ty::context::TyCtxt> for rustc_span::def_id::DefId>::to_fingerprint
  18: rustc_query_system::query::plumbing::get_query
  19: rustc_middle::ty::AdtDef::eval_explicit_discr
  20: rustc_middle::ty::sty::<impl rustc_middle::ty::TyS>::discriminant_for_variant
  21: rustc_codegen_ssa::mir::place::PlaceRef<V>::codegen_set_discr
  22: rustc_codegen_ssa::mir::block::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_block
  23: rustc_codegen_ssa::mir::codegen_mir
  24: <rustc_middle::mir::mono::MonoItem as rustc_codegen_ssa::mono_item::MonoItemExt>::define
  25: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
  26: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  27: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  28: rustc_codegen_llvm::base::compile_codegen_unit
  29: rustc_codegen_ssa::base::codegen_crate
  30: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  31: rustc_session::utils::<impl rustc_session::session::Session>::time
  32: rustc_interface::passes::start_codegen
  33: rustc_middle::ty::context::tls::enter_global
  34: rustc_interface::queries::Queries::ongoing_codegen
  35: rustc_interface::interface::run_compiler_in_existing_thread_pool
  36: scoped_tls::ScopedKey<T>::set
  37: rustc_ast::attr::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (b2e36e6c2 2020-04-22) running on x86_64-unknown-linux-gnu

note: compiler flags: -C bitcode-in-rlib=no -C codegen-units=4 -C debuginfo=1 -C overflow-checks=off -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `cdc`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [Makefile:119: build] Error 101
```

**Comment by BusyJay** [comment]
This seems a bug of rustc. Can you build it with previous commits? Can you also send it to rust-lang/rust project?

**Comment by gotoxu** [comment]
Build with commit: 8caa025d2373bd846aef4f35208f8b1ba182442b can succeed.

**Comment by BusyJay** [comment]
I tried to reproduce, but all things went well.

**Comment by gotoxu** [comment]
I noticed the first line of backtrace: 
```shell
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
```
But I can only find `backtrace-0.3.37` in the `$HOME/.cargo/registry/src/github.com-1ecc6299db9ec823` directory.

And I can't find the `backtrace-0.3.46` folder on my host. 

Will it be caused by this reason?

**Comment by BusyJay** [comment]
The trace comes from rustc binary, the string is the path of sources on rustc's release build machine. It has nothing to do with your local registry.

**Comment by gotoxu** [comment]
> The trace comes from rustc binary, the string is the path of sources on rustc's release build machine. It has nothing to do with your local registry.

Sorry, my fault.

Any other reason can cause this?

**Comment by BusyJay** [comment]
I suspect it's due to corrupted local metadata. Maybe `make clean && make build` should fix it.

**Comment by gotoxu** [comment]
> I suspect it's due to corrupted local metadata. Maybe `make clean && make build` should fix it.

I already did that, it didn't work.

I try to upgrade rust toolchain to **nightly-2020-06-29 (rustc 1.46.0-nightly (2f517ce6f 2020-06-28))**, now there are new problems when compiling again: 
```shell
error: could not compile `cdc`.

Caused by:
  process didn't exit successfully: `rustc --crate-name cdc --edition=2018 components/cdc/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -Cembed-bitcode=no -C codegen-units=4 -C debuginfo=1 -C overflow-checks=off -C metadata=362d8c0bda72862c -C extra-filename=-362d8c0bda72862c --out-dir /root/tikv/target/debug/deps -C incremental=/root/tikv/target/debug/incremental -L dependency=/root/tikv/target/debug/deps --extern engine_rocks=/root/tikv/target/debug/deps/libengine_rocks-40e82b762a2233b2.rmeta --extern fail=/root/tikv/target/debug/deps/libfail-c1ab3a27bde45b57.rmeta --extern failure=/root/tikv/target/debug/deps/libfailure-025d475bdb51777e.rmeta --extern futures=/root/tikv/target/debug/deps/libfutures-58a32f63c2e6a9d1.rmeta --extern grpcio=/root/tikv/target/debug/deps/libgrpcio-e2747b64d2dd050f.rmeta --extern hex=/root/tikv/target/debug/deps/libhex-8af5efe75bfd23b5.rmeta --extern kvproto=/root/tikv/target/debug/deps/libkvproto-ad4b4a0362ab2f38.rmeta --extern lazy_static=/root/tikv/target/debug/deps/liblazy_static-011162c4509fafa0.rmeta --extern pd_client=/root/tikv/target/debug/deps/libpd_client-8cc1846397077e7d.rmeta --extern prometheus=/root/tikv/target/debug/deps/libprometheus-dc6af725595f0ef7.rmeta --extern raft=/root/tikv/target/debug/deps/libraft-e4f70a64b15370f6.rmeta --extern raftstore=/root/tikv/target/debug/deps/libraftstore-81d4e76676ffba91.rmeta --extern resolved_ts=/root/tikv/target/debug/deps/libresolved_ts-b966899bca190bb4.rmeta --extern security=/root/tikv/target/debug/deps/libsecurity-798f0a67d5e5a4f3.rmeta --extern slog=/root/tikv/target/debug/deps/libslog-f01f5ee5cd9db4f4.rmeta --extern slog_global=/root/tikv/target/debug/deps/libslog_global-7f88632829b58955.rmeta --extern tikv=/root/tikv/target/debug/deps/libtikv-d8f3576f25aed848.rmeta --extern tikv_util=/root/tikv/target/debug/deps/libtikv_util-c0f72d4669a2ff56.rmeta --extern tokio_threadpool=/root/tikv/target/debug/deps/libtokio_threadpool-2bafeffe3873f62c.rmeta --extern txn_types=/root/tikv/target/debug/deps/libtxn_types-28cfe43c77fc2362.rmeta -L native=/root/tikv/target/debug/build/jemalloc-sys-50e56ac3cb60c748/out/build/lib -L native=/root/tikv/target/debug/build/backtrace-sys-fdb243de4adc95d3/out -L native=/root/tikv/target/debug/build/libz-sys-93305aa81a60d740/out/build -L native=/root/tikv/target/debug/build/libz-sys-93305aa81a60d740/out/lib -L native=/root/tikv/target/debug/build/grpcio-sys-ff1e194820403945/out/build -L native=/root/tikv/target/debug/build/grpcio-sys-ff1e194820403945/out/build/third_party/cares/cares/lib -L native=/root/tikv/target/debug/build/grpcio-sys-ff1e194820403945/out -L native=/root/tikv/target/debug/build/libz-sys-93305aa81a60d740/out/build -L native=/root/tikv/target/debug/build/openssl-sys-c0b6a34b54e8f287/out/openssl-build/install/lib -L native=/root/tikv/target/debug/build/librocksdb_sys-82dc573b1551f50c/out/build -L native=/usr/local/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../lib64 -L native=/root/tikv/target/debug/build/librocksdb_sys-82dc573b1551f50c/out -L native=/root/tikv/target/debug/build/bzip2-sys-5c791a5644ca88fd/out/lib -L native=/root/tikv/target/debug/build/libtitan_sys-dada7aee8f992b2e/out/build -L native=/root/tikv/target/debug/build/lz4-sys-1a18444e0cab1f39/out -L native=/root/tikv/target/debug/build/snappy-sys-1dddba45d27d0d80/out/build -L native=/root/tikv/target/debug/build/zstd-sys-e25e22f6d85d7707/out -L native=/root/tikv/target/debug/build/ring-5837b7a96afa8e1c/out` (signal: 4, SIGILL: illegal instruction)
warning: build failed, waiting for other jobs to finish...
warning: 2 warnings emitted

error: build failed
make: *** [Makefile:119: build] Error 101
```

**Comment by gotoxu** [comment]
@BusyJay 无意中发现了问题原因。是因为我们服务器默认安装的CentOS7的glibc库是2.17版本，我们为了某些原因升级到了2.18，升级后导致了该问题，具体原因未知。

目前我们将系统的glibc库升级到2.28就可以正常编译了。

**Comment by BusyJay** [comment]
Thanks for the updates! Good to know it's solved. That's new to me that glibc version can affect compilation.
