### ISSUE TITLE
storage::txn::actions::acquire_pessimistic_lock::tests::test_pessimistic_lock failed

### ISSUE THREAD

**Issue by KivenChen** [tikv/tikv#9225]
Latest build: <a href="https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37493/display/redirect">https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37493/display/redirect</a>

**Comment by KivenChen** [comment]
Yet another case failure: <a href="https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37600/display/redirect">https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37600/display/redirect</a>

**Comment by KivenChen** [comment]
Yet another case failure: <a href="https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/38023/display/redirect">https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/38023/display/redirect</a>

**Comment by youjiali1995** [comment]
```
[2020-12-15T06:40:41.526Z] test storage::txn::actions::acquire_pessimistic_lock::tests::test_pessimistic_lock ... thread 'main' panicked at 'assertion failed: (older_write.start_ts == txn.start_ts &&

[2020-12-15T06:40:41.526Z]      older_write.write_type == WriteType::Rollback) ||

[2020-12-15T06:40:41.526Z]     older_write.has_overlapped_rollback', src/storage/txn/actions/acquire_pessimistic_lock.rs:116:21

[2020-12-15T06:40:41.526Z] stack backtrace:

[2020-12-15T06:40:41.526Z]    0: std::panicking::begin_panic

[2020-12-15T06:40:41.526Z]              at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/panicking.rs:505:12

[2020-12-15T06:40:41.526Z]    1: tikv::storage::txn::actions::acquire_pessimistic_lock::acquire_pessimistic_lock

[2020-12-15T06:40:41.526Z]              at ./src/storage/txn/actions/acquire_pessimistic_lock.rs:116:21

[2020-12-15T06:40:41.526Z]    2: tikv::storage::txn::actions::acquire_pessimistic_lock::tests::must_succeed_impl

[2020-12-15T06:40:41.526Z]              at ./src/storage/txn/actions/acquire_pessimistic_lock.rs:188:19

[2020-12-15T06:40:41.526Z]    3: tikv::storage::txn::actions::acquire_pessimistic_lock::tests::must_succeed_with_ttl

[2020-12-15T06:40:41.526Z]              at ./src/storage/txn/actions/acquire_pessimistic_lock.rs:245:17

[2020-12-15T06:40:41.526Z]    4: tikv::storage::txn::actions::acquire_pessimistic_lock::tests::must_succeed

[2020-12-15T06:40:41.526Z]              at ./src/storage/txn/actions/acquire_pessimistic_lock.rs:215:9

[2020-12-15T06:40:41.526Z]    5: tikv::storage::txn::actions::acquire_pessimistic_lock::tests::test_pessimistic_lock

[2020-12-15T06:40:41.526Z]              at ./src/storage/txn/actions/acquire_pessimistic_lock.rs:566:9

[2020-12-15T06:40:41.526Z]    6: tikv::storage::txn::actions::acquire_pessimistic_lock::tests::test_pessimistic_lock::{{closure}}

[2020-12-15T06:40:41.526Z]              at ./src/storage/txn/actions/acquire_pessimistic_lock.rs:357:5

[2020-12-15T06:40:41.526Z]    7: core::ops::function::FnOnce::call_once

[2020-12-15T06:40:41.526Z]              at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/core/src/ops/function.rs:227:5

[2020-12-15T06:40:41.526Z]    8: core::ops::function::FnOnce::call_once

[2020-12-15T06:40:41.526Z]              at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/core/src/ops/function.rs:227:5

[2020-12-15T06:40:41.526Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by youjiali1995** [comment]
ah, it failed in a draft PR which modified the case. https://github.com/tikv/tikv/pull/9214

**Comment by MyonKeminta** [comment]
Oh, that was a mistake I made while working or that PR and was fixed.
